### ISSUE TITLE
Unable to see the list and join any server - Network error: SSL handshake failed

### ISSUE THREAD

**Issue by Inamaru** [drawpile/Drawpile#1000]
As title says,
when I try to see the list or join directly on a server I get this error.

I would like to point out that this problem happened out of the blue. (The day before I was joining/seeing the list of the server just fine)

But I still think this is probably caused on my end, but I'm not even sure why this is happening. (My laptop on the same network doesn't have this problem. Both machine use windows 10 64bit)

Is there something specific I should try to look for?

I tried some workaround suggested by a simple google search but nothing changed for now
Thanks in advance for your time

EDIT: not sure if this helps, but this also happen when I try to "check for updates".

**Comment by Shammiieee** [comment]
I got this error too just now! It was working fine last night though, just to be clear- I didnt make any major changes or anything.

**Comment by Inamaru** [comment]
Seems like I fixed the problem by installing the certificate on my local machine.
I don't know if this is the best workaround to "deal with it" but it works...
This Is for windows only
https://letsencrypt.org/certificates/
https://puu.sh/IfhFw/86d0c5d8b1.png
Go on:
Active:
"Cross-signed by DST Root CA X3" and choose the DER file.
Right click, install certificate. And just follow the wizard setup (no need to change anything at all, I decided to install the certificate on the local machine though, but it shouldn't matter that much)

That fixed the problem for me
Hope it helps.

I do not take any responsability if this may damage your pc,etc,etc,...
Use it at your own risk

**Comment by Shammiieee** [comment]
I'll give it a go! Thanks for the help and yeah I'll be sure to use it at my own risk, happy drawing!

**Comment by Inamaru** [comment]
> 
> 
> I'll give it a go! Thanks for the help and yeah I'll be sure to use it at my own risk, happy drawing!

Please let me know at least if that worked for you too! (This may help other people!)

**Comment by Inamaru** [comment]
Did you restart the program? have you tried to install it as a local machine?

**Comment by Shammiieee** [comment]
I wasnt so sure about installing it in my local machine so I just installed it under the current user- would I have to uninstall the certificate from the current user before attempting to download it into the local machine? (and if so how would I go about that?)

**Comment by Inamaru** [comment]
Before that just make sure that's the right certificate I pointed out.
At this point though, you can just reinstall it, It will get replaced automatically.

**Comment by Shammiieee** [comment]
Ohh noted, I did check twice making sure to clicked the right one too. Still no changes unfortunately

**Comment by Inamaru** [comment]
Oh okay :( I'm sorry to hear that, I mean, it worked for me just fine after that...

**Comment by Shammiieee** [comment]
Thats alright! It was worth a try- it might get pretty lonely drawing without friends around though :") Im willing to wait for any other changes and help tho

**Comment by Wade821** [comment]
Github is primarily intended for reporting bugs with the code of the program, or help with bugs/issues. 

For issues regarding services going down, this really should be on the Discord server, as this just clutters up bugs. The Discord Server invite link is on the website in the lower left corner. https://discord.gg/M3yyMpC

Getting to the core issue here, This appears to be a problem with LetsEncrypt Root Certificate. This just means basically that your computer is lacking a certificate to validate/justify many websites and not just Drawpile. Someone from Drawpile Discord found this fix earlier while I was at work, I suggest trying it. I'd also suggest ensuring that your computer's date and time is correct as well. 

> massy: !! my friend finally fixed their issue i'm gonna link here in case it helps anyone else!!
> These two links helped them put together the puzzle and sort the problem.
> https://www.stephenwagner.com/2021/09/30/sophos-dst-root-ca-x3-expiration-problems-fix/
> https://www.thesslstore.com/blog/how-to-remove-a-root-certificate/

**Comment by Shammiieee** [comment]
I'll be sure to keep that in mind next time! I did as the first link explained and I could see the servers now thanks for the help. :)

**Comment by Wade821** [comment]
Alright, closing this issue then. :)
