### ISSUE TITLE
Interactive Objects

### ISSUE THREAD

**Issue by jippless3024** [drawpile/Drawpile#1004]
Is it possible to add the function to place multiple moving parts on the canvas?
I want a function to display the place I want to emphasize in real time without soiling the canvas.
For example, it's like a movable chess piece.

**Comment by notfood** [comment]
As a work around, you can use text objects with the symbols you want, everyone needs the same font though but everyone has webdings. They are their own layer, everyone can move them.

Interactive objects could be rectangles or arrows that connect to other objects, it'd allow Drawpile to builds flowcharts and such. An example as reference can be Visio.

**Comment by jippless3024** [comment]
The workaround worked fine. thank you very much.
I'm also looking forward to the features of interactive objects.
If possible, consider making the image an interactive object.
