### ISSUE TITLE
About the reduced view

### ISSUE THREAD

**Issue by jippless3024** [drawpile/Drawpile#1008]
I don't know what the condition is, but regarding the screen scaling, the scaling factor behaves strangely depending on the canvas size.

For example, when the canvas size is 1800*1350
If you zoom out, you can only reduce the size to 50%. If you zoom out, the magnification goes up to 75%. Also, the behavior when entering the magnification number with the keyboard seems to be wrong.
(In the case of 500*375, it can be scaled down to 10%, and even if you zoom out at 10%, the value remains at 10%.)

**Comment by Wade821** [comment]
What you're talking about is Adaptive zoom. There's this entry on it from the news page (https://drawpile.net/news/release-2.1.8/). 

- Adaptive canvas zoom slider: the minimum value is now always the zoom level needed to fit the whole canvas on screen. [Read more](https://drawpile-dev-diary.tumblr.com/post/184531795642/minimum-zoom)

Should also say that it's not just dependent on the canvas size, but also the ratio of the size, the current resolution of your display device, and whether or not you have chat open (alt + C to show or hide chat). 


It does seem to not behave properly when attempting to manually input the zoom percentage, that is true. This would make that a bug. 

As far as the rest of what you described, I'm honestly a bit confused as you wrote "if you zoom out" twice. Going to need a better description here. 
> If you zoom out, you can only reduce the size to 50%. If you zoom out, the magnification goes up to 75%. Also, the behavior when entering the magnification number with the keyboard seems to be wrong.

**Comment by jippless3024** [comment]
It seems to be different from the function of Adaptive canvas zoom slider.
As a result of checking, it works as follows

In the case of a canvas size of 180*135 (the zoom factor is 700% to show just the whole canvas)
You can zoom out to 10% magnification
If the canvas is smaller than the window size at 100% magnification, does the adaptive canvas zoom slider not work?

In the case of a canvas size of 1800*1350 (the zoom factor is 73% to show just the whole canvas)
After zooming out to 50% magnification, zooming out again will suddenly increase the magnification to 73%.
If you zoom out from 73%, you can zoom out again to 50% and repeat the process.

In the case of a canvas size of 3000*2250 (the zoom factor to display the entire canvas is 44%)
If you zoom out from 44%, it will stay at 44%.
Once you are at 40%, is that a problem?

Also, when the magnification is set to just show the whole canvas, it is hard to adjust the scrolling so that the edges of the canvas are shown, so I think it would be more convenient to move the display position back to the center and give a little more room at the lower limit of the magnification.

Also, there are times when you may dare to turn off the Adaptive canvas zoom slider, such as when checking an example of a distant view or a scaled-down view, so if possible, you want to turn the feature on and off.

**Comment by askmeaboutlo0m** [comment]
Zoom has been changed to not behave as strangely anymore, which I think fixes the issues described here. It's available for testing in the development version of Drawpile 2.2: <https://github.com/drawpile/Drawpile/releases/tag/continuous>
