### ISSUE TITLE
Feature: Add to current selection

### ISSUE THREAD

**Issue by johannesCmayer** [drawpile/Drawpile#1009]
When I have an active selection I would like to press some button like control, to make another selection that is then "added" to the original selection. Maybe I have missed how to do it, because this seems like a very basic and useful feature, but I could not figure it out this far.

**Comment by askmeaboutlo0m** [comment]
This is implemented now. You can either hold the constrain key (Shift by default) or activate this option in the select tool settings.

![Add to selection button](https://github.com/drawpile/Drawpile/assets/13625824/5b6c627a-3916-47dc-a033-5f38cc97dde0)

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting it!
