### ISSUE TITLE
drawpile thumbnails missing!

### ISSUE THREAD

**Issue by NekoCha9** [drawpile/Drawpile#1010]
i have run into a problem recently that the sessions i have been saving arent having a thumbnail generated for them. it seems to only be the .ora files that are doing this. when im in the file viewer for drawpile, its only showing the icons and not whats in the file. and now i cant tell anything apart. i recently updated so i dont know if that could be the issue, but im not sure. or maybe .ora isnt supported in the file manager anymore? please help

**Comment by notfood** [comment]
Drawpile doesn't bring any thumbnail generator, the issue is on your file browser. Unfortunately, it depends on your enviroment and you haven't detailed anything.

**Comment by Wade821** [comment]
What NotFood is saying is that you haven't told us if you use Windows, Mac, or Linux.

If it's Windows, you can install the Shell Extension from Krita that will allow you to view ORA files in Windows Explorer.
https://krita.org/en/download/krita-desktop/

Please let us know if this works or if you're using another operating system.

**Comment by NekoCha9** [comment]
> What NotFood is saying is that you haven't told us if you use Windows, Mac, or Linux.
> 
> If it's Windows, you can install the Shell Extension from Krita that will allow you to view ORA files in Windows Explorer. https://krita.org/en/download/krita-desktop/
> 
> Please let us know if this works or if you're using another operating system.

Oh im sorry. to you and NotFood, i am using windows. AND BLESS YOU, i used the Shell Extension and it worked! i have krita as well, and now i can view my files again. thank you, THANK YOU so much. 

this is the first time i ever used this site, sorry  im kinda slow on this lol. <3

**Comment by Wade821** [comment]
It's fine. The ability to view ORA files is not part of Drawpile. So if it randomly stopped, probably something on Krita's end. Glad to hear it's working for you.
