### ISSUE TITLE
Feature request:change the transparency of application windows

### ISSUE THREAD

**Issue by jippless3024** [drawpile/Drawpile#1017]
This is a use case of mine, where several people are watching a video at the same time and doodling about it.

In this case, I thought it would be interesting to have a semi-transparent drawpile so that people can draw over the video and write circles and arrows on the highlights.
It's like a drawing version of niconico.com or Bilibili, only for server participants and only in real time.

I know that this is a way of using the software that is outside of the creator's intentions, so if it is very little work to implement, could you please do it for me?

**Comment by notfood** [comment]
This is the task of your compositor, in this case whatever Windows has. You can already do this under Linux and I believe there are tools to achieve the same thing under Windows.
A quick google yields a lot of alternatives:
https://www.thewindowsclub.com/how-to-make-windows-transparent-in-windows

This is out of scope for Drawpile.
