### ISSUE TITLE
toolbars gone

### ISSUE THREAD

**Issue by calmnivore** [drawpile/Drawpile#1026]
my toolbars have disappeared! I keep checking, unchecking the toolbar docks but they never come back! any ideas?
<img width="904" alt="drawpile_cEneW5yKxw" src="https://user-images.githubusercontent.com/13960718/163704864-e13feb84-a25f-43b5-9a86-a7b1314b2205.png">

**Comment by Wade821** [comment]
Press the tab key and let me know if that works.

If you have further questions, join the Discord server. Invite link is on the website's lower left corner.

**Comment by calmnivore** [comment]
it does not work.

**Comment by calmnivore** [comment]
> Press the tab key and let me know if that works.
it does not

**Comment by Wade821** [comment]
It should. Can you take a screenshot of this menu for me?
![image](https://user-images.githubusercontent.com/18544575/165682844-9d9c536a-0504-4f8a-954c-23dedbe1720a.png)

**Comment by calmnivore** [comment]
<img width="1079" alt="drawpile_Evem8gwBEP" src="https://user-images.githubusercontent.com/13960718/200155412-8d4a1d0d-12ee-4421-aeb2-048f2aab8979.png">
<img width="1079" alt="drawpile_gRl5uf8Cib" src="https://user-images.githubusercontent.com/13960718/200155419-c09a760e-3fe6-4203-9e00-265155e36e8d.png">
behold

**Comment by calmnivore** [comment]
sorry I know this sounds like a dumb user error thing but it is not. I have been having this problem for like a year. it might not even be a drawpile thing, but a windows thing, where the windows have somehow been banished to the shadow realm and for whatever reason using the taskbar to arrange windows doesn't bring them into view. The problem is occurring with the flip book window now too.

**Comment by calmnivore** [comment]
okay it turns out it's some kind of weird windows issue. I found a utility thing called winlister that lists every open window and recenter it if you wish, and this has fixed the issue. I now have my drawing tools toolbar back. same fix for the flipbook. sorry about not responding for so long.
