### ISSUE TITLE
connecting lines issue

### ISSUE THREAD

**Issue by Valagroyl** [drawpile/Drawpile#1027]
![image](https://user-images.githubusercontent.com/103889171/163717579-eb0715a3-9c34-48bd-a807-d0b15aad42c2.png)
When I try to draw or hatch it's just start connecting my lines in one point or with each other.

![image](https://user-images.githubusercontent.com/103889171/163717776-842410a8-b062-4516-a6aa-34509af2e66e.png)
and sometimes put these random giant circles with pressure

![image](https://user-images.githubusercontent.com/103889171/163717898-3ab35215-fac0-4214-9b89-0b6df83ed9f0.png)
It happens when I drew faster or lift the pen too much.

**Comment by Wade821** [comment]
Can you go to help, tablet tester and try in there? 

Regarding the big circles, there's nothing that can be done about that. It's a known issue as Drawpile has no hardware acceleration, but hopefully with Drawpile 2.2 coming out, those issues should largely go away since it will have multi-threading support. 

If you have further questions, join the Discord server. Invite link is on the main website's lower left corner.

**Comment by Valagroyl** [comment]
> 

It works just fine in tester, I'll be waiting for the update thank you for the reply.

**Comment by Wade821** [comment]
What's your smoothing set to in the input settings? Can you put screen shots of that and the tablet tester?

**Comment by Valagroyl** [comment]
> What's your smoothing set to in the input settings? Can you put screen shots of that and the tablet tester?

![image](https://user-images.githubusercontent.com/103889171/163869002-9344d28c-450f-46f5-b77d-d471003c0e42.png)

![image](https://user-images.githubusercontent.com/103889171/163869092-8aea57b6-9e91-4210-bc02-725e1da1472a.png)

**Comment by Wade821** [comment]
Try reducing the smoothing to a lower value. Having it high can cause issues with connecting lines.

**Comment by Valagroyl** [comment]
> Try reducing the smoothing to a lower value. Having it high can cause issues with connecting lines.

![image](https://user-images.githubusercontent.com/103889171/163869479-401caa80-dcc0-4aa6-8b7a-176a077dd3cc.png)

Now it's makes same thing with jagged lines.

**Comment by Wade821** [comment]
Are you using windows? If so, is it windows 10? What version? (Windows key + r and type `winver`, then hit enter).

What is your tablet brand, model number,  and driver version?

**Comment by Valagroyl** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/103889171/163889358-8ecd8539-eb72-4b26-be6d-885b469b0404.jpg)

My tablet is;
Wacom Intuos P S / driver version: 6.3.46-1

**Comment by MachKerman** [comment]
same issue
system: win10 21H2 19044.1645
tablet: UGEE EXRAI pro16
tablet driver version:1.6.4

i asked some one and some of them have this problem too
it seems to be randomly happens

**Comment by Wade821** [comment]
@MachKerman @Valagroyl 
Have either of you tried the latest beta version? There's a lot of changes to the way it works now, and you might find it improved. I'd also suggest trying to go to edit, preferences, input to see if changing the "driver" option helps at all.

https://github.com/drawpile/Drawpile/releases

**Comment by Valagroyl** [comment]
> 

Thank you for reminding it! After giving up for a long time, I've tried the new version and the problem is gone.

**Comment by Wade821** [comment]
> > 
> 
> Thank you for reminding it! After giving up for a long time, I've tried the new version and the problem is gone.

Excellent! I'm glad to hear it. :) 

FYI, there's also a Turkish translation of Drawpile in the beta now, so hopefully that helps as well. If you're like to contribute to that or review the translation, you can do so online.

https://hosted.weblate.org/projects/drawpile/desktop/
