### ISSUE TITLE
May I be unbanned?

### ISSUE THREAD

**Issue by Legobama** [drawpile/Drawpile#1028]
I don't know why but I got kicked from my friends session and then banned. I named myself "black midget" because we were laughing at a gif with a guy with dwarfism earlier. Is there anyway I can get unbanned?

**Comment by notfood** [comment]
Drawpile doesn't have a central server, bans are handled per server by their rules, you'll have to appeal it to their Discord. Github is for issues pertaining the code, not individual hosting.

**Comment by Wade821** [comment]
Actually this is not a ban by a session operator, but by the server owner for Cloudywave and Syntheticdreams. Regardless, Github is intended for bugs reporting and feature requests. 

If you wish to discuss this ban further, please join the Drawpile Discord server. The invite link is located on the website's lower left corner.
