### ISSUE TITLE
Hotkey to Duplicate Layer

### ISSUE THREAD

**Issue by mrjpaxton** [drawpile/Drawpile#1029]
Hello,

I was wondering if a hotkey could be set for duplicating a layer.

In GIMP, this is set to "Ctrl+D" by default, and I noticed it wasn't being used for anything anyway. In some other art programs, Sometimes "Shift+D" is used instead. The developers can agree to pick whatever would be a sane default.

The use case would be to make it a lot more convenient than having to right click to get to the menu, and clicking "Duplicate Layer". It can make most workflows easier and faster, especially when using Drawpile to work with frame-by-frame animations. Hotkeys can even be macroed!

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming with Drawpile 2.2.
