### ISSUE TITLE
Option to completely disable join/leave notification pop-ups on the UI

### ISSUE THREAD

**Issue by MagicaJaphet** [drawpile/Drawpile#1033]
Since it hasn't been suggested here yet, an option to disable this feature:

![image](https://user-images.githubusercontent.com/92384575/175146851-52102622-8a78-41ee-808c-a7878695eca5.png)

Mostly suggesting as it seems to cause Window users in particular issues when they have a different full screen tab open, it forces them to switch to the program.

**Comment by askmeaboutlo0m** [comment]
This is implemented now by letting you pick which notifications cause a popup like this in the notification preferences.

![image](https://github.com/drawpile/Drawpile/assets/13625824/fc7689de-e529-4a2d-8f8c-cd63ff7ff292)

It's available in the continuous development release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting!
