### ISSUE TITLE
There's no select tool. 

### ISSUE THREAD

**Issue by michaelleepow90** [drawpile/Drawpile#1034]
**I cannot seem to select an object on a layer to move, resize or distort. Is there a way to fix it?**

**Comment by MagicaJaphet** [comment]
Are you drawing in a server? Some servers have their permissions set to only let registered/trusted/operators be able to use the select tool.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

No response, closing this.
