### ISSUE TITLE
How to build drawpile-cli

### ISSUE THREAD

**Issue by f2d** [drawpile/Drawpile#1040]
Is it possible currently?

I tried to build 2.2.0b3 source code from https://drawpile.net/download/#Beta on Linux Ubuntu Server 22.04.1.
I used my old build script which ultimately comes down to `cmake .. -D<args> && make` command to build all possible binaries.
I tried various `-D<args>`, which did not help.
Result was always only the `drawpile` client with symlink and the `drawpile-srv` server standalone.
I found no instructions about building `drawpile-cli` on the site or in the source code (with text search in all files).

As an aside, I also built version 2.1.20 with the same script/command on the same system, which gave expected 4 binaries (client, srv, `drawpile-cmd` and `dprectool`).

I also tried to build 2.0.11, as for 2.0 I only had 2.0.10 binaries lying around from my old server backup.
This failed completely with error, and no executables in result.

My overall idea is to run multiple versions (e.g. 2.2 + 2.1 + 2.0 if possible) on different ports on single VPS.
I'm still in process of patching my [service/archive scripts](https://github.com/f2d/drawpile_webpage_automation) to allow that.

**Comment by askmeaboutlo0m** [comment]
You can run `cargo build --release`, which should give you `target/release/drawpile-cli`. Building via CMake doesn't include that bit currently.

Also, the server remains compatible between 2.1 and 2.2. You don't need to run two versions of it, it's possible to host sessions from either version of the client on either version of the server. Maybe 2.0 works too, but I haven't tried that.

**Comment by f2d** [comment]
> run `cargo build --release`, which should give you `target/release/drawpile-cli`.

This worked, thanks.
This tool seems to not to have `--acl` option, at least it its built-in help.
Is it on by default or not implemented?

Regarding version compatibility, there were some talks about "thick server" that keeps the session image in memory, which will need all clients to run same version, IIRC.

I'm taking it slowly anyway, and also have more reasons to restructure my thing (it does not update the page when service failed or stopped, etc).

**Comment by askmeaboutlo0m** [comment]
As far as I can tell from the code, ACL filtering is not implemented.

There is no thick server for 2.2 yet, drawpile-srv is (and has been) the thin/dumb server.
