### ISSUE TITLE
are texture based brushes possible?

### ISSUE THREAD

**Issue by guiguizada** [drawpile/Drawpile#1041]
I'm curious about what is the plausibility and the potential issues and drawbacks of implementing texture brushes like other programs such as krita and gimp have

**Comment by MagicaJaphet** [comment]
2.3 is currently in a beta state at the time of writing, thanks to askmeaboutloom textured brushes will most likely be a thing in it when it fully releases! Right now they implemented the mypaint brush system if you're curious and want to test it out.

There is a windows download link on the drawpile site, but if you're using another OS then you'll have to compile it yourself.

**Comment by Wade821** [comment]
Closing though as we don't need to keep open issues for which we've already made progress. If you have further questions on Drawpile 2.2, I suggest you join the Discord server. The beta can be downloaded from the website.
