### ISSUE TITLE
Flipbook isnt working.

### ISSUE THREAD

**Issue by SnowNA12** [drawpile/Drawpile#1047]
I haven't used drawpile in a while, and used to use it a lot for my animations. But recently, I opened it to look at my old animations and was thinking of creating more. When I opened my old animation and tried to ctrl F it, it didn't work. I thought maybe it was the file. So I opened a new one and drew 2 lines, ctrl F, nothing, I went in the bar, looked for flipbook, clicked, Nothing. So then I updated drawpile to the latest version (ofc, first I uninstalled the version I had on my computer, then installed new one). Still nothing, flipbook doesn't work. And I'm not sure why. Can anybody help please? :)

**Comment by Wade821** [comment]
Sorry, things have been busy. Are you still experiencing this issue?

It probably opens just fine... just off of the visible screen area. If so, can probably clear registry settings to fix that.

**Comment by askmeaboutlo0m** [comment]
Closing for now, if the issue persists, please reopen this.
