### ISSUE TITLE
pressure sensitivity just wont work

### ISSUE THREAD

**Issue by xSorrowxLightx** [drawpile/Drawpile#1051]
hello! ive tried everything, look at every thread, reinstalled both my tablet and drawpile several times, nothing. i honestly dont know what to do :(
OS: Wndows 10 64bit build 19043.2130
Tablet: Wacom Cintiq 22hd
Drawpile Ver: 2.1.20

windows ink is on in the tablet settings
![](https://i.imgur.com/094IlDK.png)

and in the drawpile settings
![](https://i.imgur.com/w1oPC0C.png)

and heres the built in tablet tester results
![](https://i.imgur.com/jpN0dK4.png)

![](https://i.imgur.com/7nF0iZN.png)

ive tried having both window inks enabled, both off, drawpiles on tablets off, vice versa. i also know about the buttons to the side of each of the freehand sliders, but i have no control over the hardness or opacity. itll just go from 0 to 100 if i draw long enough.

**Comment by Wade821** [comment]
Better responsiveness on the discord for issues. But you have to enable Pen pressure on the freehand dock to get pen pressure. 
![image](https://user-images.githubusercontent.com/18544575/197108976-0dff4b0a-d2ea-4141-bf04-e50479aae8bd.png)

Please comment back and let me know if this fixes your issue.

**Comment by xSorrowxLightx** [comment]
![](https://i.imgur.com/Dp805zi.png)
so i clicked on all of them, and it just does this. it gradients from no opacity to full opacity, regardless of my pen pressure.

**Comment by Wade821** [comment]
Oh, sorry. I just noticed you had the "input" set to "Distance". Set that to "Stylus". The options "Distance" and "Velocity" are for fake pen pressure for mouse users.

**Comment by xSorrowxLightx** [comment]
![l9T86tmdNu](https://user-images.githubusercontent.com/115955126/211179909-cd6d70da-fcb9-44f0-aa3c-43e7e0ef8991.png)
this is all ive got in that section right now
(also sorry for the late response again haha)

**Comment by askmeaboutlo0m** [comment]
Looks like you removed the stylus setting. Click on the button on the right. Then create a new input preset and set the "Pressure" setting to "Stylus". Then pick your newly created option in that "Input" box.
