### ISSUE TITLE
(Feature request) Easy cropping

### ISSUE THREAD

**Issue by ShyDoge** [drawpile/Drawpile#1054]
I wish that you could crop the canvas based on your selection on offline boards like many other applications can do

**Comment by MagicaJaphet** [comment]
This is actually a feature, although not an obvious one at first. If you select an area and then choose the resize canvas option, it'll automatically choose the area that you selected.

**Comment by ShyDoge** [comment]
> This is actually a feature, although not an obvious one at first. If you select an area and then choose the resize canvas option, it'll automatically choose the area that you selected.

Oh my god. I had no idea. THANK YOU SO MUCH, AND SORRY!

**Comment by Wade821** [comment]
It's fine. Put labels on it for easy searching/review.

Also in Drawpile 2.2, you'll be able to make a selection and save it to a file rather than have to save the whole canvas. Still in beta though.
