### ISSUE TITLE
(Feature, Usability) Change Ctrl+Scrollwheel to zoom in/out, Shift+Scrollwheel to scroll horizontally

### ISSUE THREAD

**Issue by chetchaka** [drawpile/Drawpile#1056]
_Related to / piggybacking off of #709_

On the latest version (2.2 beta 3), the current behavior for both Ctrl+Scrollwheel and Shift+Scrollwheel is to scroll to the very top of the canvas and very bottom of the canvas. This behavior is not very useful. 

Most other image viewers and art programs use Ctrl+Scrollwheel to zoom and Shift+Scrollwheel to scroll horizontally. This issue is a request to make this the default behavior in Drawpile.

**Comment by Wade821** [comment]
Please don't open another issue for the similar/related issues and just comment on the existing one. Having too many issues open makes it hard to keep track of changes. 

Furthermore, have you tried going to edit, preferences, canvas shortcuts to make adjustments?


![image](https://user-images.githubusercontent.com/18544575/208580423-25217cc7-e75d-4480-b085-e9ccb31699e7.png)

**Comment by chetchaka** [comment]
... Well don't I feel dumb. Wow.
