### ISSUE TITLE
Interface too big

### ISSUE THREAD

**Issue by ultrazebra** [drawpile/Drawpile#1085]
Same as #674, but on LMDE 5. Interface takes up 1/3 of the screen.

**Comment by askmeaboutlo0m** [comment]
That sounds like the opposite of #674, Qt can only make the UI bigger, not smaller. Can you attach a screenshot? You should be able to just hit Ctrl+V while the text box is in focus and it should paste the image in there.

**Comment by ultrazebra** [comment]
This is the smallest size I can get. Chat also looks broken - I can see chat and members, but can't the input line to send messages myself.
![drawpile](https://user-images.githubusercontent.com/56080895/236710546-83844d8e-331f-4fc5-81b5-7b83a251f03b.png)

**Comment by askmeaboutlo0m** [comment]
Hmm, it doesn't look to me like it's particularly oversized, it's just arranged in a way that makes it unusable on your resolution.

You can work around it in Drawpile 2.1 by closing some of those docks (the "X" in the corner) or dragging them around by their title bar (where it says "Brushes" and "Color" and such) and dropping them on top of each other to combine some of them until they stop pushing the window off-screen.

Drawpile 2.2 will resolve this by making the default layout less ginormously tall and letting you shrink several of the docks to smaller sizes. It also fixes the docks getting messed up when you hit tab to hide them, so even if they take up too much of the screen for your taste, you should be able to hide them while drawing.

To make sure it's not getting scaled up though, check your system settings if any scaling is enabled or not. It should be in the resolution or monitor settings. If it's above 100%, Drawpile is picking that up, so you should be able to start it with the environment variable `QT_SCALE_FACTOR` set to `1` to hopefully force it to use 1:1 scaling.

**Comment by ultrazebra** [comment]
These docks have the smallest horizontal size I can give to them (I can make them bigger, but not smaller).
I have used Drawpile (don't remember what version it was though) on Windows before, and never had problems with UI being oversized.
I have checked monitor resolution and scaling settings before opening an issue - it is set to my maximum/normal screen resolution, and scaling is set to 100%.
Using "Tab" hotkey to show/hide dockers kind of works, though, as in all software for editing, it's better to have UI being present at all times to have quick access to it.

**Comment by askmeaboutlo0m** [comment]
Does running Drawpile with the Qt scale factor set to 1 change anything? Running `QT_SCALE_FACTOR=1 drawpile` or something of that sort. If not, then this is 1:1 scale and Qt can't be convinced to reduce it, it only gets bigger. Trying the Drawpile 2.2 dev release from the [Releases](https://github.com/drawpile/Drawpile/releases) would also be an option, since it should allow for docks to be shrunken smaller horizontally.

**Comment by ultrazebra** [comment]
Haven't tried QT_SCALE_FACTOR, but tried beta release instead. This looks perfect! Here is a minimum horizontal docks comparison between two versions:
![drawpile2](https://user-images.githubusercontent.com/56080895/237003404-1f6a7de8-b0aa-4bed-b6dd-f5943f6ebf25.jpg)
