### ISSUE TITLE
[2.2.0-beta.4] Apple Magic Trackpad gesture input not working

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#1092]
On the newest beta, the beheaviour of Apple's Magic Trackpad on mac computers changed, one finger input should be disabled and instead use two finger scrolling to move around my canvas, by default it stops working like a mouse on one finger input and does a weird wobbling motion.

two finger pinch and rotate has a very long delay too before it performs the action, and currently using two finger scroll is interpreted as a wheel scroll so it just zooms and unzooms the canvas. 
I just want my trackpad to have the same utility it has on apps like Photoshop or Clip Studio where I can use two finger scrolling to scroll around the canvas and pinch and rotate with an instant response

**Comment by askmeaboutlo0m** [comment]
This is probably because gesture handling got removed in the process of making touch work on Android. It worked fine for all devices I've had access to, but apparently the Magic Trackpad and some Windows tablet PC things don't handle it properly.

I'll put it back in for the next beta, hopefully that will make it work like before again.

**Comment by askmeaboutlo0m** [comment]
I made an attempt at putting it back in. Here's a development build of it, with a macOS download at the bottom, does that work for you? https://github.com/drawpile/Drawpile/actions/runs/5283461629 (macOS download link is at the bottom, must be logged into Github to be able to download it for some reason)

The setting for it is in Preferences > Input, at the bottom under Driver. On macOS, it should automatically set it to Gesture.

![image](https://github.com/drawpile/Drawpile/assets/13625824/f5d069cc-dec6-4ff2-8eef-836e9c94f721)

**Comment by Charmandrigo** [comment]
> I made an attempt at putting it back in. Here's a development build of it, with a macOS download at the bottom, does that work for you? https://github.com/drawpile/Drawpile/actions/runs/5283461629 (macOS download link is at the bottom, must be logged into Github to be able to download it for some reason)
> 
> The setting for it is in Preferences > Input, at the bottom under Driver. On macOS, it should automatically set it to Gesture.

I just tested it, does not work, it does nothing at all really, two finger scroll is still interpreted as a wheel scroll, one finger is back to just be a cursor but the pinch and twist don't do anything at all

**Comment by askmeaboutlo0m** [comment]
Can you make an event log of it? Tools > Developer Tools > Tablet Event Log. Start the log, do the touches and then use the same menu item to stop the log. And then I think you should be able to attach the file here by just dragging it into the comment window.

**Comment by Charmandrigo** [comment]
[tablet log.dplog.zip](https://github.com/drawpile/Drawpile/files/11763427/tablet.log.dplog.zip)

**Comment by askmeaboutlo0m** [comment]
Hm, it doesn't receive any gestures at all, only mouse and tablet stuff. And Gesture is enabled in the input preferences, right?

**Comment by askmeaboutlo0m** [comment]
Hrm, okay. I'll try to figure out what's wrong then, maybe I'll need to borrow a Macbook for this one. Thanks for testing!

**Comment by askmeaboutlo0m** [comment]
Okay, got back to this now, I still haven't found a device where I can reproduce this, everything I tried just works. But there's also been reports of some trackpads on Windows not working when they did before, so there sure is something weird going on.

The current continuous release now has a touch tester: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

You can get at it through Help > Touch Tester (not Tablet Tester.) That opens a window for logging touch and gesture stuff.

![image](https://github.com/drawpile/Drawpile/assets/13625824/a03e079d-c491-44f4-b4f8-2765c49a9533)

Ideally, do a pinch on the area that says "touch here" with the checkboxes on the top-right in all four possible combinations (both on, only touch, only gestures and both off - not all of them will necessarily write anything on the right) and then hit "Save" to save the log to a text file, which you can shoot back. Hopefully there'll be some combination that produces usable inputs.

![image](https://github.com/drawpile/Drawpile/assets/13625824/037e3f0c-f712-4061-9fd9-4aad6da8d629)

**Comment by Charmandrigo** [comment]
Ok, I will check it out today and send the results

**Comment by askmeaboutlo0m** [comment]
I got other reports and made another attempted fix: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Does this make it work?

It should enable this automatically, but if it's not working, check in Edit → Preferences → Input if the Touch mode is set to Gesture.

![image](https://github.com/drawpile/Drawpile/assets/13625824/79e3861e-057b-466e-85a6-56efa0c58bc4)

**Comment by Charmandrigo** [comment]
> I got other reports and made another attempted fix: https://github.com/drawpile/Drawpile/releases/tag/continuous
> 
> Does this make it work?
> 
> It should enable this automatically, but if it's not working, check in Edit → Preferences → Input if the Touch mode is set to Gesture.
> 
> ![image](https://user-images.githubusercontent.com/13625824/282245736-79e3861e-057b-466e-85a6-56efa0c58bc4.png)

[Test 1.txt](https://github.com/drawpile/Drawpile/files/13343312/Test.1.txt)

I got the same results even with the gestures enabled, This attachment is the touch tester thing, I tested the pinching and the two finger sliding, it originally the two finger sliding allowed me to move around the canvas, and pinch allowed me to zoom in and out, current results are two finger scrolling is zooming and the pinching just makes the entire canvas shake

**Comment by askmeaboutlo0m** [comment]
Thank you! The log shows perfectly fine pinches happening, so I think it might be that it's also reporting scrolling at the same time and causing collisions. I've had another go at it, how does this behave? https://github.com/drawpile/Drawpile/actions/runs/6863294820 (the download link "Drawpile-macOS-Qt5.15.8" is at the bottom, gotta be signed into Github for it to work)

If it doesn't work still, I also extended the event log, so you can make another one of those. To start it, Tools > Developer Tools > Tablet Event Log…, same thing to stop it again. Ideally, do it once with the touch mode set to Gestures and once with it set to Touchscreen.

**Comment by Charmandrigo** [comment]
Ok so this is the tests:
Pinching zooms in and out correctly now.
Two finger scrolling idoes nothing either, in one instance it was teleporting the canvas to one corner instantly, like on the screenshot, on my second test the gesture did nothing at all.
using the rotation gesture does nothing too
<img width="1920" alt="Captura de pantalla 2023-11-14 a la(s) 8 04 04 p m" src="https://github.com/drawpile/Drawpile/assets/30424766/f8d37683-de44-4801-b085-0dd940ba605a">


SHould I mention that magic mouse uses a one finger scroll to also glide around zoomed content? (webpages, images, etc) same as two finger slide, this touch gesture could be implemented and tested for both two finger scroll and magic mouse scrolling

Now, the test with tablet mode enabled is different...
pinch for zoom works, and, surprisingly the rotation gesture that does not work on the gesture mode works on the tablet mode.
Two finger scrolling is bugged, it looks like it's scrolling on the canvas on some instances then it does sudden zoom ins.
[logs.zip](https://github.com/drawpile/Drawpile/files/13359170/logs.zip)

**Comment by askmeaboutlo0m** [comment]
Okay, the pinch gestures always have a rotation of zero, making them useless. That's something Qt would have to fix, it's not something Drawpile itself has control over. But there's a whole mountain of Magic Mouse and Magic Trackpad bugs in Qt's bugtracker, it seems like whenever they fix something it breaks something else.

But if touchscreen mode is working, then that's probably the more sensible way forward. The reason it's zooming is probably because the touch pad is sending both touch *and* mouse wheel inputs, where the latter is set to zoom by default. That may not be a sensible option on macOS, since there you tend to have a two-dimensional mouse wheel.

Go to Edit > Preferences > Canvas Shortcuts and locate the "Mouse Wheel" shortcut. It should be set to "Zoom Canvas".
![image](https://github.com/drawpile/Drawpile/assets/13625824/9e313c4b-7e2a-4818-86ca-c904a32233e5)

Double-click on it and change "Action" to "Pan Canvas". Hit OK on the way out and see how it behaves afterwards.
![image](https://github.com/drawpile/Drawpile/assets/13625824/bc928898-1086-40ac-883f-43162cabb3a9)

**Comment by Charmandrigo** [comment]
IT seems like nothing actually happened after doing that, it does the same.
Moving one finger on my trackpad when using the tablet mode makes the canvas glide around a bit as I move my mouse, I had to disable one-finger input to fix that.
removing the mouse wheel and changing it to pan canvas did nothing really
[pan.dplog.zip](https://github.com/drawpile/Drawpile/files/13361075/pan.dplog.zip)

**Comment by askmeaboutlo0m** [comment]
Alright, thank you, that helps. The mouse wheel inputs were being ignored by the touch happening at the same time, I turned that off now. It also now checks if the input device is a touch pad and, if so, will ignore one-finger touches from it. So it should no longer do that gliding stuff with one finger, even if you have one-finger touch turned on.

How does this behave? https://github.com/drawpile/Drawpile/actions/runs/6876726776

**Comment by Charmandrigo** [comment]
This build works excellent, it does the pan with two finger sliding now, and the other gestures work well too

**Comment by askmeaboutlo0m** [comment]
Great! Then I'll put that into the mainline, with the touch mode set to Touchscreen by default. On macOS, the default mouse wheel action will be to pan the canvas.

Thanks for helping figure this out!
