### ISSUE TITLE
MacOS, undocked toolbars are impossible to resize when undocked

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#1094]
This might be a Mac only bug. When toolboxes get dragged and undocked, it's impossible to resize them on this state, you can only grab them and move them, dock them back to the side panels, but not resizing, the arrows you would normally expect to appear don't appear when hovering on the toolbox corners, the cursor is gone completely and nothing happens when clicking them

https://github.com/drawpile/Drawpile/assets/30424766/a432d2a7-b260-4e43-97ad-911b340f1429

**Comment by askmeaboutlo0m** [comment]
Huh, apparently this is a known issue in Qt on macOS. There seems to be a workaround though, I'll give that a try and make a dev build of it.

**Comment by askmeaboutlo0m** [comment]
Here's an attempted fix, it should turn the docks into regular windows when they're undocked: https://github.com/drawpile/Drawpile/actions/runs/5295376750

As before, there should be download links at the bottom, gotta be logged in to get them for some reason.

**Comment by Charmandrigo** [comment]
That works better!

**Comment by askmeaboutlo0m** [comment]
Great, then I'll merge that in. Thanks for reporting it!
