### ISSUE TITLE
[2.2.0-beta.4] palette dock is overly wide

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1096]
I've mentioned the issue with the Palette making the dock size unnecessarily bigger horizontal wise during a previous test session, but I don't know if it was forgotten about, so I'm mentioning it here since its still apparent. 

I focus on drawing a lot easier with tools/docks in one corner with minimal space taking up the drawing area and I use Palette very often on the stable releases. I'm not sure if it's intentional, but most docks are able to be reduced to a small portion of the screen for Beta 4 on Windows except the Palette dock.

How I usually see the layout:
![Screenshot_6](https://github.com/drawpile/Drawpile/assets/51433534/8519d330-89cb-47bf-93e0-da5e2cfcca44)

Vs the double sized difference when Palette is added onto the dock:
![Screenshot_8](https://github.com/drawpile/Drawpile/assets/51433534/afd27c97-b8f8-4080-a1b2-e12cc441ad89)

Having the option to minimize it would be greatly appreciated. Also, the mypaint brushes change the actual brush that I have set rather than it going to the mypaint brush button setting. For example, I'll be on brush 1 and if I click onto one of mypaint brushes, the brush setting that I had will change into it, even the brush sensitivity input. I'm wondering if this is a bug or if its been addressed yet.

**Comment by askmeaboutlo0m** [comment]
Yeah, the palette got changed earlier in the 2.2 development cycle, where it lost some functionality and got wide. The sliders and color picker had similar regressions. This is a bug to be fixed anyway.

The brush palette supports all brush type, all the ones that are visible in your screenshots are classic brushes from the "Drawpile" category. So a classic brush preset changing your classic brush settings is intentional.

**Comment by vipperz** [comment]
Ohh, I didn't even realize there were preset drawpile brushes too. I get it now. Thank you for replying.

**Comment by askmeaboutlo0m** [comment]
The palette docker should be working again and will let itself be narrowed now. Is available in the continuous release.
