### ISSUE TITLE
Suggestion: Allow movement shortcuts to be bound to keys rather than combinations of modifier keys

### ISSUE THREAD

**Issue by Pockatiel** [drawpile/Drawpile#1103]
I have my own unique pattern of shortcuts across software that I use for panning, rotating, scaling etc. It would be extremely helpful if I could bind these to the keys I choose rather than using combinations of ctrl/alt/shift etc

**Comment by askmeaboutlo0m** [comment]
No worries, it's a confusing place!

This has been implemented in Drawpile 2.2 anyway. You can get the beta from <https://drawpile.net/download/#Beta>. There's also perpetual development releases at <https://github.com/drawpile/Drawpile/releases>, if you want something even more bleeding-edge. It's backward-compatible enough to join Drawpile 2.1 sessions with it.

You can find the canvas shortcuts settings in Preferences → Canvas Shortcuts. If there's anything missing or you got a question on how to set up a particular shortcut, feel free to reopen this ticket.

![canvas shortcuts settings page](https://github.com/drawpile/Drawpile/assets/13625824/0d024ecd-e92d-4d76-90ef-44ec8517d008)
![create canvas shortcuts dialog](https://github.com/drawpile/Drawpile/assets/13625824/f6913b68-7ca7-4335-b0f4-6c876274807d)
