### ISSUE TITLE
(Drawpile 2.1.20) Pen losing pen pressure on certain areas of canvas 

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1109]
When I draw on certain areas, my pressure instantly goes away for that spot but it will come back when I move away from it. It's been an ongoing issue, mostly if I were to draw above the chat box, but it's starting to show in different areas now and It's become frustrating. It doesn't happen in any other art program I've used. (Krita/CSP)

I keep Windows Ink off and have tried to use Drawpile's pen mode hack/canvas viewport entry hack but it was still getting the same results.

![scribble](https://github.com/drawpile/Drawpile/assets/51433534/b7c4f160-215e-4145-9b22-9e576046d4d7)

I've managed to catch it in the tablet tester. It registers as HOVER instead of DRAW when the pressure is gone.

![Screenshot_2](https://github.com/drawpile/Drawpile/assets/51433534/bf7af3bd-81e0-4f25-9fec-b8dbe95fd129)

Any help with this would be appreciated until the new stable release comes out.. I use a Huion Kamvas 22 Plus btw.

**Comment by askmeaboutlo0m** [comment]
To confirm, this only happens in 2.1 and is fixed when using 2.2?

**Comment by vipperz** [comment]
Yes, no similar issue in the most recent continuous version. Only wondered if there was a workaround for 2.1.

**Comment by askmeaboutlo0m** [comment]
Okay, then that is sadly out of my area of expertise. I don't know Windows and 2.1 doesn't have any even logging I could look at, but maybe someone else has some idea.

**Comment by vipperz** [comment]
I think I actually fixed the issue myself with updating a tablet monitor driver and restarting my computer. Possibly had a odd reaction issue. Thanks for replying though!

**Comment by askmeaboutlo0m** [comment]
No worries! Happy it's solved anyway.
