### ISSUE TITLE
Larger Transformation Tool Corner Selection Area

### ISSUE THREAD

**Issue by zetalambo** [drawpile/Drawpile#1116]
I'm not sure if it's a skill issue or what have you, hat being said... Often times after I've selected part of a drawing to transform and try to drag some of the corners to change the drawing, I'll often deselect the transform and I'll have to re-select it. This is a bit annoying at times and I'd like some sort of accessibility option to have the corners for transforming the selection be bigger. This could be a confirgurable held key or a togglable entry in interface options. Whatever would be most sensible and easy to implement. Thanks for reading my suggestion for usability and take care!

**Comment by askmeaboutlo0m** [comment]
Not a skill issue, definitely a problem with the way selections work. They need to be entirely remodeled, not deselecting the thing because you clicked in the wrong spot is one of the things to implement. It'll probably have to wait until after 2.2 is released, since it's a big change.

**Comment by askmeaboutlo0m** [comment]
This is implemented now. The transform handles now have a larger area to click, turn from partially transparent to opaque when you hover over them and the cursor changes appropriately.

Clicking outside of the transform also no longer instantly deselects it and ruins everything, that now takes a double-click. You can also undo transform steps. So missing a handle should be less of an issue altogether.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!
