### ISSUE TITLE
Moving Selection to snap and slide along closest axis (quadrant dependant) when pressing Shift (Suggestion)

### ISSUE THREAD

**Issue by Kvothen** [drawpile/Drawpile#1123]
Moving the selection is currently "freehand".
There are very few use cases for it but it would be appreciated..

**Comment by askmeaboutlo0m** [comment]
Yeah, that makes sense, Krita has the same binding. It's not like we're using the Shift key for anything else while dragging, so might as well assign a meaning to it.

**Comment by askmeaboutlo0m** [comment]
This has been implemented and is available in the continuous development release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting it!
