### ISSUE TITLE
notification sound specifically on private messages for you

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1128]
To let the notification sounds active in 'message received' could be kinda annoying sometimes when people are having a conversation not related to you (especially if you have multiple drawpile sessions open)... However a separate notification exclusive for PMs directed to you (and maybe another to when people mention your name on public chat) that would be really useful! Because private messages are more rare and important so they do deserve a separate notification sound!

**Comment by askmeaboutlo0m** [comment]
While I'm hesitant to complicate the chat and notification systems, being able to treat messages with hot words or PMs specially does seem like it would be useful for busier boards.

**Comment by askmeaboutlo0m** [comment]
This is implemented. Private messages are now a separate notification category in Edit > Preferences > Notifications. You can configure mentions of your username or chosen trigger words in public chat to cause private message notifications.

![image](https://github.com/drawpile/Drawpile/assets/13625824/7e680748-d1d9-41bc-99b9-bc431f820d74)

This is available in the continuous development release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting!
