### ISSUE TITLE
playback speed option for timeline play/export video

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1131]
it would be useful to have a 'playback speed' option in the timeline player, especially to have effect in the 'video export'... to share in social media as speed paint (speed up timelapse) that is very common nowadays (because nowadays nobody has the patience to watch a timelapse in real time). Usage example: youtube shorts.

**Comment by askmeaboutlo0m** [comment]
Assuming you mean the recording playback again. This exists in Drawpile 2.2 since beta 4 or something. I've been using it myself to post timelapses of drawings.

![image](https://github.com/drawpile/Drawpile/assets/13625824/d1e1ffa6-af37-420d-a3da-f7ac03f6b6bf)

**Comment by askmeaboutlo0m** [comment]
If that's not what you meant, feel free to re-open this ticket.
