### ISSUE TITLE
Emoji size unchanged

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1138]
I saw the emoji's are supposed to be seen bigger(?), but trying out the Windows 11 emoji's stay the same between the recent continuous release and 2.1.20.

![Same outcome](https://github.com/drawpile/Drawpile/assets/51433534/6cc7f71b-faa9-4cac-bb6b-204b737ad1b4)

**Comment by askmeaboutlo0m** [comment]
Yeah, this is an issue on Windows. The text matching library that comes with it is outdated or something and it doesn't know what an emoji is.

**Comment by askmeaboutlo0m** [comment]
This should be fixed, the text matching is done with violence instead of a library now.
