### ISSUE TITLE
Canvas blurs when mirroring

### ISSUE THREAD

**Issue by SadColor** [drawpile/Drawpile#1144]
When mirroring the canvas horizontally or vertically, the canvas blurs at 100% size. This doesn't happen when zoomed in at any higher multiple of 100%.
The blurring can be easier or harder to see depending on your exact view position. I found it easiest to adjust by zooming out below 100%, then zooming in back to 100% with the cursor in a different spot.
I tried checking previous versions of Drawpile, and I think it started happening in 2.2 beta 6.

Unmirrored canvas
![image](https://github.com/drawpile/Drawpile/assets/60848907/fce6fd30-cca7-4aae-84bd-8978ebe9c547)

Horizontally mirrored (most noticeable blurring)
![image](https://github.com/drawpile/Drawpile/assets/60848907/256f9645-6f29-4bdb-b6c6-f4e9c21de15c)

Horizontally/vertically mirrored canvas (less noticeable blurring)
![image](https://github.com/drawpile/Drawpile/assets/60848907/c4c5a4fd-df67-4761-bc7f-558a5224c10e)
![image](https://github.com/drawpile/Drawpile/assets/60848907/687c3a01-8b32-4db0-8bfd-ad2859bcb7c1)

**Comment by askmeaboutlo0m** [comment]
Ah yeah, it also does the same thing at 100% zoom when you rotate the canvas at 90°, 180° and 270°, even though the pixels all are at a 1:1 size. Should be simple enough to fix just by catching those cases and turning off the smoothing.

**Comment by askmeaboutlo0m** [comment]
This is fixed now, it's available in the continuous development release <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!
