### ISSUE TITLE
Broken Unfilled Rectangle With MyPaint Brushes

### ISSUE THREAD

**Issue by haxekhaex2** [drawpile/Drawpile#1151]
When using MyPaint brushes, the unfilled rectangle tool results in broken rectangles when the dimensions are greater than 1000 in either width or height.

**Comment by askmeaboutlo0m** [comment]
This is fixed now and available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!
