### ISSUE TITLE
Cannot paste selected image in Harmony OS [Android]

### ISSUE THREAD

**Issue by ariqhadiyan** [drawpile/Drawpile#1162]
I just bought a used Huawei tablet because it was quite cheap. From what I can gather, it's using Harmony OS which is a sort of offshoot of Android operating system modified by Huawei to be used in the Chinese market.  I can install the APK version of Drawpile just fine, and it worked flawlessly for the few first hour I've been using it to draw. Joined many sessions to test how it works and nothing seem to be amiss. The problem starts when I was about to copy a selected image from a layer, it wouldn't let me paste it. pressing paste won't result in anything, both using the shortcut or even by clicking the paste button. The layer isn't protected, and anyone can paste on it. I couldn't do it even when I'm opening up my own files.

**Comment by askmeaboutlo0m** [comment]
I can reproduce the issue on my phone as well, will look into it.

**Comment by askmeaboutlo0m** [comment]
Okay, turns out the system clipboard on Android doesn't support putting images on it. Drawpile now just stores the image internally instead.

The fix is available in the continuous release: https://github.com/drawpile/Drawpile/releases/tag/continuous

Thanks for reporting it!
