### ISSUE TITLE
Touch shortcuts: two-finger tap to undo, three-finger tap to redo

### ISSUE THREAD

**Issue by InconsolableCellist** [drawpile/Drawpile#1174]
Drawpile on Android is amazing! However, I find it pretty essential to have quick undo and redo options. In an app like Krita, you can two-finger tap to undo and three-finger tap to redo. I didn't see this feature requested yet on the Issues tab, but the search had some trouble with the keywords like "undo."

**Comment by askmeaboutlo0m** [comment]
In Drawpile, you can use your volume button for undo and redo. Would that work for you?

Gestures are also worth a thought still, although I myself found them really unreliable when using Krita on my Android tablet.

**Comment by InconsolableCellist** [comment]
I didn't know about the volume button, that's a partial solution, thanks. I don't find it as convenient as tapping (or, ideally, being able to configure it to what you want, like a button from an external controller).

**Comment by askmeaboutlo0m** [comment]
There's some demand due to the browser version for this anyway, since that can't make use of the volume buttons, so it'll probably end up being added in some capacity. Allowing controller input is also interesting and would make sense, although I don't think I got any controllers at hand I could hook up to my devices to actually try it.

**Comment by askmeaboutlo0m** [comment]
This is implemented now and available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

The default is to have two-finger tap to undo, three-finger tap to redo and four-finger tap to toggle the docks, but they are configurable in the preferences:

![Touch preferences](https://github.com/user-attachments/assets/5e231951-7f6a-45f4-8180-57d3c2fffaa2)

Thanks for suggesting!

**Comment by InconsolableCellist** [comment]
This is excellent, great job! I'll be sure to try it out soon
