### ISSUE TITLE
Pen does not return to brush mode after using eraser

### ISSUE THREAD

**Issue by royalboyo** [drawpile/Drawpile#1180]
I have an XP-PEN Artist Pro 16. The pen has an eraser at the end, so I flip my pen around to erase. However, when I flip my pen back, it stays in the eraser mode.
This only happens in Drawpile, and I have tried to find a fix to this with no luck. I can always manually change it, but it's a bit annoying to change it back to brush every time I erase. Is there a fix to this?

Thank you !

**Comment by askmeaboutlo0m** [comment]
I assume you are on Windows.

Usually this happens because of the wrong tablet driver set in Drawpile. You can change the driver in Edit → Tablet Driver. Just try all of the options, one of them should work.

Cf. [this question in the FAQ](https://docs.drawpile.net/help/common/faq#why-does-drawpile-not-switch-back-after-i-use-my-tablet-pens-eraser).

![image](https://github.com/drawpile/Drawpile/assets/13625824/6be02156-df44-4008-8b4b-4e13402f52bb)

Does this solve the issue?

**Comment by royalboyo** [comment]
> I assume you are on Windows.
> 
> Usually this happens because of the wrong tablet driver set in Drawpile. You can change the driver in Edit → Tablet Driver. Just try all of the options, one of them should work.
> 
> Cf. [this question in the FAQ](https://docs.drawpile.net/help/common/faq#why-does-drawpile-not-switch-back-after-i-use-my-tablet-pens-eraser).
> 
> ![image](https://private-user-images.githubusercontent.com/13625824/298345944-6be02156-df44-4008-8b4b-4e13402f52bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTQ2MDMsIm5iZiI6MTcwNTg5NDMwMywicGF0aCI6Ii8xMzYyNTgyNC8yOTgzNDU5NDQtNmJlMDIxNTYtZGY0NC00MDA4LThiNGItNGUxMzQwMmY1MmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAzMzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDU5OTQxOTdlNjdkMTBhNTY2MTQ3MmQ5YTNjY2NlMjI1MzA2YzcxN2M5NjA4MjgxYzI0NzU0NjQ3YmY2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kwSGeakwo0JwJAgegwhCr7RRxbSJ9Xe9o77khQt79LM)
> 
> Does this solve the issue?

yes this worked, thank you so much. i switched it to just wintab ! :)

**Comment by askmeaboutlo0m** [comment]
Cool! Happy it's solved.
