### ISSUE TITLE
Annotations Gone

### ISSUE THREAD

**Issue by RyanMolyneux** [drawpile/Drawpile#1186]
After updating to drawpile 2.2.1 all the annotations I had within my drawpile document are now gone, I believe them to be still there as I haven't overridden the file just yet so I'm assuming the newer version of drawpile just for some reason cannot show them, or read them not entirely sure.

**Comment by RyanMolyneux** [comment]
In the mean time I will downgrade and circle back to note if this fixes the issue.

**Comment by askmeaboutlo0m** [comment]
I don't think the annotation format changed between versions, so unsure why this issue would crop up. Can you share the file in question? That would probably be the quickest way to check what's going on.

You have disabled annotations? That's under View → Show Annotations.

**Comment by RyanMolyneux** [comment]
Downgraded to 2.1.20 fixed it will write a test doc check if is reproducible on seperate doc and then share along here/np.

**Comment by RyanMolyneux** [comment]
Yup seems to be reproducible try this one here, on 2.1.20 shows text "1234567891012" and 2.2.1 just disappears.
[TestDoc123.zip](https://github.com/drawpile/Drawpile/files/14473958/TestDoc123.zip), just to note had to zip as github ain't letting me share raster file but alternatively I'dd say give same steps a try on your end and should be able to reproduce.

**Comment by askmeaboutlo0m** [comment]
Yup, I can reproduce it, will take a look.

**Comment by askmeaboutlo0m** [comment]
Okay, apparently there *was* a change in the annotations format. Drawpile 2.1 saved the annotations inside the layer tree, which has some exciting effects on other programs that expect there to be layers there. So 2.2 will continue to save ORA files with annotations outside of the layer tree, but I made it load the old format properly now.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!

**Comment by RyanMolyneux** [comment]
Grand sounds good I'll give that a go in a bit, also no problem.
