### ISSUE TITLE
Relative links in README.md to releases, documentation project don't work

### ISSUE THREAD

**Issue by GreenReaper** [drawpile/Drawpile#1196]
[README.md](https://github.com/drawpile/Drawpile/blob/main/README.md) [contains the text](https://raw.githubusercontent.com/drawpile/Drawpile/main/README.md) `[the GitHub releases](/drawpile/Drawpile/releases).`

This is meant to go to:
https://github.com/drawpile/Drawpile/releases
But when clicked from the front page of the project it actually goes to:
https://github.com/drawpile/Drawpile/blob/main/drawpile/Drawpile/releases

Similarly `[over in this repository](/drawpile/drawpile.github.io)` does not work as intended,

**Comment by askmeaboutlo0m** [comment]
Fixed those, thanks!
