### ISSUE TITLE
A  pub.drawpile.net bug

### ISSUE THREAD

**Issue by Xx-XxknguxX-xX** [drawpile/Drawpile#1316]
I am unable to join any pub.drawpile.net servers without crashing. When I join with my main account, I get this loading screen:
![a](https://github.com/drawpile/Drawpile/assets/171099784/08073982-248e-468b-b88f-4bcf72c9db1d)

Then it says:
![b](https://github.com/drawpile/Drawpile/assets/171099784/1804ddfa-a67a-41be-bc38-86da95a4332b)

I am able to stay in a pub.drawpile.net server for around 14 minutes without an account. The other servers work; syntheticdreams.net, ahaven.net etc.

pls help :-(

**Comment by Wade821** [comment]
GIthub is intended primarily for reporting bug issues, not support. So bear that in mind. If you need help faster, it's better to use Discord server (invite link is on lower left corner of website or on welcome page in Drawpile app on startup). There's also IRC (libera.chat), which is also on the welcome page. 

It's preferred that way, cause then I can ask for more relatively private info like your username, if you're using a profile picture or not (if so, is this a picture set on drawpile.net or is it set in app under edit, preferences, avatars), what kind of internet are you using (cable, dsl, wireless hotspot/cellular, satellite... and if you're hardwired or wireless) and that sort of thing. There's a lot of reasons for the disconnect you also described, but not nearly enough information to make any kind of determination as to why it is happening. 

Also, given what you described it isn't crashing, but just failing to connect. Crashing would force the entire program to close or freeze such that it never becomes responsive (and has to be closed after waiting several minutes to be sure it is indeed frozen). 

For now I'm going to leave this open, but I think it'd be better to ultimately close this issue and have a discussion in real time.

**Comment by Xx-XxknguxX-xX** [comment]
Thanks!

**Comment by askmeaboutlo0m** [comment]
Huh, interesting. Do you still have the profile picture and is it something you can share? If so, you could you attach it to this issue, You should be able to just drag the file into the comment field. Maybe we can use that to fix the underlying issue.

**Comment by Xx-XxknguxX-xX** [comment]
> Huh, interesting. Do you still have the profile picture and is it something you can share? If so, you could you attach it to this issue, You should be able to just drag the file into the comment field. Maybe we can use that to fix the underlying issue.

Sure it's the one below.
![cropped (3)](https://github.com/drawpile/Drawpile/assets/171099784/cc7027ea-b38a-4c66-940b-6fe2489ed242)

I just tried joining with a different picture (added from the profile page in usernames) and it did the same thing; can't join pub.drawpile.net servers. I'm going to keep the profile pictures off for now.
![zzzz](https://github.com/drawpile/Drawpile/assets/171099784/e1221283-67d8-4fd4-812c-50668c0e8e69)

**Comment by Xx-XxknguxX-xX** [comment]
> Thanks, I'll see if I can reproduce it somehow.

It was the VPN that caused it.
