### ISSUE TITLE
Alternative transform handling mode upon right click or modifier keybinds

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1325]
It is possible to make it so that {right click} or the {modifier keys + left click} interact with transform as the alternative (inactive) handling mode.
Currently right click, or the modifier keys doesn't do anything during transform, and so, it could be a good addition.
![image](https://github.com/user-attachments/assets/025de1d2-1457-43d7-b21e-8d8fb77cca9a)

Another idea for adding functionality to left click during transform tool would be to cancel it, similar to double click, although this isn't nearly as useful as the former idea.

**Comment by askmeaboutlo0m** [comment]
Right-click now uses the opposite mode. Both tool modifiers (constrain and center) are already in use by the transform tool, so there's nothing else to attach meaning in that regard.

**Comment by MorrowShore** [comment]
**As of now, Both Clicks Swap Handling Mode.**
This may be a bug or intentional, but left click should have a separate purpose during transformation. Right click is enough.
for example, returning to selection, or taking the transformation result back to selection.

**Comment by askmeaboutlo0m** [comment]
This is intentional behavior. Binding a single right-click to a destructive purpose would bring us back to the old horror of accidentally missing the handle obliterating your entire transform.
