### ISSUE TITLE
Adjusting grow / shrink parameters

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1331]
Being able to adjust how soft or harsh selection grows or shrinks could be quite useful.

![image](https://github.com/user-attachments/assets/567d73d3-27fc-4435-9f46-7a349ce091b6)

**Comment by amoruwu** [comment]
![image](https://github.com/user-attachments/assets/0d87ca18-b561-4911-adda-bbb72dbe3133)
Doesn't expand and shrink already have feather for making the edges soft? :0

**Comment by askmeaboutlo0m** [comment]
It's about which pixels get grown or shrunk into, not about smoothing the result of that. You can see in the screenshot that Drawpile leaves more single pixels "jutting out" than GIMP does.

**Comment by askmeaboutlo0m** [comment]
Implemented as square expansion shape.
