### ISSUE TITLE
Transform mask on click

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1334]
### B- Inevitability of transform tool; adjustment feature
Left clicking a selection instantly brings one to the transform tool, which may or may not be good depending on the workflow.
However, left click could be better suited to show the selection, its attributes, information, and allow for manual adjustments. 

Example from GIMP:
![GIMP selection left click](https://github.com/user-attachments/assets/e89ae06a-09a9-4c3c-a270-cdaa7bbe3c36)

**Comment by askmeaboutlo0m** [comment]
Alt+left click will now start a transform of only the selection mask itself. It's also already available as a bindable action under Selection > Transform Selection Mask.
