### ISSUE TITLE
Increase double click leniency for transforms

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1335]
Double clicking to dismiss sometimes misses if it's not done "fast enough" despite being reasonably a double click.

![double click dismiss](https://github.com/user-attachments/assets/2af56959-0166-498b-ba52-9c487ca0bdb7)

**Comment by askmeaboutlo0m** [comment]
The click detector now uses the system double-click interval and distance if they're larger than the ones we would normally use.
