### ISSUE TITLE
Quick Shapes (Auto Detect Shape on Modifier and on Pen Hold)

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1339]
This feature involves using a brush to draw a rough circle, square or rectangle, and holding the brush at the end point for roughly ~2.5 seconds, and it being automatically converted to a symmetric / perfect shape with the same parameters. 

The action should also gain a hotkey for activation.

https://www.youtube.com/watch?v=7byB-bfXZ_E

An additional feature would be the ability to change the parameters during the adjustments.

**Comment by askmeaboutlo0m** [comment]
Issue was raised in chat and is still being discussed. Closing this for now to avoid opening another thread of discussion, will reopen this later if appropriate.
