### ISSUE TITLE
Changing window size adjusts dock length

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1349]
I've noticed that whenever I try to drag a drawpile window to be smaller and drag it back up to cover the whole screen again, it changes how the docks were. Making some longer or small to the point they're shrunk all the way to where you can't tell where they are. Not sure if this has been brought up before.

https://github.com/user-attachments/assets/5f093678-c299-42f3-826a-244d85fbaba0

On a side note, would be nice to have Navigator, Palettes, and Color Wheel docks to have a limit to how far they can shrink.

**Comment by askmeaboutlo0m** [comment]
I guess this is arguably a bug, but kinda just how the underlying dock system from Qt works. So unsure if it's something we can actually do anything about.

Giving those docks a non-zero minimum size would definitely make sense though, since they're not useful when you squeeze them into unexistence.

**Comment by askmeaboutlo0m** [comment]
The mentioned docks now have a larger minimum size so that you can no longer shrink them out of existence, thanks for reporting that.

The thing with the docks is trickier. I looked at Krita, they seem to behave differently, so it may be something we can steal from there.

**Comment by askmeaboutlo0m** [comment]
I couldn't figure out how Krita does this exactly, but I think I solved it in a reasonable way. The program will now try to remember your "intended" dock layout and restore it when the window resizes. Depending on how you laid your docks out, there can be some weirdness while you're resizing the window where docks shrink smaller and then pop to a bigger size once you hit their minimum size, but I don't think that's a significant enough issue to try and chase it down.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

**Comment by vipperz** [comment]
There does seem to be some weirdness in the Color Palette getting longer and the Navigator remaining its minimal size when having the window maximized again, but it's not as drastic as it was. Implementing the Reference dock was a very lovely idea that makes the issue less concerning in general, for me at least.

Thank you so much for your work on this!
