### ISSUE TITLE
Switching between eraser and brush causes color change

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1355]
When I use a brush, use the eraser right after and switch back to that brush, it changes the color once I start drawing with it. This wasn't happening before I updated to the recent continuous release.

https://github.com/user-attachments/assets/857dc8c5-fe44-42e7-8dff-9d891cb9dfa2

**Comment by askmeaboutlo0m** [comment]
Can confirm. Probably caused by 02e06ac9ac7750122c873cec50603a799329fac6.

**Comment by askmeaboutlo0m** [comment]
Should be fixed in the continuous release now. Thanks for reporting it!
