### ISSUE TITLE
Color Wheel Improvements + Design

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1361]
### There are multiple potential improvements to the color wheel:

1- Adjusting the circle width to be bigger and more proportional to the shape. 
![image](https://github.com/user-attachments/assets/cc3db3ad-42d4-42ba-b43c-0210dd528d12)
Partially covered by https://github.com/drawpile/Drawpile/commit/8bde1e2ff46169925cd225d6a287f3a42d59fe11. Could be bigger.

2- Showing color as it is being adjusted in the color wheel.
![image](https://github.com/user-attachments/assets/134e84bb-3473-42c7-8a68-f35cfcf3a6a2)
Partially covered by https://github.com/drawpile/Drawpile/commit/f8b4be278f53c8cfad69b0364052c4927863c90e. Could be prettier.

3- Implementing alignment option to have color wheel stick to the top.
![image](https://github.com/user-attachments/assets/3e6506c9-c138-4cbe-9c1e-f8bb8caeb656)
Adequately covered by https://github.com/drawpile/Drawpile/commit/40a6fc5ff7b4da14de3d3bea19418ca4ef1bf0d1.
**Currently freezes with alt-tab in windows.** 

---
### Proposed design: 

Resting: (a ring is affected by HSV values)
![image](https://github.com/user-attachments/assets/84d7998c-ce24-4352-bf6c-49b5ae6daf8c)

Dragging within HSV shape:
![image](https://github.com/user-attachments/assets/5345e7fd-01f5-4cdc-a85e-40011b3b12e8)

Dragging within HUE ring:
![image](https://github.com/user-attachments/assets/c51382ff-5f2f-4f9a-ba84-cc427bc33075)

**Comment by amoruwu** [comment]
inclusion of the "Latest Color Picked" feature may be redundant?  
Most people use the color wheel just for picking a color for their brush not much else and the pick tool already has history. That is sizeable and more useful.
![image](https://github.com/user-attachments/assets/558d65ad-84bc-49f4-b933-02a572f5827f)

> Dragging within HUE ring:


![19889a60f5b1d98ed127b2193145f550 (1)](https://github.com/user-attachments/assets/6c929fdd-c737-45e2-bf1d-5836ae9a5b46)
I actually like the simpleness of the current one!
The only design I like between these ones is the one in the middle bottom, and without it's "Latest Color Picked" it would be the same as the current one. 

> Resting: (a ring is affected by HSV values)

It's neat! Consider clarifying the purpose and utility of this? :o

**Comment by MorrowShore** [comment]
The new implementations were made before this post could be finalized, so they're essentially a quick draft of what was supposed to be this issue (and more).
The point is for the second ring is comparison. 
After discussing the concept of demonstrating the color currently dragged (which led to the implementation), we were actually workshopping a concise way of putting 3 critical colors against one another for comparison sake, and this is the best looking and most concise approach out of all the drafts.
The second ring's rest mode is just a hue ring, but affected by the current HSV parameters. This is not only for providing demonstration of how the other colors would look with the same HSV settings (which can be used as anchor to compare later down the line and may also help the color deficient). It also happens to facilitate a great spot for putting colors and comparing them, **without ruining the tool's silhouette or disabling the "rotating" angle option.** 
If you're interested, you can ask on Discord to see the older drafts as well!

**Comment by amoruwu** [comment]
I don't really think a third color is needed! if it was needed it would make more sense  for the background/foreground colors to be there not last color you picked with a tool. 
![image](https://github.com/user-attachments/assets/f67d49b4-4ee6-45c1-bf73-1f5ad3c6155a)
I don't think ruining the silhouette matters especially when you're just comparing colors. the only reasonable option is having the foreground/background color as a third color to compare. But the picker tool already has history. 

Don't mind a second ring around the wheel though :0

**Comment by askmeaboutlo0m** [comment]
Preview is now outside of the wheel, like in Krita. Less distracting and obstructive that way. Ring diameter is fine as it is, which is significantly thicker than in Krita and about the same as MyPaint. Alignment is implemented.
