### ISSUE TITLE
Layer View mode when active layer and/or parent group is hidden

### ISSUE THREAD

**Issue by incoheart** [drawpile/Drawpile#1371]
I was happy when I found **Layer View** Mode, as it is my go-to in SAI2 to isolate active layer and flip through my sketches, but I thought it was a hassle that I have to modify the layer visibilty of the active layer and the parent group first before I could both view and modify it.  I want it to allow me to modify it and view it regardless of its original visibility. This behavior is in SAI 2 as **Show Alone Layer**.  I think **Layer View** could be changed to have identical behavior as SAI2's **Show Alone Layer** behavior. Or there could be a new **Show Alone Layer** view mode added. 

![show_alone_p_03](https://github.com/user-attachments/assets/102a1947-ecd2-4c5d-8478-706bc8f7c893)

In **Layer View** Mode, Drawpile keeps the active layer hidden if the parent group is set to hidden or if the layer itself is set to hidden, and it is impossible to modify the layer even though it should be the only visible. There is a No Symbol.

Krita has two settings like Layer View mode, and they are called **Toggle Layer Soloing** and **Isolate Active Layer**. **Isolate Active Layer** differs from Drawpile's Layer View mode because it shows the active layer even if it is set to hidden normally, and even if its parent group is set to hidden. It is impossible to modify the layer, though. There is a No Symbol. (Drawpile and Krita are both differing from GIMP where GIMP allows one to work on hidden layers). I don't find **Toggle Layer Soloing** in Krita to be useable and I don't understand why it is there as it doesn't let me toggle back and forth.

Paint Tool SAI 2 has **Show Alone Layer**, and it allows the active layer to be shown even if it is set to hidden, and even if the parent is set to hidden, and it is possible to modify the active layer. Both Drawpile and Krita block the layer from being editted, but you see Paint Tool Sai 2 has a special behavior that allows the parent group to be somehow set to visible while the other sibling layers are set to hidden.

![show_alone_p_01](https://github.com/user-attachments/assets/44cf1045-0669-4486-a201-ef9bbb519845)

SAI2 briefly changed this behavior in 2019 as seen in the [changelog](https://www.systemax.jp/en/sai/history_v2.txt) but it was reverted in 2020. The changed behavior was to have the sibling layers that were in the same group would also be shown, if I recall correctly. It made the setting unuseable because I used **Show Alone Layer** as a way to work on individual layers and individual layers only. The fact that is was backtracked showed how useful this behavior is in SAI2.

(excerpts of the SAI2 changelog)
**2020-08-28**
[Changes]
- [Show Alone Layer] Changed the layer visibility operation for descended layers of [Show Alone] layers to the normal visibility change.

**2019-07-28**
[Changes]

[Layer] Show Alone mode is changed to chase a current layer among only sibling layers.

**Comment by askmeaboutlo0m** [comment]
Yeah, this is arguably a bug with how the layer view mode is implemented. In a similar vein, there was a report by MachKerman on Discord about how blend modes with alpha preserve don't work in this mode, since they will just end up entirely blank.

Instead of hiding all layers except the active layer, Drawpile should really paint the layer directly on top of the canvas background, rather than have it be affected by other stuff in the stack.

**Comment by askmeaboutlo0m** [comment]
This is fixed now and available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

It now shows the layer actually in isolation, ignoring any parent opacities and the layer's own visibility, instead just blending it directly with the background.

Thanks for reporting it!

**Comment by incoheart** [comment]
Thank you so much for making that change! It allows me to draw even when parent group is hidden. Not even Krita lets me do that. Drawpile is now a better app for sketching for me than Krita; thank you so much.

**Comment by askmeaboutlo0m** [comment]
You're welcome, glad to hear!
