### ISSUE TITLE
Shortcut Searching

### ISSUE THREAD

**Issue by MajorCooke** [drawpile/Drawpile#1377]
Blender has the ability to search for actions, and shortcuts separately. It'd be very helpful to add the ability to search one or the other so I can make sure I don't override a keybind by mistake.

**Comment by askmeaboutlo0m** [comment]
Yeah, being able to search for the keys themselves would be helpful. Currently working on #1367 and #1368, so probably makes sense to do this along with it.

**Comment by askmeaboutlo0m** [comment]
Implemented in the continuous release now: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting!
