### ISSUE TITLE
Flip Canvas ability

### ISSUE THREAD

**Issue by MajorCooke** [drawpile/Drawpile#1380]
SAI has the ability to invert the canvas which I need in order to draw my strokes at certain angles, since otherwise it's very hard to get it down naturally. Can this be implemented here too?

**Comment by MorrowShore** [comment]
By invert, do you perhaps mean rotate, mirror or flip?
At the bottom, you can see three small icons that do those.
![image](https://github.com/user-attachments/assets/1fb3de78-4675-4da4-8a11-559ec9ab4427)

**Comment by MajorCooke** [comment]
Flip the canvas. But there is no shortcut keybind for it.

**Comment by askmeaboutlo0m** [comment]
The actions are in the View menu, called Flip for flipping the canvas upside-down and Mirror for mirroring horizontally. The default shortcuts are C and V respectively. Unless that's not what you're looking for?

**Comment by MorrowShore** [comment]
Flip is bound to C.
You can conveniently search for keybinds now, like so:
![image](https://github.com/user-attachments/assets/a1bae715-6f1a-49e1-bdb7-4f063f9888b7)

**Comment by MajorCooke** [comment]
Ah, I thought that would've been in the "Canvas shortcuts".

**Comment by askmeaboutlo0m** [comment]
Yeah, it's not too obvious to a user what the difference between an global shortcut and a canvas shortcut is. Unfortunately they can't really be conflated into a single table, since canvas shortcuts don't necessarily even involve the keyboard, but the UI will change to bring it at least somewhat closer together.

**Comment by MajorCooke** [comment]
Well I was actually wondering, since it deals with canvas operations like rotate and such, maybe it would be better to move "flip" to the canvas shortcuts?

**Comment by askmeaboutlo0m** [comment]
"Canvas shortcuts" refers to things you do on the canvas specifically, like scrolling on it, middle clicking on it, holding a button and dragging etc. Those things have different meanings outside of the canvas, e.g. if you scroll on the layer list, it scrolls the list up and down, and if you middle-click on a text field it pastes (at least on Linux.)

On the other hand, regular action shortcuts are accessible across the entire window, you don't need to have your cursor over the canvas. They are also always invoked with the keyboard.

The way you set these two kinds of shortcuts is very different, the former lets you deal with modifiers and axes and whatnot, while the latter is just pressing a key or some chord and it invokes a singular thing as if you picked through the menu.
