### ISSUE TITLE
Horizontal Flip

### ISSUE THREAD

**Issue by MajorCooke** [drawpile/Drawpile#1386]
Would it be possible to add a horizontal version of flip? As a user coming from SAI(2), it'd help a lot to have one since I'm much more used to that one than doing so vertically.

Unless there is a way to change the Flip shortcut to be horizontal instead of vertical?

**Comment by askmeaboutlo0m** [comment]
Flipping is upside-down. Doing it horizontally is "mirror".

**Comment by MajorCooke** [comment]
Hmmm. I wonder if it would be a wise idea to add alternative tags to them that the search functionality can pick up. Otherwise, I think you can definitely see this can be a bit confusing.

**Comment by askmeaboutlo0m** [comment]
Maybe, although "flip" for horizontal mirroring seems like the wrong word to me in this case. It may be my non-native English, but if you e.g. flip a pancake, it goes upside-down, whereas a mirror hangs upright and so it's horizontal.

It would make conceptual sense to include additional tags or something into the shortcuts, but it would be effectively impossible to translate to other languages.

**Comment by askmeaboutlo0m** [comment]
There's now an extra, hidden "detail text" for these two shortcuts, which in English mention both "mirror" and "flip" so that they'll both show up when searching for them. Thanks for suggesting!
