### ISSUE TITLE
Build with kf5-imageformats for JXL support

### ISSUE THREAD

**Issue by incoheart** [drawpile/Drawpile#1392]
It would be cool to be able to build Drawpile with [kf5-imageformats](https://invent.kde.org/frameworks/kimageformats) installed. It's a qt image plugin made for KDE and it works in environments like LXQt to have, most primarily, JXL support.  The role of the custom JXL plugin for Qt being satisfied by kf5-imageformats is described [on its Github Page](https://github.com/novomesk/qt-jpegxl-image-plugin) as using kimg_jxl.so, if that information helps. LXImage-qt and Nomacs obtain read and write support  when kf5-kimageformats is installed (it's spelled differently [on Fedora](https://packages.fedoraproject.org/pkgs/kf5-kimageformats/kf5-kimageformats/)). 

I noticed that when Drawpile is built the file explorer when saving/exporting/opening has thumbnails like LXimage-qt in its own file explorer.  It looks very nice. So  it occurs to me that it would be cool to be able to view and open JXL images in Drawpile's file explorer since I have sketches and reference pictures and finished drawings saved in that format. KF5-imageformats would also add read and write support for AVIF, I think.

**Comment by askmeaboutlo0m** [comment]
According to their README:

> This framework is licensed under the LGPLv2.1

That's not compatible with Drawpile, we need at least version 3. So unless they update to version 3 or add an "…or later" clause, including it is out of the question to begin with.

It also does not in itself bring support for stuff like JPEG XL, that's another external library it uses. We would have to build and ship that and kf5-imageformats on all platforms, which is a lot of work and increases the size of the package. For a feature like the support of a relatively obscure image format, this is very unlikely to happen.

The file explorer you see is likely the one your system uses, which it will integrate with via XDG desktop portals. On my system without those, I just get the regular Qt file explorer, which doesn't have such previews.
