### ISSUE TITLE
Remove pointless default permissions on Android

### ISSUE THREAD

**Issue by askmeaboutlo0m** [drawpile/Drawpile#1405]
For some reason Qt requests several default permissions on Android that appear to be pointless: camera, microphone and viewing network connections. The latter may be required because of its internals, but the former two should definitely be removed because we don't use anything related to them.

Presumably this is something we'd have to adjust in the AndroidManifest.xml.

**Comment by MorrowShore** [comment]
It does not prompt for those permissions.

Even though Microphone, Camera and files are listed in the app's permissions, Drawpile never actually asks for them, and so, they are disallowed per default on Android 14+.

Would be nice for them to disappear then.

**Comment by askmeaboutlo0m** [comment]
This is implemented now, but could probably use some testing on different devices.
