### ISSUE TITLE
Selection keybinds during transform

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1415]
This feature involves being able to Ctrl c, Ctrl x, and backspace/delete during transform, to copy, cut and remove either the current state of the transform area, or the original area selected for transform.

**Comment by amoruwu** [comment]
[duplicate of issue ](https://github.com/orgs/drawpile/projects/1/views/1?pane=issue&itemId=64038646&issue=drawpile%7CDrawpile%7C1313)i made in may!

**Comment by askmeaboutlo0m** [comment]
Yep, duplicate of #1313.
