### ISSUE TITLE
SSL connection fails with a CA-issued certificate

### ISSUE THREAD

**Issue by codl** [drawpile/Drawpile#161]
The docs say that, “Unlike web browsers, Drawpile does not utilize PKI, meaning it considers self signed certificates just as valid as those signed by a certificate authority.” However, when I try to connect to a server that is using a certificate issued by a CA, the connection fails with the following:

```
SSL error: 11 "The issuer certificate of a locally looked up certificate could not be found"
SSL error: 17 "The root CA certificate is not trusted for this purpose"
SSL error: 12 "No certificates could be verified"
Login failed: "The issuer certificate of a locally looked up certificate could not be found
The root CA certificate is not trusted for this purpose
No certificates could be verified
"
Socket error: "The issuer certificate of a locally looked up certificate could not be found"
```

Additionally, if I try to connect with the server's IP address instead of its hostname, the last line is instead:

```
Socket error: "The host name did not match any of the valid hosts for this certificate"
```

**Comment by callaa** [comment]
This should now (finally) be fixed in the latest master branch version.
