### ISSUE TITLE
feature : brush/layer screentones

### ISSUE THREAD

**Issue by blurymind** [drawpile/Drawpile#181]
In this case, Paint tool is the best example of well implemented screentone effects. Each/Any one of the three approaches would be awesome

-screentone tiling pattern can be set to brush
- screentone tiling pattern can be set as a non destructive layer effect - layer texture.
  ![sai-paper-texture](https://cloud.githubusercontent.com/assets/6495061/6396796/3abb8bbe-bde9-11e4-999a-fdb14cfd5d13.png)

-screentone can be set via a "layer clip" tick box  
http://youtu.be/vMo7NC2ukA4?t=1m45s

**Comment by askmeaboutlo0m** [comment]
Drawpile 2.2 has option 3 by sticking the layers into a group and using the Recolor blend mode: <https://docs.drawpile.net/help/draw/clipping>

And also sorta option 1 through some screentone brushes that come from MyPaint.
