### ISSUE TITLE
Usability - Pen pressure

### ISSUE THREAD

**Issue by Phoninskis** [drawpile/Drawpile#200]
It seems like whatever i set my Intuos5 pen tablet sensitivity to or adjust the Input settings, I'm not really getting satisfactory thick to thin lines??  I mean It's cool this program even has it anyways, and I know this is still very new and I support it entirely I'm just hoping for the lines to maybe resemble a bit more so to the way openCanvas pressure does or possibly PS/SAI?  Maybe some sort of Stabilizer option would be a work around I don't know

![image](https://cloud.githubusercontent.com/assets/12792460/8028925/07859d3a-0d6b-11e5-924e-9f6874827cf4.png)
![image](https://cloud.githubusercontent.com/assets/12792460/8028951/6c68b4a8-0d6b-11e5-8c05-9e8809b1422a.png)

I generally use smaller brushes, so that could be why It looks bad, but it'd still be nice to be able to create thicker lines with smaller brushes.  On a sidenote since I didn't really want to create another thread, would It be possible in the future to be able to save brushes similarly like SAI?

![image](https://cloud.githubusercontent.com/assets/12792460/8028929/186f92ea-0d6b-11e5-9656-bb59b8affee7.png)

**Comment by callaa** [comment]
Have you tried adjusting the pressure curve in the "Input" dock? You can also adjust the smoothing strength there (although the current smoother is very simple, there is an open feature request for a better one: #179)

I've been thinking about improving the brush dock lately, and it is something I could do in Drawpile 2.0 (the development of which starts right after I've released 1.0.0, which should be fairly soon now.)
I opened a new issue for designing the new dock: #201

**Comment by Phoninskis** [comment]
Yes, I have tried messing around with the Input dock and the actual tablet input levels itself too!  Ahh thank you for answering tho i'm pretty excited for these!

**Comment by AliceFox** [comment]
It's easy to feel what's right but putting this issue into words is hard.

![strokes1](https://cloud.githubusercontent.com/assets/4224830/8300089/f4f5e630-194e-11e5-8192-4376f1071537.jpg)

The pressure applied bounces up or down with very little input or isn't applied enough. Notice how the width of strokes doesn't change much except under a very firm Wacom setting and lots of custom settings.

This is the most responsive brush I can create in Drawpile at the moment:

![strokes3](https://cloud.githubusercontent.com/assets/4224830/8300096/185e8834-194f-11e5-8fec-53999bbaacb2.jpg)

The minimum/maximum size of the stroke is much improved this way but there's still something off about minimum pressure. It's very difficult to get a thin line which is more apparent if you test with a large brush.

I also had to lower smoothing which makes the stroke faster and more responsive (good) but the line becomes jagged (bad). The faster I can apply a line the better it feels. Waiting for smoothing can cut off a stroke abruptly and limits size range. Right now I only see two options: have a jagged responsive line or a smooth unresponsive line.

![strokes2](https://cloud.githubusercontent.com/assets/4224830/8300113/3b93ee70-194f-11e5-81fa-a6ab3bc01e96.jpg)

Here's an example from Mangastudio (the most responsive program I can think of but even Photoshop can manage pressure variance with the right brush). There's more control and no erratic behavior.

**Comment by callaa** [comment]
![pressuretest](https://cloud.githubusercontent.com/assets/464576/8311872/fd2eafe2-19e1-11e5-934d-ef0c3f0befdd.png)

(The above test was made with a Wacom Bamboo on OSX, smoothing at around 40% and 17px brush)

Drawing thin lines with a large brush is indeed difficult. This, I think, is a quirk of the brush engine. Adopting MyPaint's brush rendering might help here.

I'm not noticing any bounciness in the pressure, though.  That might be driver related. Try if enabling the tablet bug workarounds setting from the preferences dialog helps. It makes Drawpile use mouse events for coordinates and tablet events for pressure information and can often fix jittery edges. For some reason, coordinate data in tablet events seems to be fairly noisy compared to mouse events. I'm not sure if this is normal and if other applications use some kind of special filtering to overcome it.

**Comment by AliceFox** [comment]
![smoothing](https://cloud.githubusercontent.com/assets/4224830/8313724/a1cfd592-19b2-11e5-8de4-919232cdff70.jpg)

The bug workarounds setting definitely helped smoothing. Checked on and off here at 0%. But I can see some jagged blips in your own strokes and the first two don't taper off nicely - still better lines than I can get with a Wacom Intuos4 on Windows 7, though.

Maybe I'm blind but with all of MyPaint's brush settings I can't find a minimum radius option, only random. Hmm.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
