### ISSUE TITLE
Straight line tool --> curved line tool

### ISSUE THREAD

**Issue by blurymind** [drawpile/Drawpile#209]
Mypaint has this feature in which after you create a straight line, you can actually bend it while holding shift. Additionally after it is curved, one can continue to shape it by holding shift.
http://www.davidrevoy.com/article154/mypaint-1-1-a-guide-through-the-new-features

Click and hold to create a straight line, release, click and hold again while holding shift to bend the line - you can do it multiple times.Clicking again without holding shift applies the line. mypaint's approach is more flexible because you can increase the width of the curve.

Tvpaint has this implemented as 3 point curve:
http://www.tvpaint.com/doc/tvp11/index.php?id=lesson-first-steps-drawing-tools-presentation
here is a demo:
https://www.youtube.com/watch?v=DGZP2OrO-E4
click and hold to create a straight line, release to initiate its bending, click again to apply the line.

This is incredibly useful when you are inking a character or an object that has long and clean lines that are difficult to do by hand with a tablet.

**Comment by callaa** [comment]
A bezier curve tool is now implemented. It's used the same way as Krita's curve tool, because that was easier to implement.
