### ISSUE TITLE
Recording Video Bug and Suggestion

### ISSUE THREAD

**Issue by Hirabunny** [drawpile/Drawpile#227]
So, I love this a lot! I only have two issues with it.

Bug: When I export to video, I only get a black screen with the full replay length [when not using audio] or a bugged out video that just doesn't play [when using audio]. I know audio's not perfect though, so I understand that. I just don't know why I'm getting no video when I don't use it. 
I use mostly the defaults:
Video format, 25 FPS, 480p, no soundtrack, Avi file. Is it something I'm doing wrong?

Suggestion: For the above, I have a simple enough solution being saving it as a .Dprec and then playing it back, recording the playback with a screen recorder and saving that video. It gets the job done! I would just like to ask if there's maybe a way to turn off the big bulky tag that shows what layer I'm on and have just a dot or something like that instead? I'm sorry if this is already possible, I just can't find it and the layer label is kind of in the way at times. 

Regardless, thank you for bringing us such a lovely program! c': 
Apologies if this has already been brought up!

**Comment by callaa** [comment]
All the setting combinations should work, so it clearly is a bug in Drawpile.
Which ffmpeg version do you have installed? I just tried it with version 2.7.2 and it worked (and I recall has worked with older versions too.) On another try, I did get a blank video, so I'll have to do more testing.

Another way might be to export the video as an image series, then convert that into a video with ffmpeg or something else. This will also give you more control over the quality.

The tags can be turned off by unchecking the *Show user cursors* item in the *View* menu.

**Comment by Hirabunny** [comment]
I'm using the newest version of ffmpeg so it's the same situation with your instance, I'm assuming. I may do the image series, it just takes a lot more space in some instances and I need to clear my computer clutter, so after I clear it out a little more I could be able to do that!

Thank you for the help on the second point too! I'm a little blind when it comes to things I'm freshly looking at. Thanks for the quick reply and I hope you have a fantastic day and/or night!

**Comment by Wade821** [comment]
Issue still exists, verified bug.

**Comment by Wade821** [comment]
Closing this issue, duplicate.
