### ISSUE TITLE
Small adjustments to chat

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#235]
Ctrl+C shortcut with selected text.

When resizing chat drawer, it "sticks" to top(old text) and you have to drag it back down after resizing.
Requesting it stick to bottom, most recent text.

**Comment by Wade821** [comment]
Ctrl + C
https://drawpile.net/news/release-2.1.9/

This would be a nice option only if it was toggleable to turn on and off via right clicking chat menu to turn on or off.  I feel it would be better labeled "stick to bottom" since the inverse might not make much sense to some people.

**Comment by notfood** [comment]
For the chat resizing issue see: https://github.com/drawpile/Drawpile/issues/427
