### ISSUE TITLE
Selection rotation

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#245]
Requesting ability to rotate a selection.

**Comment by callaa** [comment]
This is already implemented. Hold Alt and drag to rotate.
This feature is requested very often, so it is clearly not very discoverable. So, I'll repurpose this issue as a "make selection rotation discoverable" request.

**Comment by pachuco** [comment]
Ah, forgot to add note on this.
I was trying to Ctrl/Shift/Alt+Drag using the handles. instead of inside bounding box.
No wonder I missed.

**Comment by Wade821** [comment]
Rotation mode changed in Drawpile 2.1.12 to be more discoverable. Closing issue.
https://drawpile.net/news/release-2.1.12/

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.
