### ISSUE TITLE
Cosmetic change to selection tool

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#246]
Maybe have the bulky markers on the bounding box of a selection disappear while dragging/resizing.
Oh, better. Having them disappear when holding mouse clicked on box.

**Comment by Wade821** [comment]
Released in this version, closing issue.
https://drawpile.net/news/release-2.1.12/

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.
