### ISSUE TITLE
Recording Video Issues

### ISSUE THREAD

**Issue by Shrineheart** [drawpile/Drawpile#248]
I've been trying to test out the recording features and it's been a bit of a trial. I'm not sure if I'm not doing things correctly or if something else is up.
I downloaded ffmpeg, I set it up so that drawpile can find the executable. That worked just fine. Made a few recordings and tried to export as various file types. They will sometimes export but only as 1 second vids with nothing in them. Other times they don't export at all. And still other times they export but are corrupted.
Another issue is that sometimes I just get a static image save file instead.
I really love the program so far I just wish I could utilize this feature.

**Comment by Wade821** [comment]
Issue still exists, verified bug. See older related issue, #227

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.

**Comment by callaa** [comment]
Closing this issue since the old ffmpeg based exporter has been replaced with a webm exporter (which does have its own set of bugs, though.)
