### ISSUE TITLE
Add a portrait layout

### ISSUE THREAD

**Issue by namdoyle** [drawpile/Drawpile#253]
drawpile is now a wildscreen app,however , when work with tablet,most of the time need a portrait layout.For example,maybe the top of the view is the whole canvas,all the tools panel place near the bottom.

**Comment by Wade821** [comment]
Unfortunately, this is more complicated than just "add a portrait mode." I think this would require serious consideration. The docks would have to be redesigned to better fit a portrait layout. I'm not sure about the long term viability about this however... is this something you're still interested in having as a feature? Do you have any examples of other programs where you can show the difference between landscape and portrait modes?

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Docks are now allowed to be docked anywhere, which means you can make yourself a portrait layout. There's also a layout called "Horizontal" in the new layouts dialog (View > Layouts...) that looks like this:

![image](https://user-images.githubusercontent.com/13625824/227512060-0b3aefa1-2b03-4652-8802-920c0206a0e4.png)

This feature will be in Drawpile 2.2.
