### ISSUE TITLE
Sometime palm rejection (on wacom win8 tablet) not working....

### ISSUE THREAD

**Issue by namdoyle** [drawpile/Drawpile#255]
normal if the wacom stylus near the screen,palm rejection will be started. no ANY touch allowed,but when i using Drawpile, you will found that there is a very short time without palm rejection ( about 1 second), this issue keep happen about 20  times a minute.........

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
