### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by sasjakoning** [drawpile/Drawpile#256]
Hey, 

So ive been having this issue, not sure if its my laptop being weird or the program,
but whenever i first start up drawpile, it has no pressure. So i close the program and restart (which usually worked) but now it wont start up at all. it IS running on my computer. but for some reason it just wont show up.

Any fixes or tips for this?

Thanks

**Comment by callaa** [comment]
Does it show up in the task bar (assuming Windows) even when the window doesn't show up? Two things that came to mind first: could the window have opened somewhere offscreen? Second, when the program is closed, is it still visible in the task manager?

**Comment by sasjakoning** [comment]
No, its not visible in the taskbar, and i made sure my laptop isnt working on two monitors. whenever i close the program, it will also close int ask manager.

im using windows 10, by the way

**Comment by Wade821** [comment]
Are you still having this problem?

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
