### ISSUE TITLE
Moving stuffs always on top regardless of selected layer

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#258]
When working with selections, the selection appears always on top, regardless of which layer it's on and what other layers are above it.
It would make sense if the selection stayed in its place when operating on it.

**Comment by Wade821** [comment]
I just don't know of any particular programs that work this way off hand, but it makes sense to me.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming with Drawpile 2.2. Selections are now drawn on the selected layer, rather than way on top.
