### ISSUE TITLE
PSD import and export

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#260]
Requesting ability to import and export Photoshop PSD format, layers and all.
Very useful for those that want to remaster their drawings in external editors.

**Comment by Wade821** [comment]
From Callaa on the Official Drawpile Discord: "I actually have a private git branch kicking around somewhere with the beginnings of a PSD exporter. Haven't gotten it to work yet, though. The PSD format is very complicated and Adobe's official documentation is incomplete.

Krita has working PSD import/export, and I've tried to cross check with their implementation, but it still doesn't work"

Would like this too at some point.... :) 

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Since GIMP and Krita support the ORA format just fine, I don't think there's a need anymore for supporting PSD. If you really need it, you can just convert it using one of those programs, rather than Drawpile itself having to deal with such a monstrous format.

**Comment by askmeaboutlo0m** [comment]
Reopening this, since there's apparently piles of closed-source software that refuses to support ORA despite how simple it is. Since the PSD "spec" (in heavy quotes) is publicly available since a few years, there shouldn't be any licensing issues with the format anymore either.

**Comment by askmeaboutlo0m** [comment]
This is implemented and available in the continuous development release now: https://github.com/drawpile/Drawpile/releases/tag/continuous

Thanks for suggesting it!
