### ISSUE TITLE
feature: layer folders/groups , tags

### ISSUE THREAD

**Issue by blurymind** [drawpile/Drawpile#261]
Adding the ability to put layers in a folder would help tremendously in layer organisation.
![screen-shot-2012-04-07-at-8 40 02-am](https://cloud.githubusercontent.com/assets/6495061/9600296/000b31c0-50a3-11e5-9fcf-347bdea4687e.png)
- Layer organisation is very useful when many people are drawing on the canvas
- Layer folders would also come in handy for animation 
  Later on layer folders could be used to store animation frames, sepparating the animation sequence from the background properly and allowing for users to have more than one layers for the background image. You can also have multiple animation layers that way as well - where every layer folder is treated as an animation sequence!
  ![layerfoldersanimation](https://cloud.githubusercontent.com/assets/6495061/9600478/ee52cf50-50a3-11e5-84ba-f66b59e870c4.JPG)

This is actually how it is implemented in some other animation software. All the frames of an animated layer are stored in a folder. For now this would allow for a basic way to color animations done in drawpile properly. 

Previously you implemented a way to clean them up, this is the next basic feature that is needed for a minimalist workflow that alows the artist to get to a polished stage :)

Subfolders wont be needed I think. If you add the ability to attach "tags" or any sort of meta information to layers and layer folders, that would open the door for other fun things. For example tagging a folder as an animation sequence. Or tagging it as a background.

Adding metadata to a layer as to how many animation frames it occupies - that way to keep a drawing/pose longer you dont need to duplicate a frame layer many times.
There are probably many other ways meta tags can be used to solve design issues and limitations.

**Comment by callaa** [comment]
This is something I've been planning for a while. Probably not in 2.0, but sometime during the 2.x series.  It will also be good for interoparability, since right now Drawpile can't open ORA files containing layer groups (which both Krita and Gimp support) correctly.

**Comment by blurymind** [comment]
Here is a practical example of this put into practice. This is Clip Paint Studio EX - a japanese alternative to photoshop that is used by mangaka artists. They recently added animation features ported over from their other product - RETAS.

Basically they added a timeline, which stores all of the frames in layer folders. Each layer folder corresponds to the animation layer in the timeline editor. You can see it here:

![timelinestoringframesinlayerfolders](https://cloud.githubusercontent.com/assets/6495061/9604988/8526e492-50c3-11e5-9416-473974aff7b5.png)

I have a "lines" layer folder where my lineart frames are stored. I also have a "color" layer folder where my color for the lines is stored.

Each layer contains information as to where it is in the timeline and for how many frames (duration) it is held.

That is really enough to create a complete animation system with layers.

Right now we can not create animation timing. In order to keep a drawing.pose for longer than one frame, we have to duplicate it many many times- wasting valuable resources

**Comment by amfl** [comment]
I would love to see this implemented. Subfolders would also be useful.

I am especially interested in using folders to translate multiple layers at once around the canvas.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Folders/layer groups are coming in Drawpile 2.2.
