### ISSUE TITLE
No pen pressure with Wacom Cintiq Hybrid with latest version, .9 or .8?

### ISSUE THREAD

**Issue by rapinii** [drawpile/Drawpile#263]
Hi, my friend tried a bunch of version, including the latest one and can't get pressure sensitivity to work with her Cintiq Hybrid tablet. It works in other softwares. She has microsoft ink turned off as well as "enable pen pressure" turned on in Drawpile options. Looked around for solutions but we really can't find anything :( We really want to make this work because this software is otherwise soooo perfect compared to Opencanvas 1.1

Thank you!

**Comment by callaa** [comment]
Currently, the only advice I have is to make sure the wintab driver is installed. I'll have to look into implementing native tablet event handling, since Qt's built-in tablet support (which Drawpile uses) seems to just get more and more broken as time goes on.

**Comment by rapinii** [comment]
Which ones?

**Comment by goatsuu** [comment]
i am also having the same problem. im running wacom intuos pro on windows 8.1

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
