### ISSUE TITLE
Entire Window Moves When I Go to Draw

### ISSUE THREAD

**Issue by EPASketch** [drawpile/Drawpile#266]
Hey, all-- I would love to start using DrawPile, but I have a major issue with a glitch that's going on that I can't think of a work-around for! Basically what happens is that when I go to draw, the entire DrawPile application window moves around with it. It's bizarre.
Here's a GIF of what it looks like: https://i.gyazo.com/b422663e75f22c2da53d890158aa2133.gif
Here are some specs about my computer, in case you're wondering:
-Mac OS X, version 10.7.5
-3.4 GHz Intel Core i7
-8 GB MHz DDR3
-I use a Wacom Intuos 4 (corded, not Bluetooth)
The only thing I have strange is JTablet, to give pressure sensitivity to PChat sites, but many of my friends have that as well and nobody's heard of this issue. Help!!

**Comment by EPASketch** [comment]
Also, oh god, just to be clear-- I can do a number of troubleshooting things, but just this site alone is really confusing to me, so my apologies in advance. I tried to understand how to use that tablet… checker.. QT thing.. No idea what's going on there!!
Additionally, I've tried reinstalling DrawPile and my tablet driver multiple times.

**Comment by callaa** [comment]
Does this happen with both a mouse/touchpad and the tablet or just the tablet? And does it happen when you click/drag anywhere on the application or just the canvas area?
If if only happens in the canvas area, does unchecking or checking the "enable pressure sensitivity" or "bug workarounds" boxes in the preferences screen have any affect?

**Comment by EPASketch** [comment]
Hey! So I checked out toggling "Enable Pressure Sensitivity" and "Bug Workarounds", and the result is the same. I don't have a regular mouse to test this out with, but it happens whether I'm using my pen or my mouse on the tablet. It also allows me to click drop-down menus just fine, but anything with a slider lags, too, as do any of the tools. So, it seems like it's affected the entire application unless it's a simple click or drop-down situation, like buttons.

**Comment by EPASketch** [comment]
Sorry if I seem pushy, I just wanted to be sure you saw that I replied to this! :) I ordered an external hard drive, so I'm going to upgrade my OS soon and see if anything changes, and if not then I'll probably try removing a few things that could possibly be conflicting with the software after I back up my system...

**Comment by callaa** [comment]
Hi! I saw the reply but I haven't come up with any ideas yet on what could be behind the bug. Let me know if upgrading the OS fixes it. I have OSX 10.10 myself and I remember the program working on 10.9 ,and I think people have reported that it should work on 10.8 too.

**Comment by HyperDashPony** [comment]
I've been having the same problem. Very similar specs to EPASketch (Same version of OSX), but I'm not using a tablet right now (It decided to break) and it's still doing it.

**Comment by EPASketch** [comment]
Hey, All--
  I recently updated to Yosemite, and the program actually works now! It's a little slow, but the glitch isn't happening anymore. I'm not sure if anything related to Java or whatnot reset when I update (I had to reinstall an older Java so I could use PChat, but I didn't have to reinstall the JTablet stuff, which I was wondering was the source of the error, but apparently not!), but it looks like that wasn't part of the problem. Very odd, but there's that much!

**Comment by HyperDashPony** [comment]
It works when I go full screen, fortunately. You might wanna try that, if
you're having this problem.

**Comment by callaa** [comment]
The bug may have been introduced in the update to Qt 5.5. Here's the latest version rebuilt with Qt 5.4: http://drawpile.net/files/osx/Drawpile%201.0.2-qt5.4.dmg
Does this version work?

**Comment by Wade821** [comment]
Given the age of this issue, are you still experiencing a problem with this?

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
