### ISSUE TITLE
Feature Request: Toggleable Eraser

### ISSUE THREAD

**Issue by KurinPawpad** [drawpile/Drawpile#268]
Krita-like toggleable eraser.  Tap E to switch to eraser and,  if currently in eraser mode, tap E again to switch to last brush.  I know you can just tap E/B to do the same, but this way you don't have to remember what brush you were using.

**Comment by callaa** [comment]
A related feature already exists: if you hold down the eraser (or any other tool) shortcut, the tool will be selected temporarily. When you release the button, the previous tool will be restored.

**Comment by KurinPawpad** [comment]
the temporary-on-hold feature is nice (Just tried it out), but for more than one stroke (or for any length of time) it's a little awkward.  I know there's probably many workarounds or other solutions as well.

**Comment by Wade821** [comment]
This feature doesn't seem to work anymore on the Windows client (though I'm still somewhat new to drawpile). :C

It's keeping me from using color picker to do an area color picker for the average color between two colors (and thus shade/blend). I've asked a few people about it. The Alt + C to hide chat command also doesn't appear to be functional.

**Comment by callaa** [comment]
The eraser tool (and all other tools as well) is now toggleable in version 2.0.4.
