### ISSUE TITLE
Drawpile not registering pen pressure.

### ISSUE THREAD

**Issue by PYC-Art** [drawpile/Drawpile#276]
Even after ticking the pressure boxes, and setting it to "Stylus," Drawpile will NOT register my tablet's pen pressure, whilst my other drawing programs will.

**Comment by pachuco** [comment]
It might be that you need to plug in tablet before starting drawpile. I think this is the case with me.

**Comment by hexaditidom** [comment]
Same bug here. Using Bamboo Fun tablet with latest drivers, Drawpile won't recognize pen pressure, even with "Pressure" and "Workarounds" both checked in the preferences box. In fact, this is the case even when using previous versions of drawpile (in which pressure sensitivity used to work.) I'm guessing this is a Qt issue.

**Comment by VeeVeeTheArtist** [comment]
same here, only difference is that the program crashes whenever the pen tries to drag down or up like it's on a browser page. It's rather frustrating.

**Comment by Wontoon** [comment]
I'll have to chime in and say that pressure is not present on a Surface 4, with WinTab drivers installed. Other programs I've tested have pen pressure enabled, however.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
