### ISSUE TITLE
Jagged edges on fast strokes

### ISSUE THREAD

**Issue by vdh** [drawpile/Drawpile#281]
![drawpile bug](https://cloud.githubusercontent.com/assets/573501/11454642/af86e10e-967f-11e5-8c0d-9ca9116413cd.png)

I'm using Drawpile 1.0.2 on Mac OSX El Capitan 10.11.1, with a Wacom Intuos 5 touch (PTH-650)

This is a particularly frustrating show-stopper for me, because it makes it next to impossible to draw anything with circular shapes. If I have to spend all my time intentionally slowing down on every stroke I'll never be able to focus on what I'm doing.

**Comment by callaa** [comment]
This is related to issue #179. An improved stabilizer that generates extra smoothed points for fast strokes is needed.

**Comment by Wade821** [comment]
As Callaa said, this is already referenced in an earlier issue. As such, I'm closing this issue to clean up duplicate points. Any further questions or concerns regarding this problem should be commented within that issue.
