### ISSUE TITLE
Drawing Tools Lag

### ISSUE THREAD

**Issue by Hyenaface** [drawpile/Drawpile#282]
Just recently tried Drawpile but all the brush and pen tools etc are lagging to the point of being unusable. The lag is present regardless of using a tablet or the mouse. The select/drag tool and the laser pointer, however, don't lag at all. I also tried hosting a session with a friend and he could see the everything i was seeing. When he tried to draw Drawpile just froze up. If you need any more information i'd be happy to provide it, and thanks in advance for any help!

**Comment by callaa** [comment]
Does the size of the brush affect how badly it lags? E.g. if you use the hard edged pen tool and a thin stroke, is it faster than a wide soft brush?

**Comment by pachuco** [comment]
I get a bit of lag with input smoothing turned on. Did you check that?

**Comment by Hyenaface** [comment]
Drawing with different sizes and hardness doesn't appear to make a noticeable difference to the lag. Turning off input smoothing doesn't make much difference either.

**Comment by Wade821** [comment]
Are you still having this problem?

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by notfood** [comment]
Closing: Stale issue
