### ISSUE TITLE
Graphical issues

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#283]
https://a.pomf.cat/ddujkz.mp4
Moving cursor over canvas appears to distort the image.
Dragging the canvas away and back restores correct image. Same with switching to other app and back.

https://a.pomf.cat/txvkgr.PNG
This time around, I drag small window over DrawPile client. DP is not focused.
On focusing, the state of the UI is restored.

**Comment by pachuco** [comment]
Another interesting aspect of the first issue is that I get it between 900% zoom and 1450%(inclusive).

**Comment by Wade821** [comment]
Are you still having this problem? Might be worth joining the official Discord and posting any images/video there.

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by pachuco** [comment]
I believe this issue to be related to large cursor size and my AMD graphics card and video drivers I had at the time, rather than Drawpile itself, now that I think about it.

**Comment by Wade821** [comment]
Well those links are no longer valid. I can't see them anyway, and yeah... but you opened the issue. It might not be something that can be supported but it's hard to see what you're talking about. Trying to close duplicate issues and make this more manageable for Callaa.

**Comment by Wade821** [comment]
Only labeling this as support due to the non-standard setup in Windows XP.

**Comment by notfood** [comment]
Please, open a new issue if it's still happening.
