### ISSUE TITLE
Auto host reconnect

### ISSUE THREAD

**Issue by makkuro-4500** [drawpile/Drawpile#287]
My built- in host session has recently been disconnecting often, so I was thinking this would be helpful to have. 
If this can already be done, it would be nice for someone to inform me of how to do so.

**Comment by callaa** [comment]
This is currently not possible, since the whole history needs to be downloaded again when reconnecting. It might be possible to implement a quick reconnect feature in version 2.0, though.

**Comment by Wade821** [comment]
Added in 2.1.16.

https://drawpile.net/news/release-2.1.16/
