### ISSUE TITLE
Magic Wand Tool. Select a whole area with the same color.

### ISSUE THREAD

**Issue by ChristianJohnsten** [drawpile/Drawpile#292]
To select an area that is all the same color or near the same color (threshold control) would be very useful. Especially for removing, say white backgrounds on images, or removing a color to and changing the contents in that selection. #

**Comment by askmeaboutlo0m** [comment]
Since selections have been rewritten now, adding a magic wand tool has become possible. It's implemented and available in the continuous release: https://github.com/drawpile/Drawpile/releases/tag/continuous

Thanks for suggesting!
