### ISSUE TITLE
Server build needs an overhaul

### ISSUE THREAD

**Issue by ChlorideCull** [drawpile/Drawpile#294]
The stand-alone server build feels pretty neglected for various reasons:
- It also builds and bundles the themes, sounds and palettes.
- According to the master CMakeList, it defaults to systemd of init integration, but didn't compile it in until it was specified on the command line.
- The systemd service/socket and usertool in `server/` should really be bundled, but isn't.
  - Said service file should also use the configuration switch so you can change settings more easily.
  - Should also bundle with a config file that has sane defaults.

This applies to both the stable 1.x branch and the upcoming 2.x, with some changes. I can help out if I get some time over, but that might be a while.

**Comment by callaa** [comment]
Good points. I'll take a look at these for the next release, but I'll gladly accept pull requests too.

**Comment by velusip** [comment]
Bit of an old post, but it's still open, fair game!

Since the 1.0.5 stable server doesn't fork, the unit Type should be set to simple and the NotifyAccess to none.  The supplied unit file should be updated to reflect this.

**Comment by askmeaboutlo0m** [comment]
This is already done since, uh, a long time ago. The unit file is also correct, the server does send a notification, so Type=notify and NotifyAccess=main are correct.
