### ISSUE TITLE
Problem with a stylus in FullScreen mode

### ISSUE THREAD

**Issue by RegisterWindowClassEx** [drawpile/Drawpile#303]
Sorry for my english... So, after some presses of F11 button (set FullScreen mode and return to normal mode), when i drawing, cursor shifts up... I use tablet PC with touchscreen and pen, and the program draws the line in other place, not where i draw. It seems like some correction mechanism with pen coordinates in program for fullscreen mode. When I bring the pen to screen, i see the laser point in the same place, where i bring, but after touching the cursor jumps on 10-20 px upper the real pen position.

The problem arises exactly in fullscreen mode, after several returns to normal mode and back. When i return the program in normal mode, the cursor ceases jumping. When i set fullscreen mode, the cursor starts jump again.

Thanks

**Comment by RegisterWindowClassEx** [comment]
The problem arises exactly in fullscreen mode, after several returns to normal mode and back. When i return the program in normal mode, the cursor ceases jumping. When i set fullscreen mode, the cursor starts jump again.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
