### ISSUE TITLE
Tools request 

### ISSUE THREAD

**Issue by blvk** [drawpile/Drawpile#309]
I just discovered this program and am super ecstatic about it. It's pretty much the perfect successor to Paintchat and OC.  

Here are some features I'd really love to see:

**Stabilizer**: The smoothing function is nice, but it would be amazing to have this available. It weights/"lags" the line and is available in SAI for example.

**Pattern Brush/Fill**: Maybe just some nice halftones or textures, possibly customizable?

**Custom Brushes**: Ability to create our own brushe and/ or save brush settings.

**Comment by Wade821** [comment]
Closing this issue out since there are multiple feature requests and the fact that this already exists in other issues. If you have further ideas or feedback, please comment on those issues accordingly

Stabilizer requested in issue #179 
Pattern Brush in #181
Custom brushes in #617 & #657
