### ISSUE TITLE
Project name change

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#31]
Since the project was started 7 years ago, Drawpile is finally approaching the first officially stable 1.0.0 release. In this time, the server and networking code was rewritten at least twice, the toolkit was updated from Qt 4 to Qt 5, and a few features, such as undo/redo, were implemented that I had originally planned for after 1.0.

For a proper 1.0 release, I think the project could use a a little freshening up by giving it a new name. The name change will take place on the 1.0.0 release, or before, depending on how quickly I come up with something I like.

Suggestions for the new name are welcome!

**Comment by psy0rz** [comment]
For your info: I started using the name for my project: https://github.com/psy0rz/etherpaint

Its like etherpad, but for simple drawing and scribling. (and very realtime)

Edwin
