### ISSUE TITLE
MessageQueue timeout

### ISSUE THREAD

**Issue by Psarius** [drawpile/Drawpile#310]
I'm running a server with the latest version (1.0.2) on windows. Like issue #204 (which has been closed), myself and other clients are trying to join a session, but end up timing out.
After attempting to join, the server says:

```
MessageQueue timeout 
QIODevice::write (QTcpSocket): device not open
```

If there's a solution, I would love to know! If there's not, I hope I can help however I can.

**Comment by callaa** [comment]
A MessageQueue timeout occurs when the other end hasn't replied in long enough time. (The default at the moment is 1 minute.) Does the login proceed at all? IIRC, in the old issue, the problem was that the client was locked up while catching up with the session and didn't respond to pings, which resulted in the server disconnecting them. However, if the login doesn't complete at all, it sounds more like a network problem.

**Comment by Psarius** [comment]
Yes, it shows them as logging in (then logging out when they timeout). Is there a way to change it to something longer than 1 minute?

**Comment by callaa** [comment]
For the built-in server, the timeout can be changed in the preferences dialog and for the standalone server with the `--timeout` argument.

Does the problem occur when users are joining brand new sessions or does it only affect long running sessions with lots of history to download?

**Comment by Psarius** [comment]
I'll try using a longer timeout, but yes, it occurs when the session has been up a while.

**Comment by pachuco** [comment]
I'd like to add info to this issue.
I am connecting to own dedicated server on localhost. In-progress dprec is currently 16 mb.

The client struggles to play back dprec and disconnects.
The dedicated server outputs same message as in OP post.

**Comment by Wade821** [comment]
Given how old this is, I'm going to close this issue to reduce the number of open issues. If this is still a problem, please comment so we can reopen this issue. Or join the Discord server as noted below. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
