### ISSUE TITLE
OP status passed around willy-nilly

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#315]
I dunno how OP status is tracked, but quite often, it gets passed to other people who are not supposed to be OP. I've had layers deleted and blanked this way.
I host dedicated server.

I suggest registering via providing password, either via chat command, or some other place in UI.

**Comment by callaa** [comment]
At the moment, there must always be at least one operator per session. If the last OP leaves, the server automatically grants op privileges to the user who has been in the session longest. However, now that the server supports user authentication, new operator schemes could be supported.

For example, the server could remember which (authenticated) users were granted op status and restore it when rejoining a session, and allow operator-less sessions.
