### ISSUE TITLE
No pressure sensitivity using Wacom Cintiq 13HD with drawpile 1.0.2

### ISSUE THREAD

**Issue by Feldherren** [drawpile/Drawpile#316]
I use a Wacom Cintiq 13HD tablet for drawing, and whilst I can draw with the tablet, drawpile 1.0.2 is not picking up any varying pressure from the tablet.

**Comment by Wade821** [comment]
It's been a while, woo boy. But if you're having an issue, I'd be happy to help. Please let me know if it's still ongoing. If it is, tell me the following:

- do you have more than one monitor hooked up to your computer
- Provide the version number of drawpile installed. 
- Provide a screenshot of your settings under edit, preferences. You may want to try turning on Windows Ink in there if it's off. 

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by Feldherren** [comment]
Stopped using Drawpile ages back, I'm afraid. You might as well close this
issue now.

**Comment by Wade821** [comment]
Alright, then I shall close it then. But Drawpile supports Windows Ink now so it should work now, should you ever decide to try it again.
