### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#32]
Drawpile should compile cleanly on Windows and have an icon and all the other things expected of a Windows program.

As I am not very familiar with Windows programming, any help with this would be much appreciated!

Currently I am using Qt Creator 3.0 with MinGW compiler and cmake.
The find_package(ZLIB) line doesn't seem to work, but removing it and replacing ${ZLIB_LIBRARIES} with z.a seems to do the trick. (This is of course a hackish way to make Drawpile compile)

**Comment by devonzara** [comment]
Has something changed? When attempting follow the build instruction for Windows, I get the following:

```
C:\karchive-5.31.0\build>cmake .. -DCMAKE_INSTALL_PREFIX=%QTPATH% -DCMAKE_PREFIX_PATH=C:\Qt\5.8\msvc2015_64 -G "MinGW Makefiles" -DZLIB_LIBRARY:FILEPATH=C:\Qt\tools\mingw530_32\lib\libz.a
--

-- Could not set up the appstream test. appstreamcli is missing.
-- Could NOT find ZLIB (missing:  ZLIB_INCLUDE_DIR)
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET)
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
--
-- The following OPTIONAL packages have been found:

 * Qt5Network

-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.31.0) , Extra CMake Modules. , <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>
 * Qt5Core (required version >= 5.6.0)

-- The following OPTIONAL packages have not been found:

 * LibLZMA , Support for xz compressed files and data streams , <http://tukaani.org/xz/>
   Support for xz compressed files and data streams

-- The following RECOMMENDED packages have not been found:

 * BZip2 , Support for BZip2 compressed files and data streams , <http://www.bzip.org>
   Support for BZip2 compressed files and data streams

-- The following REQUIRED packages have not been found:

 * ZLIB , Support for gzip compressed files and data streams , <http://www.zlib.net>
   Required by the core KDE libraries and some critical kioslaves

CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FeatureSummary.cmake:319 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:91 (feature_summary)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_INCLUDE_DIR (ADVANCED)
```

Also note that `SET QTPATH=C:\qt\5.7\mingw53_32` is no longer accurate as mingw is installed under `C:\qt\Tools`.

**Comment by callaa** [comment]
I haven't tried build that version of karchive yet. However, at the top is says `(missing:  ZLIB_INCLUDE_DIR` Try setting that build variable too.

**Comment by devonzara** [comment]
I did manage to get it to build using:
`cmake .. -DCMAKE_INSTALL_PREFIX=%QTPATH% -DCMAKE_PREFIX_PATH=C:\Qt\5.8\msvc2015_64 -G "MinGW Makefiles" -DZLIB_LIBRARY:FILEPATH=C:\Qt\Tools\mingw530_32\i686-w64-mingw32\lib\libz.a -DZLIB_INCLUDE_DIR=C:\Qt\Tools\mingw530_32\i686-w64-ming32`

I'm hitting another error though when trying to run `mingw32-make`:
```
C:\karchive-5.31.0\build>mingw32-make
Scanning dependencies of target KF5Archive_automoc
[  2%] Automatic moc for target KF5Archive
Generating moc compilation KF5Archive_automoc.cpp
[  2%] Built target KF5Archive_automoc
Scanning dependencies of target KF5Archive
[  4%] Building CXX object src/CMakeFiles/KF5Archive.dir/karchive.cpp.obj
In file included from C:/Qt/5.8/msvc2015_64/mkspecs/win32-msvc2015/qplatformdefs.h:40:0,
                 from C:\karchive-5.31.0\src\karchive.h:37,
                 from C:\karchive-5.31.0\src\karchive.cpp:22:
C:/Qt/5.8/msvc2015_64/mkspecs/win32-msvc2005/qplatformdefs.h:138:13: error: conflicting declaration 'typedef int mode_t'
 typedef int mode_t;
             ^
In file included from C:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/sys/stat.h:26:0,
                 from C:\karchive-5.31.0\src\karchive.h:24,
                 from C:\karchive-5.31.0\src\karchive.cpp:22:
C:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/sys/types.h:77:17: note: previous declaration as 'typedef _mode_t mode_t'
 typedef _mode_t mode_t;
                 ^
src\CMakeFiles\KF5Archive.dir\build.make:62: recipe for target 'src/CMakeFiles/KF5Archive.dir/karchive.cpp.obj' failed
mingw32-make[2]: *** [src/CMakeFiles/KF5Archive.dir/karchive.cpp.obj] Error 1
CMakeFiles\Makefile2:117: recipe for target 'src/CMakeFiles/KF5Archive.dir/all' failed
mingw32-make[1]: *** [src/CMakeFiles/KF5Archive.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

Sorry, I'm new to all of this CMake and MinGW stuff, I normally stick to web development. Any suggestions on how to progress?

**Comment by callaa** [comment]
Looks like you're mixing MinGW and MSVC libraries. I assume you want to use MinGW and not Visual C++, so the `-DCMAKE_PREFIX_PATH=C:\Qt\5.8\msvc2015_64` argument should be `-DCMAKE_PREFIX_PATH=C:\Qt\5.8\mingw530_32` (I'm not typing this on a Windows computer, so check that the path name is correct)

**Comment by devonzara** [comment]
The problem is that I only have a MSVC folder in 'Qt\5.8'...

**Comment by callaa** [comment]
Then use the Qt maintenance tool to install Qt 5.8 MinGW version. (Or use Visual Studio, but the instructions on the wiki page are literally all I know about that.)

**Comment by devonzara** [comment]
I had looked at the maintenance tool earlier and didn't see an option... I'll look again when I get home.

**Comment by callaa** [comment]
I know there is an option, because that's how I installed it myself.

**Comment by devonzara** [comment]
Wow, not sure how I overlooked that... Anyway, I managed to get it to make with `cmake .. -DCMAKE_INSTALL_PREFIX=%QTPATH% -DCMAKE_PREFIX_PATH=$QTPATH -G "MinGW Makefiles" -DZLIB_LIBRARY:FILEPATH="C:/Qt/Tools/zlib/lib/zdll.lib" -DZLIB_INCLUDE_DIR:PATH="C:/Qt/Tools/zlib/include"` after downloading zlib manually and copying it to the `Tools` dir.

Thanks for the help.
