### ISSUE TITLE
I get disconnected halfway through loading a long server

### ISSUE THREAD

**Issue by dee96** [drawpile/Drawpile#320]
Anytime I try to join a server that has been around, say, an hour or more, it only loads halfway (and lags horribly while doing so) and suddenly says "not connected". Is this intentional? Is there a way to fix this? There doesn't seem to be any info about this on the Help section of Drawpile's site. Please help!

**Comment by pachuco** [comment]
I get same on my own dedicated server, joining from localhost. I resorted to using ridiculously high timeout parameter.
The message in console was probably https://github.com/callaa/Drawpile/issues/310

**Comment by Wade821** [comment]
Same. However, the only "solution" I was given to rehost the board. Save the drawing, clear out everyone out of the board, and create a new hosting session. Everyone should be able to rejoin. Might have something to do with the board size as well. I've seen some larger boards that suffer from this issue fairly quickly while smaller ones do not seem to get this quite as fast.

**Comment by callaa** [comment]
I hoped I had fixed this problem in version 1.0.1, but apparently the fix I made wasn't enough. It seems that replaying the session starves out the rest of the application enough that the keepalive messages are not sent. The multithreaded paint engine in version 2.0 (assuming I get it working properly) should help with this problem.

**Comment by sushirom** [comment]
Oh darn, I just posted about this on the facebook. I should have checked. The /force_snapshot doesn't work on drawpile.net hosted servers. Says it's an unrecognized command. I think I asked about this before on the facebook and was told that the drawpile.net server wasn't actually updated to the current version?

**Comment by Wade821** [comment]
I'm going to go ahead and close out this issue. I haven't seen it myself in a long time, and I've even tried connecting to sessions on the side of a mountain using a cellular hotspot that took about 15 minutes to load and worked (outside of a slow and sometimes intermittent connection anyway). Trying to clear up old issues. 

If this is still a problem however, please feel free to comment so it can be re-opened. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
