### ISSUE TITLE
I can't join any servers.

### ISSUE THREAD

**Issue by tombaloomba** [drawpile/Drawpile#326]
Ok, to explain, I try to join a friend's server, and this just pops up immediately: http://prntscr.com/b16000
We've been trying things like restarting our routers and restarting the program, and I've also checked the permissions on Windows Firewall.  I have very little knowledge on such things and we've been trying since yesterday.

**Comment by Wade821** [comment]
You need to either enable UPnP on your router if it is disabled (preferred method), or enable port forwarding on the router and assign the computer that is hosting the drawpile session with a static IP that is controlled by the router (not on your computer, preferably).

If you can't figure it out, then you could always host on drawpile.net instead. I wrote a guide that should help. [https://docs.google.com/document/d/1QrHd6x-ShLK-bj2U0P8CxiZgecdnWwB5O2tdTeRxtTw/edit](url)

**Comment by tombaloomba** [comment]
OK I'VE DONE IT, I JUST REALIZED THAT I NEEDED TO HOST ON THE IN WEBSITE SERVERS PROBLEM RESOLVED
