### ISSUE TITLE
Cintiq 13HD not working upon launch. Drawpile 1.0.2

### ISSUE THREAD

**Issue by cow5030** [drawpile/Drawpile#333]
For the latest version of Drawpile, whenever I launch the program, I lose the ability to move the cursor around the Drawpile window, unable to move or do anything within the space at all. I've tried calibrating, restarting my laptop and closing out of my drivers only to bring them back up again and none of it worked.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
