### ISSUE TITLE
Selection relative to current rotation

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#335]
It would be nice if selection bounding-box and stretching would be relative to current rotation angle.

**Comment by Wade821** [comment]
I'll be honest, I'm not sure what you mean here. Could you maybe show some screenshots? Or is this already implemented and I'm just forgetting here...?

**Comment by pachuco** [comment]
Well, when stretching a selection, it is transformed as a rectangle.
When rotating the selection and then stretching it, it is transformed as a rhombus, therefore skewed.

The idea is that even with rotation applied to selection, it is still transformed as a rectangle, preventing skewing. Photoshop's selections work like this.

The benefit is being able to stretch a selection without skewing, even after rotation.

![alternate_stretch_transform](https://user-images.githubusercontent.com/1591054/69834863-f757ef00-1245-11ea-86f9-0d9828c1c247.png)

**Comment by askmeaboutlo0m** [comment]
This is implemented now. It works even when skewing and distorting the transform, so nothing was taken away in that regard.

![Relative scaling handles](https://github.com/drawpile/Drawpile/assets/13625824/86e73d86-c6b3-43a5-a8f2-6d0918a738ba)

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!
