### ISSUE TITLE
Adjustable playback speed during join

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#337]
It would be nice to be able to adjust playback speed during join.
Two benefits here:
A) Watching the show at comfortable speed.
B) Prevent choking of server-client keepalive.

Also suggested is that chat and canvas be locked during this.

**Comment by callaa** [comment]
This sounds like a pretty good idea. Right now, Drawpile tries to return to the main event loop every now and then when receiving large amounts of history, but it obviously does not work as well as I thought it would. Adding a deliberate speed limit might indeed work better.
