### ISSUE TITLE
Request: Option to disable permanent tool switching on short press.

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#363]
This applies to both 1.x and 2.x.
Requesting config for disabling permanent tool switching on short key press. Option would have it behave like on long press'n'hold, where releasing would switch back to original tool, regardless of press length.

**Comment by Wade821** [comment]
So what you're asking for in there is an option to disable the shortcut ability to switch between tools when tapping a button. In place of that, the Drawpile client ALWAYS temporarily switches to another tool when using keyboard shortcuts regardless of the time pressed to hold down that button (whether half a second or 60 seconds). When you release the button, it switches back to the currently selected tool in the user interface. So in that case, one would switch tools by clicking the tool bar item to change to it.

**Comment by pachuco** [comment]
Yes, option for disabling of shortcut's short-press action, and leaving only long-press.
