### ISSUE TITLE
Request:  Lock Transparency

### ISSUE THREAD

**Issue by itman496** [drawpile/Drawpile#367]
So something I do a lot in art programs is lock the transparency of a layer so I can change the color of something.  So I shade in the entire layer how I want as a flat color, and then I can lock transparency and draw over with a huge brush to change the color, or start messing with shading and things while not affecting other layers.  I can't seem to figure out how to do that in DrawPile?  Does it exist? It would be very useful if it did.

Great program though, thank you! Also not sure how to mark this as a feature request.  Not used to GitHub.

**Comment by callaa** [comment]
There is no transparency lock that works for every tool, but brushes have a blending mode named "recolor", which does the same thing. (All blending modes other than "normal" and "behind" have no effect on transparency) You can also recolor areas with the selection tool by using the "recolor selection" action from the edit menu.

**Comment by itman496** [comment]
Oh, thank you! That's exactly what I wanted!

Is there any place I can find a list of all the tools and their functions? I can't seem to find a good description of /every/ thing in drawpile, which leads to stuff like this happening..
