### ISSUE TITLE
Cannot change windows size

### ISSUE THREAD

**Issue by ghost** [drawpile/Drawpile#370]
Hi, it is not possible for me to change window size of Drawpile linux app. Because of that I cannot access to some functions at the bottom part of the window. Is it something wrong with app or I do not know how to fix it?

![screenshot drawpile](https://cloud.githubusercontent.com/assets/22841962/19593965/3fa14e28-9783-11e6-889d-1a8db2d02587.png)

**Comment by shadowcopalypse** [comment]
I'm running it on Linux, manjaro KDE environment. No issues . 

If the bottom windows can't be reached they can be removed from dock by clicking and dragging. 

If worse comes to worse I think Drawpile works with wine as well. So that's an option.

**Comment by Wade821** [comment]
Tt looks like there are too many docks so the window can't be resized. You can combine docks together by clicking and dragging them over another to combine them.

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by notfood** [comment]
Stale issue. Closing.

By the way, the fix is just to rearrange your docks as they have a min-size and it stacks past your screen size.
