### ISSUE TITLE
Pressure Sensitivity not working

### ISSUE THREAD

**Issue by theredmanor** [drawpile/Drawpile#373]
I'm using Intuos Pro with the latest driver and the pressure sensitivity is not working at all.
I already set "Pressure" to "Stylus" and ticked "Size", "Hardness" and "Opacity", but still not pressure

Is there any solution to this? Is anyone else experiencing this?

**Comment by callaa** [comment]
Hi. Sorry for the late reply.
Do you have the Wintab driver installed? Drawpile does not yet support the modern Windows Ink version.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
