### ISSUE TITLE
Undo Bug while hosting a server/in one

### ISSUE THREAD

**Issue by Phoninskis** [drawpile/Drawpile#377]
Whenever I'm undoing a lot in a session, it sometimes glitches and the drawing my friends and i were did dissapear and the old drawings from like hours ago reappear into the session.  Whenever this happens, I have to have one of my friends save the load and send it to me, so that I can load it and restart the session but it happens almost every time and it's VERY annoying!!

**Comment by callaa** [comment]
Session history can stretch back all the way to the beginning of the session, but undoable history should be capped to something like the past 30 actions, so it truly is a major glitch for that to happen. When the glitch occurs, does it happen to all users or only some?

**Comment by Phoninskis** [comment]
It only happens to me, so i have to have one of my friends who's also in
the board save the session, send me the .ora file, then i have to close the
session i was hosting then reopen back up from save where we left off
before it glitched for me.  But it happens more frequently if people are
trying to undo at once and it just goes :^(

**Comment by Wade821** [comment]
Given how old this is and how much Drawpile has changed, I'm going to close this issue. I myself haven't seen this issue about old drawings re-appearing, but I do know undo history is rather limited.

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
