### ISSUE TITLE
User Nicknames Suggestion

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#383]
The added layer of spammer protection with the user login is great, but I've had a few complain that they enjoy being able to change their name much like in the main public server. Is there any way to have an added field in the login box to ask if they want to use a session nickname, that is just a temporary superficial value? (Plus the option to disable it on server-side for those who run a server with user authentication but wouldn't want users under a session nickname.)

**Comment by Wade821** [comment]
Closing the issue as out of scope. 

**Reasoning:** Registered nicknames exist as a way to identify users reliably. Nicknames would complicate this matter, you'd have to render it on the board, user list, and in the chat list. Users can simply just choose to not use a registered nickname.
