### ISSUE TITLE
segfault when typing a number into the brush size box

### ISSUE THREAD

**Issue by yorgje** [drawpile/Drawpile#384]
I can't figure out the exact conditions for triggering this, but it has happened several times in both drawpile 1.0.5 and 1.0.6, both when hosting a session and when just drawing locally. Basically, when the brush tool is selected, I go to the box that lists the brush size, type a different number, and press enter, which immediately causes the program to crash, leaving just a "Segmentation fault" on the terminal. But only sometimes.

If it's relevant, I'm running the AppImage on ubuntu 16.04.

**Comment by Wade821** [comment]
Given how old this is and how much Drawpile has changed, I'm going to close this issue. If for some reason this is still happening to you, please feel free to comment so we can re-open it. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
