### ISSUE TITLE
Unable to host/connect to majority of servers 

### ISSUE THREAD

**Issue by ThePapayaking** [drawpile/Drawpile#397]
Almost everyone i know is having an ungodly amount of trouble trying to join servers that others are either able to join, OR were previously able to join hours to days earlier. Messages we keep getting are that when hosting we "cannot find host" (or something to that extent) and when joining "Could not connect to server; Certificate of a trusted server has changed!" People who used to be able to host can't anymore and it makes it incredibly hard to use Drawpile at all.

**Comment by callaa** [comment]
Are you talking about sessions on the public server or ones hosted on private servers? The public server at least doesn't give me the certificate error.

**Comment by ThePapayaking** [comment]
Public and Private servers. There also used to be a fix where if you could type drawpile.net into the remote you'd be able to host again but that doesn't work for most anymore either and just gives the certificate error again. Also once in a blue moon changing the server name sometimes allowed people to host correctly again although it may just be a coincidence.

**Comment by callaa** [comment]
Just to confirm, you are getting the certificate error when connecting to `drawpile.net` and the server worked for you just recently? I just checked and the certificate has not changed.

You can delete the remembered copy of the certificate by going to the "known hosts" tab of the preferences dialog and removing the server's entry. After that, you should be able to connect again. If that works for drawpile.net, can you copy&paste the certificate details here? (After logging in, go back to the known hosts tab, double click on drawpile.net and copypaste the text in the details tab.)

**Comment by callaa** [comment]
Oh, one more thing. Are you using a Mac? If so, are you using the latest stable version (1.0.6)?

**Comment by jane-fox** [comment]
I am able to search for and join public rooms without any issue,  1.0.6 on Linux.

**Comment by ThePapayaking** [comment]
Tested out the fix a couple times with some other people and it works like a charm, thanks alot.

**Comment by callaa** [comment]
Out of curiosity, can you copy&paste the new certificate here?

**Comment by alin20008** [comment]
when i try to join it says this username ia already in use
