### ISSUE TITLE
A very big latency. How can I create my own server ?

### ISSUE THREAD

**Issue by KKotel** [drawpile/Drawpile#401]
Hi, I have a problem. I want to draw with my friends, so I host a session at drawpile.net I am using hamachi too. But I have a very big latency and my friend's draws are not smooth. There are a lot of lags.  Do create my own server help ? If yes, please tell me how to do this. I tried understand this tutorial: https://drawpile.net/help/server/ but I don't understand. 
This program is soo cool and I want to use it without lags.
I am from Poland, so I guess there is a biiig trace from my and my friends laptop to drawpile.net's server. what is a reason for a big latency ~ 500ms ?

PS. Sorry for my English :)

**Comment by callaa** [comment]
If you're using the public server, then you don't need to use hamachi. Hamachi adds a bit of latency on its own. If you choose the "built in" server option, then you're running on your own server with minimum latency. If you don't have a public IP address, that's where hamachi will help.

You can also try the 2.0 beta version. The 2.0 dedicated server has a GUI and is much easier to set up if you're using Windows.

**Comment by KKotel** [comment]
Without hamachi, my friends can't join to my session. So I have private IP I think.
I can't run drawpile-srv. Error: (...) missing Qt5Sql.dll

**Comment by callaa** [comment]
Looks like I've forgotten to include that DLL in the package. I'll release the next version soon, which will include everything necessary.

When you host with the built-in server, you can see your IP address in the bottom right corner of the status bar. If you have UPnP enabled, the program will try to automatically set up port forwarding for you. If it works, the IP will change to a public one. You can also set up port forwarding manually, but how that happens depends on your router. I've gathered all the tips I know on the [hosting help page](https://drawpile.net/help/hosting/).

**Comment by KKotel** [comment]
Ok, so I'll wait for next version. Thanks for answers :)
