### ISSUE TITLE
Crash upon join of specific servers [1.0.6]

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#405]
https://files.catbox.moe/46pfj8.zip
This crash comes when joining certain servers that, curiously, have 0 players. I've seen a few of these today, all crashing.
The join would replay up until a point, where crash happens.

I tried recording one such join, but to no avail. Playback of dprec works fine

**Comment by callaa** [comment]
If I'm reading the crash dump right, it looks like the crash is happening inside the layer putImage function. When the program crashes, the latest part of the recording (particularly the message that triggers the crash) is probably still buffered and doesn't get written out, which might be why the playback works.

**Comment by notfood** [comment]
Stale issue, closing. If you happen to be having the same issue, please open a new issue, a lot has changed from 1.0.x to 2.1.x.
