### ISSUE TITLE
Session Hosting Permissions

### ISSUE THREAD

**Issue by jameslis** [drawpile/Drawpile#406]
In Drawpile 1.x there was a config option to specify a hosting password which was needed to create new sessions on the server.

How can you do this in Drawpile 2.x now?

**Comment by callaa** [comment]
You can create registered user accounts and restrict hosting to only those registered users with the HOST flag. Do you feel that the hosting password works better for your use case?

**Comment by jameslis** [comment]
Actually that's even better as only registered users (mods only) should be able to host on our server. It's also more convenient vs having to enter the hosting password every time a room is needed.

Thanks for clarifying, I will try this out.
