### ISSUE TITLE
Jagged lines

### ISSUE THREAD

**Issue by Klopotuk** [drawpile/Drawpile#407]
When I host there are jagged lines in some part of the screen. Example: http://i.imgur.com/DOElMww.png
On the left I can draw a straight line with no problem and on the left it comes out jagged. Same problem my friends have that connect to me and everyone have them in different places. I've tried 2.0 and 1.06 with no success.
Just realised it's probably same issue as here https://github.com/drawpile/Drawpile/issues/346

**Comment by notfood** [comment]
Stale issue, closing. Seems to have been fixed in recent builds.
