### ISSUE TITLE
Canvas doesn't scale properly on 5K iMac (Retina)

### ISSUE THREAD

**Issue by HaikuOezu** [drawpile/Drawpile#408]
I'm running Drawpile 1.0.6 on a Retina iMac and while it seems like the app itself is properly running at 2x resolution (the UI looks fine) the canvas I draw in has some very clearly visibly pixelation on every stroke
I can't seem to find anything about retina support in Drawpile other than it was added way back in version 0.9.5, is there a way to make the canvas work in hidpi as well?

**Comment by callaa** [comment]
My guess is that the scaling ratio is too high for the display resolution. Other parts of the UI are drawn with vector graphics, so they should be sharp at every scale. On my retina macbook pro, the scaling ratio is 2. The 5k iMac has about 1.5 times the horizontal lines as my macbook, so it's possible the scale could be as high as 3 (although its much larger screen should balance it out.)

It might be possible to add a hidden correction factor to the canvas zoom value. Try zooming the canvas to 50% and 66%. Does it look better at either of those values?

**Comment by HaikuOezu** [comment]
Actually it does.
I actually tried using a different hidpi resolution (I'm actually using Drawpile on a Cintiq Companion 2 which has a 2560x1440 display set at 1280x720 HiDPI mode so 2x scaling) but it still didn't solve the issue, not sure if the fact that it's an external display has something to do with it...
I actually have a Retina MacBook I can borrow to see if I get the same issue hooking it up on that one instead

**Comment by callaa** [comment]
If you have two screens, it might be possible that the program is getting the scaling factor from the wrong one.

I made a test build that adds a hidden 0.5x scale to the zoom: https://drawpile.net/files/osx/Drawpile-1.0.6-scaletest.dmg

Does that give you the right pixel scale? If you start it through the terminal (Open terminal, cd to the folder with the app and run `./Drawpile.app/Contents/MacOS/Drawpile`), it will print out the scaling factors it's using.

**Comment by HaikuOezu** [comment]
Hey, that actually did the trick! Here's my output

cache scale=1.000000, painter scale=2

Is this what Drawpile does on Windows by the way? Because I noticed over there it looks crisp even at 100% but the canvas looks bigger than it does on macOS

**Comment by callaa** [comment]
I think it depends on the screen resolution. I'm not entirely sure how Qt determines the proper scaling ratio. Those numbers are the same as the ones I get on my macbook, however the canvas looks as it should.

I think I'll add a scale correction input box to the settings dialog in version 2.0.1, until I can figure out how to determine the proper scale automatically.

**Comment by Banderi** [comment]
Is there any way to fix this under Windows? I can't find any scale correction dialog anywhere so I'm not sure if it was ever added after all.

I think the way Qt calculates the scaling ratio is indeed not working properly; this is most probably the exact same bug so I haven't opened a new ticket yet, but the canvas doesn't render correctly (appears jagged and aliased as when rendering and viewport resolutions don't quite match) for any zoom levels that aren't multiples of 50% or 100%. This has actually been a bug for a very long while so I assumed it was either well known and hard to fix, or very rare - but I got confirmation that it happens consistently on many of my friends' systems.

This is the same lines at 100%, 90% and 50% zoom:

![100%](https://i.imgur.com/w2twEg6.png)
![90%](https://i.imgur.com/TIe5GA8.png)
![50%](https://i.imgur.com/u73F6X3.png)

**Comment by callaa** [comment]
To be honest, I've forgotten what I did to fix it in the test build. I don't have a high-dpi screen myself, so fixing these kinds of issues is quite difficult, because I'm effectively working blind. Apparently, what fixed it before was adding a correction factor somewhere (probably where the canvas zoom is set.) The problem is where to get this correction factor. Or rather, is there a better way to do it than ask the user?

**Comment by Banderi** [comment]
Hmm I see. If CMAKE worked on my machine I'd absolutely love to try and poke around the code to help a bit, I've tried so many times but it's always a nightmare.

I have also made a few more tests it and confirm that it occurs in both Win7 and Win10, both desktop with multiple dedicated monitors and laptop, at both 100% (standard scaling) and 125% DPI, if it helps.

Just for the heck of it I stumbled upon this on another vaguely similar thread:
> Create a text file (using notepad for example) named "qt.conf" in Drawpile's installation directory.
> Copy & paste this into the file:
> 
> ```
> [Platforms]
> WindowsArguments = dpiawareness=2
> ```

But it didn't change anything, so either I used it incorrectly, or it was for a completely different problem altogether.

**Comment by Banderi** [comment]
Confirming this issue seems to be completely gone with latest update (I'm on 2.1.7)
Thanks so much for fixing this! ♥

**Comment by callaa** [comment]
@HaikuOezu Version 2.1.8 is now built with Qt 5.12 on macOS too. Can you check if it works now for you?

**Comment by notfood** [comment]
Stale with no response from submitter, though seems fixed.

**Comment by HaikuOezu** [comment]
I thought I responded but I was wrong, sorry
Unfortunately I no longer use Drawpile on macOS anymore so I wasn’t able to test it
