### ISSUE TITLE
American English Keyboard 'z' char ignored in "ID alias" Text Field (Drawpile 2.0 RC)

### ISSUE THREAD

**Issue by mysterypaint** [drawpile/Drawpile#409]
Hi there! Holocausto might have already mentioned, but I tried to host a session on Drawpile 2.0 RC and couldn't type 'z' in the text field for ID alias. It seems to work for all the other text fields, though:

![image](https://cloud.githubusercontent.com/assets/17608279/23572910/10b77d58-0038-11e7-835f-e3f27a50a016.png)

**Comment by callaa** [comment]
This was indeed a bug in the ID validation code! I was comparing against the allowed character ranges like `c >= 'a' && c<'z'`, when I should have been using `c<='z'`.

Thanks for reporting!
