### ISSUE TITLE
[Release Candidate 2.0 Mac] No Quick Tool Preset in Brush Dock

### ISSUE THREAD

**Issue by shinnosama** [drawpile/Drawpile#412]
As I posted there aren't any of "five presets", and I also searched on the settings. To be a "Release Candidate is not a good thing. Hope you will fix it!

<img width="1678" alt="schermata 2017-03-12 alle 00 41 35" src="https://cloud.githubusercontent.com/assets/26347469/23824593/b23c1000-06bc-11e7-9159-3d127e0ea2a2.png">

**Comment by callaa** [comment]
The buttons were replaced with a tool preset pie menu (hit Z key to open) in beta 3. See issue #389. The purpose of the release candidate is to help discover any final release blocking bugs (and it has!) before it replaces the old stable version, so I do think it is a good thing.
