### ISSUE TITLE
Chat sounds

### ISSUE THREAD

**Issue by blvk** [drawpile/Drawpile#414]
I think I noticed that the chat makes sounds every so often? It would be nice to have it consistently make a sound every time and the option to turn it off. It's a feature I've been looking forward to having, as small as it is!

**Comment by callaa** [comment]
All individual notification sounds can be switched off from the settings dialog. The chat notification sound is not played when the chat text entry box is focused. The idea is that if you're already focused on the chat, it's not necessary to play the sound. However, presently it does not take other factors in account.

I feel that a better solution would be to improve the idleness detection so the sound would play even if the input box is focused, but the user hasn't touched the computer in a while. Do you agree, or do you think always playing the sound would be better?

**Comment by askmeaboutlo0m** [comment]
Notifications have been reworked in Drawpile 2.2 and should now work consistently. Specifics can be configured in the notification preferences. So I think that should resolve this issue, if not, feel free to reopen it.
