### ISSUE TITLE
QT 5.8 and win XP support [2.0rc]

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#416]
Not sure if it's a compile flag or if QT canceled XP support altogether, but drawpile 2rc cannot start due to missing imports in QT.

**Comment by callaa** [comment]
I'm using a different compiler toolchain to build the 2.0 version, so that might also be the cause. Does it say what DLLs are missing? I don't have a Windows XP machine to test on. Also, even Microsoft ended mainstream support for XP eight years ago, so I don't officially support XP either.

**Comment by pachuco** [comment]
There is no missing dll, only missing imports, coming from the QT dlls.

**Comment by callaa** [comment]
Ok. That might be due to a different libstd or libgcc, since I'm now building the 2.0 versions with a newer GCC version.
