### ISSUE TITLE
Unknown option 'persistent'.

### ISSUE THREAD

**Issue by phoe** [drawpile/Drawpile#418]
I'm running the server for 2.0.0rc. When I'm running it with option `--persistent`, I get the error `Unknown option 'persistent'.` and running it without that option makes sessions non-persistent.

The `--persistent` option does not show up when the server is run with `-h`.

**Comment by callaa** [comment]
That setting (and all others that can be changed at runtime) must now be set in the configuration file or database:

    persistence = true
