### ISSUE TITLE
Cursor not synced with Tablet Pen

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#420]
Drawpile under Linux.

This is something that has been bugging me for a while. The circle cursor doesn't follow the tablet pen so it's easy to get lost. All function keys fail as well, like holding ctrl for eyedropper.

This appear to only happen in the ArchLinux's AUR distributed version (which is the same as compiling it locally) but not in the AppImage version. I suspect it's an issue with the QT version used. 

I've uploaded a video to illustrate the bug:

<p align="center"><a href="https://youtu.be/HlE8N6qMU3E"><img src="https://i.ytimg.com/vi/HlE8N6qMU3E/hqdefault.jpg" alt="Video"></a></p>

This doesn't happen with the mouse. Only happens with the tablet pen. I'm able to use the function keys with the mouse as well.

This bug happened in the old 1.x versions and is happening in the 2.0.0 version too.

**Comment by callaa** [comment]
I noticed all Qt programs on Arch are similarly affected. Curious that the appimage version is not affected. I wonder if the true problem is in arch's Qt build or the KDE platform plugin.

Try using the latest master branch version. I pushed a commit that makes the brush cursor configurable.

**Comment by notfood** [comment]
I can see the new cursor, sadly circle still stuck and function keys don't work either.

<p align="center"><a href="https://youtu.be/dhVos7hIFxw"><img src="https://i.ytimg.com/vi/dhVos7hIFxw/hqdefault.jpg" alt="Video"></a></p>

**Comment by callaa** [comment]
The change I made just added the cursor. I don't think there's anything I can do about the stuck outline, since it seems to be a bug in Qt. The tablet hover events are just not delivered to the application. (On my Arch/KDE desktop, hovering over any Qt or KDE application with the tablet doesn't work)

The fact that the appimage version works (which contains a different build of Qt) indicates that this could be a problem specific to ArchLinux's Qt package. I haven't tested it on any other distro, so I can't confirm it, though.

**Comment by notfood** [comment]
I see. I'll try with a self compiled QT5 to rule it out.

For now I'll stick to the AppImage then.

**Comment by notfood** [comment]
This could be related https://bugreports.qt.io/browse/QTBUG-54085

**Comment by notfood** [comment]
It appears to be related to touch events http://kde-bugs-dist.kde.narkive.com/u9WfrPUw/krita-bug-363225-new-sometimes-the-pen-inputs-events-are-locked-in-clicking-state-on-the-krita

Is there a way to disable it? My tablet doesn't even support them.

**Comment by notfood** [comment]
Just tested it. Spinning my finger on the tablet wheel makes the circle follow the pen correctly, somewhat. Can't really keep my finger spinning on it forever though.

**Comment by callaa** [comment]
I just tried a build with Qt 5.7 from Debian testing and the same bug occurs. This seems to be a regression in Qt 5.7 and not limited to ArchLinux.

**Comment by notfood** [comment]
Is the newest AppImage packed with QT 5.7? All the bugs that didn't happen before with the AppImage came back to haunt me.

Any solution to this? It's pretty annoying to be unable to use the pen to navigate and the stuck cursor is worse.

**Comment by callaa** [comment]
Archlinux just updated to Qt 5.9 and looks like the bug still hasn't been fixed. Probably the best way forward now is to downgrade the Appimage Qt version to 5.6.

**Comment by notfood** [comment]
For now no other choice. I tried to delve into the code and disable the touch events myself but it doesn't fix it.

**Comment by callaa** [comment]
I managed to get Krita's modified XInput tablet event handler working in Drawpile and it seems to have fixed the problem.

**Comment by notfood** [comment]
Compiled 2.0.9 it isn't fixed.

A video to show:

[![Issue](https://img.youtube.com/vi/4YSsk0bo5UU/0.jpg)](https://www.youtube.com/watch?v=4YSsk0bo5UU)

**Comment by callaa** [comment]
Did you include the `-DKIS_TABLET=on` flag when calling cmake?

**Comment by notfood** [comment]
I thought that only applied to the AppImage, I'm using native.

**Comment by callaa** [comment]
If the KIS_TABLET flag is not passed, the new tablet code is not compiled in.

**Comment by notfood** [comment]
Ah, I'll try again then.

**Comment by notfood** [comment]
Tried again, no success, unless I compiled it wrong.

https://gist.github.com/notfood/c17409fd1fc2b619f661d93c004cd8b3

**Comment by notfood** [comment]
Works! Thank you!

**Comment by starndust31** [comment]
Wait, I have the same problem. How do I fix it?
