### ISSUE TITLE
User with HOST and MOD flags conflict

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#422]
In the users section of my drawpile.config file I put the following:
```
[config]
allowGuestHosts = false
[users]
User:plain;password:HOST,MOD
```

User is able to create rooms except when you do, you don't become the OP of the room and you can't moderate it either. You still receive the MOD star but modding controls are greyed out, same as layers as if you were a normal user. Room bugs out for you when you leave and rejoin, you become unable to do anything as the canvas and layers don't appear and the chat is not sending anything.

Removing the MOD flag is my current work around.

Drawpile version 2.0.0 dedicated server and client, both for Linux.

**Comment by callaa** [comment]
Thanks for reporting. This is now fixed in the master branch. Since a few major bugs were found so quickly, I'll release version 2.0.1 either tomorrow or the day after.

**Comment by notfood** [comment]
Confirmed working.
