### ISSUE TITLE
Presets should keep color

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#423]
Currently when saving presets they don't keep the chosen color. This used to be a feature in the old 1.x versions. Is it intended?

I like that you can set the tools and erasers with the preset pie/ctrl+# but I'm really missing the color switching feature, I used it a lot before.

**Comment by callaa** [comment]
Separating color selection from the brush type selection was an intended feature. However, since the new system has not been well received, I'm planning on redesigning the whole brush dock and returning the brush slot buttons.

**Comment by notfood** [comment]
I don't mind the brush slots or the wheel since ultimately I only use the numbers in my keyboard.

Perhaps adding a tiny locks to the brush spinners and color chooser to keep the presets from overriding it would do the trick to keep both sides happy.
