### ISSUE TITLE
Cross Cursor is gone in DP 2.0??

### ISSUE THREAD

**Issue by Phoninskis** [drawpile/Drawpile#424]
Trying to draw in drawpile without the crosshair-cursor is extremely difficult for me especially because i'm using such a tiny laptop and it's hard for me to see where my cursor is on the screen because the default circle cursor blinks in and out of existence-- was the crosshair-cursor removed from DP 2.0 because I can't seem to find it :^(

and if it is, will it be coming back in future updates?  Because if so i think i'll go back to 1.6 until it becomes available

**Comment by callaa** [comment]
The cursor will be back in version 2.0.1, which I'll release very soon.

**Comment by callaa** [comment]
Version 2.0.1 is now out.
