### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Drawordie** [drawpile/Drawpile#425]
Upgraded to the 2.0 yesterday. 
First issue is when I host, going to the session settings tab, On the locked features, it only allows me to tick 3 things only ? Rather than all four.
![2](https://cloud.githubusercontent.com/assets/26545303/24101959/eada693a-0d82-11e7-8362-a2af350bb9ec.gif)

 Also Another bug is after I host, It seems as if the canvas is locked,where I'd try to start putting strokes down, but they get removed instantly as soon As I stop drawing it.
![wat](https://cloud.githubusercontent.com/assets/26545303/24101808/602085fe-0d82-11e7-9eb1-cc0a475d358e.gif)

Same happens if I try to paste a drawing from a previous session. 
Also I wanna point out that seems to happen to a layer I locked for use only to myself, but it seems to work fine on other laters.

**Comment by callaa** [comment]
Confirmed, thanks for reporting. I'll fix this, and a couple of other bugs that have been reported, then release 2.0.1.

**Comment by Drawordie** [comment]
Also another bug that I found is ,When someone comes in the room , draws and then leaves without erasing their stuff, When i try to erase it, it does the same thing like with the brushe I pointed earlier.It erases and half a second after I lift the pen it undoes the erasing.
![3](https://cloud.githubusercontent.com/assets/26545303/24110237/96505a1e-0d9b-11e7-8efd-2abb5213199a.gif)

**Comment by Drawordie** [comment]
ALSO for some reason when using the drawpile server to host a session, it randomly kicks me out of my own room. And when I try to reconnect back it reroutes me to some other pass protected rooms. And I rehost a fresh room and my old one still shows up in the list

**Comment by callaa** [comment]
It connects you to a password protected session without asking the password? Now that's a serious bug. When you're kicked out, I think the server is crashing. The old session sticking around is (or should be) a feature: the server recovers the sessions after a crash. If it's working properly, you should be able to just join back.

**Comment by Drawordie** [comment]
no it doesn't let me in the room, it just pops a server list dialogue of like "choose one of those 3 rooms" and they're all password protected.Naturally I can't connect to either

**Comment by callaa** [comment]
I just released version 2.0.1. This should fix the session setting checkbox problem and the disappearing strokes. (And many other bugs)

I haven't yet figured out what crashes the server, though.

**Comment by callaa** [comment]
The server crash problem should be solved now.
