### ISSUE TITLE
Fullscreen switching and dock hiding

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#428]
A minor nuisance, when exiting fullscreen mode with maximized window, the window is no longer maximized and is positioned awkwardly.

As an addon to this bug, requesting Tab key to (un)hide tab+chat and F11 to control fullscreen separately.

**Comment by callaa** [comment]
The fullscreen->maximized window bug is now fixed.

You can customize the chat hide/show shortcut from the preferences dialog. It looks like it doesn't accept just a Tab, but Ctrl+Tab seems to work.
