### ISSUE TITLE
Line lags behind cursor after update

### ISSUE THREAD

**Issue by kjhdgaidos** [drawpile/Drawpile#429]
![e8ab72b3dc6cd085f21535a31c293141](https://cloud.githubusercontent.com/assets/20525660/24163410/e5e6cb62-0e40-11e7-9915-f7132fc377cb.gif)
![7ad612f567a0e866209d189ba06fa1af](https://cloud.githubusercontent.com/assets/20525660/24163498/2a4e244e-0e41-11e7-9491-f2811402cca1.gif)

**Comment by callaa** [comment]
Check your smoothing setting in the input dock. That looks like normal operation when smoothing is set to maximum.

**Comment by kjhdgaidos** [comment]
Ah! You're right, I set it to half and it works perfectly again, thank you, I was confused because I've always had it at max smoothing but it never did that before
