### ISSUE TITLE
Version 2 not compatible with Windows Vista

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#432]
After install, I get the following error when running Drawpile:

> This application failed to start because it could not find or load the Qt platform plugin "Windows" in "".

and then

> Microsoft Visual C++ Runtime Library: This application has requested the Runtime to terminate it in an unusual way. 

Reinstall does not fix the problem.
I get the same error when I run the version 2.0 (wich doesn't requires installation).

Seems like the issue is due to my Windows version (Vista 32bits service pack 2) wich is not compatible with Qt 5.8+

**Comment by justburn** [comment]
+1
Tried on Vista 32-bits SP1 and it also throws the same message boxes and crashes.

Qt 5.8 seems to be the culprit: https://forum.qt.io/topic/75581/qt-5-8-error

**Comment by callaa** [comment]
I tried building the 32 bit version using Qt 5.7.1: https://drawpile.net/files/win/drawpile-2.0.1.1-setup-w32.exe

Can you try it if works?

**Comment by pachuco** [comment]
I tried it in XP, seems to work.

**Comment by Le2222** [comment]
Well Im on Windows Vista 32bits SP2 after install the @callaa setup I selected 'launch Drawpile' on the end of installation and got the error 'Drawpile Client has stopped working' but then I double clicked the Drawpile icon on my Desktop and it did open without any error and seems to be working now (I even joined a session). Thank you very much for the good-and-fast support :)

**Comment by justburn** [comment]
Tried now on Vista SP1 and that version works without any issues.
On my case the 'launch Drawpile' at the end of the installation didn't caused any crash.

**Comment by Le2222** [comment]
I uninstalled and then reinstalled (for test purpose) and launched it on the end of the installation: zero errors this time, it was just bad luck. This installer is working perfect on Windows Vista 32bits PS2.

**Comment by callaa** [comment]
Great! I'll keep using Qt 5.7 for the 32 bit version then.
