### ISSUE TITLE
Attempting to draw drags canvas

### ISSUE THREAD

**Issue by alekratz** [drawpile/Drawpile#435]
Hi, I'm trying to use the client and I'm unable to actually draw anything on a custom server. Every time I go to use a tool and click and drag, it starts to drags the canvas using the "hand" cursor. Please note that I'm using a mouse.

A few things I've tried:

* Varying combinations of the tablet settings
* Disabling touch settings
* Zooming out all the way until there are no scrollbars

All of these still yield the same result. I am using Arch Linux 64 bit. (sorry if this is a duplicate, I searched some and came up dry).

**Comment by alekratz** [comment]
oddly enough, using the 2.0.0 beta version works for me. Very odd.

**Comment by callaa** [comment]
Are you building from sources or using the appimage? If you're building from sources, you can try a git bisect to identify the commit that introduces the problem.

**Comment by alekratz** [comment]
I might give that a try, if I find some free time.

**Comment by notfood** [comment]
Stale issue, closing. Feel free to reopen if it's happening with current version.
