### ISSUE TITLE
Unable to set single Alt, single Ctrl, single Shift or MouseButtons on Shortcuts.

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#436]
In **Preferences > Shortcuts** I would like to assign, in an example, the **Color Picker** on the '**Alt**' key. But when I press '**Alt**' to set it as a shortcut the software keeps waiting for a second key to be used combined with '**Alt**' (but I want just a single '**Alt**'). The same happens with the '**Ctrl**' and '**Shift**' keys.

Also, it would be very useful the power to assign mouse keys like (example) '**Right Click**' for **Eraser**, '**Middle Mouse Button**' for **Color Picker** and '**Mouse Wheel**' to switch **Tools** or switch **Layers**. But when I push these controls the shortcut editor ignores them.

ps: remember, pen buttons usually works as mouse buttons (so it would be really usefull).
ps2: in the case of the mouse buttons, they should work as the 'tool + click'. Example: a right click n drag would work as a click n drag with the eraser tool (not just used to switch to eraser). Same on the color picker: it would be better the middlemouseclick work as a click with the colorpicker tool.

Version: 2.0.2 for Windows 32 bits.

**Comment by notfood** [comment]
This feature has been implemented since 2.1.13

**Comment by mattmanlex** [comment]
Version 2.3.0 this no longer works
