### ISSUE TITLE
Yet another brush dock redesign

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#437]
Since the previous change to the brush dock (replacement of the tool slot buttons with the pie menu) was not received well, I think another redesign is needed.

Mockup:

![drawpile-main](https://cloud.githubusercontent.com/assets/464576/24464198/cb2e4b5c-14b1-11e7-9dc5-d594929e7197.png)

This design brings back the brush slot buttons, but also provides a box for stored presets,
thus combining the good parts from the old system and the preset pie.

The *pen*, *brush* and *watercolor* are merged into a single *freehand* tool. Whether the tool draws in hard-edge mode (pen), soft mode (brush) or smudge mode (watercolor) depends on the selected brush. This decouples the brush from the active tool type, allowing you to use all brushes with the shape tools as well. (E.g. use the straight line tool with a watercolor brush.)

Another change is that the eraser would no longer be a separate tool. Instead, any brush could be switched into eraser mode.

The main brush dock offers quick access to the most commonly needed brush settings. Clicking on the settings button (top right) would pop up the full brush configuration view.

![drawpile-brushedit](https://cloud.githubusercontent.com/assets/464576/24464220/d9f986d8-14b1-11e7-9511-ee25bfdc49d9.png)

(rough mockup)

Whether the brush operates in pen, soft brush or watercolor mode can be selected here. In the future, more modes and shapes can be added as well.

Improvements over the current UI:

 * This UI layout lines up better with the way Drawpile works internally
 * It exposes more functionality (there's no technical reason you can't use a watercolor brush with the line or rectangle tool, the current UI just isn't flexible enough)
 * Common UI for all brush based tools
 * Restores the brush slot buttons feature
 * Also includes explicitly saved presets
 * Ready for future extension (e.g. alternative brush shapes or even the Mypaint brush engine)

Opinions and suggestions welcome!

**Comment by Le2222** [comment]
"The pen, brush and watercolor are merged into a single freehand tool": Good! Less is more; simple is best.
"...any brush could be switched into eraser mode": Good! I miss the ability to use the line tool with eraser (currenty I do it using white when I'm on the bottom layer).

**Comment by NewSpice** [comment]
I love this idea! No complaints at all. 
From your mock-ups provided it's hard for me to interpret where the eraser will be; However, as long as it's a button on the interface and not a keyboard/stylus shortcut, I'll be happy with it!

**Comment by blurymind** [comment]
Why not have both designs :) i liked the pie design

**Comment by notfood** [comment]
I like the shortcuts. Ctrl+number to set, number to get. Up to 10 presets. Please keep that feature. I don't really care/mind about the buttons, I'd be happy if I could just hide them.

Pie was new and new requires learning. Just have it as an extra feature that can be toogled on or off.

The rests of the mockup features sound like an improvement.

**Comment by callaa** [comment]
A test release that includes the new UI is now out: https://drawpile.net/news/release-2.0.3-pre1

**Comment by notfood** [comment]
I dislike the idea of brush settings in non dockable inner window, it clutters the taskbar unnecessarily.

![screenshot_20170408_184329](https://cloud.githubusercontent.com/assets/5370107/24833338/7d8c0524-1c8b-11e7-9aac-9581c03ee643.png)

The brush palette can be its own dock. 

My suggestion is to make the brush settings dockable and separate brush palette from brush preview, so we can hide the palette for those who find it useless.

And woe is me, no more than 5 presets now... I'll miss going up to 10. I'll also miss being able to set them with the ctrl + number key combo. That feature in 2.x is good.

**Comment by callaa** [comment]
Moving the palette to its own dock will free up some empty space in the brush dock, so perhaps it would be best to just show all the sliders in the dock like before. The reason for moving them into a separate window was to better support alternative brushes in the future, but perhaps planning for that was premature.

> And woe is me, no more than 5 presets now... I'll miss going up to 10. I'll also miss being able to set them with the ctrl + number key combo. That feature in 2.x is good.

This is one of those situations where it's impossible to please everyone. Quite a few people complained about the lack of the old-style buttons. Although, if I move the eraser+mode buttons onto their own row, there should be room for more than 5 buttons.

**Comment by notfood** [comment]
Well, I don't mind not having 10 presents.

The feature I really liked was being able to set presets by ctrl + number. But since changes are saved at any modification in the new/old view, that feature wouldn't work.

**Comment by soljak** [comment]
I like this but unless I'm just not seeing them, I seem to be missing the buttons to change the various pressure settings like opacity, size, and hardness.

**Comment by callaa** [comment]
I just uploaded new test builds:

 * [Windows 64 bit](https://drawpile.net/files/win/drawpile-2.0.3-pre2.zip)
 * [OSX](https://drawpile.net/files/osx/Drawpile%202.0.3-pre2.dmg)
 * [Linux AppImage](https://drawpile.net/files/appimage/Drawpile-2.0.3-pre2.AppImage)

Changes:

 * Brush editor window merged back into the dock
 * Tool palette moved to a separate dock
 * Added arrow to blend mode dropdown button
 * Various small fixes

Opinions on the new version?

**Comment by notfood** [comment]
I don't understand why we need hard brush and soft brush when the hardness slider at 100% turns the soft one into the hard one. They are pretty much the same.

I like that I can hide the brush dock without losing everything else.

I love the color erase tool.

I love that the pointer is easier to look with the new color contrast.

I like the blend modes position.

Thing I miss from 1.x version: The colored icons for each preset. They were useful to know what was what. In this version if I close today and open it tomorrow, I don't know what is what at first glance.

Overall it's good.

**Comment by callaa** [comment]
> I don't understand why we need hard brush and soft brush when the hardness slider at 100% turns the soft one into the hard one. They are pretty much the same.

Unlike the soft brush even at 100%, the hard edge brush has no antialiasing, which makes it useful for pixel art.

> The colored icons for each preset.

How about this: (I also tried changing the color of the buttons themselves, but that didn't look so good.)

![colorstrip](https://cloud.githubusercontent.com/assets/464576/25013085/145d8624-207b-11e7-958a-56fadb203ae9.png)

**Comment by notfood** [comment]
Ah. Call it pen instead of brush then, most drawapps do so.

That looks nice and clean.

**Comment by ShyDoge** [comment]
I absolutely LOVE the fact you  can use eraser with any brush now, it makes it much easier and faster to do artwork! I personally only use drawpile for my art and I really like how simple it is to use, with this version it takes some getting used to, mainly because you have to constantly remember to turn off the eraser mode manually.
 One thing that would be cool would be if there could be two hotkeys to slightly rotate the canvas, that like manipulate the slider left and right a bit instead of having 90, 180 and 270 degree angles, but of course just using the slider is okay, it would just be a bit more convenient. xD

**Comment by callaa** [comment]
> Call it pen instead of brush then, most drawapps do so.

Yes, that's a good idea.

> One thing that would be cool would be if there could be two hotkeys to slightly rotate the canvas, 

I added hotkeys for rotating the canvas by 5 degree increments. By default, they're `shift+,` and `shift+.`, which should correspond to the `<` and `>` keys on the US keyboard layout.

**Comment by callaa** [comment]
Since there seems to be no objections, I'm merging the new brush dock branch to master in preparation of the 2.0.3 release. Thank you for your comments and suggestions, everyone!
