### ISSUE TITLE
[Wacom] No Pressure Control 

### ISSUE THREAD

**Issue by Dave-LeDev** [drawpile/Drawpile#439]
Due to driver issues, I'm forced to use an older driver for the Cintiq 27QHD Touch. 

**Wacom Driver:** 6.3.17-3
**OS:** Windows 10x64
**Drawpile:** 2.0.2
**Qt:** 5.8.0

I dare not upgrade to the current driver version as I know it'll break other things, but is this a possible issue with pressure sensitivity not working? 

Wacom's debugger shows full pressure control. Pressure compatibility is also enabled for 1024-level support. Workaround was tried but failed.

**Comment by callaa** [comment]
Have you tried the 32 bit version also?

**Comment by Dave-LeDev** [comment]
I wasn't aware that was an option. I'll find the installer and give it a go.

**Comment by Dave-LeDev** [comment]
Unfortunately no luck. I did notice, however, that it kept which brush I was using last and its settings. Where can I clear settings? Unless that isn't associated.

**Comment by Dave-LeDev** [comment]
I will note, though, that touch input works beautifully.

**Comment by Dave-LeDev** [comment]
Mm. If this has any impact:
Nvidia GTX 1080 v378.92

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
