### ISSUE TITLE
[0.8.5] Pressure sensitivity no longer works

### ISSUE THREAD

**Issue by howdoicode** [drawpile/Drawpile#44]
There seems to be no pressure sensitivity in this build. I've confirmed it's not a driver bug by using other programs. "Pressure sensitivity: Size" is ticked.

**Comment by PYC-Art** [comment]
I'm having the same issues. Even after ticking the pressure boxes, and setting it to "Stylus," Drawpile will NOT register my tablet's pen pressure, whilst my other drawing programs will.
