### ISSUE TITLE
Missing commands on chat (mIRC style)

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#442]
I miss some commands on chat. Specially:

/pvt (private messages): Sometimes I want to say something private or something in portuguese to someone in chat without to bother the others in the room.

/ping (server lag): My internet connection isn't the best It would be nice a command like this to check the current lag.

/away (status): grey out the nickname to let the others know that I'm afk.

/nick (update nickname): sometimes after lose connection I need to change my nickname for something like Nickname2 it would be nice the possibility to update the nickname inside the session.

**Comment by callaa** [comment]
The ping feature already exists. Right click on the host address text in the status bar and select *statistics*. It will display the total amount of data transferred and the current ping.

**Comment by notfood** [comment]
There is a command I miss a lot. Terminate a session. There is no way to do it in Drawpile 2.x.

**Comment by callaa** [comment]
I added a menu action for terminating a session. The server did have an implementation of the killsession command, I had just forgotten to add it to the client UI.

**Comment by notfood** [comment]
Thank you.
