### ISSUE TITLE
Tool Request: Bezier

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#443]
A bezier tool would be useful specially for users with mouse. If implemented, the request #209 wouldn't be necessary (since a bezier can do both single curved lines and paths with multiple segments).

**Comment by Le2222** [comment]
Following, math info about cubic and quadratic bezier curves using SVG sintax (may be useful to implement this feature).

SVG paths work with 4 kinds of curves: cubic (C), smooth cubic (S), quadratic (Q) and smooth quadratic (T).

**SVG CUBIC CURVES (C):**

The SVG cubic values are made of a curve that is changed by 2 control points. Sintax values: It takes the previous coords as the line start point (x0 y0). Then we have the coordinates of 2 control points (x1 y1 and x2 y2) and then the coordinates of the end of the line (x y):

Sintax: M x0 y0 C x1 y1, x2 y2, x y
(the M is just an example of previous coords)

Now with these values we build a line made of dots, where each dot is a 't' segment from 0 to 1 (Example: the middle of the line will be at t=0,5). Here's how to calculate the x/y coordinates of each 't' segment:

Ax = ( (1 - t) * x0 ) + (t * x1)
Ay = ( (1 - t) * y0 ) + (t * y1)
Bx = ( (1 - t) * x1 ) + (t * x2)
By = ( (1 - t) * y1 ) + (t * y2)
Cx = ( (1 - t) * x2 ) + (t * x)
Cy = ( (1 - t) * y2 ) + (t * y)

Dx = ( (1 - t) * Ax ) + (t * Bx)
Dy = ( (1 - t) * Ay ) + (t * By)
Ex = ( (1 - t) * Bx ) + (t * Cx)
Ey = ( (1 - t) * By ) + (t * Cy)
	
Px = ( (1 - t) * Dx ) + (t * Ex)
Py = ( (1 - t) * Dy ) + (t * Ey)

So Px and Py are the coordinates of the curve spot in the given 't' segment. Example of a curve with 6 dots: x0 y0, Px(t=0,2) Py(t=0,2), Px(t=0,4) Py(t=0,4), Px(t=0,6) Py(t=0,6), Px(t=0,8) Py(t=0,8), x y.


**SVG SMOOTH CUBIC CURVES (S):**

It follows a C/S command and uses its values as a mirror creating the same curve inverted on the opposite side. Sintax values: It takes the previous coords as the line start point (previousx will be our x0 and previousy will be our y0) and also takes the coordinates of the last control point (mirrored previousx2 will be our x1 and mirrored previousy2 will be our y1) to use in a reflected way. Then we have S with the values of the second control point (x2 y2) and then the coordinates of the end of the line (x y):

Sintax: M previousx0 previousy0 C previousx1 previousy1, previousx2 previousy2, previousx previousy S x2 y2, x y
(the M/C are just an example of previous coords)

If it comes after a C curve, to take the mirror version of the x1 y1 values, we do as the follow:

x1:= 2 * previousx - previousx2
y1:= 2 * previousy - previousy2

Now we have all values so we build a line made of dots in the same way as we do to get the Px Py values on the regular cubic curves:

Ax = ( (1 - t) * x0 ) + (t * x1)
Ay = ( (1 - t) * y0 ) + (t * y1)
Bx = ( (1 - t) * x1 ) + (t * x2)
By = ( (1 - t) * y1 ) + (t * y2)
Cx = ( (1 - t) * x2 ) + (t * x)
Cy = ( (1 - t) * y2 ) + (t * y)

Dx = ( (1 - t) * Ax ) + (t * Bx)
Dy = ( (1 - t) * Ay ) + (t * By)
Ex = ( (1 - t) * Bx ) + (t * Cx)
Ey = ( (1 - t) * By ) + (t * Cy)
	
Px = ( (1 - t) * Dx ) + (t * Ex)
Py = ( (1 - t) * Dy ) + (t * Ey)

So Px and Py are the coordinates of the curve spot in the given 't' segment. Example of a curve with 6 dots: previousx previousy, Px(t=0,2) Py(t=0,2), Px(t=0,4) Py(t=0,4), Px(t=0,6) Py(t=0,6), Px(t=0,8) Py(t=0,8), x y.

**SVG QUADRATIC CURVES (Q):**

The quadratic SVG curves are more simple: they have a single control point. Sintax values: It takes the previous coords as the line start point (x0 y0). Then after Q we have the coords of the control point (x1 y1) and the coordinates of the line's end (x y):

Sintax: M x0 y0 Q x1 y1, x y
(the M is just an example of previous coords)

Just like in the other curve types, now we use these values to build a line made of dots, where each dot is a 't' segment from 0 to 1 (Example: the middle of the line will be at t=0,5). Here's how to calculate the x/y coordinates of each 't' segment:

Px = (1 - t) * (1 - t) * x0 + 2 * (1 - t) * t * x1 + t * t * x
Py = (1 - t) * (1 - t) * y0 + 2 * (1 - t) * t * y1 + t * t * y

So Px and Py are the coordinates of the curve spot in the given 't' segment. Example of a curve with 6 dots: x0 y0, Px(t=0,2) Py(t=0,2), Px(t=0,4) Py(t=0,4), Px(t=0,6) Py(t=0,6), Px(t=0,8) Py(t=0,8), x y.

**SVG SMOOTH QUADRATIC CURVES (T):**

It's a short version of Q: it takes the start point coords and the control point coords from the previous curve (Q or T). Sintax values: previousx is our start point x0 and previousy is our start point y0. The control point comes from the previous curve aswell, mirrored previousx1 is our x1 while mirrored previousy1 is our y1. Then we have the T letter followed by the x and y of the line's end.

Sintax: M previousx0 previousy0 Q previousx1 previousy1, previousx previousy T x y
(the M/Q are just an example of previous coords)

If it comes after a Q curve, to take the mirror version of the x1 y1 values, we do as the follow:
	
x1= 2 * previousx - previousx1
y1= 2 * previousy - previousy1

Now we have all values so we build a line made of dots in the same way as we do to get the Px Py values on the regular quadratic curves:

Px = (1 - t) * (1 - t) * x0 + 2 * (1 - t) * t * x1 + t * t * x
Py = (1 - t) * (1 - t) * y0 + 2 * (1 - t) * t * y1 + t * t * y

So Px and Py are the coordinates of the curve spot in the given 't' segment. Example of a curve with 6 dots: previousx previousy, Px(t=0,2) Py(t=0,2), Px(t=0,4) Py(t=0,4), Px(t=0,6) Py(t=0,6), Px(t=0,8) Py(t=0,8), x y.

**Comment by SuperEx2234** [comment]
I need a curve tool, but by the looks of it callaa doesn't have any desire to respond to the requests. :(

**Comment by Le2222** [comment]
I don't agree with the callaa part, His answers are usually quick whenever we found issues on the app. We can't forget this is a freeware and there is not a team to cover all requests.

**Comment by callaa** [comment]
I'm sorry I didn't respond immediately. I did add the *Feature* tag, which means this request is on the backlog and not rejected. (If it were rejected, I would have said so right away.) Please understand that I work on this project as a hobby so the time I can spend on it is limited and I have to prioritize. For the past few weeks, that priority has been on bugfixes. Once I've released version 2.0.3, all the critical bugs discovered so far should be fixed, and then I'll be able to work on new features.

**Comment by callaa** [comment]
A bezier curve tool is now implemented. It works almost the same as Krita's curve tool. Click to start a straight line segment and drag to adjust the curve. Right clicking erases the last curve segment. Clicking without dragging draws a straight line and ends the curve.
