### ISSUE TITLE
Feature design: User authentication without registration

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#447]
At the moment, Drapile has two levels of user authentication: guest users and registered users. If a username hasnt' been registered, anyone can claim a name. There is no way for other session participants to verify that the person behind the handle is indeed the same as the one who had visited before.

For community based drawing sessions, this is inability to verify user identities is a big vulnerability. The opword feature mitigates the problem slightly by making it possible to deliver the operator password out of band, but it does not help regular non-op members.

Registered user accounts solve this problem, but they may not be available for various reasons: on the public server, only moderator accounts are registered; the built-in server does not support registered accounts at all; and setting up user accounts on private servers may be too demanding.

So, an alternative way of proving one's identity that does not require explicit registration is needed. One approach used by many image boards is tripcodes: a password that the server uses to generate a pseudorandom hash that is shown next to the username. Without knowing the password, an impersonator cannot have the server generate the same code.

I think the tripcode is a good starting point for this feature. Let's define the basic building blocks for the algorithm:

Let *P* be the secret sent by the client to the server.  
Let *S* be a server specific salt.  
Let *U* be the username.  
The server produces the idenficiation hash *H* with *h(P+U+S)*, where *h* is some cryptographic hash function.

Now, we must consider the threat model. We'll assume attackers are using a modified client and/or server program and thus cannot rely on obfuscation for security. We assume the goal of the attacker is to impersonate another user and gain access to private resources, such as the session operator status or the trust of other users. This can happen by:

 * Cracking the password and causing the server to generate a correct hash
 * Attacking the weakest link: fooling the human participants even though the hash is not correct
 
It is also worth noting that the adversary this scheme attempts to protect against is a common Internet bully with too much time on their hands, rather than the NSA. Therefore, it is OK to trade off some theoretical security for ease of use.

## The identification hash algorithm

Let's look at the first attack. The attacker could attempt to recover the password by:

 * Intercepting network traffic with a sniffer
 * Having the victim connect to modified server
 * By cracking the password with a dictionary or brute force attack

The third attack mode is easiest to thwart technologically: we must simply make the hash long enough and use a suitable hash function, such as bcrypt, to make a brute force attack expensive. The salts used can be kept secret, which increases the difficulty further.

Intercepting network traffic is often difficult, as it requires physical (or logical) proximity, so this attack is likely seldom carried out. The best protection is to connect to a server using TLS.

Using a hostile server is an easier avenue for attack, since a user can be fooled into joining it from anywhere in the world and social engineering attacks are easy to pull off.

This attack can be countered by making *P* server specific. From the server's perspective, the details of the algorithm used to generate *P* are irrelevant, but in general it could be something like: *P = h(password + username + server_hostname)*

By never sending the plaintext password, the client protects itself against hostile servers that record the passwords or misconfigured servers that do not perform adequate hashing when generating the identification hash. (These servers provide no identity protection, so the client should warn the user when if the returned identity hash is the same as *P*)

To summarize: the client should generate a unique *P* for each server. The server combines this code with the username and a secret salt to produce the idenfication hash. (Note: the ID hash should still be secure even if the server salt is not secret. Keeping it a secret just provides an additional hurdle against bruteforce attacks.)

### Passwords

Generally speaking, people are bad at picking passwords. Unless they are using a password manager or have preternaturally good memory, there is just no way around it. (When I was a kid,
my email password was "Qwerty123" and I thought I was so damn clever because it had capital letters and numbers in it.)

Possible solutions:

 * Hidden per-client salt. Drawbacks: may be lost on reinstall, ties account to a specific computer
 * File as a password: Drawbacks: difficult to set up.
 * Identity manager: Autogenerate and remember passwords. Drawbacks: requires passwords to be manually set when moving to another computer
 * Password entry box with strength estimation. Drawbacks: still allows weak passwords (but at least the user has been warned...)

### Proving one's identity

The ID hash can be used by the server in place of a traditional password to remember the OP status of a user and restore it when they return to a session. Since this all happens in software, it is as secure as the algorithms used.

The other major use is proving one's identity to the other users of the session. This is where things get difficult, since it involves a human element. The simple way would be to just display the hash next to the username, tripcode style. However, humans are terrible at remembering long bit sequences, so as a means of verifying that the "McCoy" who just logged in is indeed the real "McCoy", it fails terribly.
 (Tripcodes work in message boards because you have the prior messages right there to compare
against.)

Possible solutions:

 * Just show the hash (terrible: need to remember prior hashes yourself)
 * Generate an [identicon](https://en.wikipedia.org/wiki/Identicon) (same problem)
 * Uploadable avatars that can be associated with ID hashes (easy to steal, not secure)
 * Client remembers hashes associated with each username and flags users as "real", "fake" or "new"
   * Good: users don't need to remember anything!
   * Hmm: when seeing a user for the first time, how to know if they're the real one? (To be fair, all schemes not based on a central registry or a web of trust share this one.)
   * Bad: vulnerable to username spoofing with unicode characters: "callaa" vs "саllаа". The latter uses cyrillic с and а letters and is not identfied as the same name by the server. The client says both users are authenticated, but which one is the right one?

Of these options, only the last one is viable, but only if the visual spoofing problem can be solved.

A possible solution would be to generate a "hash key" name from the username by replacing all confusable characters with canonical ones. Hash checks could then use this key rather than the actual username and alert if the given hash (which was generated from the true name) does not match the stored hash (which was remembered with the normalized key)

So, if "callaa" joins the session with the hash "fa01", the hash key is "callaa". Then "c𝐚llaa" joins with hash "fb02". The normalized key is again "callaa". The client looks up the hash for key "callaa" and sees that "fb02" does not match "fa01" and flags the new user as "fake".

## Open questions

 * Is the hashing scheme I proposed secure? What attacks didn't I think of?
 * Which is better, the identity manager or the simple password box with strength meter?
 * Is flagging remembered users as "real", "fake", or "new" good enough, or is there a better solution?
 * Is the proposed solution to the visual spoofing problem adequate?

**Comment by notfood** [comment]
The flagging could become an issue, if someone's password becomes public somehow and the user wants to change their password, new user/pass combo will be marked as fake. You can't delete a user in this authentication scheme.

May as well implement something IRC authentication akin, allows guests user with any name and if name is being in use mark as unauthenticated and have the option for rooms to forbid unauthenticated users. After all, login is done when entering room, have the rooms be able to enforce it or not.

Additionaly have the option for accounts to expire if not being used for a time, just like IRC.

**Comment by callaa** [comment]
That's a good point. Each user would have to curate their own list of trusted users, and that's just not going to work.

Nickserv type authentication sounds like a much more practical idea. The downside is that it requires more serverside support, whereas the hash based scheme would work on any server. However, nickserv style authentication is so much less prone to user error that it's obviously the better trade-off.

Currently, the server has a list of registered user accounts like: `{username, password, flags}`
With the new nickserv style system (let's call it GuestPass) it would have a second list of registered guests: `{username, password, lastUsedDate}`

Registered accounts would take precedence, so those names would require authentication to use, as before. For GuestPass accounts, the password would not be mandatory, but if not provided, the username would be marked as unauthenticated.

This system, like the hash based one, also suffers from the visual spoofing problem, so the same normalization method should probably be used.

The next problem is how to register the guest accounts. A really simple way would be to implicitly register the user whenever a username/password combo is used. Although, this doesn't seem like a good idea, since it would be too easy to accidentally register usernames.
A better way would be to add *Register Username* option option to the *Session* menu.

There is one problem this scheme suffers from, though. A griefer could host a room on the target server, then register all the yet unregistered usernames from other rooms at their leisure. So, it might be a good idea to include a `lastIp` field in the GuestPass list to identify this behavior. The autoban script could notice when a single IP is registering usernames that have previously logged in from other IPs and automatically clear those registrations and ban the offender. (Although this would require careful adjustment to avoid false positives, as having alt-accounts is a perfectly legitimate use case.)

**Comment by Le2222** [comment]
With registered nicknames implemented, it could have a 'friends list' so we would get notified when a friend joins the session.
