### ISSUE TITLE
Request: alt + ctrl drag to resize the brush

### ISSUE THREAD

**Issue by jameslis** [drawpile/Drawpile#449]
In some drawing applications you can resize the brush via a shortcut like alt + ctrl then dragging left/right to resize the brush. It's a handy shortcut and can be more convenient than [ or ] keys which are how this is currently implemented in drawpile.

Not sure how difficult it would be to add this functionality but it would be nice for us that use this method. (Most people familiar with PS or Clip Studio are familiar with the alt-ctrl drag)

**Comment by callaa** [comment]
I could have sworn I had implemented this feature already, but apparently I had it confused with the drag to zoom feature. I'll implement this for the next release. There is also a shift+mouse wheel shortcut to adjust the brush size, but that's only useful when drawing with a mouse.

**Comment by jameslis** [comment]
Ah I didn't know that; I have [ , ] mapped to the touchstrip on my tablet and it works similarly. Anyhow, thanks for considering this on the next release!

**Comment by notfood** [comment]
2.1.x rework for screen shortcuts introduced **shift + (hold up/down)** for tool resize. You can also use **shift + mouse wheel**.
