### ISSUE TITLE
Unable to connect to a session

### ISSUE THREAD

**Issue by HirundoArvensis** [drawpile/Drawpile#450]
Hello!

I and my friends have been trying to create a session and to connect to it but so far we didn't manage to. 
We have tried to do so on more than one device but still, failed. We've opened the port, deactivated the firewall, as well as followed all the other instructions. We tried joining some rooms opened by others as well, without success. When we try to join a session our connection times out. 

Is there anything we're still missing?

**Comment by callaa** [comment]
Is everyone using the same version?
Are you able to connect to drawpile.net? If not, what does the error message say?

There are two common reasons why the connection fails by timing out: when connecting to a 1.x server using a 2.x client, or when there is a firewall somewhere in between. If it's a firewall, the most common reason is that either the port forwarding is not set up correctly or there is more than one personal firewall software running on the PC. Another option is that the firewall is at the ISP level. (E.g. carrier grade NAT)

**Comment by notfood** [comment]
Stale, closing. Appears to be connectivity, unrelated to Drawpile. Feel free to re-open if you are still having the same issue.
