### ISSUE TITLE
window don't proper fits on the screen after hover some buttons

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#452]
I was used to have this issue: the software opens properly and fits well on the screen but then after a while I realize it isn't ok anymore (the statusbar is out of the screen). But I was in an old system (Windows Vista 32bits) so my thought that time was 'well it may be my fault I'm in an old system' so I just workaround the issue restoring the window then maximizing it again.

But then I updated my system to Windows 10 32bits and now I have the same issue again. What happens: I open the software it fits nice on the screen until the mouse cursor go hover any of the following icons (marked in red):

![issue buttons](https://i.gyazo.com/0d3e65cccb56c54e8d435c0e6dcc51e9.png)

Interesting fact, it also happens when the mouse go hover some top inner menu items, as marked on the pictures:
![issue menu items1](https://i.gyazo.com/eeaaa1d57f812979e56de6301bbdede6.png)
![issue menu items2](https://i.gyazo.com/ad48873561b72b357695cad1c87b71aa.png)
![issue menu items3](https://i.gyazo.com/11f3356e6339ccad53cc657ab2cfd3c2.png)
![issue menu items4](https://i.gyazo.com/00f4aa7a7868f2ab41b3ddee1021f78c.png)
![issue menu items5](https://i.gyazo.com/639408464b1e11b4f45c5adb70d3dcfc.png)

So the bottom of the screen gets cropped and, again, to workaround it I need to restore then remaximize the window.

ps1: This does not happens in my v1.0.6 copy. It happens only in my v2.0.3 copy.
ps2: It happens always doesn't matter if the Windows' taskbar is in the 'auto hide' mode or in the 'never hide' mode.
ps3: my screen resolution 1280x800

**Comment by callaa** [comment]
This happens when having multiple docks open cause the minimum window height to become larger than the screen height. I haven't yet come up with a good way to avoid this.

It can be fixed by rearranging the docks. You can either close unneeded docks, tab them over other docks or move them to the other side of the screen.

**Comment by Le2222** [comment]
It fixes the issue. So I have a feature request: 'collapse dock to button' option just like it is on photoshop (right side buttons on the picture):

![photoshop](https://i.gyazo.com/cb4e485ad45ad06a24f30aae4f25a59d.png)

**Comment by Le2222** [comment]
A suggestion to fix this issue: when the docks gets bigger than the screen, it could call a scrollbar to roll the docks.

**Comment by callaa** [comment]
As far as I know, the framework doesn't directly support those features, so I would have to find an alternative dock implementation.

**Comment by Le2222** [comment]
I'm not sure but seems like once I try to rearrange the docks, drawpile don't allow a pile of docks taller than the screen? If yes, this is good it means the problem is just the docks that came built in the first installation; so the fix would be let some docks floating or collapsed in tabs in the first time that you run the app.

**Comment by Tomycase** [comment]
The problem might be related to the "Free hand" option in "View - Docks", when desactivated, the issue doesn't occur for me anymore.

**Comment by notfood** [comment]
Stale, closing. Feel free to re-open if the stretching-over-hover is still happening.
