### ISSUE TITLE
could not load layer data/layer0.png

### ISSUE THREAD

**Issue by Partyflies** [drawpile/Drawpile#453]
So i was brainstorm drawings and ideas for a few hours
saving to make sure i wouldn't lose my work
slowly the canvas got bigger and bigger
around 9000 by 6000
i couldn't save it as a jpeg which was weird
so i saved it as a ORA file

then i tried opening it to see if i could open it then i get this error
could not load layer data/layer0.png
i cant open it with any other programs either 

is my work lost??
help?

**Comment by callaa** [comment]
If you open the ORA file with winzip or the equivalent, does it contain anything? That error does suggest that the layer data was not saved. I justed tested saving a 9000x6000 file and the program should be capable of it. Why couldn't you save it as a JPEG? Did you get an error message?

**Comment by Partyflies** [comment]
Thank you for your reply
The open ORA file contains the following 
stack.xml
mimetype
mergedimage.png
and 2 folders, labeled data and Thumbnails
inside data is as followed
Layer0.png
Layer1.png
Layer2.png
all at the size of 0 bytes

and inside Thumbnails is thumbail.png


i just rechecked the size of the canvas as it was 11744 x 6062

as for the message, I believe it said "couldn't save jpeg" in a popup box

**Comment by callaa** [comment]
Okay, then unfortunately it doesn't seem possible to recover the image. I'm not sure what caused the problem, but I'll add additional error checking in the ORA saving code so it will show an error message it it's unable to save the layers.

These types of data-losing bugs really shouldn't happen, but in practice they still do. When working on something important, I recommend enabling recording (from the file menu.) The recording format is very resistant against data loss, so even if the program crashes it is possible to recover most of the canvas from it.
