### ISSUE TITLE
Drawpile 2.0 startup hangs as daemon

### ISSUE THREAD

**Issue by jameslis** [drawpile/Drawpile#454]
The script provided in server/drawpile-srv.service will still start the server but will hang waiting for a signal.

I'm running CentOS 7 and used this workaround to get it running:
edit the file server/drawpile-srv.service and change
`Type=notify`
to
`Type=simple`
and it is able to start via systemd like v1.x .

I'm not sure if this is entirely correct or if it affects any other flavors of linux but it worked in my case.

**Comment by callaa** [comment]
I updated the same unit file to include both socket activation and simple startup styles, with the SA commented out by default. The AppImage is currently not built with systemd support, so `Type=simple` must be used with it.
