### ISSUE TITLE
Compile error when using -DINITSYS=systemd

### ISSUE THREAD

**Issue by dixonte** [drawpile/Drawpile#456]
It looks like someone forgot to comment out line 72 of src/server/initsys_systemd.cpp, it still references a 'logger' class (Or whatever it is? I'm not a C++ programmer).
I noticed the other references to 'logger' in this file were commented using compiler directives. I was able to get the code to compile after commenting out this line in the same manner.

**Comment by callaa** [comment]
Thanks for reporting. I had changed the way log messages are written and forgotten to update the systemd integration part.
