### ISSUE TITLE
unable to type with input method in linux

### ISSUE THREAD

**Issue by ZX-WT** [drawpile/Drawpile#458]
I am a Chinese user and apparently I cannot input Chinese when I switch to other input method, the input method is just not functioning which I can only enter normal English keys.

OS: linux mint 17.2
Drawpile version: 2.0.4 Appimage

**Comment by callaa** [comment]
I'll check it out. Perhaps there's a library missing from the appimage build.

**Comment by callaa** [comment]
This is now fixed.
