### ISSUE TITLE
Feature request: Ability to resize and move the chat

### ISSUE THREAD

**Issue by ZX-WT** [drawpile/Drawpile#459]
Now the tools are movable dockers, however, the chat is fixed at the bottom, is it possible to make it act like a docker to give control for users to rearrange the UI?

**Comment by callaa** [comment]
The chat box is already resizable. (Depending on the widget theme, the divider is not always very visible, though.) I'm not sure about making it dockable. The bottom is really the only sensible place for the chat. There's not enough room in the sides for it.

**Comment by Le2222** [comment]
i think the possibility to let the chat window floating would be interesting.

**Comment by ZX-WT** [comment]
does drawpile work in multiple monitors? I cannot test it with only one monitor, if yes, making it dockable maybe useful as you can put the chat in another screen and maximize the canvas.

**Comment by Wade821** [comment]
Detaching the chat box is now a feature. I'm closing this issue.
https://drawpile.net/news/release-2.1.11/
