### ISSUE TITLE
The ability to clear the server list under the join a session window

### ISSUE THREAD

**Issue by ZX-WT** [drawpile/Drawpile#460]
It seems that drawpile will remember all the url I have entered and the list is keep on growing, it is not a big problem but I find it annoying, is it possible to clear the record somewhere now? Am I missing something?

OS:linux mint
version: 2.0.4 appimage

**Comment by callaa** [comment]
I changed the code so that it now only keeps the last 8 addresses. Currently, there is no UI for clearing the list, but you can do it manually by editing the configuration file `~/.config/drawpile/drawpile.conf`
