### ISSUE TITLE
language naming problem

### ISSUE THREAD

**Issue by ZX-WT** [drawpile/Drawpile#462]
A problem I encounter when I am working on the Traditional Chinese translation, the wiki suggested the use of ISO-639-1 language code in naming the file, however, this cannot distinguish Traditional Chinese and Simplified Chinese. I would like to name the file following the linux locale which is also used in the qt linguist, is that alight?

In addition, I try to just copy one of the translation file and modify it, I also try to use lupdate to create a new file, I find out that there is a different in the amount of string to be translated which the later has less, I will work on modifying the existing file instead, just want to know why lupdate is behaving in this way.

**Comment by callaa** [comment]
As long as Qt finds the translation file, it should be fine.

Currently, the translation files are not up to date, which probably explains the different number of translations compared to a fresh lupdate generated one.
