### ISSUE TITLE
Main Lobby

### ISSUE THREAD

**Issue by weylin6** [drawpile/Drawpile#469]
There's currently no way to talk with other users to get help or invitations to locked boards.
A main lobby could act as a kind of staging area to find people with similar interests, or just give and receive technical help.

**Comment by callaa** [comment]
I'm currently working on an update to the website so that I can add social features like a user gallery and a forum. Also, I'm planning on restarting the old IRC channel too.

**Comment by Le2222** [comment]
I saw two websites where we were able to join an IRC channel without to have the software installed. It looks friendly to me but I am oldschool, maybe a prefabricated chat like [Dischord](https://discordapp.com/) would be a more contemporary solution (theres several teenagers on the sessions).

**Comment by notfood** [comment]
The advantage of IRC vs Discord is that it allows for guest users. To use Discord you need an account. A webchat in Drawpile.net would be good enough though you would need moderation too as it'd need to be "public".

Currently, the decentralised structure of Drawpile allows many servers, if implemented in client, you'd join that server's global chat which wouldn't help you find any new "server", there would be no difference than joining that server's public drawing rooms. It'd be an useless feature unless all servers would connect to a single chat authority which gives username issues and such. Also, there is the issue that artists may not want to join a chat only thing so the population of that hub wouldn't be very active if at all.

Seems like a troublesome feature if implemented in client, either useless or very complicated.

Visiting the available rooms announced in drawpile.net is enough to meet new people and connect to other artists. If people desire to invite others, they'll make it public.

**Comment by notfood** [comment]
This will be left to each community to handle with the new communities feature. They will be able to use any means of contact, they'd merely need to advertice it with the welcome message feature that is already implemented.
