### ISSUE TITLE
Fill Bucket's Expand

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#470]
Fill Bucket's don't work with me if I use on **Expand** any value different of **zero**.
ex: I click inside the shape to be filled and nothing happens. Did I miss something?

v2.0.4 Windows 32bits (ps: size limit is on max)

**Comment by callaa** [comment]
Confirmed. This appears to be a Windows specific bug, as I can't reproduce it on Linux or OSX, but the windows version, even when run in Wine, does exhibit the problem.

**Comment by callaa** [comment]
Okay, I figured it out. I had added a new field to the FloodFillResult data structure, which wasn't initialized properly when expanding a fill. On the Linux and OSX builds, that field just happened to default to a zero value, which is why I didn't notice the problem immediately.
