### ISSUE TITLE
Request: Hiding Host IP

### ISSUE THREAD

**Issue by kirmon64** [drawpile/Drawpile#471]
If you're hosting/connected to a session, it displays the IP at the bottom by the rotational tools. The problem is that if you're streaming, this IP is displayed for all to see. Which is an issue if it's a private server hosted from your own computer, because now everyone in the stream knows your IP address.

So would it be possible to have a checkbox in settings somewhere to turn off this display?

**Comment by callaa** [comment]
I added an option to the host address label context menu to hide the address. This feature will be included in the next release.

**Comment by kirmon64** [comment]
Thank you! Much appreciated.
