### ISSUE TITLE
'Zoom in' shortcut and multiple shortcuts.

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#472]
Some keyboards (mainly on laptops) don't have a numpad. I have it, but even with the numpad avaible, I'm used to use the Ctrl with regular - and regular + to zoom in/out in every drawing software.

The problem is: the + key on the regular keyboard is in fact = (+ is on top):
![keyboard](https://computerhope.cachefly.net/keyboard/equals.jpg)

So when I press Ctrl and = on every drawing software (like Photoshop), it zooms in (because = and + are, in fact, the same key). The same don't happen in Drawpile (Krita have this problem too), it only accepts the Numpad's + to zoom in. It can be fixed if I edit the 'zoom in' shortcut to Ctrl+= but I think it should be a default setting like it is on Photoshop and others.

A second issue: if you simply replace the current Ctrl++ by Ctrl+=, the Ctrl++ don't works anymore. So, to let it like it is on the other drawing software, a new feature would be needed: the ability to set more than one shortcut for the same function (in this case, Ctrl++ and Ctrl+= to 'zoom in').

**Comment by notfood** [comment]
This has supposedly been fixed by the shortcut overhaul in 2.1.x. You can remap the canvas shortcuts now. Feel free to re-open if you're still having this issue.
