### ISSUE TITLE
can't use stylus to zoom & adjust brush size (stylus mmb is not the same as on mouse?)

### ISSUE THREAD

**Issue by JulianNymark** [drawpile/Drawpile#473]
![image](https://cloud.githubusercontent.com/assets/819074/26279855/bfd931cc-3dbf-11e7-9b7b-7cd9146aa6ac.png)

nothing happens when i hold the stylus 'middle mouse button' trigger and a modifier key such as ctrl + shift. (I can still pan as normal though without using any of the modifier keys)

I use:
- wacom intuos pro s
- Linux m 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux
- the AppImage (Drawpile 2.0.4)

**Comment by callaa** [comment]
I added the modifier workaround to the pen press event handler too and it appears to work now.
