### ISSUE TITLE
Drawpile Suggestion

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#474]
This is a bit out there,

How about a Drawpile **Cryptocurrency**?

With the Crypto Market taking off it would be the only drawing application applying this incentive. 

It could be made to fund a stock-type exchange for Drawpile development and perhaps grow this project into a whole Suite. 

Obviously this is highly complex but I felt it worthy of a discussion.

**Comment by callaa** [comment]
I believe a cryptocurrency is out of scope for this project.
