### ISSUE TITLE
Image Paste Preview

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#476]
When I paste an image the preview ignores the layers order (the image appears on top, even in lower layers). The problem: is hard to paste the image exactly on the right place because the image itself covers the rest of the art. 

I guess this is a technical limitation, so I have a suggestion to workaround this issue: in the paste preview (before to deselect or press Enter), the image could have a transparency (like 70%) so we would be able to see the rest of the art even without the layers order.

**Comment by Le2222** [comment]
I have a second idea (also a feature request) to workaround this limitation: guidelines (just like it is on Adobe Photoshop).

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will becoming with Drawpile 2.2. The paste preview is now actually rendered on the selected layer, rather than being just a floating thing on top.
