### ISSUE TITLE
Tablet lag with drawpile on mac.

### ISSUE THREAD

**Issue by elokelo** [drawpile/Drawpile#477]
I downloaded drawpile yesterday but when I draw with my tablet, the cursor takes ages to complete the stroke I've put down. It keeps going really slowly after I've pulled the pen from the tablet. 
I tried just using mouse and that works fine, no lag.

I'm using a huion giano tablet.

**Comment by callaa** [comment]
The next version will include a built-in tablet test utility that might help reveal what is going on.

**Comment by notfood** [comment]
Stale, closing. Feel free to re-open if you are still having this issue.
