### ISSUE TITLE
Unable to open save dialogs of any kind

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#478]
For some bloody odd reason, I cannot open filesave/fileload dialogs in DP 2.0.4 anymore. Also for some bloody reason, same occurs in 1.0.6.
This includes Open, Save As and Record. Save works fine if you work from opened file.
Restarting applications does nothing.
Restarting OS... dunno, reluctant to try(I keep mine on like server).

**Comment by callaa** [comment]
If it affects 1.0.6 as well, the cause is most likely external.

Which operating system are you running? If Linux, are you using the AppImages?

**Comment by pachuco** [comment]
Ooops, winXP.

**Comment by pachuco** [comment]
Back with results, OS restart changes nothing.
Also, threw a bunch of other QT5 applications at my file dialog testing: SqliteBrowser3, SMPlayer, Pencil2D, Polyphone. They're fine. Dunno about internal details of them.

**Comment by pachuco** [comment]
Did some poking around and traced problem to 'HKEY_CURRENT_USER\Software\drawpile\drawpile\window'

**Comment by pachuco** [comment]
Found the fucker.
In 'lastpath', with value of 'file:///C:/sssssssssssssssss.png'
Opening this file results in a lockout from file dialog.

**Comment by pachuco** [comment]
Did some more testing with both x64 and x86 in x64 win7 and win10.
This seems to happen only in XP with x86 version.

**Comment by callaa** [comment]
Could it be the URL style file path that causes it? If you replace the registry entry with a `c:\ssssssss.png` does the same thing happen?

**Comment by pachuco** [comment]
it works fine without the above.

**Comment by Wade821** [comment]
Even though I just labeled this, not sure it should be considered a bug. 

Making Drawpile work backwards compatible for XP is not something good long term unless it can be implemented without creating a security hole or issues for newer systems.

**Comment by pachuco** [comment]
While drawpile was supporting XP when I made this issue, that is no longer the case.
Also, Qt has changed as well. GetOpenFileName()/GetSaveFileName() has been replaced by Common Item Dialog, which is Vista+ winapi.

Therefore:
1. I cannot test this bug anymore.
2. It's likely irrelevant, since the platform where this bug happened is no longer supported.

**Comment by Wade821** [comment]
Alright, then I shall close it then.
