### ISSUE TITLE
Drawpile window auto-resize problem

### ISSUE THREAD

**Issue by Tomycase** [drawpile/Drawpile#479]
Hello,
What's happening is, each time i leave the tchat toolbar, the program's windows auto-resize itself and become too high for my screen :
https://img15.hostingpics.net/pics/674462Bug.png
I tried to move the windows toolbar on the side, but it's the same, it goes below my screen borders and I can't access to the tchat.
Do you know how it can be fixed? Thank you

**Comment by Le2222** [comment]
This is maybe the same issue of the topic #452

**Comment by Tomycase** [comment]
Thanks, but I think I found what cause the issue, when I desactivate "free hand" in the docks options, the issue doesn't occur anymore.
