### ISSUE TITLE
tab not working w drawpile, pressure sensitivity problem (mac)

### ISSUE THREAD

**Issue by cerosxxy** [drawpile/Drawpile#480]
Okay, so my tab (a Genius EasyPen i405x) isn't working with Drawpile 2.0.4 on mac. It's not able to make strokes of any kind, or used to press down or interact with Docks and GUI. Although when i tried it on an older version, there are strokes: but when I edit the Input curve, or make a stroke, the lines are dotted.

Please fix as soon as possible, if ever.

**Comment by callaa** [comment]
Version 2.0.5 now includes a tablet test tool. (*Tablet Tester* in the *Help* menu) Does it print out any tablet events? Try also enabling the bug workaround mode in the settings dialog.

**Comment by notfood** [comment]
Stale, closing.
