### ISSUE TITLE
invalid SSL certificate for host drawpile.net

### ISSUE THREAD

**Issue by Modpai** [drawpile/Drawpile#481]
i keep getting an error message that says exactly that, and im just trying to join a friends drawpile. This is the first time ive used drawpile and i have no idea what im doing btw, so it might just be me having this problem. Either way, if you know how to get drawpile to stop saying that and connect to the server, that would be super cool if you could tell me how to.

**Comment by callaa** [comment]
Which operating system are you using? Also, if you go to the preferences dialog and select the "Known Hosts" section, do you see `drawpile.net` on the list? If so, try removing it to see if it has any effect.

**Comment by Modpai** [comment]
Im using a Windows PC, and once i get home ill try that and tell you if it works or not. Thank you for responding!
