### ISSUE TITLE
Tablet problem

### ISSUE THREAD

**Issue by SandGal** [drawpile/Drawpile#482]
When I try to do a brush stroke the cursor will randomly move, making the lines shaky and imprecise... the strangest thing is that it does not happen on all the canvas.

![image](https://user-images.githubusercontent.com/29640058/27452083-f2b613ac-5756-11e7-8060-ab90ace20dd1.png)

 Also, when I try to touch the tablet with the stylus, once the surfaces are meet. The cursor immediately jumps to the right.

**Comment by callaa** [comment]
This could be a tablet event related problem. Try the new tablet tester (in the help menu) in version 2.0.5 if it displays the same problem.

**Comment by SandGal** [comment]
It does (or at least I think it does orz. The blue line goes crazy at some parts)

**Comment by callaa** [comment]
Does enabling the bug workaround mode (in the preferences dialog) help?

**Comment by notfood** [comment]
Stale, closing.
