### ISSUE TITLE
Feature Request: Rotate + Skew

### ISSUE THREAD

**Issue by VRArt1** [drawpile/Drawpile#483]
Since the beginning I've loved this program and even up to this point there's only been two basic tools I and many of my friends have been desperately wanting.

Rotation and skew tools. Whenever I draw on my own I always abuse the skew tool so that I can get things at the right shape I want it too and rotating it around until it's just right.

**Comment by pachuco** [comment]
Yes, please.

**Comment by callaa** [comment]
Rotation is already implemented: hold down alt and drag a selection. I implemented a skew transformation as well for the next release.
