### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by DizThePenko-in** [drawpile/Drawpile#484]
Some friends and I have been having trouble to connect in both public and private sessions made by ourselves. We can join others' sessions just fine, but we would rather avoid that.

We've tried simple private room, private with password, simple public room with a low and high users limit and also public room with a password, it always gives us a "Connection time out" mistake like this:
![image](https://user-images.githubusercontent.com/29719471/27566433-f5e298b4-5aaa-11e7-8e07-f19a556b6f94.png)

We've been trying for a week now and we haven't found a solution, any help?

**Comment by callaa** [comment]
If you're using the built-in server, this is most likely a firewall problem. Have you tried the tips in the *Dealing with firewalls* section of the [hosting help page](https://drawpile.net/help/hosting/)?
