### ISSUE TITLE
b, e, and ctrl+e hotkeys all work as toggles

### ISSUE THREAD

**Issue by ghyun** [drawpile/Drawpile#486]
I don't know if this is the intended behavior, but it seems like all three of b, e, and ctrl+e toggle between the freehand and eraser tools (running 2.0.5.1 on ubuntu). It seems like it would be much more intuitive if the "b" hotkey always switched you to the freehand tool and the "e" hotkey always switched you to the eraser tool, regardless of what you were on before.

**Comment by callaa** [comment]
This is intended function. Tool shortcut keys toggle between the target tool and the previously selected tool, similar to the way holding a shortcut key down will temporarily switch to that tool. If you don't like this behaviour, you can disable it in the preferences dialog. (The option to disable it was introduced in version 2.0.5.)

**Comment by ghyun** [comment]
Ah, that explains it. Where in the preferences dialogue can I change this? I just skimmed through everything but didn't see something that looked relevant

**Comment by ghyun** [comment]
Oh never mind, got it, it was "shortcut toggles last selection" under "user interface"
