### ISSUE TITLE
Feature Request: Voice Chat

### ISSUE THREAD

**Issue by aquapaulo** [drawpile/Drawpile#487]
Sorry for not labeling, I'm new to this.

After several sessions in Drawpile I noticed long periods of silence in the chat and artists interrupting their work to write and chat with the others, and since noone has mentioned a voice chat request since 2015 I decided to request it.

I think with a voice chat artists would be able to not increase the quality of Drawpile's social features but people would also be more open to conversation.

**Comment by callaa** [comment]
A voice chat, while it would be a nice feature, is a bit out of scope for this project I feel. Despite both being realtime communication tools, there is not much overlap in the architecture of a voice chat application and a collaborative drawing program. I think it is more effective to use a separate dedicated voice chat, such as Discord or Google Talk, in conjunction with Drawpile. Perhaps there are some features that could be added to improve integration with them?
