### ISSUE TITLE
friend can't draw?

### ISSUE THREAD

**Issue by AwkwardPawter** [drawpile/Drawpile#488]
So i just downloaded drawpile, both me and my friend can draw just fine on seperate things, but when I made a server, she was able to join, but she couldn't draw. I could draw just fine, but when she hovered her mouse into the program, it disappeared, and she couldn't click on anything, or draw. i use windows and she has a mac. What can we do to fix this?

**Comment by callaa** [comment]
Did the cursor disappear entirely or turn into a 🚫 symbol?The latter would mean the canvas was locked for her. Did the program become responsive again at some point or did it have to be force-quit?
