### ISSUE TITLE
Feature request: Make other users pointers always visible (as an option)

### ISSUE THREAD

**Issue by szkielethor** [drawpile/Drawpile#489]
It would be very helpful for me, because I'm using Drawpile to conduct online science lessons. Often my students are asking me about some formula or something on the screen and pointing to it (not with laser pointer, who would remember to switch to it), but I don't see what they are pointing to. It's pretty annoying. Something idroo-like would be perfect. I've recorded video to make my request more understandable:
[https://www.youtube.com/watch?v=6VPKqrazmtk](url)

**Comment by notfood** [comment]
Track hovering pointer feature for the laser pointer should do the trick
