### ISSUE TITLE
Banning

### ISSUE THREAD

**Issue by poopdoopmoop** [drawpile/Drawpile#490]
Hey callaa, sorry if this is too personal of an issue to be posted here and should be sent through message but ive recently been IP banned from drawpile.net (hosting and joining servers on there) through being kicked too many times.
I was wondering if this ban is permanent? If it is, is there some way i can appeal and get unbanned? I'm still able to access syntheticdreams.net but i'd like to be able to draw with my regular friends.

**Comment by poopdoopmoop** [comment]
My friend said he's not totally sure if you can get IP banned from being kicked too many times. that was our original assumption but i suppose that might not be the case.

**Comment by poopdoopmoop** [comment]
Also i get that you're probably swamped from ideas from the community but some things that i'd love to see one day in drawpile would include
-Built in pictionary mode
-Built in scroll mode (The screen constantly scrolls to, say, the left and all your drawings slowly disappear as they go off the screen. your camera would automatically pan along with the board so you dont have to scroll to keep up with your drawing but maybe you'd be able to toggle this panning somehow. Speed and direction of scroll could be controlled by host.)
-Locking pieces of the boards to "teams" (this could have different uses. Hosts could lock off a piece of the board for things like RP'ing and give exclusive access to certain people. Alternatively hosts could create contests, locking each half of a board to a Red and Blue team and they would compete at different things.)
Thanks in advance for looking over my walls of text btw.

**Comment by callaa** [comment]
Hi. I removed your ban. The bans now auto-expire on their own as well. The default ban time is 3 weeks. Previously autobanning was based on kicks, but since server version 2.0, it's based on how often a specific IP address is banned from different sessions. So, if you get banned from multiple sessions in a short time period, the server automatically adds a temporary serverwide ban.

Feature requests:

> Pictionary mode

Can you elaborate how this would work? A generic support for game modes might be a cool feature.

> Scroll mode

This might be possible to implement using a bot. Might tie in with the game mode idea.

> Region locks

This is technically possible to implement (but requires a protocol change, so can't be done before version 2.1 at the earliest.) The biggest problem is UI design, since all the locking options are already pretty complicated.

**Comment by poopdoopmoop** [comment]
Oh okok. Thanks a ton for unbanning me. It'd be nice if it said how long your ban persists for but its great knowing now.
So i know that i kind of asked for a mountain of things there heehee but i was thinking that maybe when a host opens a server, they have a couple of options like
1. Regular server.

2. "pictionary" server. Sort of how Skribbl.io goes about it, the computer selects one person at a time to draw and the others have to guess what they're drawing as quick as they can. The person drawing is assinged 3 words, ranging in difficulty. (easy is shit like, Apple, medium is something like Throwing, hard is something like Taxes or whatever)
Maybe have one chatbox for chatting and another for guessing, and as the person is drawing you write your guesses in and points are awarded based on things like how fast you guessed the drawing, or how many people were able to guess what you were drawing. I guess that this would require a vigilant host/mods to quickly switch out the person drawing if they attempt to just write that their word is but it could be a lot of fun. It would also be nice if the computer that checked the guesses ignored small typos of up to 2-3 letters. When the word is guessed correctly it is not displayed in the box so as to not give away to the other players.
Hosts could have privileges like forcing someone to draw next, changing how much time you've got to draw for, booting a player out of drawing if they're just trying to write out what their word is, etc.
I can't really explain how this would work in technical coding terms, i'm sorry i dont know the coding langauage :( maybe sometime i'll bother to learn and try to contribute more to Drawpile. I think its the best way to draw online with friends and holds an incredible amount of potential and would definitely love to help out any way i can.

3. Scroll mode
screen slides off to the left or top or wherever the host has selected. Could be a fun idea. maybe its shit i have no idea what it would be like lol. like i said, you would automatically pan along with your drawing but you could enable/disable this. Host controls speed of drawings getting "eaten up" by the frame.


Region locking seems hard to implement but could be quite useful sometime. Opens up a possibility for team competitions and such. Maybe as soon as you join you're automatically in "spectator" but you can choose a team or something. Or maybe some people would just region lock a section of their regular server for them and their friends to RP on. not sure.

if you did have region locking another nice feature would be a Silhouette Game.
Maybe the board is divided into quarters or halves or whatever. Each person drawing is assigned a piece of the board and the same silhouette (Maybe the computer just chooses from a bunch of pre-drawn silhouettes, like small abstract shapes and pieces and mixes and matches the pieces?) And everyone is assigned the same word- something like Space Gun, Pirate Ship, Flying Boat, Exotic Bird from a random collection of words.
Then they've all got sayyy two minutes (host can change the timer) to turn their silhouette into the thing everyone's been assigned (Space Gun or Pirate Ship or Robot Overlord, whatever concept has been assinged). you can erase/add whatever you like to the silhouette but you can't see what anyone else is doing with theirs until the timer's up. Maybe once time's up a judge or team of judges assigned by the host decides which drawing they like the most. I think it would be really cool to see everyone's different takes on the same silhouette and same word.

Anyways i'm sure you're totally swamped with suggestions. You can ask me for more contact info if you want my help with anything at all, im not super code saavy but i'm super comitted to drawpile. but if you dont want my help that's totally okay. I just can't wait to see drawpile blossom further and see what you do with it.

**Comment by notfood** [comment]
Fixed, closing. You should re-submit the feature ideas in a new issue.
