### ISSUE TITLE
Chat box with newest version

### ISSUE THREAD

**Issue by doushite** [drawpile/Drawpile#491]
Hello. I recently downloaded the newest version of Drawpile (v. 2.0.5.1) and now, when I go into Drawpile, my chat will disappear off screen. 
I've tried to hide my task bar, but it doesn't help; the chat will fall under the screen entirely, or some bit of it will, and I cannot bring it all the way back up. This happens on the 32 bit and 64 bit version for Windows.
 I wish to have my older version back (the one right before this new version) but I can't seem to find it in the list of older versions.
Please help.

EX.
https://gyazo.com/cf3e3afa02044fef0eaf305aa2c18925

**Comment by doushite** [comment]
So to follow up on this, it's started working, but only in one window (I haven't tried to open up any others and see if it's working there)

**Comment by Le2222** [comment]
This is maybe the same issue of the topic #452

You also miss the page zoom controls, under the chat.

**Comment by doushite** [comment]
It was sort of like that problem; however, even if I moved the docks around, the chat would still disappear, no matter what I did. Even toggling with the task bar's functions didn't work so well.
Weirdly enough, the problem seems to have fixed itself, and my chat isn't disappearing (for now, at least).

**Comment by notfood** [comment]
Stale, closing. Issue appears to be related to docks min-size stacking.
