### ISSUE TITLE
Recognizing the tip of my tablet pen as an eraser - very annoying

### ISSUE THREAD

**Issue by ToxicPotato** [drawpile/Drawpile#493]
Using a Huion 1060PRO+, and it's recognizing the tip of my pen as an eraser. The troubling part being A, it was working completely fine a few months ago, and B, the pen doesn't even _have_ an eraser to begin with.

This wouldn't be a problem if it didn't switch to erasing every single time it detects my pen after lifting it. Basically unusable as it stands.

EDIT: Scratch that, not just when I lift it but basically every 10 seconds of using it, so keeping it close doesn't work either.

**Comment by callaa** [comment]
Most likely a driver bug. Probably the easiest fix/workaround for me will be to add an option to disable eraser detection.

**Comment by callaa** [comment]
The latest version now has an option to disable eraser detection.
