### ISSUE TITLE
MessageQueue timeout issue centos

### ISSUE THREAD

**Issue by sachinbanugariya** [drawpile/Drawpile#495]
hello
we are using centos 7,
download drawpile app image and while trying to run default app image file
service is running on 27750, after that when i try to connect with hostname:27750 it gives backend error like: 
MessageQueue timeout
Info/Leave 0;::ffff:123.xxx.xxx.74;: Non-logged in client removed.
Info/Status 0;::ffff:123.xxx.xxx.74;: New client connected

and issue seems frontend like:
�P��{"flags":["MULTI"],"message":"Drawpile server 2.0.5","type":"login","version":4}

what was the issue any configuration need for default installation?
thanks.

**Comment by callaa** [comment]
A messagequeue timeout means no traffic has passed within about 60 seconds (the default timeout IIRC.) This normally shouldn't happen, since the program will periodically send keepalive messages. Does it otherwise work normally or does it just hang at the login phase?

**Comment by sachinbanugariya** [comment]
ok,

i am just run default app image after download with drawpile user,
after app image process run it will show service started on 27750.

so after that i try to open webpage using servername:27750 but getting above issue,
need to know how to install and configure drawpile on centos 7 server.
 
after download default drawpile app image need to configure anything ??
thanks.

**Comment by callaa** [comment]
The default configuration should work. But I'm a bit confused about this part:

> so after that i try to open webpage using servername:27750

Are you trying to access the server with a web browser?

**Comment by sachinbanugariya** [comment]
Are you trying to access the server with a web browser?

yes after start service i trying to access from web browser.

**Comment by callaa** [comment]
Well, there's the problem. You need to use the Drawpile client. The server does have an HTTP API for server administration, but the actual drawing side is not a web application.

**Comment by sachinbanugariya** [comment]
you mean after start drawpile service, need to install drawpile client on my local PC and then need to connect with server ???

**Comment by callaa** [comment]
To participate in a Drawpile session, the client software is needed.

**Comment by sachinbanugariya** [comment]
ok can you please send me link or steps where i can see the interface steps for connect drawpile client with drawpile server sessions.

**Comment by callaa** [comment]
You can download the client from the [download page](https://drawpile.net/download/) and the instructions are on the  [help page](https://drawpile.net/help/).

**Comment by sachinbanugariya** [comment]
ok thank you so much for guide.
nice to meet you, thanks.
