### ISSUE TITLE
export image via command line

### ISSUE THREAD

**Issue by jameslis** [drawpile/Drawpile#496]
Is it possible to export the current canvas to an image file by using a command?
Our sessions can run for weeks on a headless server, so we would just cron this every so often to give a peek as to what's currently on the drawpile. (currently we just log in manually to check but we don't always have access to the program)
If there's no command for this, can it be implemented in a future release?

**Comment by callaa** [comment]
This is not yet possible, but it is definitely on the TODO list! When I'll start working on improvements to the paint engine, this feature will be an indispensable development tool as well.

**Comment by jameslis** [comment]
Thanks for considering this request, hope to see it live one day!

**Comment by callaa** [comment]
This feature is now implemented. There is now a new `drawpile-cmd` command line tool in the master branch for rendering recordings. A future improvement to it will be a caching mode so that when run repeatedly on an unfinished recording, it won't need to re-render it from the beginning.

**Comment by Wade821** [comment]
So is this feature still a thing? I don't see the tool generated as part of the installation so I'm a bit confused on how to make this work.

**Comment by johannesCmayer** [comment]
I would like this.

**Comment by askmeaboutlo0m** [comment]
@johannesCmayer the feature exists. You run `drawpile-cmd -f png something.dprec` and it'll generate a PNG file. It can also take a bunch of other options that you can interrogate with `--help`.

On Windows, the drawpile-cmd is in a separate "server and tools" package: <https://drawpile.net/download/#Archive> On Linux, it's in the AppImage and will be run if you pass `--drawpile-cmd` as the first argument. On macOS, you can find it inside of the Drawpile.app application bundle.

**Comment by johannesCmayer** [comment]
Apparently nix currently only packages drawpile and drawpile-srv, but not the other tools (the tools are not embedded in the drawpile executable). Somebody could make a package request. I now downloaded the AppImage and that works as you described.

**Comment by askmeaboutlo0m** [comment]
Yes, you'll have to direct your request to the package maintainers of those third-party packages. They can ask if they need help building the command-line tools or something.

-------- Original Message --------
