### ISSUE TITLE
Problem with pen eraser.

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#497]
This didn't happened on previous drawpile versions.
I use a Cintiq 21UX and the problem comes when I use the pen eraser.
The eraser IS detected, but I can't turn back to pen mode without having to manually change the brush.

Flip the pen to eraser: detects eraser, good
Flip back to normal pen after erasing: Doesn't work, it still on eraser.

I really doubt this has anything to do with drivers cuz the eraser detection worked perfectly on DP 2.0.2, which was the last version I used where the pen mode detection worked.

**Comment by notfood** [comment]
Stale, closing. If it's still happening, please feel free to re-open the issue.
