### ISSUE TITLE
minimum/maximum brush size?

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#498]
A feature I find myself missing from other programs is the ability to set a "minimum size" for a brush, ala PTS, so that I even with the lightest stroke, I wind up with say, a 25% pressure line. Is this something that would work well in drawpile, or would this end up making the UI too cluttered? Maybe something gated behind a checkbox or a menu?

**Comment by callaa** [comment]
I tried this in version 2.0.0, but the new UI proved unpopular, so I had to revert to the old style. Technically, Drawpile does support it, there just isn't an UI for it. The pressure response curve in the input dock can be adjusted to achieve this effect, though.

**Comment by ParisGreen** [comment]
True, but the only bummer with the input dock is that it simultaneously controls -every- pressure response at once, so you can't have a different minimum for say, size and opacity. I agree that the current UI is better an less cluttered, though. Either way, sorry if I'm being a pain.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

A proper brush editor with pressure curves and minimum/maximum sizes has been implemented and will be coming in Drawpile 2.2.

![image](https://user-images.githubusercontent.com/13625824/227440450-725726f1-307b-4b24-955f-769ec36237b8.png)
