### ISSUE TITLE
Drawpile didcated server User Configuration Helper

### ISSUE THREAD

**Issue by Wolvan** [drawpile/Drawpile#499]
It has taken me quite a while to figure out how to set up a drawpile server, and even more time to get salted and hashed passwords working. I even ended up writing a NodeJS script to create a salt/hash pair for me to make my job easier.

But I ended up getting fed up with that approach and wanted something easier, so until I find a place where this is provided (**or until there is an official thing coming from the drawpile devs**), I made a helper for people who don't exactly know how to do all these fancy shenanigans.

All is done in browser, no passwords are transmitted over the network.
http://drawpile.wolvan.at/

**Comment by notfood** [comment]
The docker DpWebServer project should make it even easier.

https://github.com/drawpile/dpserver
