### ISSUE TITLE
Connection problems on public server

### ISSUE THREAD

**Issue by ToxicPotato** [drawpile/Drawpile#501]
Attempting to connect to a room hosted on the public drawpile.net server results in endless "Catching up". 

Hosting my own on this server makes some actions simply not work (namely undo and laser pointer), and a friend attempting to join faces the same endless "Catching up" message but has no problems with other public rooms.

Seems to be my end, yet nothing has changed with my connection since I last used Drawpile with this same friend just fine three days ago. Tested on versions 2.0.2, 2.0.3, and 2.0.5.

**Comment by doushite** [comment]
Yeah, that was happening to a few users in a public room we were in earlier, now the entire Drawpile server has died- the list and rooms are jacked up, and caught in that endless 'catching up.'
Also, the official online Drawpile page/website is experiencing Server Error (500). Only syntheticdream.net server is working.

**Comment by callaa** [comment]
The server had run out of disk space. I freed up some space and improved the cleanup script so this shouldn't happen so easily again.
