### ISSUE TITLE
X-axis inaccurate 

### ISSUE THREAD

**Issue by TeeHallums** [drawpile/Drawpile#502]
When drawing in drawpile, the x-axis is incredibly exaggerated. 
![image](https://user-images.githubusercontent.com/30741394/28992559-72e0bff2-7965-11e7-857a-6a4677639b38.png)

Here is a near perfect circle that a drew, when done in drawpile. This is an issue specific solely to drawpile, no other applications present this problem.

**Comment by callaa** [comment]
Does this happen when drawing with a tablet stylus or a mouse (or both?)

**Comment by TeeHallums** [comment]
From what i can tell its most likely just when its with a tablet. Though its hard to say for sure because im not very confident in my ability to consistently draw a perfect circle with a mouse. 
![image](https://user-images.githubusercontent.com/30741394/28999074-1b35fa9c-7a00-11e7-8ae6-e60dd2653854.png)

Heres a circle drawn with mouse.

Again, this issue exists literally only in drawpile, no other software.
I suppose its worth noting that I have 3 displays. The left and right displays are 720p and the middle is 4k.

**Comment by TeeHallums** [comment]
![image](https://user-images.githubusercontent.com/30741394/29284048-d2caade8-80ee-11e7-99aa-11897d8907f6.png)

I have no idea if this is helpful, but here are the logs for when I draw a circle.

**Comment by callaa** [comment]
I just released version 2.0.9, which has improved tablet support. Can you try if it fixes your problem?

**Comment by notfood** [comment]
Stale, closing.
