### ISSUE TITLE
IP ban per session

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#503]
An idea, but I don't know how easy it is to implement. Banning an IP per session, or having a "Add User" to the session settings dialogue that keeps the user list for 10 minutes (possibly filtering duplicate IPs internally?). OR, could have a list of only the past 15 users? Occasionally I see users that know they're going to be banned that will just enter and leave immediately, just to be antagonizing.

**Comment by callaa** [comment]
Should be possible to implement. Currently, the in-session ban hides the user's IP for privacy reasons, but an IP only ban could be added as an alternative.

**Comment by askmeaboutlo0m** [comment]
This was already partially existent and should now work properly. You can ban past users by opening Session > Event Log and going to the Users tab. In Drawpile 2.2, this will ban their username, their ext-auth account and their IP address. Non-moderators can only view the username, but the other types of bans are there in the background and visible to mods.
