### ISSUE TITLE
Remote admin banning expiration is stuck

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#506]
I figured this may be because of my remote admin login issue, but a server restart did not fix.

Currently, trying to ban an IP using the remote admin tool. No matter what I do, it states that the expiration is **2017-08-15 08:59:57**. Even if it is currently beyond that server time now...

**Comment by callaa** [comment]
Is there an existing ban for the same IP already? At least in that case the server will just return the existing entry instead of updating or adding a new one.

**Comment by tincancrab** [comment]
No. I think this is actually tied to the remote admin tool disconnecting. If I leave it open, I can keep a connection going (but if I close the program, I'm screwed). Despite keeping that connection, the ban tool breaks and makes the expiration the current time, and I must edit it in SQLite config.db to mitigate the issue.

**Comment by notfood** [comment]
Is this still happening?

**Comment by tincancrab** [comment]
No, and callaa found the bug causing remote admin to eventually time out recently, so this issue is solved.
