### ISSUE TITLE
locked layer editable with select tool.

### ISSUE THREAD

**Issue by NGMZero** [drawpile/Drawpile#508]
Issue: Users can cut and paste (basically still being able to use keyboard shortcuts) to a locked layer using the "select tool".

**Pasting**
1. Ctrl + V in a locked layer.
2. Click "Enter" to confirm. 

**Deleting**
1. Select something using the "Select Tool" in a normal layer.
2. move to a locked layer and use Ctrl + X or Delete.

Edit: Removed the delete part, because it Undo it self.
Edit2: Readded it because it work on HOSTED sessions.

**Comment by callaa** [comment]
This is now fixed.

The commands were being properly filtered, so the changes were limited to the local canvas only and would be rolled back as soon as the user did something else.
