### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#511]
Buddy system where people can friend each other and see what room peers are in later on. Could be disabled manually of course. (I've met several people I'd liked to draw with again but have never seen them again.)

Way to switch layers by clicking the colours on the canvas. (In Krita it's done by holding R and left clicking canvas)

Built in pictionary bot (people could load .txt files into it)

**Comment by Luca1211** [comment]
would love to see such a feature in Drawpile.. for me i love to do collabs with other peoples, its a fun way to learn new techniques and get fresh inspiration.. and its realy sad when u have no way (by sides social media and stuff) to find those peoples again.

So Please Drawpile ._. make a Friend System,

**Comment by callaa** [comment]
A small update on this: I'm currently working on adding some basic social features (user accounts, gallery, groups, etc.) to the website that will integrate with the drawpile.net public server and can be used by other servers as well.

**Comment by callaa** [comment]
The layer picking feature (select layer by holding ctrl+shift) is now implemented. I'm closing this issue now, but social features are coming too.
