### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by Nocturnacat** [drawpile/Drawpile#512]
Most of the issues are linked to resizing the window. 
For one, the part of the chat bar where you type sometimes isn't there and other times it is. When resizing the chat it only shows the top  instead of scrolling down to the most recent chat.
When resizing the window the scroll bars disappear most times and sometimes when making the window smaller it will just disappear completely. Also the actual minimize, restore down and close buttons (on the top of the window) disappear sometimes. This is a bit annoying especially if I wanted to open up another tab on the other side of the screen for reference when drawing. 

Also, sometimes it will draw in straight glitchy lines (but i assume this is more of a lag-related problem)

**Comment by callaa** [comment]
Which operating system are you using? I've never encountered the window button disappearing issue. Do just the buttons disappear, or does the window go past the screen? A common problem is that the window is higher than the screen, so either the top or the bottom gets cut off. Is this what's happening when the chat bar is missing?

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Since there was no response in so long, I'll close this for now.
