### ISSUE TITLE
No pen pressure on Drawpile 2.0.5

### ISSUE THREAD

**Issue by Drunkperidot** [drawpile/Drawpile#513]
About a few days ago my pen pressure gave out for seemingly no reason at all on Drawpile 2.0.5 
There was no issues untill then and it still doesn't work still. Bascially when I draw it just looks like chicken scratch like this:
![pen](https://user-images.githubusercontent.com/31380143/29747237-b2d15d44-8aa7-11e7-8188-0d3d842f328f.JPG)

This is what I have done:

- Reinstalled drawpile completely 

- Have all the nodes checked in the program in order for it to supposed to work.

- My tablet works on all other programs except this one.

- Made sure my tablet is updated

- Restarted my computer

Guys I am begging I can't find any solutions and I am actually starting to get driven to tears because I 
can't join my friends.

**Comment by bananapotsticker** [comment]
I have the exact same issue and it's a little disheartening to see nobody responding to these.

**Comment by NGMZero** [comment]
What tablet is that?

**Comment by Drunkperidot** [comment]
@NGMZero 

Wacom Intuos Art tablet.

and i'm still having these issues to this day.

**Comment by callaa** [comment]
Is this after the Windows 10 creator's update (like issue #531)?

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
