### ISSUE TITLE
Notification sounds don't work ?

### ISSUE THREAD

**Issue by JamesDelaneyyy** [drawpile/Drawpile#514]
I just found out, to my surprise, after looking trough the preferences that there were notification sounds ?They're all ticked,but needless to say they're not working .I've been using DP since release, and I've always had to rely on the small bubble that pops out,when a person enters and leaves,which can be difficult if my attention is elsewhere.Can the notification sounds be fixed so they can work? It would be a big help.

**Comment by callaa** [comment]
Is this on the Windows version?

**Comment by JamesDelaneyyy** [comment]
Yes it is

**Comment by callaa** [comment]
This is now fixed for the upcoming release.
