### ISSUE TITLE
Feature suggestion: change default size so pressure doesn't appear broken

### ISSUE THREAD

**Issue by TheLastProject** [drawpile/Drawpile#515]
The default size of both the stylus and eraser in Drawpile is 1px. With this size, pen pressure doesn't work because 1px is always 1px. I'd recommend to change the default size to something like 10px for both, so that in a clean install, pen pressure does not appear to be broken. It would also be good to add some text stating something like this when pressure size is enabled, so that people don't get confused like I did.

I don't know how many of the issues refer to that, but I know that I spent a good two hours trying different builds and trying to figure out what was wrong because it works without changing anything in Krita. I even almost made a bugreport asking for help on this. Making this change would be very small and could fix a lot of confusion for new users.

**Comment by callaa** [comment]
That's a good idea. I'll have to remember to clear my settings every once in a while to see how Drawpile looks just after a clean install.

As you suggested, I changed the default brush size to 10px.
