### ISSUE TITLE
Get list of logged-in users?

### ISSUE THREAD

**Issue by bctiemann** [drawpile/Drawpile#516]
Hi,

I'm running a dedicated server. I'd like to be able to publish a list of the logged-in usernames to an external site. Is there any way to query that info from the running server?

Apologies if this isn't the right place to ask this.

**Comment by KurinPawpad** [comment]
Depending on which version of the server (1.x or 2.x) you are running, you can query the server on the RESTful API documented here: https://github.com/drawpile/Drawpile/blob/master/doc/server-api.md

The server will respond with JSON data.

**Comment by callaa** [comment]
Hi! Sorry it took me so long to answer.
As Kurin noted, you can get this data via the web-admin API. (Make a GET query to `/users/` and it will return a JSON formatted list of users.)

The web-admin interface itself only provides all-or-nothing access control, so it can't be published on the Internet as is. To work around that, I created [a little tool](https://github.com/drawpile/pubsrvproxy/) to safely proxy read-only requests for session and user lists. You can see it in action here: http://pub.drawpile.net

**Comment by bctiemann** [comment]
Works for me. Thanks!
