### ISSUE TITLE
People can't join my host

### ISSUE THREAD

**Issue by kej-ngwpo-ine-FW** [drawpile/Drawpile#517]
I've already made the port forward. However, no matter what happens all my room codes are expired to anyone who uses them. Help!

**Comment by callaa** [comment]
Does it say the room code is expired or do they get some other error when connecting?
If the room code is expired, it means the session listing is not being refreshed. In that case, the server should send an error message to the chat.

**Comment by notfood** [comment]
Stale, closing.
