### ISSUE TITLE
Ip banned...

### ISSUE THREAD

**Issue by snoxhon** [drawpile/Drawpile#518]
Hello, 
My Ip was banned from Skribbl.io,
Because my friends often kick me „for fun“ 
And why we can get banned from kicking??
On the german servers is a word „nothing“ if i dont draw anything because the word is so
I got kicked... 

I hope i got unbanned

Snoxhon

Ps: sorry for my bad english im from german.

**Comment by callaa** [comment]
Hi, sorry for the late reply. I'm not affiliated with skribbl.io, so there is nothing I can do.
