### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by mukkky** [drawpile/Drawpile#519]
I'm trying to connect to a public room created by a friend but I always got time out and a message that says that I can't connect to the server. The same happens to them when they try to join my session. But we can join other people's sessions. We always joined to a server number 45.72.149.129 but it is not working now.

**Comment by callaa** [comment]
Most likely a firewall issue. Have you checked the "dealing with firewalls" section of the [help page](https://drawpile.net/help/hosting/)?

**Comment by notfood** [comment]
Stale, closing.
