### ISSUE TITLE
Delay causes "flatspot" when drawing lines.

### ISSUE THREAD

**Issue by Yellow-Somethingidgaf** [drawpile/Drawpile#520]
First off, I'm using a wacom pen-enabled laptop along with wacom tabletpc drivers.

When drawing a line, there seems to be a delay at the beginning of the stroke causing a "flatspot". I've disabled gestures and flicks, onscreen keyboard/handwriting, using latest wacom drivers, tweaked with every setting in drawpile, turned on/off pressure and line thicknesses, different brushes, sizes, erasers, etc.
Nothing seems to be fixing it and I know it's not directly a windows problems because, as shown in the attached image, programs such as managa studio work fine. (paint, photoshop, krita all tested)

![drawpile issue](https://user-images.githubusercontent.com/32561549/31263325-202c3a00-aa27-11e7-9783-2029993bda9b.png)

**Comment by ParisGreen** [comment]
This almost looks related to lag. Does it do this when you draw without being connected to anyone else?

**Comment by Yellow-Somethingidgaf** [comment]
The screenshot was taken in an offline session

**Comment by callaa** [comment]
Does the same delay happen in the tablet tester (found in the *Help* menu)?

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
