### ISSUE TITLE
Unable to join Session when server only has template

### ISSUE THREAD

**Issue by KurinPawpad** [drawpile/Drawpile#521]
I've attempted to create a server that has templates (.dptxt) for 4 different sessions, and clears out sessions after 4 hours of idle.  Once this happens (or the server otherwise has no active session, only the template such as on fresh startup) I cannot join the session by drawpile:// link.  I have to manually connect, choose one of the four sessions, and then join that.  once the session has been joined, I can connect to it via link as expected.  The error I receive is Could not connect to server, Session not found!  In the server log, I also see 'New client connected', then 'Non-logged in client removed.' and finally 'Disconnected due to error: login error'.  On the server I have enabled 'Allow anyone to host sessions', but this does not resolve the issue.  What can I do to resolve this?  I'd like anyone to be able to initiate a templated session by joining via link, as long as the server is running.

**Comment by callaa** [comment]
Thanks for reporting! This is a bug in the current version. The fix is now in the master branch and will be part of the 2.0.6 release.
