### ISSUE TITLE
Holding undo drags canvas

### ISSUE THREAD

**Issue by reeniebear99** [drawpile/Drawpile#522]
I just newly installed Drawpile, and my biggest problem is my undo. When I hold the undo button on my tablet pen, it drags the canvas up and down until I release it. It still goes through with the undo, but it drags at the same time, and makes it a hassle to keep my position on the canvas. I tried to go into shortcuts, thinking that they may be clashing, but I couldn't find a shortcut for dragging at all. Any advice?

**Comment by callaa** [comment]
Try the tablet tester (help menu.) When you hold the undo button there, what does it show?

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
