### ISSUE TITLE
A link on the site that linked directly here would be nice

### ISSUE THREAD

**Issue by Pandikko** [drawpile/Drawpile#524]
It was so hard to find this place. I'm not familiar with github and actually found this accidentally by clicking anything I thought might be helpful after seeing someone get directed here from the google+ page. There are probably so many more people who have problems but have no idea where to go to ask them.

**Comment by callaa** [comment]
You're right! The website used to have a bug reporting guide with a link to here, but it seems that I forgot all about it when I rebuilt the site. I added a short bug reporting guide to the help page.
