### ISSUE TITLE
Drawing straight lines causes it to zig-zag

### ISSUE THREAD

**Issue by DucktorSpiffy** [drawpile/Drawpile#525]
I've been trying to draw with a friend but I've found a few problems (maybe tablet related?)

One of the main problems is [this](https://imgur.com/a/Pu0zo). Notice how it's randomly had a sharp 'jolt' upwards? I just tried to draw a quick squiggle. It seems to only happen when the brush has a size > 1 so possibly some kind of pressure bug?

I'm using a Ugee M708 tablet (I've had ALOT of problems with this tablet with programs) with the latest drivers & such.

**Comment by ParisGreen** [comment]
Have you tried enabling the bug workarounds?

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
