### ISSUE TITLE
Reset occasionally wipes board

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#529]
Sometimes, and I'm trying to find a reason why, a reset will wipe a board of all drawings much to everyone's dismay. I'm not sure the root cause. Generally, the board that is most suspect has heavy traffic; approx 30 users to 50 at peak times. Age of session is generally a day or two old when this happens. Canvas is 5784 x 4338 (yes, I've repeatedly warned them about size). Auto reset happens at about 14 MB (had to increase max session size due to heavy traffic boards resetting too often).

**Comment by callaa** [comment]
When the reset happens, do you still get phantom brush moves over an empty canvas? If so, what's probably happening is that the snapshot filtering is not working right. If you have a session recording of this happening, it would help. (Just the first 100 KB or so should be enough to tell.)

**Comment by tincancrab** [comment]
Will see if somebody can record this once this occurs. Its unpredictable when it happens, so we may not be able to get anything beyond the aftermath, if that's ok.

**Comment by callaa** [comment]
This problem should be fixed now in the latest release. I found two different reset related bugs that could result in a wiped board. Hopefully those were the only ones.
