### ISSUE TITLE
Network error? Bad gateway?

### ISSUE THREAD

**Issue by Infires** [drawpile/Drawpile#530]
So I clicked on join and went to find a room, this popped up. I'm not sure why, i'm pretty sure I haven't done anything for this to happen. My network is doing just fine so I tried restarting my computer, but the error is still there. Even when I go to the drawpile website, it shows me an error too.
<img width="670" alt="capture" src="https://user-images.githubusercontent.com/34263491/33598330-76905008-d9f6-11e7-963d-56cff83ea0de.PNG">

<img width="434" alt="capture" src="https://user-images.githubusercontent.com/34263491/33611231-be2a177a-da21-11e7-87c8-22e89d778748.PNG">

Is there any solution or way I can fix this?

**Comment by chaoscontrolled123** [comment]
This is happening to me too. Going to https://drawpile.net/api/listing/ in the browser throws a bad gateway error, so I think the problem is on the public server's end?

**Comment by callaa** [comment]
Sorry for the late reply. IIRC, this was caused by the listserver not automatically coming back up after a server restart due to a misconfiguration.
