### ISSUE TITLE
Windows 10 creator's update seems to break pen pressure

### ISSUE THREAD

**Issue by bananapotsticker** [drawpile/Drawpile#531]
See title.

Everything was working fine until I updated to the creator update and now it's all broken. The pen either moves the canvas around like I was touching it with my finger or just doesn't give me any pressure. I've spoken to several others and they all said the same thing happened to them when they updated.

I've tried:

Removing drawpile and all files related to it (went hunting down) and even went into the registry and searched for anything with drawpile and deleted them.
Reinstalling wintab drivers, both x32 and x64
Reinstalling drawpile and using previous versions
Countless restarting and cursing.

**Comment by NGMZero** [comment]
Sense you mentioned wintab driver i am assuming this is a surface device, you will need Microsoft Visual C++ 2010 Redistributable Package too, found [here](https://www.microsoft.com/en-us/download/details.aspx?id=14632) and may be a restart.

A work around for the canvas moving when trying to draw is disabling "Scroll with finger" from draw pile settings. 

If you have found a better fix, it will be great to know! good luck.

**Comment by callaa** [comment]
Many people have encountered this problem and it seems to affect other programs that use Wintab as well. Based on what's been reported, it seems that after the update, Windows is reporting tablet events as touch events. (Why would they make such a change I cannot imagine.) Once I remember to buy new batteries for my stylus, I'll take a look if there is something I can do. The ideal situation would be if the pen pressure is included in the touch event. In that case, I could add pressure support to the fingerpaint mode and hopefully it would work normally.

**Comment by NGMZero** [comment]
For surface devices, I think the pen is working fine. It just conflict with touch. if the mouse is pressed (touch is pressed) and the pen is also detected, Drawpile should ignore touch input. instead of applying the move canvas.
In the tablet tester, touching the screen or clicking with mouse both result in (mouse press, mouse move, mouse release).

**Comment by HaloRings** [comment]
Hello, 
I'm not sure if this issues is related. When I join server, my surface pen keep moving the canvas. But when I create a new file. It work normally. Not sure what causing it behave this way.
![ice_video_20180128-192156](https://user-images.githubusercontent.com/35905328/35489262-6a97e572-0462-11e8-9327-27be7d010c94.gif)


![ice_video_20180128-193949](https://user-images.githubusercontent.com/35905328/35489311-32a17c0e-0463-11e8-8cbf-b056b9a004a2.gif)

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
