### ISSUE TITLE
Tablet pressure not working HUION

### ISSUE THREAD

**Issue by sasjakoning** [drawpile/Drawpile#533]
Heya, 

I have the HUION GT-220 v2 (monitor tablet) on which tablet pressure works on all programs but Drawpile.

I tried
- reinstalling
- switching to 32 bit
- downloading wintab (doubt that has anything to do with huion tablets)
- all the recommented fixes shown on the website and obvious things.

Any idea?

**Comment by tincancrab** [comment]
This isn't really a fix; more of a suggestion based on my knowledge of Drawpile.

https://docs.krita.org/List_of_Tablets_Supported

Looks like its supposed to work according to here. I'd look to see if it works with Krita, as that's the base for Drawpile. If it doesn't, I'd look into solving it for Krita by reaching out to the devs/community. It's not guaranteed to fix Drawpile, but it's the best starting point I can give you.

**Comment by sasjakoning** [comment]
thanks for the suggestion, I'll look into it!

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
