### ISSUE TITLE
Snap package?

### ISSUE THREAD

**Issue by mrjpaxton** [drawpile/Drawpile#534]
Hey, I would really like a Snap package of Drawpile (available along with AppImage), so it can self-update.

More info here: https://snapcraft.io/

**Comment by callaa** [comment]
I'm still waiting for Snap (or Flatpak) to mature a bit. At the moment, Snap is still not very well supported outside Ubuntu. Flatpak has better cross-distro support, but until KDE officially supports it, I don't consider it mature either.

On the other hand, building an AppImage with up to date dependencies that actually works cross-distro is getting harder and harder, so I hope either Snap or Flatpak becomes a viable replacement soon.

**Comment by callaa** [comment]
Drawpile is now available as a flatpak via Flathub. It's not Snap, but should do the same thing.
