### ISSUE TITLE
Feature Suggestion: rotate canvas shortcut should repeat when held

### ISSUE THREAD

**Issue by Yowesephth** [drawpile/Drawpile#535]
Coming from other art programs, setting keys to rotate the canvas is very helpful, but drawpile is the odd man out in terms of holding they key down to continously rotate to the proper angle. you have to repetitively press they shortcut, which is much slower and interrupts workflow. Having the key repeat when held would be an improvement.

**Comment by callaa** [comment]
I think the key-repeat not working is related to how shortcuts of that type work in general. However, you can rotate continuously by dragging the mouse while holding Ctrl+Space. This is documented in the *shortcuts* help page on the website, but not many people seem to find it. Perhaps there should be a shortcuts help screen available directly from the Help menu?
