### ISSUE TITLE
DB and config file do not work on Appimage server

### ISSUE THREAD

**Issue by codl** [drawpile/Drawpile#538]
Neither of DB or reading a config file seem to work with the Appimage server build. the DB just fails on startup and the config file starts but none of it seems to be read

**Comment by callaa** [comment]
Try giving an absolute path to the file. If I recall, the working directory is inside the AppImage bundle, so it will try to look for the file in the wrong place.

**Comment by codl** [comment]
indeed, absolute paths work, thank you

this could use documenting

**Comment by callaa** [comment]
Good idea. I added a paragraph about it to the dedicated server help page.
