### ISSUE TITLE
Floodfill glitch when using over previously erased area

### ISSUE THREAD

**Issue by weylin6** [drawpile/Drawpile#539]
If you draw an enclosed shape, then use the eraser to smooth or carve it out or make adjustments, using the floodfill tool will only work on part of the enclosed area and require several attempts, often leaving several small unfilled pockets everywhere.

It's as though the eraser itself is drawing an entirely different "color" than the blank canvas, so the flood fill treats it differently, even at max tolerance.

**Comment by callaa** [comment]
Does this happen with the "sample merged" option unchecked or checked? My guess is that there is still hidden color information in the transparent areas. If this is what is causing the problem, it (and hopefully a few other problems) will be fixed when I change to a alpha premultiplied layers.

**Comment by weylin6** [comment]
I just tested it a bit further, and this only happens with "Sample Merged" disabled.
Enabling it made the problem go away, at least from what I noticed so far.
When I tested it last, it took a tolerance of 72+ to floodfill the entire same-color area with it disabled.

**Comment by callaa** [comment]
This is now fixed.
