### ISSUE TITLE
Some icons (buttons) could be better (UI Design).

### ISSUE THREAD

**Issue by Le2222** [drawpile/Drawpile#540]
Imo 4 drawpile icons could be better. As a suggestion, I did 2 major changes in 2 drawpile icons and 2 minor changes in another 2 drawpile icons.

Changes list:

**Bezier**: It got flipped to let the weight of the image heavier in the bottom. (minor change)
**Text**: The letter got serif to do not let it confusing with regular lines. (minor change)
**Color Picker**: The waterdrop icon in Photoshop means 'blur tool' so to do not let people confused I changed it to a color-picker. (big change)
**Select (rectangular)**: It is now easier to identify it as a sister-tool of the 'select (free-form)'. (big change)

Preview of the new icons in the UI:
![new icons](https://s17.postimg.org/kryw90d0f/newicons.png)

Icons download link (place in drawpile folder/theme to try):
https://mega.nz/#!8ZZRQaCD!K5lqaBYvlhyrnBaqTyJ-3_TPpHOR9A_nUFIQ9UPSSb8

_ps: I made the icons so they're free to use, if you want._

**Comment by callaa** [comment]
Thanks, the new icons look good. The icons are originally from KDE's Breeze icon theme, so if you're interested you can submit them upstream as well.
