### ISSUE TITLE
Issue with left handed controls

### ISSUE THREAD

**Issue by karai17** [drawpile/Drawpile#542]
Hello,

I have a left handed mouse that unfortunately swaps the button 1 and button 2 on hardware. SO this mouse has button one as the right click. To compensate, I have swapped the mouse buttons in Windows config so my left button is again left click (with my middle finger). When I am using my tablet, Windows UI is generally fine but in Drawpile only it is enforcing a right-handed approach and when I press my pen down on the X button to close or other buttons within the program, it triggers a right click instead of a left click. Some buttons such as picking a tool work with either left or right click whereas other options such as modifying the options of a tool do not work.

**Comment by callaa** [comment]
I'm unable to replicate this problem. Do I understand it correctly: when right button is selected as the primary button, stylus press event is interpreted as a right mouse click?

**Comment by karai17** [comment]
yeah, that seems to sum it up. I'm not sure if it's a driver issue though.
I'm using the huion 580

**Comment by callaa** [comment]
Okay, then it is probably tablet driver related, since the same doesn't happen with my tablet.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
