### ISSUE TITLE
[2.0.6] Interface theme fails to load

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#546]
Windows users are reporting the interface theme isn't loading.

![2.0.6 interface](https://imgur.com/ggpVDaa.png)
![2.0.6 another example](https://i.imgur.com/nvjZNah.png)

**Comment by callaa** [comment]
Now that you mention it, that does look different to what it used to. Between this and the previous release, I made some changes to the build environment to include libsodium. Perhaps that introduced other changes as well. I'll see if rebuilding everything from scratch has any effect.

**Comment by callaa** [comment]
Looks like there was a style DLL missing. I wonder why it worked previously.
