### ISSUE TITLE
[2.0.6] Color history saving duplicates

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#547]
In 2.0.5 drawpile color history kept only unique colors.

It's triggered by just changing color with the swatch then going for the same color.

It should only save the last color you used, not the last color you picked. It goes unusable fast the way it is in 2.0.6.

![1](https://i.imgur.com/qXwgWUt.png)

![2](https://i.imgur.com/YXemell.png)

Alternatively, if you pick a duplicate it should remove the old one.

**Comment by callaa** [comment]
This is now fixed.

**Comment by notfood** [comment]
I really tried to like the new color history but it's a pain, duplicates are still a big issue and it becomes unusable fast when you are switching tools, you even lose history under certain tool toogling, which happens often when you are coloring. Can we go back to the old way of saving history? It made sense and never got duplicates. New way is very awkward to use reliably, even with the bugs ironed out it doesn't make sense.

**Comment by callaa** [comment]
I suppose we can. Just to remind myself: the old way was when there was only one color history and pressing X switched just the first color, right?

**Comment by notfood** [comment]
Nono, separate X history is fine. I like that feature.

The old way is, only save history after you have drawn the line. Not during picking the color.

**Comment by callaa** [comment]
Ah, good thing I asked first. Yeah, I think I'll have to revert that change. If the new feature worked properly, it should be equivalent to the old way, but there seems to be no end to the corner cases where it acts oddly. Which then raises the question of what extra value does the realtime update provide.
