### ISSUE TITLE
Mac Screen Problems

### ISSUE THREAD

**Issue by kateellec** [drawpile/Drawpile#549]
I have a MacBook Pro and decided to download the new update. Unfortunately, the entire screen goes past the bottom, and I can't find a way to fix this. It refuses to adjust to move up because it goes too far past the screen, but I can still adjust side to side. Is there any way to fix this? Thank you.
![screen shot 2018-01-22 at 9 18 22 pm](https://user-images.githubusercontent.com/35180231/35256498-cbdd575c-ffb9-11e7-9fef-6b90ebcde9aa.png)

**Comment by notfood** [comment]
Try moving the brush dock into the color dock so they share space. It's the docks minimun height pushing the window past your screen size.

**Comment by callaa** [comment]
At the moment, there are no other fixes, except to rearrange the docks so they take up less space. They can be hidden, tabbed together or moved to the other side of the window.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

The default layout has been made to fit better on small screens and you can pick layouts from View > Layouts. That will be coming in Drawpile 2.2.
