### ISSUE TITLE
Logging in as signed user - issue

### ISSUE THREAD

**Issue by LuraDream** [drawpile/Drawpile#551]
Today with friend we tried to use option of logging into server with our accounts. Person hosting session seems fine, issue is with either of us trying to connect to session. For some reason after getting pass trough logging to account part, we are stuck on that screen, without option of putting session password or do anything else that is not canceling.

![image](https://user-images.githubusercontent.com/24532934/35291110-971da7e8-006c-11e8-88fe-bd7425700090.png)

**Comment by callaa** [comment]
Confirmed, the password entry field is disabled after logging in with a registered user account. The appears to affect only logins using the new external user account system and not the old built-in accounts.

Thanks for reporting!

**Comment by callaa** [comment]
The bug is now fixed. I'll release a new version that includes this, and a few others, later this week.
