### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#552]
Not to be a stick in the mud, but is there any reason why the 2.0.6 interface has those weird windows95 looking bezels instead of using color to show things? Not a huge deal either way, but it just feels a little dated.

![screenshot 2017-10-10 23 04 37-1](https://user-images.githubusercontent.com/8505474/35412712-137c61c4-01eb-11e8-846f-9763bce4d79f.png)
![screenshot 2018-01-25 16 12 54](https://user-images.githubusercontent.com/8505474/35412713-138c2d0c-01eb-11e8-8726-c85c47497f40.png)

**Comment by callaa** [comment]
It's caused by a missing DLL. I will release an update later today that will fix it, as well as a few [other bugs](https://github.com/drawpile/Drawpile/blob/master/ChangeLog)

**Comment by callaa** [comment]
The new version is now out.
