### ISSUE TITLE
Help, I'm stupid; Mac download "No Mountable File Systems"

### ISSUE THREAD

**Issue by orbasama** [drawpile/Drawpile#553]
I have not been able to use DP since the 2.0.6 update; every time I open up the mac file, I get a message stating: no mountable file systems.

This also goes for the newest update 2.0.7.

I have already re-downloaded the files more than once, I restarted the desktop and I updated the software but I still receive the same message. I was then told that I'm not the only person experiencing this and that the file may be the problem, not the comp. I'm aware of how bad macs are, I can attest to using one (but I have no choice). 

Just wanted to see if there was anything up about it and if not, what can I do to help fix this? Not an experienced mac user either.

**Comment by callaa** [comment]
Hi! Thanks for reporting! You're the first one to notify me of this problem.

The DMG opens on my macbook, but I noticed I had built it using an older version of Qt.
Between versions 2.0.5 and 2.0.6, I updated my macbook to High Sierra and the Qt version from 5.7 to 5.10. Those are the first things that I can think of that might have any effect.

I rebuilt the package with the latest version and uploaded it here: https://drawpile.net/files/osx/Drawpile%202.0.7.1.dmg

Does the new version work better?

If it doesn't can you check if the file has been corrupted during download by running `shasum` on it? The expected value is:

    5c7f220cab5d71a6b3245304c8d904c7f175d3a3  Drawpile 2.0.7.1.dmg

**Comment by orbasama** [comment]
I understand the problem now. 

You're using High Sierra, I'm currently on El Capitan 10.11.6. For the other mac users I've spoken to, the file also doesn't work for them and they also use El Capitan. 
I can't upgrade to High Sierra (the others can) so it may not be necessary to do anything to the file just for one or two people to be able to use it.

As for running shasum on it, I don't know how to do that but I doubt that the file itself is corrupted (perhaps you can show me?).  Aye man, I'm just yabadabadoing my best on this dino craputer.

**Comment by callaa** [comment]
I believe I figured it out. High Sierra changed the file system format to APFS, which older OSX versions do not support. By default, disk images will be created in the new format. I found [this Qt bug report](https://bugreports.qt.io/browse/QTBUG-65844) that explains the problem.

Here's a new package in the older disk format: https://drawpile.net/files/osx/Drawpile-2.0.7.2.dmg

**Comment by orbasama** [comment]
It works! 

I'm sorry to have made you go through the trouble. I am stuck with a mac for the time being while I save money to build a new pc. The mac I have does not belong to me and I just have to make due until then. Thank you so much for everything, I will be sure to check the problem first before I open up a new thread, haha. I will keep you updated if I experience any new problems.

**Comment by callaa** [comment]
Great! Thanks again for reporting. There are still lots of people running older OSX versions, so it's important for me to know when compatibility breaks.
