### ISSUE TITLE
"Size limit" in "Flood fill" shows boxes instead of digits

### ISSUE THREAD

**Issue by yurivict** [drawpile/Drawpile#554]
![image](https://user-images.githubusercontent.com/271906/35479567-73666466-03af-11e8-9b1a-f33c3a4f1546.png)

Version 2.0.6 on FreeBSD 11.1

**Comment by callaa** [comment]
Does any other input field or text label have the same problem?

**Comment by yurivict** [comment]
Only this one.

**Comment by callaa** [comment]
Strange, there shouldn't be anything special about that particular spinbox, except for that suffix. But even then it's odd that the X character renders, but the regular digits do not. Missing font glyphs, perhaps? Can you try replacing the cross character with a regular X to see if it has any effect? (The file is `src/desktop/ui/fillsettings.ui`, line 139)

**Comment by notfood** [comment]
Stale, closing. Feel free to re-open if you're still experiencing the issue.
