### ISSUE TITLE
Getting a dot on the end of a brush stroke

### ISSUE THREAD

**Issue by Miumix** [drawpile/Drawpile#556]
After trying a few times finally I found out how to get rid of glitchy lines from Issue #346 by enabling "bug workarounds" option. But unfortunately this brings a new issue with it:

![dottedlines](https://user-images.githubusercontent.com/13894094/35486196-ec7989be-0440-11e8-9b53-9f1ab13d39f9.png)

For some reason I'm getting a dot at the end of every brush stroke. Actually it's not a big deal when I draw on big canvas but It's a little annoying when I write or try to doodle on smaller spaces since the writting/doodle looks awful. If there's a way to fix it let me know, please 8 v 8

Thanks for a prompt reply~

**Comment by callaa** [comment]
This might be tablet driver related, or it could be a bug in the smoother. Can you try drawing a stroke in the tablet tester (help menu) and paste the results here?

**Comment by Miumix** [comment]
Sure. Here you go~
That doesn't look good haha

![dottedlines_tablettester](https://user-images.githubusercontent.com/13894094/35486613-eb1493c4-0446-11e8-9bae-0af0fb9e3a28.png)

**Comment by callaa** [comment]
The pressure values look good. If you set the smoothing value (input dock) to zero, does the glitch still happen?

**Comment by Miumix** [comment]
Yup. and it gets worse <x'DD

![dottedlines_smooth0](https://user-images.githubusercontent.com/13894094/35489250-a8be4e38-046a-11e8-90ec-670c57c40f0f.png)

**Comment by callaa** [comment]
Okay, so it's not the smoother causing it. Looks like it doesn't happen on every stroke, though. Can you replicate the problem (rising P% at the end) in the tablet tester?

**Comment by Miumix** [comment]
like this?
![tryingtablettester](https://user-images.githubusercontent.com/13894094/35544837-c38932e0-0542-11e8-8301-3ef1b9836939.png)

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
