### ISSUE TITLE
drawpile won't draw??

### ISSUE THREAD

**Issue by illicitrez** [drawpile/Drawpile#565]
honestly i have no idea whats going on. i downloaded draw pile to draw with some friends and it worked fine for like. a moment. and then i went to make a layer and actually start drawing and it. won't work. none of the brushes or shapes or anything work, on my tablet or with my mouse. i've restarted it and tried to draw on my own private drawpile, none of it works. i'm not technologically adept please send help. also idk if u need specs or anything but uhhhh. i guess tell me and i can upload them.

**Comment by callaa** [comment]
What happens whey you draw? Does the brush just not make any strokes? Do any of the other tools work? (E.g. can you select a region and then fill it with Edit->Fill region?)

Do you have the tablet bug workaround mode enabled (edit->preferences dialog)? It can fix some tablet related bugs, but I recently discovered a bug where it can lock the pen pressure to zero even when using a mouse.

**Comment by pachuco** [comment]
What are your windows version and drawpile version?

**Comment by OfficerAbbacchio** [comment]
Mine has been doing the exact same even tried both versions if it and it just doesn't work. I got it to work on only one canvas yesterday but trying to draw on a new canvas nothing would work. I pasted in a copied drawing I did to see if it'd change anything and all it would do would just erase it even though I'm on pen?? I just want some solution to this as it's my favorite program for drawing and it's annoying I cant do anything.

**Comment by callaa** [comment]
Which brush blending mode do you have active? (The dropdown box in the brush properties dock.) Does it say something other than "Normal"? From your description, it sounds like you might have eraser mode activated.

**Comment by Wade821** [comment]
The blending mode can definitely cause issues. Also may want to check if the eraser is checked on the brush itself. I've included a picture to help illustrate the brush's blending mode. 

![image](https://user-images.githubusercontent.com/18544575/62004802-8b6e4a00-b0de-11e9-8e7a-4f410ad675ef.png)

**Comment by notfood** [comment]
Stale, closing as there has been no answers.
