### ISSUE TITLE
'Scroll with finger' applies to Stylus

### ISSUE THREAD

**Issue by BaronVonJimmy** [drawpile/Drawpile#567]
Drawpile 2.0.9. Surface Pro 2, Windows 10 (2017 Fall Update).

On initial install, found that the Stylus wouldn't draw, and would instead move the canvas around. Disabling 'Scroll with finger' in preferences restored expected behaviour.

**Comment by callaa** [comment]
Yes, this is a known problem that affects all programs that both use Wintab and support touch. The solution is to use Windows Ink mode.

**Comment by BaronVonJimmy** [comment]
This did occur in Windows Ink mode; however turning off 'Enable Bug Workarounds' fixed this.

**Comment by callaa** [comment]
That's a good point. I added this tip to the FAQ page. The reason bug workarounds mode does this is that in this mode, the actual tablet events are ignored. When the tablet event is ignored, Windows generates a touch event. For some reason, in Wintab mode Windows seems to always generate a touch event, even when the tablet event was accepted.
