### ISSUE TITLE
Drawpile won't open  High Sierra

### ISSUE THREAD

**Issue by Feloise** [drawpile/Drawpile#570]
Couldn't open in El Capitan so updated to High Sierra - still no success.
Tried running in Terminal:
/Applications/Drawpile.app/Contents/MacOS/Drawpile
dyld: Library not loaded: @rpath/QtMultimedia.framework/Versions/5/QtMultimedia
  Referenced from: /Applications/Drawpile.app/Contents/MacOS/Drawpile
  Reason: image not found
Abort trap: 6

**Comment by callaa** [comment]
Probably the same problem as in issue #569. The previous version works, so I recommend using it instead until I can fix the new package.

**Comment by Feloise** [comment]
Thanks, 2.0.8 is working

**Comment by callaa** [comment]
I just uploaded version 2.0.10. Can you try if it works now?

**Comment by notfood** [comment]
Stale, closing.
