### ISSUE TITLE
Can only draw on background

### ISSUE THREAD

**Issue by ShippingLord** [drawpile/Drawpile#573]
Hey, so I recently started having this problem. By recently, I mean last night. Just as the title says, I can only draw on the background. Last night when it happened, I just thought,"must be a simple bug or something" I quit drawpile and turned off my computer for the night. I open drawpile just now and the same thing is still happening. The weirdest part is is that I was in the middle of drawing something on the program and then all of a sudden I just wasn't able to draw. Has anyone else been experiencing this issue?? And I checked, the opacity on the foreground layer isn't all the way down. Even if I make a new layer, the same thing still happens.

**Comment by callaa** [comment]
Have you selected a brush blending mode other than "normal"? Most other blending modes will only draw on non-transparent pixels.

**Comment by ShippingLord** [comment]
I just tried all of the blending modes and still nothing works.

**Comment by ShippingLord** [comment]
I've only been using normal

**Comment by callaa** [comment]
Can you make a short session recording (Record from File menu) that demonstrates the problem?

**Comment by ShippingLord** [comment]
I can't send a .dprec file

**Comment by callaa** [comment]
Okay, then can you make a recording in dptxt format and copy&paste it here? Just one stroke should be enough to tell what the problem is and makes the file short enough to fit in a comment.

**Comment by momorsa** [comment]
I'm having the same problem too, i'm going to send the .dptxt within a zip file if it's alright
[ok.dptxt.zip](https://github.com/drawpile/Drawpile/files/1945383/ok.dptxt.zip)

**Comment by callaa** [comment]
@momorsa Thank you for the sample file. At least in your case, the problem is that you have selected the "Recolor" blending mode. This mode works otherwise like Normal mode, but it leaves pixel transparency untouched. (All modes other than Normal and Behind only affect non-transparent pixels.)

**Comment by momorsa** [comment]
hahahaha oh my god can't believe it was this kinda mistake, thank you so much anyway!!

**Comment by notfood** [comment]
Stale, closing. Very likely a blending mode issue for the original submitter.
