### ISSUE TITLE
Can't connect to drawpile whatsoever

### ISSUE THREAD

**Issue by Sotcho** [drawpile/Drawpile#574]
So a few days before the new 2.0.8 update, I could connect to the drawpile servers just fine. Servers and website. After the update, I can't connect whatsoever. I can't even go onto the website or look at any available servers to join. I' totally disconnected from the servers. Any help please? Thank you!

**Comment by callaa** [comment]
> I can't even go onto the website

Do you mean with a browser? If that's the case, then the problem must be external to the Drawpile application itself. What kind of error message are you seeing?

**Comment by Sotcho** [comment]
With the browser and the application. I would try to go on the website through my phone on my wifi and then nothing. But if I switch the Wifi off and then try again it works just fine. It's just a long wait and then it tells me It can't connect.

**Comment by callaa** [comment]
If it works via the phone network but not WiFi, it sounds like a network problem. Can you try if the "US West" link works here: https://www.linode.com/speedtest (that's the datacenter the server is hosted at)

**Comment by Sotcho** [comment]
No it doesn't work. That's what I thought at first

**Comment by callaa** [comment]
If the speedtest link does not work, the problem must be somewhere between Linode and your ISP, so there is nothing I can do.
