### ISSUE TITLE
Prevent Logging in Config file

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#576]
Logging is done to my my config.db file, making it ridiculously big (130.11 MB) even after cleaning it up. Is there a way to stop this? I much rather having the event log go into a file much more manageable, as strings of text store 10x better in a text file than a database table, and its far easy to visually search and purge.

**Comment by callaa** [comment]
The log messages are also written to stderr, so you can get them also from journald's log.

I've been meaning to add a setting for automatically deleting old log entries, but it has always slipped my mind. It can also be done right now with a cronjob that runs this SQL statement with sqlite3: `DELETE FROM serverlog WHERE timestamp < DATE('now', '-30 days')` (for example)

If I add that as a built-in feature, then I don't think it's necessary to add an option to disable database logging entirely. (That would disable some other features too, such as log viewing via the admin API and the GUI.)

**Comment by callaa** [comment]
I've now implemented a feature to automatically purge the database log. (Will be included in the upcoming 2.0.10 release.) The log retaining period can be adjusted via the server GUI.
