### ISSUE TITLE
Failed Auto-Reset Causes Duplicate Layers

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#577]
https://i.gyazo.com/1238aec6fe7c68a9f75b8be5b4198975.png

This has been happening after an auto-reset happens. Not sure how drawpile chooses who is the one to say "x is resetting" in auto reset, but if they have poor net, it causes the reset to sit and hang despite waiting a minute. Un-#ing them causes the reset to cancel, but then proceeds to duplicate all layers as what you see in the screenshot. Original layers are the top ones, while the ones above background are all duplicates. Trying to move these layers to perform a merge causes whoever tries to crash.

User is re-#, and drawpile will again choose them to reset next time around. I do believe kicking results in the same, not completely certain. Saving canvas and rehosting makes those layers not crash when moved, allowing us to merge and continue on with our day.

**Comment by callaa** [comment]
Hmm, when a reset is cancelled by de-opping a user, the user may still have buffered the reset image for upload. With the reset now cancelled on the server side, the reset image is appended to the current  session, which results in the duplicate layers. This is a quite tricky problem. The simplest fix (or band-aid solution) is to automatically kick the user in this situation. A nicer solution would be to send a "stop now!" message to the resetter and ignore all input until the client has acknowledged it. (I can probably do this in version 2.1)

Merge causing a crash is a clear-cut bug. What probably happens is that when the client executes the "new layer" command, it doesn't check if a layer with the same ID already exists. The rest of the program assumes layer IDs are unique, so all sorts of weirdness will happen when they're not. Luckily, this should be easy to fix.

The way the program picks the user to perform the autoreset is fairly simple: the operator with the lowest ID number is the one who resets. The server tries to give returning users their old IDs back, which explains why the same user is chosen to do the reset even after logging out and back in.

In version 2.1, I plan to make the resetting logic a bit smarter. The server will (once again) be responsible for selecting which user should do the autoreset, and it will do so  by pinging all operators and picking the one with the lowest latency. There are some other changes I've  planned too that will make resets a bit smoother. (Including a soft reset mode, which will work pretty much like the snapshotting did in 1.0.)

**Comment by callaa** [comment]
I've now implemented the layer duplicate fix and the kick-resetter-on-deop workaround.
