### ISSUE TITLE
Newer versions do not work on OS X 10.9.5

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#580]
Have a user who can't even do the version 2.0.9 workaround with version 2.0.8. They still crash.

https://i.gyazo.com/152b3a70207dc5a5caaa0e5d73d73843.png

**Comment by callaa** [comment]
Looks like the latest Qt version only promises support down to OSX version 10.11. (The screenshot shows version 10.9) I'll try downgrading the Qt version used for the OSX build in the next release.

**Comment by callaa** [comment]
Version 2.0.10 is now out and is built with an older Qt version that should support OSX 10.8 and newer.
