### ISSUE TITLE
Changes in the HSV/RGB slider

### ISSUE THREAD

**Issue by NewSpice** [drawpile/Drawpile#581]
Hello! I'm really not a fan of the changes made to the color HSV/RGB color sliders in the newest release.

In all previous versions, clicking on either side of a bar would move the slider/cursor in that direction by increments of 10. 
In 2.0.9, the slider is moved directly to the location of the click instead of moving there gradually, thus making it far harder to adjust colors by small changes to the individual hues or values. 
I feel the functionality of the sliders are greatly decreased, and I sincerely hope the change is revoked in the future. 

Thanks!

**Comment by notfood** [comment]
I'm the opposite. I like the change, it was a minor annoyance to not work as you would expect when you clicked. Perhaps holding a function key to use alternate behavior would work for both?

**Comment by tincancrab** [comment]
I have to agree I enjoy the jump as well. Adding a function key could work, but at least in newest version there are up and down arrows next to the value input textbox, which gives you the gradual up and down.

**Comment by notfood** [comment]
Holding *ctrl* or *shift* + mouse wheel moves the slider in 10 increments now.
