### ISSUE TITLE
Hello~ I am interested in the project

### ISSUE THREAD

**Issue by alll4u** [drawpile/Drawpile#582]
I am a college student，and I am very interested in this project。But as a beginner，I don's know too much about how to build the develop environment。Can I use Qt Creator only on Windows/Mac OS to develop the client？

**Comment by callaa** [comment]
If you're using Windows or Mac, Qt Creator is probably the easiest way to get started. Of course, you can use Qt Creator on Linux too (I do,) but it's also easy to use any other IDE or text editor and build from the command line.

You can find instructions on how to set up the dev environment here: https://github.com/drawpile/Drawpile/wiki/Building-from-sources

The only required library, other than Qt itself, is KArchive. The other libraries are optional and only enable extra features, so you don't need to install them unless you plan on working on those features.

Is there any particular feature you're interested in developing? If you have questions, feel free to ask.
