### ISSUE TITLE
Feature: Dark/Night Mode

### ISSUE THREAD

**Issue by HaloRings** [drawpile/Drawpile#583]
It would be nice to have a enable feature where you can change the interface to a dark mode to the program. 
![drakmode](https://user-images.githubusercontent.com/35905328/37496788-f18c5bc0-288a-11e8-8410-4923faae1bfc.png)

**Comment by callaa** [comment]
Adding this to the TODO list.

Out of curiosity, is that an actual screenshot or a mockup? Drawpile should work nicely with Plasma's dark desktop theme and I know Windows used to have color themes too.

**Comment by notfood** [comment]
Works fine under Plasma...

![image](https://user-images.githubusercontent.com/5370107/37545463-ec21864a-2936-11e8-8f12-7991007eec5b.png)

**Comment by HaloRings** [comment]
It's a mockup. But I'm love the Plasma even better.

**Comment by Waloumi** [comment]
i found that if you use a dark windows 10 theme like penumbra you get dark colors in drawpile too.

**Comment by erik90mx** [comment]
> Works fine under Plasma...
> 
> ![image](https://user-images.githubusercontent.com/5370107/37545463-ec21864a-2936-11e8-8f12-7991007eec5b.png)

It really gives another feeling to the program. I'm very interested in this (windows 8.1 user here) because after you use Drawpile for more than 4 hours, your sight get tired of the bright colors, and this theme helps.

Regards
