### ISSUE TITLE
Difficulty connecting to boards with many people drawing at once

### ISSUE THREAD

**Issue by ooaa** [drawpile/Drawpile#584]
Hello! I've been having problems with getting connected to boards with more than 15 people drawing at once. I have it so that I disconnect if the connection blips out for 2 minutes. Usually what happens is that i'm unable to get through even 10% of the load before it disconnects. If drawpile can be optimized for people with worse internet, that would be fantastic!

**Comment by callaa** [comment]
This is a bit of an open-ended issue, but I do have some performance optimizations planned for version 2.1 that might help a little.
