### ISSUE TITLE
Extra Pen Buttons

### ISSUE THREAD

**Issue by ArconosRuva** [drawpile/Drawpile#586]
Could you create a way to disable the extra pen buttons? Whenever I accidentally press them my pen will either remove all pressure/max the pressure or undo/erase.

**Comment by ArconosRuva** [comment]
Same topic but, wouldn't mind a way to specific where drawpiles saves too, so I can just dumpload stuff to the desktop.

**Comment by callaa** [comment]
I'll check if there is something I can do about the stylus buttons. If the stylus button is triggering an undo, then it sounds like you've bound a shortcut key to the button, in which case I don't think it can be filtered away by the program.

Can you explain what you mean by being specific about where drawpile saves to? I'm not sure I understand.

**Comment by ArconosRuva** [comment]
http://puu.sh/zLka1/212ecff4cb.png

For the save directory, I remember around DP 1.6, you could just save anywhere, and it would remember your last save location. Now, it always defaults to the drawpile install folder, and won't change no matter what I do.

**Comment by callaa** [comment]
Ah, I have a vague recollection of removing some code that was related to remembering the last save location. On Linux, (or at least on Plasma desktop) the platform's save dialog remembers the last location internally and I must have thought it works like that everywhere.

**Comment by ArconosRuva** [comment]
On windows atleast, it doesn't. Or, atleast not on 7, 8.1, or 10.

**Comment by displayerror** [comment]
> I'll check if there is something I can do about the stylus buttons.

Hello, is there any way to do this yet? I'd prefer to assign my stylus buttons shortcuts via AutoHotkey (a macro scripting language for Windows) - but Drawpile always seems to intercept the stylus buttons which causes unintentional canvas dragging/zooming/drawing :(

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been fixed and will be coming in Drawpile 2.2. You can assign mouse/pen buttons freely and right-clicking will no longer cause full-pressure drawing.
