### ISSUE TITLE
Installation of 2.0.10 on windows 10 fails

### ISSUE THREAD

**Issue by jhb** [drawpile/Drawpile#587]
First: thanks a lot for drawpile. I am amazed that such a gem exists!

I am trying to install drawpile 2.0.10 in a windows 10 machine, and it fails. The error message is (in German):

ShellExecuteEx schlug fehl; Code 67. Der Netzwerkname wurde nicht gefunden.

This roughly translates  to:

ShellExecuteEx failed; Code 67. The network name was not found.

I have tried both 32bit and 64bit versions. Installation on windows 7 works fine.

P.S: a cool workaround would be a  zip archive instead/additional to the installer :-)

Thanks a lot!

**Comment by callaa** [comment]
Based on googling that error code, it seems to be related to network shares or possibly incorrect domain configuration.

In any case, I packaged version 2.0.10 up as a ZIP file: https://drawpile.net/files/win/drawpile-2.0.10.zip

**Comment by jhb** [comment]
I googled as well, and had collegue tried to install it in the same domain setup, but on windows 7, and it worked. But anyhow, I am really grateful for the zip file, and amazed by the speed of your reply. Thanks a lot for your help, looking forward to the file tonight!

**Comment by jhb** [comment]
Works like a charm. Thanks again!
