### ISSUE TITLE
Call for feedback: would you miss these brush/layer blending modes?

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#588]
I'm currently working on improving the brush and layer composition operations. Drawpile currently supports many blending modes, but not all of them are used often. Specifically, these ones:

 * Multiply
 * Divide
 * Burn
 * Dodge
 * Darken
 * Lighten
 * Subtract
 * Add

It would make my life a bit easier if I could just drop the unused (?) ones from version 2.1. So, are you using any of these blending modes and would you miss them if they were not included in version 2.1?

**Comment by Lawyer-M** [comment]
I personally dont use those modes just about... ever, so I won't miss them too much.
Regardless, I'd still feel bad to take away ANY tool options, but if it turns out no one else really uses them either, it seems reasonable enough to me.

**Comment by Lawyer-M** [comment]
OH I didn't notice this was for layers too. That might cause some problems for people that don't use public sessions that often. I know a few people, including myself, that like to experiment with multiply/burn/lighten layers while using the client offline.

**Comment by callaa** [comment]
Ok, since people are using these features, I will keep them.
