### ISSUE TITLE
Pen pressure not working - Huion

### ISSUE THREAD

**Issue by egeskjold** [drawpile/Drawpile#589]
I'm using a Huion GT-191 KAMVAS and even though I've tweaked and checked every box I could, there is no pressure sensitivity at all. I don't think it has anything to do with my tablet since it's working fine in other programs.

**Comment by callaa** [comment]
Have you tried restarting the application after unchecking the Windows Ink checkbox? Check also the log file (under Help menu.) Right after a "Drawpile started" line, there should be something about activating tablet support.

**Comment by egeskjold** [comment]
The uncheck and restard seems to have worked! Thank you!
