### ISSUE TITLE
Crosshair too small

### ISSUE THREAD

**Issue by henriquebg88** [drawpile/Drawpile#596]
i'd love to have the option to change to something i can see... really.. it's really annoying for me having to find where is my pen on the screen..

**Comment by callaa** [comment]
This is the option in the preferences dialog I mean:

![image](https://user-images.githubusercontent.com/464576/38317630-2acc3b20-3836-11e8-9617-9c73b62f4770.png)

**Comment by henriquebg88** [comment]
oh.. sorry about that.. thanks

2018-04-04 12:31 GMT-03:00 Calle Laakkonen <notifications@github.com>:

**Comment by f2d** [comment]
Swapping the Logging option (to bottom) with Brush cursor + Tools (to top, under the Language) on that screen could probably help a bit. But that's really a minor thing.
