### ISSUE TITLE
Drawpile Server tabbing?

### ISSUE THREAD

**Issue by kalo-J** [drawpile/Drawpile#597]
I'm tyring to load into two boards one on SythenticDreams and one thats on Drawpile. I get kicked out of the drawpile one and have some glitches (like can't undo or can't zoom in with clicking the button though im sure thats what ur supposed to do i just use my mousepad with two fingers open n close) on syntheticdreams and then the Drawpile one if I load back into DP server (itll kick me out soon after). I have a mac and my internet has handled it before, so idk if it's DP itself or my internet.

**Comment by tincancrab** [comment]
Would like to add user stated restarting fixes this problem for a day or so.

**Comment by callaa** [comment]
I'm not sure I follow. After a while the server kicks you out? By this do you mean that the application crashes or that it just disconnects or that you get a notification that you have been kicked?

By can't undo or zoom in, do you mean just these functions are not working or is the whole application unresponsive?

Finally, what do you mean by "tabbing"?

**Comment by kalo-J** [comment]
tabbing is the sense of having both open at the same time and going back and forth, im sorry for the confusion im not the best as explaining things. And yes the zoom and undo commands are all unresponsive when it happens besides the click button. And the server yea just says 'disconnected' out of random no lag warning or anything. My computer has handled it before, but it fixes when I restart my computer as a whole.

**Comment by notfood** [comment]
It sounds like you are running out of resources and the Windows scheduller puts the "idle" windows to sleep to give you some resources to use.

Something similar happened with an user with very low ram.

**Comment by tincancrab** [comment]
They're actually a Mac user, but the low RAM would make sense. I asked their RAM info, though, and they said its 16GB. You'll be hard pressed to max out 16GB if youre not running a million applications at once, unless there's a memory leak.

**Comment by notfood** [comment]
Stale, closing. Feel free to re-open if it's still an issue.
