### ISSUE TITLE
low opacity messes up colors

### ISSUE THREAD

**Issue by yorgje** [drawpile/Drawpile#599]
![bug](https://user-images.githubusercontent.com/24980717/38457209-60784b7a-3a5b-11e8-8977-ad8a18ba33f0.png)

When turning down opacity, it seems like colors get desaturated. See the top row, where the purple color turns to grey when changing the opacity to 1%, and to white when further turning the hardness down to 1%. It seems less bad for colors in the top left quadrant of the color picker (see the second row), although my color knowledge isn't strong enough to tell if that's actually correct (it seems like it's shifting towards pink more than it should perhaps).

**Comment by callaa** [comment]
Probably related to this: https://drawpile-dev-diary.tumblr.com/post/172280623402/premultiplied-alpha

If you can make a recording of that same image, I can try playing it back on the dev version to see if the changes have fixed the problem.

**Comment by yorgje** [comment]
https://www.dropbox.com/s/mjlvxf7d4ncf1hc/bug.dprecz?dl=0
I think I swapped the rows, but it's the same idea. Do you have an eta on the 2.1 release?

**Comment by yorgje** [comment]
Thanks for the update!

**Comment by notfood** [comment]
2.1 is out!
