### ISSUE TITLE
Pressure sensitivity doesn't work with windows ink off

### ISSUE THREAD

**Issue by redpharoah** [drawpile/Drawpile#600]
As the title says, as long as I have windows ink disabled, Drawpile does not register my pen pressure, the tablet tester seems to consider it a "mouse" rather than a stylus.

Of course enabling Windows ink fixes the pen pressure, but it causes more trouble than it's worth, WIndows ink causes my cursor to lag outside of the main drawing space (when I'm using the pen to, say, pick a new colour) due to the accursed radial menu that I have tried to disable to no avail, as well a case of a disappearing cursor on other programs (I have the "show cursor" option enabled, so I'm guessing Ink is just broken, which isn't surprising)

My point being, up until version 2.0.10 I could use my pressure without windows ink, and I would very much rather that stay as an option.
![image](https://user-images.githubusercontent.com/38376624/38767902-e93e1a68-3fea-11e8-8761-efbc099e733c.png)

**Comment by callaa** [comment]
When Windows Ink is disabled (and the program is restarted,) the Wintab event handler is used instead. There were no changes between 2.0.9 and 2.0.10 that I can think of that would have broken wintab support. Can you check the log file? (Via the help menu.) Right after the line that says "Drawpile started", there should be something about the tablet.

**Comment by redpharoah** [comment]
![image](https://user-images.githubusercontent.com/38376624/38769642-911c0a68-4006-11e8-8d3d-9fedc0ad243c.png)
Here you go, from what I've seen it recognizes the tablet as a pen device, but for some reason it's using Windows 8 pointer input, even though I'm using Windows 10, I'm not tech savvy enough to know if that's a problem or not

**Comment by callaa** [comment]
Those messages still indicate it's activating the Windows Ink event handler. (It's just called Windows 8 pointer input, but it means the same thing.)

Can you uncheck the Ink option, then restart the application. You may need to restart it twice to see the latest messages.

**Comment by redpharoah** [comment]
I've restarted it 4 times now, still shows the same messages, and windows ink is definitely off
