### ISSUE TITLE
feature request: color dynamics

### ISSUE THREAD

**Issue by yorgje** [drawpile/Drawpile#603]
Photoshop has a feature called color dynamics where each on each stroke of a brush, the hue, saturation or value is randomly selected within some % range of the actual color you've selected. It would be cool to have this in drawpile!

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

MyPaint brushes have been implemented, they support this kind of thing. They will be coming in Drawpile 2.2.
