### ISSUE TITLE
Opacity Artifacts

### ISSUE THREAD

**Issue by Waloumi** [drawpile/Drawpile#608]
when drawing with low opacity brushes artifacts start to appear after many strokes

![drawpilebug](https://user-images.githubusercontent.com/36631015/39428552-1300cbc6-4c88-11e8-9260-d488150a3dc0.PNG)

**Comment by tincancrab** [comment]
This is a known issue within the framework that callaa has been looking into having improved/fixed for version 2.1

**Comment by notfood** [comment]
:tada: 2.1 is out!
