### ISSUE TITLE
[Feature Request] Custom macOS Installer

### ISSUE THREAD

**Issue by HandsomePixel** [drawpile/Drawpile#610]
Basically title, I think it would be nice if on the macOS side of Drawpile that when we download the latest release, it gets packaged in a DMG or PKG file to make the installation look more professional.
I have already made some examples of what it could be like.
DMG Version: https://github.com/HandsomePixel/Drawpile-DMG-Installer
PKG Version: https://github.com/HandsomePixel/Drawpile-PKG-Installer

**Comment by callaa** [comment]
This looks great, thank you! I'll see if I can update my DMG build script to include this in the next version.
