### ISSUE TITLE
Drawpile cannot find ffmpeg.exe

### ISSUE THREAD

**Issue by SyntaxError73** [drawpile/Drawpile#613]
I have set the path to the ffmpeg executable in my preferences and drawpile still cannot find it when exporting a video.

I am using windows 10, and I have tried both 64 and 32 bit applications. I am running Drawpile 2.0.10.

There's not really much else to it.

**Comment by callaa** [comment]
Can you take a screenshot of the path input box?

I have to admit that the ffmpeg exporter feature is a bit buggy and neglected. You will get better results if you export as an image series and convert into video format using either ffmpeg manually or with a video editing software.

I'd like to replace the ffmpeg exporter with a built-in webm encoder, but I haven't yet found good documentation on how to use the relevant libraries.

**Comment by notfood** [comment]
This issue is stale, can you check if it's still happening? Re-open if you're still experiencing the issue.
