### ISSUE TITLE
[feature request] timeline animation

### ISSUE THREAD

**Issue by Fredlyb** [drawpile/Drawpile#618]
Timeline animation, even if the number of layers gets limited when activated. This would be a powerful tool for story-boarding and making rough animations as a team.

necessary features of a timeline ;
-selectable frames (the definition of a timeline)
-insert frame between frames
-copy frames, creating new identical frames
-move frames about the timeline
-delete frames from the timeline

That'd be the coolest, methinks.

**Comment by blurymind** [comment]
Related to https://github.com/drawpile/Drawpile/issues/275

:)

**Comment by Fredlyb** [comment]
oh well, that's much better articulated!
Yes, that!
