### ISSUE TITLE
hosting working literally yesterday but not working anymore

### ISSUE THREAD

**Issue by smoochan** [drawpile/Drawpile#619]
my friend can host and i can join her just fine, but today i can't host a session at all. i don't think any of my settings have changed and my firewall is allowing drawpile. we are also on the same version.

**Comment by notfood** [comment]
Can you host it on drawpile.net ?

Where it says server -> remote, set it to drawpile.net

**Comment by callaa** [comment]
Are you using the built-in server? What sort of error do you get? Does the connection just time out?

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
