### ISSUE TITLE
Time Warp Reset 

### ISSUE THREAD

**Issue by SpaceDustCM** [drawpile/Drawpile#622]
We had an issue earlier today where a reset happened and it seemed the board went back in time;

A user had just come into board and was automatically made an operator because they're a recognized member.

The board then had gone into reset mode, but chose the new member who was still loading in as the person to reset it.

So when the board finished resetting, it took a screenshot to use from earlier in the log instead of where it actually was.

**Comment by callaa** [comment]
I'm overhauling the reset system in version 2.1. Among other changes, I'll change the resetter selection algorithm so that this bug cannot happen anymore.
