### ISSUE TITLE
Persistent session termination by moderator is not logged to stdout.

### ISSUE THREAD

**Issue by f2d** [drawpile/Drawpile#626]
If a session flagged as persistent is terminated by mod, "Last user left" is written to log, but nothing after that.

"Closing (...) session" is written to log when closing a non-persistent session whatever way (mod termination or all users gone).

I used that line to trigger my archive processing.

As a workaround, now I'm catching "Last user left", then wait a couple of seconds and see if there are any *.archived files.

I'd suggest logging something in any case, and maybe something distinct for mod termination, e.g. "(Non-)persistent session was terminated by moderator".

**Comment by notfood** [comment]
It now appears as "Session terminated" as well as who users did so. Issue has been fixed, closing.
