### ISSUE TITLE
[MAC] HUION H610 Works, But...

### ISSUE THREAD

**Issue by Avocadoflavored** [drawpile/Drawpile#627]
So, the tablet works well, it seems supported. It picks up drawpile and it can draw and create strokes. However, when I do so, it lags heavily. I have pictures and screenshots of how it lags, and it seems to strike out randomly every so often while it does so. Does the HUION not work specifically with this program? Do I have to have a completely different tablet? Please help me with this. This HUION to add, is new.
![screen shot 2018-06-17 at 4 01 32 pm](https://user-images.githubusercontent.com/40342976/41511721-80eb4b7e-724a-11e8-8110-b4fc7761a3f4.png)

**Comment by tincancrab** [comment]
Have you tried it with other programs? This is the big identifier of your problems. Krita, Photoshop, other Mac compatible programs.

**Comment by Avocadoflavored** [comment]
I have, it works with Photoshop very well, almost perfect. It even works with the most minimal of drawing programs like skribbl.io and I might test it on Gimp, but, it's just drawpile sadly, I don't know exactly what to do for it.

**Comment by tincancrab** [comment]
Huion should work. It should work in Krita, which uses the same tablet framework. You could try testing it in that program. If it doesn't lag, it may be something in Drawpile itself.
You uninstalled all other drivers prior to the Huion ones, correct?
Did you use drawpile with a different tablet before and it worked?

**Comment by callaa** [comment]
Have you tried with and without the new Windows Ink mode? Try toggling the option in the settings dialog, then restarting the program.

**Comment by tincancrab** [comment]
I had a Huion Kamvas GT-191 on Linux Mint and it works perfect as far as I could tell. Used Digimend drivers. I'm under the assumption that Qt's standard tablet event handling. Possibly turn smoothing down? I would also try completely uninstalling and reinstalling the drivers.

Curious if it does the same thing in Krita, which I refer to a lot for tablet compatibility, considering they use the same tablet infrastructure (correct me if I'm wrong, Callaa).

**Comment by notfood** [comment]
Stale, closing. If you're still experiencing the issue, feel free to re-open it.
