### ISSUE TITLE
[Feature idea] Square brush

### ISSUE THREAD

**Issue by poopdoopmoop** [drawpile/Drawpile#632]
A square brush would be a very cool addition to Drawpile, maybe along with a toggle-able option of choosing whether or not to have the brush rotate and point in different directions as you draw. Me and my friends all love using square brushes and they're pretty popular for painting.

Maybe if brushes that rotate/are unusual shapes cause lag, people with # could have the option to keep everyone restricted to the standard circle brush.

**Comment by callaa** [comment]
I've actually been contemplating adding this feature! Since I haven't released version 2.1 yet, I can still add it for 2.1.0. (Or version 2.2, in which I plan to add more brush improvements anyway.)
