### ISSUE TITLE
Could not connect / server timed out??

### ISSUE THREAD

**Issue by itsamedee** [drawpile/Drawpile#633]
I'm trying my best to get my server working but it's not responding and no one can join?? it never did this before.. even when I reset it and fix the setting from private to public its unresponsive... 

help???

**Comment by tincancrab** [comment]
Have you read up on this?

https://drawpile.net/help/hosting/

Sounds like you're using "Built-in" server instead of a remote server. To use a built-in server, you need to have port forwarding set up on your router.

My suggestion is to use a remote server like drawpile.net or syntheticdreams.net.
