### ISSUE TITLE
No pen pressure on Drawpile

### ISSUE THREAD

**Issue by A-wkee** [drawpile/Drawpile#634]
Pen pressure will not work. It always a full stroke, as if it doesn't recognize it when I'm pressing soft or hard. I've been having this problem for half a year now, and just downloaded the newest Drawpile update after a few months of not being on it, and I'm STILL having this problem. 

I've tried the following:

1.Reinstalling the Drawpile
2.restarting my tablet
3.download the latest Wacom drivers(I use a Wacom Intuos Pro tablet)
4.Checked and unchecked the Windows Ink option. (would show Windows 8 in log file anyways) 
5.And I've tried using later versions of Drawpile. 

Still the same results. The pen pressure sensitivity just will not work with me. Can anyone help with this?

**Comment by tincancrab** [comment]
You didnt mention checking the WinTab option. Did you try that as well?

**Comment by erulon** [comment]
Win 7 SP1
XP-Pen Star 06 tablet
Driver Ver: 1.4.2(Build:Jan 4 2018)
Drawpile 2.0.10 
Was trying every option with restarts. Pen pressure is not working. Pen pressure working only with tablet's relative mouse mode option (no absolute cursor placement, hard to use, adds other bugs).
Pressure is still working in drawpile 2.0.7.

**Comment by A-wkee** [comment]
@tincancrab Sorry for the late response. I tried it with and without the Wintab only option. Still doing the same thing.

**Comment by tincancrab** [comment]
[b]@erulon[/b] XP-Pen is notorious for focusing on working in Photoshop and everything else is open game. Wintab was introduced in 2.0.8 if I'm not mistaken. It could have been the implementation of an updated tablet framework that broke compatibility. Does XP-Pen only work with bug workaround option enabled in Drawpile?

[b]A-wkee[/b] Have you tried messing with input from the Input window? I am pretty sure I heard of this before, and messing input helped (try with previous options as well just to be sure). I will dig around for further solutions if that doesn't work for you. I'm not at my computer at the moment, I could be overlooking something in settings.

**Comment by erulon** [comment]
@tincancrab works in v2.0.7 with and without bug workaround option.

**Comment by callaa** [comment]
In version 2.0.9, I added Krita's tablet event handlers for Windows Ink and Wintab tablets. Unfortunately, while it seems that the new Wintab code works better for most users, for some users the old version worked better. I'm not quite sure why. I'm also not sure what would be the best way to fix it, since it's not possible to switch between the two versions at runtime and separate builds would be needed for both.

**Comment by Banderi** [comment]
Is there any link to versions like 2.0.8 or 2.0.7 anywhere to test if this is the issue I'm facing?

**Comment by notfood** [comment]
It's been a while, there has been a lot of changes to tablet handling, please test again. Feel free to re-open the issue if you're still experiencing it.
