### ISSUE TITLE
Error when trying to launch AppImage in Arch

### ISSUE THREAD

**Issue by teleportingtortoise** [drawpile/Drawpile#636]
There is an AUR package but it's not currently working and the maintainer doesn't have a fix atm, so tried the AppImage, but getting:

`This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.`

Have xcb packages installed and other programs that use it like Krita are working.

This is a great program and any help would be appreciated.

**Comment by callaa** [comment]
Confirmed. This has worked before (I use Arch myself too,) so something must have changed recently.

**Comment by notfood** [comment]
Related: https://github.com/AppImage/AppImageUpdate/issues/85

libfontconfig and friends neeed to be in the excludelist

**Comment by notfood** [comment]
Appimages have been phased out. You're alternatives are the [AUR package](https://aur.archlinux.org/pkgbase/drawpile/) which I maintain or [Flathub](https://flathub.org/apps/details/net.drawpile.drawpile)
