### ISSUE TITLE
Build Failure 2.0.10 with GCC8

### ISSUE THREAD

**Issue by plinnell** [drawpile/Drawpile#637]
When trying to compile drawpile on openSUSE Tumbleweed, it fails with 

  205s] /home/abuild/rpmbuild/BUILD/drawpile-2.0.10/build/src/desktop/drawpile_autogen/IMAN36LHMA/moc_userlistwidget.cpp:128:65: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]

Complete log is here: https://build.opensuse.org/package/live_build_log/home:mrdocs:branches:graphics/drawpile/openSUSE_Tumbleweed/x86_64

Let me know if you need further info on the build environment.

**Comment by callaa** [comment]
Hi, sorry I didn't respond sooner. I think this is the same problem that was fixed by commit bc06dce. Can you confirm if works with that patch applied?

**Comment by notfood** [comment]
Had to revert to 2.0.10, couldn't build it.

This fixes it.

**Comment by plinnell** [comment]
Indeed, this fixes the build. Thanks,
