### ISSUE TITLE
Saving Issue 2.0.10

### ISSUE THREAD

**Issue by JessicaVi** [drawpile/Drawpile#638]
Hello,

I've been enjoying Drawpile ever since 1.0! Not until patch 2.0.8 have I been having the issue that whenever I try to save. Either using "save as..." or just plain "save...", it says it has been saved, but the save file is no where to be found. When I look in "open recent" it says the save exists, but when I click on it, I get the error;
"file not found". I haven't found this urgent as I mostly draw on my friend's server, but since late I've been wanting to save screenshots.

Thank you in advance for your help!

**Comment by callaa** [comment]
In version 2.0.6 I changed the way files are saved so the saving happens in the background without blocking the UI. If the image is very large, saving can take up to 30 seconds in some cases. I can't think of any change in version 2.0.8 that would explain this, so perhaps the problem started at 2.0.6?

Does saving fail every time or just on certain images or formats?

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
