### ISSUE TITLE
Pen presser not working correctly and can't join servers

### ISSUE THREAD

**Issue by Shingapow** [drawpile/Drawpile#640]
When i try and join a server it never connects. And the pen presser is backwards. When i press not hard it acts like I was pressing with full force. And when I press hard it acts like Im pressing not hard.

**Comment by Waloumi** [comment]
Hi, try the windows ink builds?

https://drawpile.net/files/win/

```
drawpile-2.0.8-ink.zip                             13-Feb-2018 17:29            22641569
drawpile-2.0.8-ink2.zip                            15-Feb-2018 15:49            22641735
drawpile-2.0.8-ink3.zip                            17-Feb-2018 18:05            22661238
drawpile-2.0.8-ink4.zip                            18-Feb-2018 12:24            22661204
```

i had trouble once with pressure and it was because there was conflict with wacom drivers and windows ink. what is your tablet?

**Comment by notfood** [comment]
Invert the pressure curve, most likely your configuration.

About being unable to connect, perhaps the windows firewall is preventing it? Does it show any server in the find menu?

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
