### ISSUE TITLE
[Request] Overlay and Linear Light Layer mode

### ISSUE THREAD

**Issue by Waloumi** [drawpile/Drawpile#641]
Those are layer modes i use a lot in SAI or photoshop compared to subtract or divide.. would be an awesome addition. 

I use them to light and darken at the same time because Burn and Dodge only do one at a time.

![witchshade](https://user-images.githubusercontent.com/36631015/43326148-6153768c-91b8-11e8-864e-7156d403d8a5.jpg)

Thanks calle

**Comment by blurymind** [comment]
Your example also uses a gradient tool :p

**Comment by Waloumi** [comment]
yeah its just to demonstrate how a drawing i made in drawpile reacts to different shades and brightness in addition to the layer modes :D

**Comment by callaa** [comment]
I'll consider adding this feature in version 2.1 or  2.2.

**Comment by Waloumi** [comment]
Thanks Calle, i'm looking forward to it.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming with Drawpile 2.2.

**Comment by Waloumi** [comment]
yessss
