### ISSUE TITLE
[Bug report] Pressure sensitivity not working

### ISSUE THREAD

**Issue by hsm64** [drawpile/Drawpile#642]
im using an XP-Pen Deco 01 and i'm not getting any pressure sensitivity and my tablet pen is being detected as a mouse

[https://i.imgur.com/rmUj2xM.png](url)

**Comment by tincancrab** [comment]
Looking this up, can you try this?

Open the driver window for the XP-PEN tablet and enable "Windows Ink". This option is located in the lower left corner of the PenTablet window.

Also, have you tried the options under General preferences? Has WinTab and Windows Ink support. You may need to enable one of those.

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
