### ISSUE TITLE
[Bug report] Pressure sensitivity trouble

### ISSUE THREAD

**Issue by Slendermanyshka** [drawpile/Drawpile#643]
Pressure is not working correctly , 
![123123](https://user-images.githubusercontent.com/42029005/43573910-84aea128-964b-11e8-8176-a9d045ba2be8.png)
you may see that there is an area that pressure wont work 
but it will work fine if you start drawing on proper working area and go to not working area 
but it will also wont detect pressure once you start drawing on non working area , but the pressure will start working once you go to working area.

Tablet (Parblo A610)

**Comment by callaa** [comment]
Have you tried toggling the Windows Ink mode in the settings dialog? (The application must be restarted for the change to take effect.)

**Comment by daianpan** [comment]
Yes, I've tried that. I've already done the following
-Windows Ink Toggling/restart
-reinstalled wacom drivers
-reinstalled rawpile

Any other solutions would be greatly appreciated.

**Comment by notfood** [comment]
I have two users with the same issue. One is using Wacom Cintiq, the other is using XP-Pen Deco 01. 

I've tried to debug the issue with the same steps as above, it doesn't work.

It used to work fine for the Cintiq user but after a windows update I assume it failed.

**Comment by notfood** [comment]
Tablet handling has changed since then. If you're still having the same issue feel free to re-open it.
