### ISSUE TITLE
Join panel duplicate entries

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#644]
Minor bug.

Whenever you enter servers by find, the join panel's combo box is filled with duplicates. The list can end with the same server repeated all the way as you are browsing rooms, pushing your favorite servers that can't be found in the find menu out of the way.

**Comment by callaa** [comment]
This is now fixed in the 2.1 branch. Turned out to be a much simpler bug than I thought, so I could have just as well fixed it in the master branch. Oh well.

**Comment by notfood** [comment]
I went and patched my client but I see no difference. Am I missing something?
