### ISSUE TITLE
Cintiq 13HD Initial lag spike

### ISSUE THREAD

**Issue by CuriLagann** [drawpile/Drawpile#645]
Hello~!
I recently got back into drawpile but with .7-.10 I can't seem to draw without that darn initial lag spike

Now I'm not new to this issue at all, I have it settled on CSP PS and Krita, but for some reason, going thru github and trying every solution people have come up with doesn't seem to change a thing

I have hold disabled, I still use windows ink, but even when I turn it off it doesn't work. When I use the workaround it also doesn't do anything, same with turning off/on windows ink in drawpile, and turning off scroll with fingers turns up nothing!

Is there some combination I've missed or am I doing something wrong? Thanks for the help! 
![image](https://user-images.githubusercontent.com/29205474/43813025-d1fa077a-9a78-11e8-9926-c99a89f66e1c.png)

**Comment by daianpan** [comment]
I have this same problem, also on a Cintiq 13HD... The first bit stroke always has a straighter lag induced line to it even with curves

**Comment by callaa** [comment]
Do you have pen gestures enabled in Windows? I recall seeing something like this caused by that feature.

**Comment by CuriLagann** [comment]
Nope! Gestures/Flicks are off, everything is set up to work with my other programs I use professionally, which is why I'm confused drawpile has such a hard time with my tablet? I've never experienced this after getting flicks and gestures and ink set up correctly in any other program

I've tried every combo I can think of with ink/bug workaround/scroll finger on/off and nothing seems to change anything?

**Comment by callaa** [comment]
If you still have the "bug workaround mode" option, it means you are using version 2.0.9. Try updating to 2.0.10. It removes a change I made to the Wintab code in 2.0.9 which I found could cause problems for some users.

**Comment by daianpan** [comment]
I've been on the lastest client build (2.0.10.) and also have gestures and flicks off as well. Pretty much the same boat as curilagann so far.

**Comment by CuriLagann** [comment]
Sorry whatever it is called in .10 I used that, I also tried the previous versions too and the solutions for them just to see if I could get it to work, but no luck

If it helps I'm running the second generation of cintiq 13hds (2011) and the latest wacom drivers, I did update the drivers right before using drawpile at all, so there might be something there?

**Comment by notfood** [comment]
Stale, closing. Tablet handling has changed since then, If you're still having this issue feel free to re-open it.
