### ISSUE TITLE
Tablet cursor bug

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#646]
Visual bug.

Version 2.0.11 Linux

Whenever I use the tablet the cursor doesn't hide, which doesn't happen to the mouse. It seems to be a focus issue, no keyboard shortcuts work either whenever the tablet cursor looks like this. I have to move the mouse so focus returns and I'm able to use the shortcuts once again.

Here is a video showing the issue.

[![Video](http://img.youtube.com/vi/2XxmIj3P2Hg/0.jpg)](http://www.youtube.com/watch?v=2XxmIj3P2Hg)

This didn't happen before, some system library that updated in my ArchLinux has created this issue.

I tested 2.0.10 and it happens there too... After I rebuilt it. I didn't had this issue this morning before the rebuild.

-edit-

This bug doesn't happen in the 2.0.11 AppImage. So it's pretty much a QT library breaking something.

I tried to downgrade the QT libraries in my ArchLinux system but it's such a pain, everything just breaks and it still doesn't build.

**Comment by callaa** [comment]
Did you include `-DKIS_TABLET=on` in cmake options?

**Comment by notfood** [comment]
Outdated aur package strikes again.

Thank you, that fixes it. I completely forgot.
