### ISSUE TITLE
Drawpile 2.0.11 not launching on macOS High Sierra

### ISSUE THREAD

**Issue by kashidom** [drawpile/Drawpile#647]
Just downloaded the new release of 2.0.11 and upon launching (using the Open dialog) it simply closes again. Every relaunch after that closes before the app does anything at all.

Even after full uninstall (using AppCleaner) this issue persists.
No logfile or crash report found.

**Comment by notfood** [comment]
Can you run the app from command line and share the error that displays? It's probably missing a library.

**Comment by kashidom** [comment]
Yep, Qt is a problem:

> dyld: Library not loaded: @rpath/QtMultimedia.framework/Versions/5/QtMultimedia
>   Referenced from: /Applications/Drawpile.app/Contents/MacOS/Drawpile
>   Reason: image not found

I'll see about throwing it in and if anything else borks up.

**Comment by Kisa135** [comment]
I'm trying to run it on El Capitan and it tells me just "It won't run because of an issue"

**Comment by pastaandpencils** [comment]
I'm having the same issue. I originally had drawpile and then the comments stopped working and I wasn't able to move the canvas around. I decided it might need and update (which it did) and upon updating I can no longer open up the app at all! It really sucks cause it was a lot of fun. I hope it gets fixed soon.
(P.S. My computer is running on Mac OS High Sierra 10.13.6 )

**Comment by callaa** [comment]
There was a problem with the packaging. I just uploaded a version that should work.
