### ISSUE TITLE
bad resolution

### ISSUE THREAD

**Issue by uguutegu** [drawpile/Drawpile#648]
For some reason, the window resolution for my drawpile program has seemed to ruin itself. It happened before i updated the app, but the problem remained after i updated. I attempted to uninstall it completely and reinstall it in 32 bit instead of 64, messed around with the dpi scaling settings, everything. I just cant seem to figure out how to fix the program's individual resolution. any help would be highly appreciated as i cant really draw in the app as even the resolution of my lines are messed up. Please help!

**Comment by tincancrab** [comment]
This is a shot in the dark, but have you made sure the canvas is rotated to 0 degrees? Also, what is your screen resolution? Anything special?

Can you recall what may have triggered this? Possibly a graphics card driver update?

**Comment by uguutegu** [comment]
it is, yes. and i didnt have a graphics card update between when it was working and when it stopped working. https://gyazo.com/ac30fb711dd392e14c25962b9dd3711d here is an image of what it looks like. its almost like i have my screen magnified, but it's only drawpile. my screen resolution is 1920 x 1080

**Comment by notfood** [comment]
Could be the theme hasn't loaded https://github.com/drawpile/Drawpile/issues/546

Try changing your windows theme?

**Comment by uguutegu** [comment]
It actually turned out to be a strange scaling option setting in advanced scaling settings that for some reason didn't effect any other program. After removing the custom scaling options and redoing them, restarting several times in between, i fixed the problem i was having. Thanks for all the help!
