### ISSUE TITLE
Docker build environment for windows

### ISSUE THREAD

**Issue by KnicKnic** [drawpile/Drawpile#651]
It would be nice to have a docker build environment for windows. Therefore I wouldn't have to setup a long list of steps for my build environment. As a start here is a docker file for visual studio. https://github.com/Microsoft/vs-dockerfiles

**Comment by callaa** [comment]
If someone wants to create one, I'd be happy to include it. Right now, I have an dockcross build environment I use to crosscompile the windows version, but I'm not very familiar with the actual Windows side of things and how you actually run Docker on Windows. (Do you still need a virtual machine or does it run natively on WSL these days?)

**Comment by CodyEakins** [comment]
@KnicKnic @callaa 
I use Windows when working with `drawpile-srv`.

There is some setup involved. First, your computer needs to support virtualization, then it's really down to how you install and use Docker.

I use WSL personally, but there are also configurations/options available for Powershell and Git Bash terminals.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Drawpile 2.2 can be built natively on Windows using vcpkg for dependency management, which means there's not many steps involved anymore. WSL is also an option. I think that obsoletes the need for having a Docker container as yet another variant.
