### ISSUE TITLE
Can't Paste? 

### ISSUE THREAD

**Issue by FrostDrive** [drawpile/Drawpile#652]
I'm new to using drawpile but I've heard you can't copy/paste.

If you could, that would open up so many new possibilities. 

If it's already possible can someone tell me how? 
If not, I would really really love it.

**Comment by tincancrab** [comment]
You can copy/paste. Its under the Edit menu.

Many public boards lock this feature to avoid abuse (I'm sure you can see how this feature could be abused).

**Comment by FrostDrive** [comment]
That makes sense if it was locked every time I tried. But since it's
possible that's awesome. Thank you! :'D
