### ISSUE TITLE
No mountable file systems

### ISSUE THREAD

**Issue by Shingapow** [drawpile/Drawpile#656]
I tried to re-download it on my Mac computer that runs IOS X El Capitan Version 10.11.6 but it tells me this "No mountable file systems"

**Comment by michaeldchin** [comment]
I also get this on my Mac El Capitan 10.11.2 
It only happens while downloading the 2.0.11-1 version but not the beta version 2.1.1 of drawpile

**Comment by notfood** [comment]
It's been fixed in 2.1.x
