### ISSUE TITLE
Airbrush & Custom Brush?

### ISSUE THREAD

**Issue by blvk** [drawpile/Drawpile#657]
Hello, I was wondering if adding an airbrush and custom brush features (even just stamp type brushes) could become a feature in the future?

**Comment by tincancrab** [comment]
Callaa has expressed interest in custom brushes! It's going to need a brush engine rehaul, as far as i understand. MyPaint is being looked at as a sort of baseline.

**Comment by callaa** [comment]
Yes, I will look into implementing more varied brushes in version 2.2! In the upcoming 2.1 version, I've done some preliminary changes to the architecture to make it possible to have different brush engines.

**Comment by Wade821** [comment]
Closing, duplicate issue. Please comment on Custom brushes in issue #617.
