### ISSUE TITLE
Dmg dl not working; "No Mountable File Systems"v.2.0.11-1 

### ISSUE THREAD

**Issue by orbasama** [drawpile/Drawpile#659]
As the title suggests, the newest version has this issue on mac systems.

**Comment by BigPapaMadRam** [comment]
please help im on mac and this is very agitating, it was working fine two days ago then suddenly it doesn't? whats going on?

**Comment by callaa** [comment]
The new package uses the new AFPS filesystem which only works on the latest OSX version. I'll fix this in the next release.
