### ISSUE TITLE
I can't access private session

### ISSUE THREAD

**Issue by Maroy42** [drawpile/Drawpile#660]
With some friends we created a private session with a password.
When I am typing the password (even copy and paste) I get the message: "incorrect password".
They don't have this problem.

I tried to create my own session so they could join me there but I get the same message... I am absolutely sure to type the right password.
My friends didn't even find the session I created 

I am on mac, High Sierra.

What can I do?

**Comment by tincancrab** [comment]
Have you modified your default port on your drawpile settings in any way?

Also, make sure, if you are hosting on drawpile.net that you sign up at drawpile.net

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
