### ISSUE TITLE
Pen-Pressure-Sensitivity stops working after a while

### ISSUE THREAD

**Issue by VeruAmari** [drawpile/Drawpile#661]
Hi! I've got this problem where Drawpile will at first detect my pen's pressure sensitivity, but after a while it just won't, no matter what I mess with in the program's settings.
The only working fix I've found so far is restarting my computer, but it seems to be an only temporary fix.

I've tried:
*Checking and unchecking Wintab and Windows Ink options separately
*Having both checked/unchecked simultaneously,
*Reinstalling the program.
*Reinstalling tablet drivers.
*Restarting the program.
*Restarting the PC (as mentioned above, it solves the problem for just a while).
*Inverting pressure curve.

**Comment by tincancrab** [comment]
What tablet do you have? Thats an odd bug, I'm not 100% sure whats going on.

When pressure sensitivity fails, does it still work in other programs?

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
