### ISSUE TITLE
[Feature request] Blur tool, whisper for chat, friend adding

### ISSUE THREAD

**Issue by ShyDoge** [drawpile/Drawpile#662]
The new changes to the watercolor tool are amazing, but I was wondering if there could be a blender blur tool that was somewhat like the ones in Krita?

It would also be a cool feature to be able to add friends and whisper in chat.

**Comment by Waloumi** [comment]
I second the blur tool, would be great.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Blur tool has been implemented in the form of MyPaint brushes, coming in Drawpile 2.2. Whispers have been in there for a while. Friend list is discussed in #726.
