### ISSUE TITLE
Drawpile program no longer picks up pen activity on canvas

### ISSUE THREAD

**Issue by Shykactus** [drawpile/Drawpile#663]
My Drawpile program on my windows 10 computer has suddenly stopped drawing on an online and not online canvas. It does detect change of tools. I can press my pen onto the canvas and no brush follows as i move it, leaving it completely untouched.  
I have uninstalled, reinstalled closed out and checked anything with my own computer, but it narrows down to the program itself.

**Comment by tincancrab** [comment]
What was it?
