### ISSUE TITLE
"Lock New Users" not saving after session reset

### ISSUE THREAD

**Issue by PucaShell** [drawpile/Drawpile#664]
I help run a daily session on Drawpile, and a frequent issue we face is trolls coming in to grief people's work; We've tried to fix this by setting up the session to automatically lock new users after seeing another session do the same, but for some reason "Lock New Users" doesn't save after a manual or automatic session reset. Is this being worked on at all?

**Comment by callaa** [comment]
I think this one should be fixed in the upcoming 2.1 version.
