### ISSUE TITLE
Feature request: expand the unusable border around workspace

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#665]
As it stands, the grey area around the space you can draw in is a little on the small side, which makes it difficult to work in the bottom right corner of the canvas if you say, favor the top left of your tablet. It's an obscure problem, and honestly a pretty minor one, but is there a setting somewhere to expand that grey space? 

![screenshot 2018-11-06 19 18 53](https://user-images.githubusercontent.com/8505474/48102394-d1a21700-e1f8-11e8-98f8-62203a62e246.png)

**Comment by askmeaboutlo0m** [comment]
This is implemented in Drawpile 2.2 now, it no longer puts a fixed border around the canvas and instead just caps it so that a sliver of it remains on the screen. It is available in the 2.2 development version <https://github.com/drawpile/Drawpile/releases/tag/continuous>
