### ISSUE TITLE
End of strokes not responding to pen pressure

### ISSUE THREAD

**Issue by ArtOfCombat** [drawpile/Drawpile#666]
I'm using windows 10, up-to-date drivers, a wacom intuos, and the latest version of Drawpile. When I draw lines, they respond to pen pressure at the start, but this pressure cannot be alleviated later. I can start a thin line, but if I thicken it, it's thick forever. Is there a workaround or fix for this?

![image](https://user-images.githubusercontent.com/14318980/48400772-4a233f00-e6f5-11e8-9910-a4fb51eed641.png)

**Comment by callaa** [comment]
Looks like you have the "distance" pressure mode selected. Switch to "stylus" mode to get real tablet pressure.
