### ISSUE TITLE
Cannot Connect to anyone - Pings not sending or not receiving

### ISSUE THREAD

**Issue by ArtOfCombat** [drawpile/Drawpile#667]
I can see the servers in the find menu, and I am allowing Drawpile through my firewalls. However, I cannot connect. The server I am trying to connect to is not behind NAT, nor is it using IPV6 when I am not. I cannot in fact connect to several servers, though some I can, and I can't find a pattern.

Relevant Log files available on request.

**Comment by tincancrab** [comment]
It is possible these servers are looking for resgistered users only, which you can go register through drawpile.net. The other thing I can think if is if they aren't using default port.Your best bet is to be in contact with the session creator. I get a feeling it has nothing to do with you.

**Comment by callaa** [comment]
More information is needed. What error message are you seeing?

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
