### ISSUE TITLE
Banning not working ?

### ISSUE THREAD

**Issue by JamesDelaneyyy** [drawpile/Drawpile#668]
I'm really having issues with a certain troll. After multiple banning seems he resets his IP address trough proxy or something and keeps coming back in to harass me. Can something be done about this please ?
![capture](https://user-images.githubusercontent.com/31395047/48525850-3ced8800-e88e-11e8-8df1-ffd0be216fd7.JPG)

Maybe make it so the rooms can be accessible from registered users only, or something to that extend ? Because people like that are really despicable.

**Comment by tincancrab** [comment]
You can make a room to not allow guests, if youre looking for registered users only. Its under your session settings.
