### ISSUE TITLE
No pen pressure in Wacom intuosCTL 6100

### ISSUE THREAD

**Issue by Observia** [drawpile/Drawpile#669]
I've tried in SAI and CSP with Pressure feedback successfully,but no use in drawpile
I've reinstalled Drawpile and Wacom server
Sorry for my bad English

**Comment by callaa** [comment]
Things to try:

 - try with both Windows ink mode enabled and disabled (application must be restarted for this setting to take effect)
- try the 32bit version

**Comment by notfood** [comment]
Stale, closing.
