### ISSUE TITLE
Tablet doesn't register full strokes, only initial dots

### ISSUE THREAD

**Issue by Ghast505** [drawpile/Drawpile#670]
I just opened the program, can't get it to pick up my tablet strokes. When I put my pen down on the canvas, it records a dot, but not anything after- though, it does pick up the position of my pen. However, I have had it work a few times, just not... all the time. It works just fine with my mouse. 
I'm using a Wacom Intuos Pro Medium with the latest version of Mac. My drivers are up to date, tablet works just fine with all other programs.

**Comment by tincancrab** [comment]
As... I dont have a Mac, I'm giving this a shot in the dark. Are any of the boxes under Preferences>General selected, like wintab or windows ink?
