### ISSUE TITLE
Weird line glitch

### ISSUE THREAD

**Issue by JohnTaco** [drawpile/Drawpile#672]
For some reason whenever I draw on the canvas, there is always a specific spot where the line will just jut out, even when I draw a straight line. I've tried avoiding the spot, but it's not that easy. I use an Artisul D16 and I have Windows 10. 
![image](https://user-images.githubusercontent.com/45222667/48820526-4dd14a00-ed23-11e8-8c21-a0b7211fb26d.png)

**Comment by tincancrab** [comment]
This is probably a redundant question, but does this happen in other programs?

**Comment by JohnTaco** [comment]
No, not at all.

**Comment by tincancrab** [comment]
Could you see if this occers in Krita? If so, I suspect its the underlying tablet framework, since Drawpile and Krita share that.

**Comment by JohnTaco** [comment]
![image](https://user-images.githubusercontent.com/45222667/50533573-786caa80-0afa-11e9-8930-354f400df712.png)
Nope. Krita works just fine

**Comment by gibbermagash** [comment]
Did you start drawing at the top of the page or the bottom?
And could you post all of the coordinates?

**Comment by JohnTaco** [comment]
I tried drawing from all angles. no matter where I draw from, the line will always glitch at a specific spot. Also what do you mean by post all of the coordinates?

**Comment by gibbermagash** [comment]
I was looking through the numbers trying to see specifically where the
error occurred but I didn't notice a big change.
So I thought maybe the coordinates you posted may have been incomplete.

**Comment by notfood** [comment]
Still an issue? This used to happen to me but it's been fixed since then.
