### ISSUE TITLE
Dock Issues with Tablet

### ISSUE THREAD

**Issue by amyanimalover** [drawpile/Drawpile#673]
When using the tablet to fidget with the brush dock, it doesn't want to move left or right when I click drag so it will not change size, opacity, hardness etc. It will after I wait a few seconds to coax it to work, but not sure what the problem is. Works instantly if I use a mouse to click drag.

There's no problem with the drawing canvas, so I find it strange.

https://i.imgur.com/k2R29UY.gifv

**Comment by notfood** [comment]
Is this still happening?

**Comment by amyanimalover** [comment]
It has been fixed by now!
