### ISSUE TITLE
User Interface UI not scaling properly on High DPI device (Surface Pro 6)

### ISSUE THREAD

**Issue by Kotters** [drawpile/Drawpile#674]
![unknown 1](https://user-images.githubusercontent.com/21274106/50061262-f5e00480-0163-11e9-8d39-19efc8546dfe.png)

The user interface is far too large, and no compatibility settings seem to change the scaling behavior. Additionally, the canvas appears to be zoomed in. I attempted the fix that was mentioned in an earlier issue by creating a qt.conf file and setting various dpiawareness settings, but nothing changed the behavior.

The device is a Surface Pro 6 on Windows 10 build 1803

**Comment by tincancrab** [comment]
Have you tried right-clicking your desktop, selecting Display Settings, and changing the selection under the "Change the size of text, apps, and other items"?

I have a high resolution monitor, and by default, Windows 10 had it suggested to a recommende which wasnt 100%. Not sure if it was 150 or 200%.

Let me know if this fixes things!

**Comment by callaa** [comment]
Versions 2.1.7 and 2.1.8 are built with Qt 5.12, which reportedly fixes some high DPI problem. Can you try if the new version fixes this problem for you?

**Comment by Autumn-Apple** [comment]
I have the same problem with the 2.1.11 version and idk how to fix it

**Comment by SeanIncorporated** [comment]
I'm also having the same issue. I have this issue with 2.1.13 and 2.1.14. My Wacom Cintiq 13 display settings have app size up to 150%, but didn't have this issue before.
![bandicam 2019-11-20 10-51-14-858](https://user-images.githubusercontent.com/58002639/69261642-8e0e1700-0b87-11ea-914c-ed67f6576b9e.jpg)

**Comment by callaa** [comment]
In version 2.1.13, I enabled a high DPI mode, but looks like it didn't help any. I will disable it for the next release again.

**Comment by Wade821** [comment]
I still don't know about outright disabling or removing it, I think it'd be better to have the option since high display screens is going to continue to be a thing. 

Right click the desktop, display settings, and try setting the scaling down and see if that improves it.

**Comment by Kotters** [comment]
I hate to muddy the waters further, but I'll update my experience.

After making my initial bug report, I restarted my Surface Pro 6 and the UI scaled properly. It has worked properly ever since, though I'm not sure what version my Surface is currently on.

Additionally, my Desktop currently runs Drawpile 2.1.11 and it scales correctly. DPI is set to 125% for my 4k screen on my Desktop, which is on Windows 10 1903.

I wish I could give a better update other than what amounts to "Works on my machine" or "nvm, fixed it," but it is what it is. I'm not sure why restarting the Surface worked.

**Comment by Wade821** [comment]
High DPI mode was enabled in Drawpile 2.1.13. I would try that since that is where the high DPI mode was introduced.

**Comment by ultrazebra** [comment]
Bump, this issue persists on LMDE 5

**Comment by askmeaboutlo0m** [comment]
This should be fixed as of Drawpile 2.2.1. It has a setting to enable high-DPI scaling and lets you override the scale factor and font sizes if it's not detected properly. Any kind of compatibility mode in Windows needs to be turned off for this to work properly, otherwise Drawpile is presented with the wrong reality by the operating system.

![image](https://github.com/drawpile/Drawpile/assets/13625824/de894128-3eb3-4e8b-92a3-97c8a34b14eb)

If there's still problems with it, feel free to reopen this or create a new issue.
