### ISSUE TITLE
Brush size shortcut?

### ISSUE THREAD

**Issue by panhartstuff** [drawpile/Drawpile#675]
> Hold Shift+middle mouse button (or stylus button) and drag up & down.

The help file mentions the above, but it does not work at all. Even when only using mouse

**Comment by tincancrab** [comment]
Odd. Try the [ for decrease and ] for increase?

**Comment by panhartstuff** [comment]
The incremental button works fine. Shift+Scroll also works.
But, Shift+middle mouse button just triggers the pan tool.

**Comment by panhartstuff** [comment]
Oh, never mind it works now, maybe I just didn't notice it due to the lack of visual feedback and the pan tool obscuring the cursor.
