### ISSUE TITLE
Fill tool not working properly

### ISSUE THREAD

**Issue by mysillycomics** [drawpile/Drawpile#680]
Previously, I was able to draw an enclosed space on one layer, and then fill it in on a different layer (so I can have a lines layer, color layer, etc.). Now, I cannot do that unless I either fill it in on the layer I drew the enclosed space on, making drawing more difficult, OR I have to disable the background layer in order to do what I previously did. This was never a problem until a few days ago. This makes my drawing process much longer and tedious than it needs to. I can record my screen and show the issue if need be.

**Comment by notfood** [comment]
Check/Uncheck sample merged.
