### ISSUE TITLE
Drawpile keeps switching between fullscreen window and smaller window

### ISSUE THREAD

**Issue by Mrifk** [drawpile/Drawpile#682]
I usually run things in a maximized window, so naturally I would do the same for Drawpile. It does what I expect and fills the entire screen sometimes, but occasionally it will switch to a window size that I would expect from hitting "restore"—only, it is still in maximized state. Hitting "maximize/restore" a few times does nothing. Then, sometime later, the maximized state will switch back to fullscreen.

The switch (one way or the other) usually happens on some sort of button press—like switching a brush or selecting "View → Docks → [something]".

I'm running the 2.0.11 appimage on Debian 9.

**Comment by callaa** [comment]
Which window manager are you using?

**Comment by Mrifk** [comment]
Marco. (part of the MATE desktop, fork of GNOME metacity.) For the record I've never had this problem with any other program, even appimages using Qt.

**Comment by notfood** [comment]
Appimages is no longer the recommended way to install drawpile on Linux. Please try again with [Flathub](https://flathub.org/apps/details/net.drawpile.drawpile)

Feel free to re-open the issue if you're still experiencing it.
