### ISSUE TITLE
No pen pressure :(

### ISSUE THREAD

**Issue by kipzi** [drawpile/Drawpile#683]
I have windows 10 latest build, XP Pen artist 12, Wacom Bamboo CTH 670. These drivers do not conflict with one another.

Pen pressure on the latest version of drawpile doesnt work with either one.
Ive disabled windows ink. Ive tried wintab. Pen pressure works on both tablet in every single other program Ive tried. 

The tablet tester DOES register the pressure though. It just doesn't reflect in the brush strokes.

I thought multimonitor might be the issue but same result when I unplugged the rest.

**Comment by kipzi** [comment]
Update thought Id include my tablet tester DOES see my pen pressure. But it doesnt work in drawpile.

**Comment by callaa** [comment]
If the pressure registers in the tablet tester, check that you have the right pressure mode in the Input dock (Stylus) and that the pressure curve is normal.

**Comment by kipzi** [comment]
Stylus press X=219.16 Y=94.41 B=1 P=10.9%
Stylus move X=219.16 Y=93.87 B=1 P=14.6% (DRAW)
Stylus move X=219.29 Y=93.27 B=1 P=19.5% (DRAW)
Stylus move X=219.29 Y=92.70 B=1 P=24.3% (DRAW)
Mouse press X=219 Y=94 B=1
Mouse move X=219 Y=93 B=1
Stylus move X=219.29 Y=91.97 B=1 P=28.1% (DRAW)
Stylus move X=219.29 Y=91.37 B=1 P=31.1% (DRAW)
Stylus move X=219.29 Y=90.83 B=1 P=33.6% (DRAW)
Stylus move X=219.29 Y=90.52 B=1 P=35.7% (DRAW)
Stylus move X=219.29 Y=90.13 B=1 P=37.9% (DRAW)
Mouse move X=219 Y=90 B=1
Stylus move X=219.29 Y=89.79 B=1 P=39.8% (DRAW)
Stylus move X=219.29 Y=89.53 B=1 P=41.4% (DRAW)
Stylus move X=219.29 Y=89.40 B=1 P=42.9% (DRAW)
Stylus move X=219.29 Y=89.27 B=1 P=44.1% (DRAW)
Mouse move X=219 Y=89 B=1
Stylus move X=219.29 Y=89.19 B=1 P=45.3% (DRAW)
Stylus move X=219.29 Y=89.19 B=1 P=46.4% (DRAW)
Stylus move X=219.29 Y=89.19 B=1 P=47.6% (DRAW)
Stylus move X=219.29 Y=89.19 B=1 P=48.6% (DRAW)
Stylus move X=219.29 Y=89.19 B=1 P=49.7% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=51.1% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=52.5% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=54.2% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=55.9% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=57.3% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=58.7% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=60.0% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=61.0% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=62.0% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=62.9% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=63.7% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=64.4% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=64.9% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=65.6% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=66.4% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=67.2% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=67.9% (DRAW)
Stylus move X=219.29 Y=89.12 B=1 P=68.6% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=69.4% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=70.5% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=71.8% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=72.9% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=74.1% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=75.2% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=76.3% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=77.4% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=78.4% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=79.4% (DRAW)
Stylus move X=219.29 Y=89.06 B=1 P=80.3% (DRAW)

The pressure works in the tablet tester but it doesnt DRAW on the tablet tester like it should. Its all the same width red line.  But it says it sees the pressure.

My size / opacity / hardness are all checked in the freehand panel on the right.

Is that what you meant by input panel?

**Comment by callaa** [comment]
By the input panel I mean this:

<img width="235" alt="" src="https://user-images.githubusercontent.com/464576/52897127-70b3b300-31d9-11e9-9858-2d261d64d1b2.png">

The pressure mode should be "Stylus". Also check in the settings dialog that you have "Enable pressure sensitivity" checked.

**Comment by kipzi** [comment]
Wow! I feel like such a dummy! That panel wasnt showing at all, I found it and it was set to velocity! I changed it to stylus and now its working great! Thanks!
