### ISSUE TITLE
No pen pressure in Dp 2.1.0

### ISSUE THREAD

**Issue by WinterVermillion** [drawpile/Drawpile#685]
I use a parblo a610 with the ugee m708 drivers, and normally I have great pressure in Dp. But, I recently downloaded the new version of Dp with the big update (v 2.1.0) and everything else I tested out seems to work fine, other than that I don't have any pressure sensitivity. But as I said other then that it works pretty nice, if I get the problem fixed ill update this issue, but for now that it. keep up the great work though, I'm really liking the new things yous have added to Dp, especially all the new hosting settings. Have a good day!

Sincerely, Winter

**Comment by callaa** [comment]
Sorry, I this issue must have slipped by me. Can you check if pressure shows up in the tablet tester? (Help menu -> tablet tester)

Also, have you tried checking or unchecking the Windows Ink option in the settings dialog?
