### ISSUE TITLE
Fails to properly install desktop file/icons when the stage directory is set

### ISSUE THREAD

**Issue by yurivict** [drawpile/Drawpile#686]
```
install  -m 0644 /usr/ports/graphics/drawpile/work/Drawpile-2.1.0/desktop/drawpile.desktop /usr/ports/graphics/drawpile/work/stage/usr/local/share/applications
install: /usr/ports/graphics/drawpile/work/Drawpile-2.1.0/desktop/drawpile.desktop: No such file or directory
*** Error code 71
```

**Comment by callaa** [comment]
Does this error come from Drawpile's own makefile or some external system? The desktop file name has changed to `net.drawpile.drawpile.desktop` as recommended by the current desktop entry standard.

**Comment by yurivict** [comment]
It comes from the port script that installs desktop file and icons.

The reason this script exists is that you install desktop and icons incorectly.

You use xdg-* commands. This command hangs:
```
63192  3  I+       0:00.01 /bin/sh /usr/local/bin/xdg-desktop-menu install --novendor /usr/ports/graphics/drawpile/work/Drawpile-2.1.0/desktop/net.drawpile.drawpile.desktop
```

```xdg-desktop-menu``` installs the .desktop ```file``` into a final destination. This only happens when the final user builds the program, which for the most part the aren't supposed to do. They should install from a package provided by the OS distro.

So your cmake files fail to install into the stage directory. You should just copy files into the stage directory. Optionally, you can also do installation into the root using xdg when no stage directory is set. But users aren't supposed to do this, because they can't be building/installing all software themselves. This is just not realistic.

**Comment by yurivict** [comment]
Many systems have packages form Drawpile: https://repology.org/metapackage/drawpile/versions
If some systems don't have packages, you should ask them to create them through their mailing lists.

Expecting users to build manually is a wrong thing to do.

**Comment by callaa** [comment]
Ah, I was under the impression that using the xdg install commands was the correct way to do it. Can you point me to documentation that explains the actual best practice?

While I can't expect users to build the application from sources, that's still a use case that needs to be supported. (If for nothing else, because *I* build it from sources, rather than rely on a package made by someone else.)

I don't think it's up to me to go around asking distros to make packages, but rather the users of said distros to make or request packages if they want Drawpile natively packaged for them.

**Comment by yurivict** [comment]
Just copy the files with cmake's install instructions.

**Comment by callaa** [comment]
I committed an update that removes the use of the xdg- tools (56b0d95)
I looked at how Krita installs its binaries, icons and other resources and did it the same way. Does it work correctly from a package managers perspective now?

**Comment by yurivict** [comment]
Yes, it works correctly now, thanks!

You could also compress the .svg icon. They are normally compressed and have the extension .svgz

**Comment by callaa** [comment]
I compressed the scalable icons.
Thank you for informing me about the problem with the build scripts.

I'll will probably release 2.1.1 beta very soon. Unless any more major bugs are discovered, version 2.1.2 will be the next stable release.
