### ISSUE TITLE
Issues with connecting

### ISSUE THREAD

**Issue by GoldDynamo** [drawpile/Drawpile#688]
Perhaps it may just be a simple problem, but for some reason or another, I cannot host a room/join a room with this program at certain times. When I make a room and a friend joins, they will either be stuck with a loading screen, or it'll say they're unable to connect. Same goes for me when I'm trying to make a room or public server with a password. Somehow, it works for me when I join other people's rooms. It works in random intervals and quite frankly, I'm getting sick of how wonky it is.

**Comment by callaa** [comment]
Are you using a remote server (like the one at drawpile.net) or the built-in server? Most of these problems are usually caused by firewall issues (either at the ISP level or at home) when hosting the server on your own computer.

**Comment by Wade821** [comment]
Are you still having problems with this? 

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by notfood** [comment]
Stale, closing.
