### ISSUE TITLE
Incompatibility or Pressure?

### ISSUE THREAD

**Issue by TigerMC** [drawpile/Drawpile#689]
So In the new version of Drawpile (2.0.11) My pressure is absolutely not working... 
I downloaded an older version where the pressure is working but when i try to join a session i get the message 'Incompatible Server', or when i go to 'find' I get 'Session announcement: Error creasing SSL context ()'

Anyone can help me or with fixing the pressure problems, or making the old versions compatible again??

**Comment by callaa** [comment]
How much older? If you went all the way back to Drawpile 1.0, it's not going to be compatible with any of the servers people are running these days.

In version 2.0.11, did you try enabling or disabling the Windows ink mode? Check also the tablet tester (in the help menu.) If it picks up pressure events, then the problem must be the pressure setting in the "Input" dock.

**Comment by TigerMC** [comment]
Yeah is was like 1.0.7 I think.. And why is that change that older clients don't run servers anymore? :c

I don't know where to disable/enable that, and I found tutorial only for Wacom (I have a Huion GT-190)

![new canvas](https://user-images.githubusercontent.com/47946599/53665967-8911dc00-3c75-11e9-976d-f6f43d0f4755.jpg)

This is what the tester shows. 

And i've been also trying to solve it with "Input" dock but no matter what i do the pressure don't works.

**Comment by callaa** [comment]
In 1.x series versions, the server version was strongly tied to the client version because of the way the protocol worked. So if I had released version 1.1, it would not have been compatible with version 1.0. However, all 2.x clients are compatible with all 2.x servers (with some caveats.)

Version 1.0 servers do still work, it's just that everyone has upgrade to 2.0.

In your screenshot, the tablet tester is detecting pressure, so the tablet should be compatible. Can you show what you have in your Input dock? (The one tabbed together with the tool settings dock.)

**Comment by TigerMC** [comment]
I understand.

and sure

![image](https://user-images.githubusercontent.com/47946599/53666973-469dce80-3c78-11e9-8f00-e366569df7bb.png)

![image](https://user-images.githubusercontent.com/47946599/53666979-4ac9ec00-3c78-11e9-9130-7205a4cd48b2.png)

![image](https://user-images.githubusercontent.com/47946599/53666985-50273680-3c78-11e9-9da7-73e653be88ea.png)

**Comment by callaa** [comment]
Okay, with the "Pressure: stylus" setting it should work.
Next, check the Preferences screen (via Edit menu.) Do you the "Enable pressure sensitivity" box checked?

If that is OK, can you try the tablet tester one more time like this: draw a short stroke and copy&paste the whole log here. (I'm interested in the beginning, specifically: does the mouse or stylus press event come first)

**Comment by TigerMC** [comment]
Yes is it Checked

Stylus press X=162.27 Y=111.90 B=1 P=2.7%
Stylus move X=162.46 Y=111.73 B=1 P=13.3% (DRAW)
Stylus move X=162.65 Y=111.56 B=1 P=17.9% (DRAW)
Stylus move X=162.74 Y=111.39 B=1 P=19.7% (DRAW)
Stylus move X=162.83 Y=111.22 B=1 P=20.7% (DRAW)
Mouse press X=162 Y=112 B=1
Stylus move X=162.93 Y=111.14 B=1 P=21.7% (DRAW)
Stylus move X=162.93 Y=111.05 B=1 P=22.9% (DRAW)
Mouse move X=163 Y=111 B=1
Stylus move X=163.02 Y=111.05 B=1 P=24.3% (DRAW)
Stylus move X=163.02 Y=111.05 B=1 P=26.1% (DRAW)
Stylus move X=163.02 Y=111.14 B=1 P=27.8% (DRAW)
Stylus move X=163.02 Y=111.31 B=1 P=29.7% (DRAW)
Stylus move X=163.02 Y=111.48 B=1 P=31.5% (DRAW)
Stylus move X=162.93 Y=111.73 B=1 P=34.1% (DRAW)
Stylus move X=162.93 Y=112.07 B=1 P=36.8% (DRAW)
Stylus move X=162.74 Y=112.50 B=1 P=39.3% (DRAW)
Stylus move X=162.65 Y=113.01 B=1 P=41.3% (DRAW)
Mouse move X=163 Y=112 B=1
Stylus move X=162.55 Y=113.69 B=1 P=42.5% (DRAW)
Stylus move X=162.46 Y=114.54 B=1 P=43.2% (DRAW)
Stylus move X=162.36 Y=115.73 B=1 P=43.7% (DRAW)
Stylus move X=162.27 Y=117.00 B=1 P=44.0% (DRAW)
Stylus move X=162.27 Y=118.62 B=1 P=44.3% (DRAW)
Stylus move X=162.46 Y=120.58 B=1 P=44.6% (DRAW)
Stylus move X=162.65 Y=123.13 B=1 P=44.6% (DRAW)
Stylus move X=163.02 Y=126.10 B=1 P=44.6% (DRAW)
Stylus move X=163.69 Y=129.85 B=1 P=44.7% (DRAW)
Stylus move X=164.54 Y=134.18 B=1 P=44.7% (DRAW)
Mouse move X=162 Y=115 B=1
Stylus move X=165.67 Y=139.37 B=1 P=44.7% (DRAW)
Stylus move X=167.18 Y=145.32 B=1 P=44.7% (DRAW)
Stylus move X=168.98 Y=151.70 B=1 P=44.9% (DRAW)
Mouse move X=166 Y=139 B=1
Stylus move X=171.06 Y=158.33 B=1 P=44.8% (DRAW)
Stylus move X=173.23 Y=165.31 B=1 P=44.7% (DRAW)
Stylus move X=175.69 Y=172.54 B=1 P=44.3% (DRAW)
Stylus move X=178.61 Y=180.19 B=1 P=43.6% (DRAW)
Stylus move X=181.73 Y=188.10 B=1 P=41.6% (DRAW)
Mouse move X=176 Y=173 B=1
Stylus move X=185.32 Y=196.18 B=1 P=35.7% (DRAW)
Stylus move X=189.01 Y=204.51 B=1 P=23.1% (DRAW)
Stylus release X=189.01 Y=204.51 B=0 P=0.0%
Mouse move X=189 Y=205 B=1
Mouse release

**Comment by callaa** [comment]
Okay, that log looks fine too. Hmm, this is getting strange. So far, everything looks like it should work. This is a silly question, but it's the only one I can think of. Do you have the pressure checkboxes checked on the brushes you're using? (Size or Opacity, for example)

**Comment by TigerMC** [comment]
SO THIS HAPPENED (And yes they were checked all the time)

![image](https://user-images.githubusercontent.com/47946599/53668185-d98c3800-3c7b-11e9-849e-37a3228d8349.png)

**Comment by TigerMC** [comment]
So I have no idea what happened that now it suddenly works.. but i'm really glad it does! Maybe just had to run the tester?? idk.. Anyways thank you so much for your help and time <3

**Comment by callaa** [comment]
Perhaps there was a stale setting that got reset by opening the preferences dialog? In any case, I'm glad you got it working.
