### ISSUE TITLE
 windows version isnt compatible

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#692]
My friend uses windows 7 and it says the new 2.1.2 isnt compatible but the previous version worked fine.

edit: The previous being  2.0.11 but I found out the problem was 32bit compatability. 

I'm just finding it strange to release this version of drawpile as the main download so early, basically forcing all older users to upgrade because newer users will have this version.
You can't join 2.0.11 servers on 2.1.2 and vice versa

**Comment by callaa** [comment]
Can you be more specific? By previous version do you mean 2.1.1 or 2.0.11?

**Comment by Nujiao** [comment]
> Can you be more specific? By previous version do you mean 2.1.1 or 2.0.11?

Sorry, I edited my main post for clarity

**Comment by callaa** [comment]
The 32 bit version is now up.

Version 2.1.0 beta was released almost two months ago, and the last 2.0 series release was a year ago, so I'm not sure what you mean by early. My previous experience with the 2.0.0 beta was that hardly anyone actually tries out the beta. So I don't see any other way than to release the new stable when it seems stable enough. This time at least both 2.0 and 2.1 sessions can share the same server.

**Comment by Nujiao** [comment]
> The 32 bit version is now up.
> 
> Version 2.1.0 beta was released almost two months ago, and the last 2.0 series release was a year ago, so I'm not sure what you mean by early. My previous experience with the 2.0.0 beta was that hardly anyone actually tries out the beta. So I don't see any other way than to release the new stable when it seems stable enough. This time at least both 2.0 and 2.1 sessions can share the same server.

Yeah, I understand now. Betas are pretty hard to round up people for but thanks for putting up.
also, idk if u guys could fix it but in 2.0.11 after a session reset the brush and eraser would occasionally rubber band from their last position but now in 2.1.2 after rapid use of of brush and eraser hot key it will rubber band and get worse after a session reset. I will add a gif so you can view what I'm talking about.
![ezgif-3-a62b5bbc4f25](https://user-images.githubusercontent.com/39990590/54084872-db559b80-430c-11e9-8348-9bc9258450fe.gif)
