### ISSUE TITLE
My brushes have lost their pressure sensitivity

### ISSUE THREAD

**Issue by MooMooMilk64** [drawpile/Drawpile#695]
Some background, I work on a Huion Kamvas and use windows 10. I have recently updated draw pile to the newest update (2.1.2) and I've noticed something strange going on with my brushes. The settings for them have stayed the same from the older version, but they seem to have lost their pressure sensitivity. I noticed this while trying to color something, but no matter how light I held the pen to the screen, it would always be bold. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/48533959/54315989-9dc36d80-45ad-11e9-9207-745e17004b75.png)
The first one is before the update and the other one is after the update.

**Comment by callaa** [comment]
This might be caused by changed setting keys if you updated from 2.0.10. Try this:

1. Open the settings dialog
2. Make sure "Enable pressure sensitivity" is checked
3. Click Ok (important: this will rewrite the settings)
4. Restart the application

**Comment by MooMooMilk64** [comment]
Thank you so much! This helped a lot. 
![image](https://user-images.githubusercontent.com/48533959/54388029-ccebe480-466a-11e9-8795-97f6e9be2585.png)
