### ISSUE TITLE
a few suggestions and bugs

### ISSUE THREAD

**Issue by ShyDoge** [drawpile/Drawpile#696]
I think the update is pretty great but there are a few issues I have run across and so have my friends. We miss the old navigator and wish the zoom buttons and turn buttons were on the extra bar that was included in the update instead. Also the icons are rather large in the chat bar and unless you extend it you can only see one message at a time while drawing, so I wish there was an option to either make them smaller or have a read only mode for chat if that is possible? Also when people draw you cant see what layer they are on by their pointer anymore.  

When hosting with a syntheticdream.net server we cannot use custom icons and setting a user as trusted also doesn't seem to work and results in both the user and operator being kicked. Also automatic session reset is broken as well. And when loading into a board I crash if I click ok to see the session load unlike in previous versions. I don't know if it is a bug but, Every time I open DP the extra bar always repositions beneath the first though I constantly try to lock it as one bar. 

But I love the idea of having individual icons, it's really fun, and the square brush is **AWESOME!!**

**Comment by callaa** [comment]
Navigator: which bar do you mean?

Chat: next version will include a compact mode that can be enabled by right clicking on the chat area.

Layers: this will be fixed in the next version.

The synthetic dream server hasn't been updated to the new version yet, which is why the new features don't work there yet.
