### ISSUE TITLE
Appimages for 2.1

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#697]
Currently, the Appimage build scripts are broken for 2.1, and even for 2.0 because the base image used is no longer compatible with modern kernels.

The build scripts should be updated to use a compatible base image, but one that still produces builds that work on a variety of distros. The bundled library versions, especially Qt, should also be upgraded.

**Comment by necronoise** [comment]
Any update? I really want to use the new version, the flathub for void linux is not working. (Also https://flatkill.org/)

**Comment by callaa** [comment]
No-one has yet volunteered to help with this, and I don't have much motivation to work on the appimage build scripts at the moment.

**Comment by probonopd** [comment]
Would you accept a pull request that builds AppImages on Travis CI and uploads them to GitHub Releases?

Are there concise instructions on how to build 2.1 on Ubuntu xenial?

**Comment by callaa** [comment]
The most up to date build instructions are here: https://github.com/drawpile/Drawpile/wiki/Building-from-sources

Looks like Ubuntu 16.04 comes with Qt 5.5, which Drawpile no longer compiles against, so either an external repository or a self-built Qt would be needed. I used a self-built Qt with the Centos based appimage base, because the one provided in the repository was broken. But even then, I couldn't get anything newer than 5.6 to work properly for some reason.

I haven't used Travis CI myself, but it would certainly be convenient.

**Comment by probonopd** [comment]
Thank you. Tried building it on xenial but getting `error: ‘class KZip’ has no member named ‘errorString’`.

Here is what I am doing:
https://github.com/probonopd/Drawpile/blob/patch-2/.travis.yml

Here is the build log:
https://travis-ci.com/probonopd/Drawpile/builds/121998615

**Comment by Wade821** [comment]
I'm at work so I can't explain specifics, but look for orawriter.cpp at the link below. I made scripts for compiling and setting up drawpile from source for raspberry pi running Raspbian. I would explain more, but my cell phone won't load the page for me to get the details. You can run the sed command to make the replacement to make it compile, but you'll need to change the file location at the end to the location of your orawriter.cpp file. If you can't figure it out, I should be able to help more in about six hours.

https://github.com/Wade821/PiDrawpile/blob/master/drawpile-installer-official-build-from-sources

**Comment by probonopd** [comment]
Please test https://github.com/probonopd/Drawpile/releases/download/continuous. Some fine-tuning may still be needed.

**Comment by Wade821** [comment]
> Please test https://github.com/probonopd/Drawpile/releases/download/continuous. Some fine-tuning may still be needed.

Link is invalid.

**Comment by f2d** [comment]
I never used appimages (ones available were 64-bit, and my server OS was 32-bit at that time), so I wrote [this small bash script](https://gist.github.com/f2d/e649fc91b2114d12314879452b8dec85) some time ago, to automate things I had to do every time building new versions of drawpile-srv from source code. I currently use it on Ubuntu 16.04 server with QT 5.9.

All it does is check it's in the right folder, clean up previous attempts, optionally fix code in the same way as @Wade821 mentioned, and run cmake with arguments.

I left a comment down there with a little more details. Maybe it will help someone.

**Comment by probonopd** [comment]
> Link is invalid.

Sorry, it is

https://github.com/probonopd/Drawpile/releases/continuous

Corrected above.

**Comment by probonopd** [comment]
Known issue: Icons are missing. We are already bundling those inside the AppImage at `usr/share/drawpile/drawpile/theme/`, but it is not being picked up from there. Probably we need to change the source code to (also) pick up the privately bundled icons from there.

https://doc.qt.io/qt-5/qicon.html#setThemeSearchPaths sets the search paths for icon themes to paths. Would possibly need to set this to `QCoreApplication::applicationDirPath() + "../share/drawpile/theme"`, something along the lines of https://github.com/Jet1oeil/openhexviewer/blob/aae71ea5d0d277fbe717ce4b26e00e0fd5babc1d/src/main.cpp#L66-L85.

Can a Drawpile developes please check this and make the required change?

**Comment by callaa** [comment]
That AppImage works, thank you!

The fallback icons do not use the theme path, instead the standard data locations + `/theme/{light,dark}/` is used. The standard data locations include the location of the application binary + XDG data paths (`~/.local/share/<APPNAME>`, `/usr/local/share/<APPNAME>`, and `/usr/share/<APPNAME>`)

If the location is `$PWD/../share/drawpile`, adding this line to `src/libclient/utils/settings.cpp` should do:

    datapaths << qApp->applicationDirPath() + "../share/drawpile";

**Comment by probonopd** [comment]
Thanks @callaa I have added this line.

**Comment by probonopd** [comment]
Worked. Much better now! Thanks @callaa 
Is anything else not correct in the latest AppImage?

**Comment by callaa** [comment]
Looks good to me. One last thing might be to add `-DKIS_TABLET=on` to the cmake call. This fixes a few tablet related quirks.

**Comment by probonopd** [comment]
Now I get the following build error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xinput_LIB (ADVANCED)
    linked by target "drawpile" in directory /home/travis/build/probonopd/Drawpile/src/desktop
-- Configuring incomplete, errors occurred!
```

**Comment by callaa** [comment]
I'm not sure which is the right package for Ubuntu, but `libx11-dev` looks like it might contain the needed files.

**Comment by probonopd** [comment]
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xinput_LIB (ADVANCED)
    linked by target "drawpile" in directory /home/travis/build/probonopd/Drawpile/src/desktop
```

**Comment by Wade821** [comment]
Fixed in the beta client, closing this issue since the beta includes compatibility mode. 

I also don't believe it will be used for the older version explicitly. Please feel free to comment if you have any remaining concerns on this issue.

Latest version available here:
https://github.com/drawpile/Drawpile/releases

Last release on website (out of date):
https://drawpile.net/download/#Beta
