### ISSUE TITLE
User markers for Navigator

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#698]
In 2.1.3, the navigator is no longer rendered using QGraphicsView, which means only the canvas pixel content is rendered. Getting the user markers back is a much requested feature, so let's take this opportunity to redesign it.

Since the navigator is now drawn independently, the user markers do not have to work exactly the same way they do on the main canvas. Feel free to submit your ideas here.

**Comment by Uboaaaaaa** [comment]
It's good in the way it is. Though maybe there could be an option to see what tool user is using?

**Comment by beenyuk** [comment]
If we have different type of color selector(HSV square/component sliders/ color palettle), maybe we can have two different type of navigator?
One is using the way in 2.1.3 for basic overview without showing user makers, the other is using the way in 2.1.2 for quickly konwing user's activity with showing user makers. And the one showing markers is selected by default.

As i know, a lot of ppl back to using 2.1.2 because of this issuse(user marker not showing on navigator). Including me , even i really want to have the latest version.
So hopefully we can have it back soon!

**Comment by callaa** [comment]
There is now a new user cursor implementation for the navigator:
![image](https://user-images.githubusercontent.com/464576/54864129-0acbc580-4d5b-11e9-974c-bfcbb69c3548.png)

Since it's now possible to render a different cursor in the navigator, I chose not to reimplement the exact same shape as shown on the main canvas:

 * The navigator cursors show only the user avatar, so they can be smaller and all the same size
 * The cursors currently only update at the same time as the navigator. This is a performance optimization. It is possible to add an option to make the navigator update in real time again, though.
 * The navigator cursors can now be enabled independently of the main canvas cursors. So you can show them on the main canvas but not the navigator, or vice versa.

> Though maybe there could be an option to see what tool user is using?

This is not possible, because the original brush settings are not transmitted to other clients.

> maybe we can have two different type of navigator?

We have that now in the new version. Right clicking on the navigator lets you toggle the cursors on and off.

Note that this design is not set in stone! I'll keep this issue open for a while longer to gather feedback.

**Comment by Uboaaaaaa** [comment]
> The navigator cursors show only the user avatar, so they can be smaller and all the same size

It's good that you think of its compactness and size, but people would find it hard to recognize a user only by their avatar, which users tend to change even more often than name (not saying about users without it at all). So let us still have an option to toggle user names and layers. It's easier to find trolls this way.

> It is possible to add an option to make the navigator update in real time again, though.

Please do.
