### ISSUE TITLE
Stroke bug 2.1.2

### ISSUE THREAD

**Issue by Saova** [drawpile/Drawpile#699]
![unknown](https://user-images.githubusercontent.com/48629611/54479734-57d7f680-47b3-11e9-9444-e03eade01e61.png)
![unknown (1)](https://user-images.githubusercontent.com/48629611/54479735-57d7f680-47b3-11e9-8708-06220c2ab6bc.png)

good afternoon. report this error that my friends are having recently with the new update 2.1.2, which is that when you perform the strokes in a specific way, or when you start the trace for the first time, the symmetry is automatically cut. it's like a bug that causes the drawpile not to recognize the stroke properly.

**Comment by callaa** [comment]
Does this happen when drawing with the mouse, tablet or both?

**Comment by Saova** [comment]
> ¿Esto sucede cuando se dibuja con el mouse, la tableta o ambos?

it only happens with the tablet

**Comment by Nujiao** [comment]
Try lowering or raising the Smoothing in the input tab, lowering or raising the hardness and lowering or raising  the spacing within the free hand tab.

**Comment by notfood** [comment]
Is this still an issue?
