### ISSUE TITLE
drawpile version 2.1.3 crashing

### ISSUE THREAD

**Issue by callmejev** [drawpile/Drawpile#702]
for some reason after the update 2.0.2 to 2.1.2 and 2.1.3  the moment i try to open up drawpile it crashes without fail even though
<img width="983" alt="Screen Shot 2019-03-19 at 6 53 55 PM" src="https://user-images.githubusercontent.com/48733941/54637398-efad3d00-4a5e-11e9-82c0-7843288d2787.png">
 i restarted my mac and reinstalled it it just keeps crashing was wondering if anyone else has this issue.

**Comment by callaa** [comment]
Most likely caused by unsupported macOS version. (Qt 5.9 supports only OSX 10.10 and up.) I've updated the minimum supported version on the website and in the app bundle.
