### ISSUE TITLE
Different servers and a bug

### ISSUE THREAD

**Issue by JamesDelaneyyy** [drawpile/Drawpile#703]
I updated to the 2.1.3 version.The bug happening for me is that it doesn't show in the navigator when someone else is drawing.
The suggestion/question is, when are you anticipating to switch servers to one version. The issue specifically is that there are people that don't use drawpile daily, and there's no indication of this new version unless you check the site often.Since the servers are not backwards compatible a person that's not a regular might come and not see any servers except the few that haven't switched yet and just think people are just not around, since there's no indication there's a new version. I  suggest there can be a message when you host/join using the drawpile.net server that there's a new version out  so they can get notified and make the switch.

**Comment by callaa** [comment]
If by not seeing who is drawing in the navigator you mean the cursors are not drawn, that's not a bug. Please see issue #698.

Yes, I suppose implementing a version check is a good idea. In fact, I have some experimental code for it that I never finished around somewhere.

**Comment by callaa** [comment]
Automatic version checking is now implemented.
