### ISSUE TITLE
Feature: Deskop widget 

### ISSUE THREAD

**Issue by Uboaaaaaa** [drawpile/Drawpile#705]
Is this possible to create a widget for deskop that allows to see how many users in the server and the list of usernames? Like, there could be a button where we choose the server and then there is that info about it. This would be useful if people just want to see who's online without running Drawpile and logining in.

**Comment by callaa** [comment]
Yes, that is possible. Check out http://pub.drawpile.net for an example of what can be fetched from the server's web API.

**Comment by erik90mx** [comment]
The documentation that I found here: https://github.com/drawpile/pubsrvproxy/
Said that the variable in the configuration should be **UserView = true**

When I tried the one used for sessions listing there aren't any problem: http://pub.drawpile.net/safe/sessions/

But when I tried for users, it didn't worked: 
http://pub.drawpile.net/safe/users/

It will be interesting to implement a little java app to the list of active users this way (or maybe from the registers ones in the Drawpile server, that are log in), or the same in a mobile app.

Regards

**Comment by callaa** [comment]
User listing is not enabled at pub.drawpile.net for privacy reasons.

**Comment by notfood** [comment]
This feature is already implemented, in both pubsrvproxy and webadmin.
