### ISSUE TITLE
Updated automatically DETECTED

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#708]
Hi,
Recently I just discovered that Drawpile has a new update, because I was curious to visit its web page (I'm a real fan of Calle Laakkonen work here)… and when downloaded it, I saw that not all the users updated their versions immediately (and was hard to find someone in the newer version, so this make it hard to switch from the older version to other users and so on).

In my daily work I use a lot an Open Source note taken application called Joplin: https://github.com/laurent22/joplin

What I REALLY like about it, is its **automatically update detection** when I first open it because (it shows windows with the listed fixes too):

- It always give me the last fresh version in just 1 click from the application, to download it.
- I feel exited to test the solved issues and new little features.
- It gives me that psychology perception that “this project is very active and alive”
- Proudness to use software that I think its creator care about it.

Regards

**Comment by callaa** [comment]
Funny coincidence, I've actually been working on this very feature for the past couple of days.

**Comment by callaa** [comment]
Automatic update detection is now implemented.

**Comment by erik90mx** [comment]
Hi,

I uninstalled Drawpile entirely from my system (now that I know the new version is up), to test out this feature:
- I installed again the V2.1.4 that has this new implemented feature.
- The problem was that it didn't mentioned me that there were a new update available, when I first open Drawpile after the installation.
![image](https://user-images.githubusercontent.com/3485891/55281298-e9894d00-52f7-11e9-936f-45d9f40c4445.png)
- When I go to "Check for updates" manually, I can see the new version alert is working fine
![image](https://user-images.githubusercontent.com/3485891/55281318-35d48d00-52f8-11e9-940d-52100032df58.png)

![image](https://user-images.githubusercontent.com/3485891/55281327-42f17c00-52f8-11e9-9c9e-b61d9ea3dda9.png)

The check box "don't check automatically" is disable (that's why I was expecting to see the notification when I first open Drawpile)

Regards

**Comment by callaa** [comment]
The automatic check is done only once per day. Uninstall does not remove Drawpile's saved settings (although perhaps it should?) so if you've already used Drawpile on this day, it won't check again until tomorrow.

**Comment by erik90mx** [comment]
That means that if you are using Drawpile in a day , before an update in the same day, you will not receive the notification because it checked the first time you opened the program?

**Comment by callaa** [comment]
Yes.
