### ISSUE TITLE
Option for mousewheel zooming without keyboard modifier

### ISSUE THREAD

**Issue by not-surt** [drawpile/Drawpile#709]
Currently the unmodified behaviour of mousewheel is vertical scrolling.
Personally I consider mousewheel scrolling on two-axis scrolling widget to be pretty much useless as it only allows scrolling on one axis without use of keyboard modifiers.
I'd personally find unmodified mousewheel zooming to be much more useful and fits nicely with MMB panning.
An option to allow such would be nice to see.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming in Drawpile 2.2.
