### ISSUE TITLE
find real ACTIVE drawing sessions

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#713]
Hi,
First to all, I like to draw in rooms where people still actively drawing (that’s the point to use this collaborative drawing software I guess), it is very common to found very old sessions In the host list like in the next image:

![image](https://user-images.githubusercontent.com/3485891/54870070-7582fe00-4d67-11e9-849f-81d1d97014e3.png)
 
By probability if “I want to find an active session”, I should join one that has many users (like the 25 ones there), but this are some cases that are common:

- A lot of time people is just “taking a spot” and maintains connected (without drawing a single stroke in hours), I guess they do that to maintain a session "crowded" and catch the attention to more users.
- I end up in a normal-heavy crowed session where literally nobody is drawing (a ghost session as I like to call it) with even 17 users inside.
- By probability I end up organizing the sessions by AGE and joining to the more recent ones, because is more likely that people there is just fresh and drawing.

In order to “find an active drawing session” it will be great to have:

- A new column (updated/used/last_stroke) in the in the Session list window, that stores the last time that “somebody” did a stroke there.
- The updated time can be resolved as the delta from the creation time to the recent stroke time.
- The new column/variable can be very useful to spot “ghost sessions” at glance.

This can be useful to give more attention or to spot sessions where there are just 3~5 people **actively drawing**. Using the number of users is a good option, but we will end up having the same distribution of users.

This "updated" value calculation can be more complex (the delta is to have a simple but partial solution), like analizing each user brush stroke times, or even proportional lenght (considering the overall time), to generate an average of "activity" for user and then compare it with the rest to get a single value, considering the next scenarios to resolve that value algorithm:

- in a session with 2 people, one is doing a brush stroke each 1 hour the other just did 1 stroke since de begining, if the session is up 5 hours, this should be an "active" session? (because the last stroke from the 1st user was exactly in the 5th hour)

- In a session with 1 person, that is up for 3 hours, since de begining he/she didn't make any brush stroke, but in the las minute of the 3th hour he/she begin to draw, this should be an "active" session?
 
- In a session with 10 people, that is up for 10 hours, everybody has a "normal" brush stroke behavior BUT everyone stops in the 7th hour (a lot of times because everyone shares the same time zones), that leave us 3 hours wihtout a single brush stroke in the canvas, this should be an "active session"?

Regards

**Comment by callaa** [comment]
Yes, something like this would be useful.
Perhaps the server could calculate an "activity score" based on the number of commands that has passed through it since the last listing update, for example.

**Comment by erik90mx** [comment]
this will involves that the chat will be considered in the "activity score" ? (cases when people just chat without use the canvas)

**Comment by callaa** [comment]
Not necessarily. The server can distinguish chat messages from canvas activity.

**Comment by Waloumi** [comment]
I like this idea!

**Comment by erik90mx** [comment]
Yesterday I was exploring some (not all of them) boards as I usually do after work, and wasn't able to found an active one besides the ones with more than 20 people (where were drawing just ~4 users, and where focus in Roleplay activity), at the end I decided to do my daily practice offline.

There are even users that create their open session (without password and listed in Drawpile), that kick every one that joins in, and maintains it with 0 users inside apart of themselves, so I guessed:
- They are using the session list, as a way "to announce" to their friends, that they are connected (it's the only way that your username will be visible for everyone)
- They are just "occupying a spot" in the server in case it runs out of hosting sessions.
- Usually if you continue looking, you can find those users connected in other room participating in a dynamic (chatting, drawing etc.), but still having their own session empty and open in a host.

Regards

**Comment by Waloumi** [comment]
Letting people have a preview of the session too before they join could be nice. I have a lot of people in my public sessions that join and leave 30 seconds later making chat spam and really undesired sounds when you have them on for people you're really expecting.

**Comment by notfood** [comment]
One way to solve this is just to identify and tag the idlers and not count them for the announcement and instead substract them from the max users so the available spots number remains correct.

**Comment by askmeaboutlo0m** [comment]
Solved by added an "active drawing users" count to drawpile-srv, the list server and on the listing website (e.g. the Community Servers page on drawpile.net). It counts a user as active if they've done any kind of drawing in the last 5 minutes. Stuff like chat messages or fiddling with the laser pointer don't count as drawing.

I think that kind of value gives a better idea of activity than an abstract "activity score" of some sort. It also catches the case of someone being done drawing and leaving, because their activity won't be counted anymore when they're gone.

This will be coming in 2.0.x, where x > 0.
