### ISSUE TITLE
Better Inspector Granularity

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#714]
Hi,
I was just trying out the new tool called "inspector" that is very useful to know "who draw something" or "who was the troll that did something".
The problem is the next one
 
![image](https://user-images.githubusercontent.com/3485891/54871534-2cd54000-4d7b-11e9-814f-8cb2883a6a59.png)

If I erase one of those as usual (using the eraser and doing it by hand), it still spotting the empty area as part of the same user.
 
![image](https://user-images.githubusercontent.com/3485891/54871535-33fc4e00-4d7b-11e9-95c9-208bd2f4e640.png)

NOTE: Is nice to have the name appearing in the tool properties, but to be honest I was expecting to see the user name directly in the canvas (I use to draw with the docks hide, using shortcuts for the tools)

The previous erased marked area is reduced when it’s created a new brush stroke, even if we can’t find something visible in it:
 

![image](https://user-images.githubusercontent.com/3485891/54871538-3ced1f80-4d7b-11e9-8b9f-2d5aa6457497.png)

So I wanted to try it out more, to see if that spot disappears, and it did it:
 
![image](https://user-images.githubusercontent.com/3485891/54871540-44142d80-4d7b-11e9-95c3-bf0650866b9b.png)

Sometimes it shows the erased spot from more than 2 iterations.

Regards

**Comment by callaa** [comment]
This is not really a bug, but rather the inspector revealing certain internal technical workings of the application. The inspector shows all non-null tiles last touched by a specific user. Fully blank tiles get cleaned up periodically, and will therefore show up in the inspector for a while, even after erased. If a tile sticks around, it means there is still at least one not fully transparent pixel left.

**Comment by erik90mx** [comment]
A lot of users erase their draws with the eraser tool (so few use a selection with the select tool and delete the content), and this way to erase the content is not perfect, because we end up with very little colored pixels left, or with almost alpha 0 pixels left, that aren’t visible for a normal person. Will be a good idea to have an acceptation range (for length and alpha, even considering that the last tool used was the erased)?

I was using this tool in real scenarios inside Drawpile yesterday after created the issue, a lot of times I saw people interacting very close to other people drawings, erasing without caution when:

- There is an activity called “RP” (Role Play), where people draw over and over again their characters interacting with other characters, this means they erase very quick and re draw in a different position their characters (they move a lot), meaning that they left a lot of empty spots (not completed cleaned) that are occupied by other user joining this activity a lot of time, and after that the inspector gets very imprecise to determine who is the owner.
- Usually the users prefers to communicate in the canvas instead to use the chat directly, that leave us with a lot of empty spots all over the canvas, that the users used to communicate and express ideas, that were erased on the go, but not in a very precise way.
There is another activity called “collab” where some users draw in the same spot, to create something together, this involves to draw over the other user’s brush strokes or erase each other brush strokes, after the piece is complete, the inspector have a hard time determining who did what (NOTE: A lot of times users use different brush values and colors to distinguish each other brush strokes) 
- A lot of times, troll people comes in a room and starts rage sketching all over the session, drawing in other people drawings in big canvas spots, a lot of times the users just banned the troll or disable its functions, and start erasing its brush strokes by hand, that leave us with a lot of spots detected by the inspector as the troll ownership.

Regards

**Comment by callaa** [comment]
The way the inspector is currently implemented, it's primary use is to detect trolls. It does not work reliably enough as a "proof of authorship" tool.

It would be possible to make the inspector work on a per pixel basis. In this case, it would highlight individual pixels, not tiles. However, this means every pixel operation becomes heavier and more memory is needed too. And even then, it can easily be abused: someone could use a very low-opacity brush to replace the "last-edited-by" tag of someone else's painting and claim it was theirs.

So, I'm not sure the tradeoff is worth it. In its current state, the limitations of the tool are immediately obvious. Making it more accurate might make it more misleading.

**Comment by erik90mx** [comment]
First to all, I just read you post about this tool:
https://drawpile-dev-diary.tumblr.com/post/183452691227/canvas-inspector-tool

I didn't knew it uses 64x64 pixel chunk of canvas, and that it works based on "a tag" for each chunk, now I understand more what you mean.

If we want to get a pixel base, it will means to have a more dense granularity or mesh, to store those tags in every chunk, even if we have a lot of chunks without use at all (empty spaces), their creation requires resources. Maybe there can be alternative algorithms that, not necessary needs a quadratic mesh, to reduce the granularity of the chunks in the canvas (my first thought was the Dynamic Topology implemented in Blender: https://code.blender.org/2011/10/dynamic-topology-sculpting/), but to be honest this doesn't seems like an issue with high priority for now, and sounds like it might needs a very heavy engineering.

I think that Drawpile is excellent to "social drawing" sharing the canvas (I know it’s the main purpose), so having a tool to "know who did what?" seems useful considering its main environment. The tool works for moderation, social interaction facilitator and art information as far I see it, because now Drawpile web has a user registration DB, so maybe in the future, somebody can track a user in-canvas art into the user's Drawpile gallery.

I identify fresh cases when this tool is useful as it is right now:
- A lot of times when you first enter to a session and saw a very great piece of art, because our innate curiosity, you want to know “who did that?” , a lot of time in the actual version of the tool, it works to identify the owner (when drawings are very wide apart each other).
- Sometimes when you are drawing and have the zoom in applied (usually because you are drawing details), people use to leave notes or hearts, and in those situation to be grateful you want to know “who was ?” because you didn’t see it in real time.

I hope that there exist an optimal solution for this issue in the future, seems like tool thought especially for Drawpile.

Regards

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

The erased areas thing has been fixed in Drawpile 2.2, blank tiles get purged. But the tile granularity is still an issue, so I'll keep this open and just rename it.

**Comment by Wade821** [comment]
https://github.com/drawpile/Drawpile/commit/93827ff3d46a9de52acee31b1755d827fb628271

Fixed in the beta client.

Latest version available here:
https://github.com/drawpile/Drawpile/releases

Last release on website (out of date):
https://drawpile.net/download/#Beta
