### ISSUE TITLE
NAVIGATOR drag is not wokring

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#715]
Hi,
I’m using this version of Drawpile:
 
![image](https://user-images.githubusercontent.com/3485891/54871637-17f9ac00-4d7d-11e9-8fe9-de71d6d91b38.png)

Seems like the drag functionality of the navigator is lost in this version:
 
![image](https://user-images.githubusercontent.com/3485891/54871639-1c25c980-4d7d-11e9-9a5d-c28063102a80.png)

Here I was in position 1 then I clicked the navigator in position 4 (maintained the click) and dragged to position 2, but it wasn’t working anymore.
The way I use the navigator is to easily and quick **explore big canvas** (dragging the viewer box) without doing a pan with the mouse or pen tablet.

Regards

**Comment by callaa** [comment]
Fixed in master branch now. Will be included in the next release.
