### ISSUE TITLE
Brush preset can't be saved in 2.1.4

### ISSUE THREAD

**Issue by beenyuk** [drawpile/Drawpile#718]
Recently, i try to change the default brush preset and create some new presets, but turn out it seems not working at all, which it all back to default after restart drawpile.

System info：Windows7 with drawpile2.1.4
This issues happened in both situation of default preset and new preset.
Situation1: manually change the default preset.
![Snipaste_2019-03-28_00-28-32](https://user-images.githubusercontent.com/48846565/55094481-71513a80-50f1-11e9-9789-eee178d1c88f.png)

Situation2: create a new brush preset.
![Snipaste_2019-03-28_00-30-52](https://user-images.githubusercontent.com/48846565/55094517-8037ed00-50f1-11e9-9d09-9073275742df.png)

**Comment by callaa** [comment]
Confirmed. Thank you for the detailed description. I was now able to reproduce this bug.
