### ISSUE TITLE
Windows installer V2.1.5 64 Bits Failing

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#720]
Hi,

While trying to install the new version of Drawpile, I got the next error in Windows 8.1 64 Bits

![image](https://user-images.githubusercontent.com/3485891/55280399-bbe9d700-52ea-11e9-982f-28b754f2ff87.png)

EDIT: After try it in admin mode, it works, but the error message still appearing at the beginning.

Regards

**Comment by callaa** [comment]
After a bit of googling, it seems like this error is caused by antivirus software: https://stackoverflow.com/questions/35130522/shellexecuteex-error-299-when-launching-installer-created-with-inno-setup

**Comment by notfood** [comment]
Stale, closing.
