### ISSUE TITLE
Fullscreen  mode shortcut doesn't works when join a session. 

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#721]
Hi,

I just downloaded V2.1.5 64Bits for Windows, testing out the new hide docks and fullscreen preserving docks feature, they seems to work just perfect when you first open the new version (offline), but the problem seems to appear when:
- You join a session listed.
- After join in try to get in fullscreen mode with F11 and it doesn't trigger the action.
- You can still get in fullscreen mode selecting the option from View -->Fullscreen
- You can't use the F11 shortcut to toggle back to normal window mode.
- This not affect the TAB shortcut to toggle the dock' hiding.
 
Regards

**Comment by callaa** [comment]
There appears to be a shortcut clash with the session settings shortcut. I suppose I should hardcode "shift+ctrl+F" as the fullscreen shortcut.

**Comment by erik90mx** [comment]
To be honest the "F11" shortcut is more world wide known for fullscreen than "shift+ctrl+f", as a personal opinion, I will prefer change the session setting shortcut one.

**Comment by callaa** [comment]
F11 is the default shortcut on Windows. On Linux and macOS, shift+ctrl+F is the default one. I have a vague recollection that I've already changed the session settings shortcut once. I wonder what the previous clash was.

**Comment by callaa** [comment]
I removed the default shortcut for the session settings action so it no longer clashes with the fullscreen shortcut on Windows. The action can still be assigned a shortcut via the preferences dialog.
