### ISSUE TITLE
Pen registering as a mouse click when drawing lightly, causing dots to appear.

### ISSUE THREAD

**Issue by Rorysaur01** [drawpile/Drawpile#723]
As the title says, dots are appearing when drawing lines due to the tablet registering strokes with mouse clicks. Multiple people I know are experiencing this as of the latest update.

**Comment by callaa** [comment]
This is likely related to issue #722

**Comment by callaa** [comment]
Here's a new build of 2.1.5 with KIS_TABLET enabled and the latest wintab code copied over from Krita: https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test.zip

Does this fix the problem?

**Comment by AngreFalcon** [comment]
That test build seems to have fixed the issues I was experiencing with pen sensitivity since updating to 2.1.5, including the problem with dots being left behind with every pen stroke.
