### ISSUE TITLE
FULLSCREEN mode: option to hide horizontal and vertical scroll bars

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#724]
Hi,

I was testing V2.1.5 and noticed that the scroll bars are  showing up when you enter to fullscreen mode.
![image](https://user-images.githubusercontent.com/3485891/55287905-ba60f300-536c-11e9-9f3d-2c0f5a7f8582.png)

It will be great to have the option to hide them automatically when we enter to fullscreen mode (optional, thinking in mouse users)

In Photoshop it is the default behavior.
![image](https://user-images.githubusercontent.com/3485891/55287929-2d6a6980-536d-11e9-870a-db9cb37e47e4.png)

(Fullscreen mode)
![image](https://user-images.githubusercontent.com/3485891/55287942-42df9380-536d-11e9-89dc-6b689c8da739.png)

In Krita too:
![image](https://user-images.githubusercontent.com/3485891/55287969-b2ee1980-536d-11e9-8e01-40a0d6316185.png)

(fullscreen mode/ canvas mode)
![image](https://user-images.githubusercontent.com/3485891/55287980-e6c93f00-536d-11e9-95a5-14686511e7bc.png)

Regards

**Comment by kvnvallis** [comment]
This problem appears to be back in 2.2.2. When you go into fullscreen mode, both scrollbars are visible, as well as the menu bar.

**Comment by kvnvallis** [comment]
I found the setting `Edit > Preferences > User Interface > Miscellaneous > Show scroll bars on canvas` and unchecked it. Solved the problem for me, because I don't need scrollbars outside of fullscreen mode either.

**Comment by askmeaboutlo0m** [comment]
The behavior changed intentionally.

You can hide the canvas scroll bars in the preferences altogether, which I think makes more sense. People usually have a preferred way of panning the canvas that doesn't change whether they're in full screen mode or not.

The menu bar got un-disappeared to avoid getting you stuck in full screen mode if your device has no keyboard to press F11 on or cursor to slam at the top edge of the screen. Bringing back menu bar hiding is tracked in #1387.
