### ISSUE TITLE
Weird drawing glitch

### ISSUE THREAD

**Issue by slammoooo** [drawpile/Drawpile#729]
Hey so I've had drawpile for awhile now, and this used to happen time to time in drawpile but I used to only just simply go to services and restart wacom to fix it. It's been 2 years since I even had pen pressure ever, and trying to draw decent curve lines are impossible because it would freeze a little bit and create these god awful lines. One day, it just stopped working and I haven't had a single clue to fix it ever since. This is what it looks like when I try to draw a circle or even a curve. It even does it on the tablet tester. My tablet works fine in other drawing programs but for some reason it rejects Drawpile.

I've tried redownloading drawpile and unchecking and checking the pressure sensitivity but I still haven't had any luck.

![i hate this](https://user-images.githubusercontent.com/49135836/55300154-d790d280-53fb-11e9-94ee-03a2b4b6a67c.png)

**Comment by callaa** [comment]
Did this bug appear with version 2.1.5 or did you experience it with the previous versions too?

**Comment by slammoooo** [comment]
> Did this bug appear with version 2.1.5 or did you experience it with the previous versions too?

Yeah, I've been experiencing it ever since last year and I have no idea what is up with it. I even tried updating my drivers and it still doesn't work.

**Comment by callaa** [comment]
I recall seeing something like this being caused by Windows' pen gestures being enabled. The OS would eat the start of each stroke while it was trying to decide whether it was the start of a gesture.

**Comment by slammoooo** [comment]
I believe I just disabled it, and restarted my computer, but it didn't seem to work also.

**Comment by Nattdal** [comment]
Same exact thing happens for me too, and has been for a few months.  
Other art programs work perfectly fine.

I noticed that it's not just the strokes that do this, but when I try to adjust sliders, pick a colour, or do _anything_ really, drawpile will freeze for a moment and only after that will it do what I want it to do. If I use the mouse however, drawpile does **not** freeze at all. ![drawpile_2019-04-08_16-59-39](https://user-images.githubusercontent.com/49406142/55734737-65824400-5a20-11e9-92b8-d4aed931f5d0.png)

**Comment by callaa** [comment]
Here's a new build of version 2.1.6 that solves some tablet related problems for some users: https://drawpile.net/files/win/drawpile-2.1.6-tablettest.zip

However, if you've had this problem for a long time, I'm not sure whether this new build will fix it.

**Comment by notfood** [comment]
Stale, closing. Tablet handling has changed since then, please try again. If you're still experiencing the issue feel free to re-open it.
