### ISSUE TITLE
weird drawing glitch??

### ISSUE THREAD

**Issue by sonitheking** [drawpile/Drawpile#730]
![Screenshot_71](https://user-images.githubusercontent.com/49143557/55309288-f3f43580-5422-11e9-9eaa-929ec9e21dc8.png)
im usually a quick doodler/sketcher, but now in this new update when i try to draw, these weird thick lines happen. and if i doing a down stroke, an icon saying "scroll down" comes up, and my canvas scrolls down...?? can this be fixed?? it isnt my tablet, i checked on several other art programs, this doesnt happen. thanks.

**Comment by callaa** [comment]
Version 2.1.5 on Windows is broken. Try this test build: https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test2.zip
