### ISSUE TITLE
Scrubby Zoom feature for Zoom tool.

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#731]
Hi,

I mentioned this idea thinking in a solution for this issue:
https://github.com/drawpile/Drawpile/issues/717

Right now I think it deserves its own analysis, scoping the functionality just for current Zoom tool that is accessible through the Drawings Tools Menu (don't thinking about the other ways to zoom in)

![image](https://user-images.githubusercontent.com/3485891/55358340-63523f80-548c-11e9-8c62-7b3765666749.png)

**Scrubby Zoom** is a feature from Photoshop, where the left-click and drag to the right is to zoom in, and drag to the left to zoom out (it even maintains the normal click to just zoom in a step forward)

Here you can found a better explanation of the process:
https://www.designeasy.co/2013/11/what-is-doing-scrubby-zoom-in-photoshop.html

And here you can see it working in a video:
https://www.youtube.com/watch?v=gVAonIw55Tc

Why it is a good option?:
- Considering that the main target of Drawpile's users have a pen to draw (no matter display or pen tablet), it is not very comfortable to use in a regular basis this 2 buttons (because you need to readjust your grabing over the pen a little bit each time).
![image](https://user-images.githubusercontent.com/3485891/55358154-efb03280-548b-11e9-97d8-e89751e7a04c.png)
- With the current tool you can **zoom in** a selected area, avoiding to make a lot of clicks with the pen (or you can just touch the tablet surface with the pen several times, without change the fingers position, maintaining the drawing grab in the pen):
![image](https://user-images.githubusercontent.com/3485891/55358614-0f942600-548d-11e9-8df3-5e2fe6b11ea3.png)

![image](https://user-images.githubusercontent.com/3485891/55358624-1884f780-548d-11e9-8106-29f030bc0c75.png)

- The problem comes with the **zoom out** , because you need to click several times this button from the pen, which involves change the hand drawing position over the pen (that usually, depending on the grabbing technique, leave those buttons more up the fingers)
![image](https://user-images.githubusercontent.com/3485891/55358915-cc868280-548d-11e9-9bf7-00207f5d8533.png)

(one grabbing technique)
![image](https://user-images.githubusercontent.com/3485891/55359190-782fd280-548e-11e9-9147-64cc1cac26bd.png)

- It leaves the zoom proportions and percentage to the hand natural movement (you can still move vertically the dragging, because that movement doesn't affect the result), considering the actual canvas view, achieving in real time the "this is the exactly image zoom I want" in an intuitive way.

- Scrubby Zoom can be an option in the actual tool, in case people want the classic way to zoom in or out.

Regards

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming with Drawpile 2.2. You can define a canvas shortcut that will zoom by scrubbing, with the option to scrub vertically or horizontally.

![image](https://user-images.githubusercontent.com/13625824/227438762-2ff54c9c-a0e8-45e3-9b36-b9a5101c4c86.png)
