### ISSUE TITLE
NSFM Layers and Parental Controls

### ISSUE THREAD

**Issue by Wade821** [drawpile/Drawpile#734]
I have some ideas for the NSFM censor layer feature, but in order to make that idea work, this also means that there must be additional updates to the NSFM sessions options in parental controls. So I'll present that idea first. 

```
NSFM Sesssions: 	- Unrestricted
				- Automatically uncensor NSFM layers in SFW rooms
			- Hide NSFM Sessions from Listings
				- Block layer uncensoring
				- Disallow joining NSFM sessions
				- Disallow joining SFM sessions with censored layers
				- Disconnect from SFM session when censored layer is added
				- Disconnect from SFM session when updated as NSFM
				- Temporarily allow listing and joining NSFM sessions with parental password verification
```

I tabulated the list as the options underneath should be more checkboxes than separate options, as this would then presumably allow for the combining of multiple parental type controls. Not seeing a listing wouldn't prevent a direct link from being shared, is the idea. Perhaps the computer is shared with a younger sibling, for example. 

I also presume that "Disconnect when tagged as NSFM" would allow a user to still attempt connecting  to a NSFM session and I don't see as much use for it being a separate option. I do see it being useful however if a SFW session suddenly becomes NSFM. 

----------------------------------------------------------------------------------

I feel as it stands the NSFM censor layer approach is somewhat limited in usefulness given that the 18+ content must be drawn first, because applying the censor locks the layer from being able to be drawn on. I think perhaps a better way to implement it's use is the following (given that rules being applied are all client side anyway).

Censored layers appear to a user based on the user's preferences under Edit, Parental Controls. With a NSFM unrestricted saved setting, these layers will not be censored by default when a user joins NSFM room using these layers (although I would expect these cases to be rare). In a SFM room, all censored layers are censored to all users by default, unless an option (to be added in parental controls) is checked to "Automatically uncensor NSFM layers in SFM rooms". Users can, provided they aren't restricted by parental controls, uncensor a layer by right clicking a layer to see and edit the layer as appropriate. I don't think restricting the ability to mark a layer as censored has any real benefit as it currently stands, so that option should be allowable regardless of settings. I would rename that option to "NSFM censored" in order to clarify its purpose. People will break rules I suppose, given the chance. 

With a Parental Control setting using anything else other than "unrestricted", the layers are censored as appropriate and locked from being drawn on accidentally. This allows the setting to exist and be more useful for mixed content rooms.

**Comment by callaa** [comment]
> I also presume that "Disconnect when tagged as NSFM" would allow a user to still attempt connecting to a NSFM session

No, the restrictions add up. The "Block layer uncensoring" option disables the "Show censored layers" option from the Layers menu.

Adding a "Disallow joining SFM sessions with censored layers" would require the addition of a "contains censored content" flag to the the sessions metadata, which would have to be set by the client.

> given that the 18+ content must be drawn first, because applying the censor locks the layer from being able to be drawn on. 

Not true, you can draw on censored layers just fine as long as you have "show censored layers" option selected. This layer flag allows you to set the flag *first*, before drawing anything, without having to remember to maintain a maintain a separate censor layer manually.

**Comment by Wade821** [comment]
I see. It just isn't apparent to me I guess since they're separate options and you can only click one at a time. And I missed the option of it being in the layers menu, I guess because I'm so used to right clicking the layer or the padlock in the layers dock that it never occurred to me to check up there for some reason. I guess there's no reason to really implement it in this way unless there's something about this idea/suggestion you like. I swear I spent a lot of time trying to think about it and put this together. I just... missed that option in the sub menu.

**Comment by Wade821** [comment]
So I guess I'll close the issue out then. :)
