### ISSUE TITLE
Full Screen mode: option to not hide status bar under chatbox

### ISSUE THREAD

**Issue by liziaa** [drawpile/Drawpile#735]
![Snipaste_2019-04-02_21-39-23](https://user-images.githubusercontent.com/48847128/55406526-e065dd80-558e-11e9-9255-e2b26bd3a5bf.png)

The status bar under chatbox is include some useful info and tool, which is better not hide it on full screen mode.

- Session history value
- Session connected status(online or offline)
- Session code
- Session address
- Flip tool and mirror tool
- Rotation tool

The bottom status bar in mypaint and krita also both aren't hiden under full screen mode.
![Snipaste_2019-04-02_21-39-51](https://user-images.githubusercontent.com/48847128/55406279-62a1d200-558e-11e9-8f62-429051bf9f5b.png)

**Comment by callaa** [comment]
Yes, I suppose it would be more consistent if the status bar hiding/showing was part of the Tab shortcut instead, since it hides and shows the toolbar too.
