### ISSUE TITLE
Tapping with graphics tablet pen ignores pressure sensitivity

### ISSUE THREAD

**Issue by chippledipple** [drawpile/Drawpile#736]
For some reason, any quick tap preformed with my graphics tablet ignores pressure sensitivity and fills in the brush completely. Pressure sensitivity functions perfectly well in any other situation. It seems like the input is being recognized as a click but any tablet settings or Windows settings related to that are disabled.
[Here's a gif showing what I mean.](https://gfycat.com/JauntyUglyBluefintuna).

I'm running the most recent version of Windows 10 Home build 1809 and Drawpile 2.1.5. My graphics tablet is a Wacom Intuos Pro M running driver update 6.3.33-3 (most recent as of now)
So far here's what i've found:

- This issue doesn't occur in Photoshop or any other program that uses Wintab/Windows Ink, it's completely specific to Drawpile
- Disabling Windows Ink in my tablet settings isn't a solution because doing so disables pressure sensitivity altogether 
- Enabling the relative pen mode hack in Preferences doesn't do anything
- Disabling the flicks in Pen & Touch settings doesn't change anything. (Press & hold, double tap, single tap, etc)
- Messing with the settings in Pen & Windows Ink doesn't do anything

I'm stumped. I've tried everything I could think of at this point.

**Comment by mis7a** [comment]
I've been struggling with this too, I don't know what to do but it's impossible to draw on it

**Comment by mis7a** [comment]
i downloaded the tablet fix 2 test, and it worked for me. hopefully this works for you. https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test2.zip

**Comment by JamesDelaneyyy** [comment]
I have this issue too, especially when starting a new stroke, the dot happens, either that, or if I try to deliberately draw a more focused line, the windows ink circle thing pops up and I know I've disabled it too. It didn't happen on the previous build of the 2.1 btw.

**Comment by chippledipple** [comment]
> i downloaded the tablet fix 2 test, and it worked for me. hopefully this works for you. https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test2.zip

This worked for me! I'll use this until they fix it in the official releases. Thanks a million!

**Comment by callaa** [comment]
The new official release is out already.
