### ISSUE TITLE
Pop-up notification for released info seems not working?

### ISSUE THREAD

**Issue by sciicee** [drawpile/Drawpile#737]
Currently, there are 3 ways for people knowing there is a new version of drawpile is available.

- Pop up notification when start the program( only automatic check once per day)
- Check for updates via help menu
- Check official website

I think pop up notifications is the most obvious, convenient and efficient way for users to know the information. Also this is the meaning why we have this pop up notification.

The situation is : i just open drawpile today, but there is no any pop up notification, and i pretty sure i haven't used it for more than 24 hours.
I don't know what is the problem, it just not works here. 
The situation in the other program is : user always can see the pop up notification when start the program each time. also the user can disable it by the help menu like the way in drawpile.

Nice example program: joplin  https://github.com/laurent22/joplin/releases
![Snipaste_2019-04-05_01-16-35](https://user-images.githubusercontent.com/49031545/55575072-93296d80-5740-11e9-854b-7dd5b8a2145e.png)

So i think it's better making drawpile automatic check all the time, which people can see this pop up notification when start it any time.
Is it possible that you can make it work this way?

**Comment by callaa** [comment]
Yes, it's possible to make it pop up every time, but isn't that really annoying?

**Comment by beenyuk** [comment]
Agreed, me and my friend are still using 2.1.4, but we both haven't seen this pop up notification yet.
Looks like it's not easy for user seeing this pop up notification if only automatic check once per day.

**Comment by sciicee** [comment]
> Yes, it's possible to make it pop up every time, but isn't that really annoying?

I don't think it would be annoying, because it only appear this pop-up when there is a available version, isn't it? Also people can disable it via the help menu.

**Comment by erik90mx** [comment]
I agree with that, it is not annoying if it appears only when a new update is ready. It can turn annoying if we continue skip the update, and Drawpile continues asking us minute over minute.

I just tested the update notification feature today with this new version. It works but it doesn't downloads or direct me to the download page to get it (as Joplin does for example).

This is related to this one:
https://github.com/drawpile/Drawpile/issues/708

Regards

**Comment by Wade821** [comment]
This should be fixed for a long while, closing this issue. Please feel free to comment if this issue is still persistent.
