### ISSUE TITLE
Canvas view size didn't immediately fit/sync with the navigator dock in 2.1.5

### ISSUE THREAD

**Issue by beenyuk** [drawpile/Drawpile#739]
![Snipaste_2019-04-05_20-53-34](https://user-images.githubusercontent.com/48846565/55662218-21d2e300-5844-11e9-886a-6c46c8a9dce4.png)
![Snipaste_2019-04-05_20-25-21](https://user-images.githubusercontent.com/48846565/55662248-429b3880-5844-11e9-96da-cc2b806db3f6.png)
Step: 
1. Make the current canvas size to 1700*750
2. Click "new" from the file 
3. Change size to 750*1700

Situation happen in:
1. Change the current canvas size via "new"
2. When joining a session

None of these issues happened in 2.0.11.

**Comment by callaa** [comment]
This is now fixed.
