### ISSUE TITLE
Packaging question: do I enable kis by default?

### ISSUE THREAD

**Issue by fgaz** [drawpile/Drawpile#744]
I'm restructuring the drawpile NixOS package, and I'm wondering if kis should be enabled by default or not

**Comment by fgaz** [comment]
I see that you used to enable it in the appimage build but stopped doing so in [the flatpak one](https://github.com/flathub/net.drawpile.drawpile/blob/2ff6b3216033663d83bbe7466b0be3a51816b7d8/net.drawpile.drawpile.yaml)

**Comment by callaa** [comment]
It depends on which Qt version you're using. If it's something recent, Qt's own tablet handing should work well enough. Krita is no longer using the modified event handler either.

**Comment by fgaz** [comment]
Nice, thanks for the info!
