### ISSUE TITLE
Sign up email not received 

### ISSUE THREAD

**Issue by vdsdf** [drawpile/Drawpile#746]
Im new to drawpile and i want to sign up, but the email never shows up. Ive tried countless emails, but the link just wont send.

**Comment by callaa** [comment]
This issue is more related to the website, but I'll answer here. Have you checked your spam box? The messages sent by the server often get flagged by spam filters.

**Comment by Wade821** [comment]
Has your issue been resolved? Please let us know so we can close the issue or proceed forward with assisting you.

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by notfood** [comment]
Stale, closing.

**Comment by tuxutku** [comment]
Outlook seem to block it outright, I've tried with two different outlook accounts (checked spam folder and everything) none worked, gmail works though (goes to spam)

**Comment by Wade821** [comment]
@tuxutku yeah, nothing that can be done about that I believe without paying money to use a more well known email provider. Right now the way it is sent, it looks rather spammy so they tend to get outright blocked/deleted before it even arrives.
