### ISSUE TITLE
Missing the ability to zoom in and out with UI buttons

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#749]
I guess you don't notice what you had till it's gone, right? Ever since the UI update I've been floundering without the ability to zoom in and out with a button click. Going to the keyboard takes my head out of whatever I'm working on, and the zoom slider can't go out past 50%. I know they're ugly and crowd out the app, but I wish there was a setting I could tick in the preferences so that I could have my ugly UI extras and everyone else could have a clean look.

**Comment by callaa** [comment]
In the upcoming version, the zoom slider now goes all the way down to whatever value is needed to show the whole canvas. Will this satisfy your use case, or are the buttons still preferable?

**Comment by ParisGreen** [comment]
The new zoom is a huge improvement, and way less frustrating that being capped at 50%. Although I can still imagine a couple of edge cases where zooming out even further than new slider caps at, the current method no longer feels like I'm stumbling to work around it, good stuff.
