### ISSUE TITLE
Partial canvas reset

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#750]
Are you able to replicate an undo system relative to flockmod??
its pretty hard to recover stuff unless you're actively saving the drawpile and copy pasting what was lost

**Comment by callaa** [comment]
I've never used flockmod. How does undo work in it?

**Comment by Nujiao** [comment]
It works by save states and allows a milestone based recovery for the entire canvas in order to return the canvas WITH the option of selection, I believe the Reset feature is similar enough but I do not like the fact that it is based off of seconds and deletes the previous states as well.

![ezgif-3-325916402bcb](https://user-images.githubusercontent.com/39990590/57169096-d1af5800-6dd2-11e9-827f-dae0f54d3708.gif)

**Comment by neiriod** [comment]
> I've never used flockmod. How does undo work in it?

Here is a more detailed description i found in its home page.
![Snipaste_2019-05-04_09-25-13](https://user-images.githubusercontent.com/49644585/57172130-8cc90700-6e4e-11e9-92a5-294e77c9ff30.png)
![Snipaste_2019-05-04_09-24-51](https://user-images.githubusercontent.com/49644585/57172195-2f818580-6e4f-11e9-81e1-5c228c225f4b.png)


After a quick try, i think its best advantage is that it can reset to very old history image without keep manually saving the canvas as file, which this is very helpful to recover the damage. And it has partial reset function.

In drawpile, reset is very limited. If you want to reset to old history image (such like couple mins ago), then you have to keep manually saving the canvas as file.

**Comment by Nujiao** [comment]
> In drawpile, reset is very limited. If you want to reset to old history image (such like couple mins ago), then you have to keep manually saving the canvas as file.

exactly, its pretty painful not having any ability to recover

**Comment by callaa** [comment]
Thank you, that description helped.
It seems like with the new version 2.1.8, some of those features are now here. Using the reset dialog no longer clears out the reset history, and the history is now always kept for the past minute. (I'll probably make this adjustable later)

That partial reset tool is something I've actually been planning for a long time now, just haven't gotten around to implementing it.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented since a while.
