### ISSUE TITLE
Show zoom level in Full Screen mode (without docks)

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#751]
Hi,

When you are in a blank canvas, and switch to full screen mode, it is very easy to loss the scale perception (due the lack of drawings to track the size), so you end up drawing in a very different scale that you pretended at first.

Krita manages this issue, creating a floating notification that disappears in short, each time you zoom in or out.
![image](https://user-images.githubusercontent.com/3485891/57059038-e546ab80-6c78-11e9-85cf-942fbbeaa50e.png)

Regards

**Comment by askmeaboutlo0m** [comment]
This has been implemented. It's available in [the continuous development release](https://github.com/drawpile/Drawpile/releases/tag/continuous) and will also be included into Drawpile 2.2 beta 6.
