### ISSUE TITLE
Please make NSFW sessions choose unrestricted by default

### ISSUE THREAD

**Issue by ckodx** [drawpile/Drawpile#753]
![Snipaste_2019-04-13_22-11-34](https://user-images.githubusercontent.com/49644344/57109020-f53cb900-6d66-11e9-9c16-b3799598d3e7.png)

Recently, i introduced drawpile to a couple of friends. This is all their first time to use drawpile.
And i just host a nsfw room, but end up they all can't finding my room, which i find out the reason is they all can't select the NSFW filter option in the join page.

So i realize what's the problem here.
The lay out change is making the NSFW session hidden note no longer showing, turn to NSFW filter option instead. That is why my friends all can't select it, also i have to tell them to choose "unrestricted" via the preferences, in order to enable this NSFW filter option .

In 2.0.11, the nsfw session is hidden, but at least there is a note on lower left corner. The nsfw session can be showing by click the note on the join page.
Cuz i start use drawpile since 2.0 series and drawpile will remember the selection, that is why i can select NSFW filter option even update to 2.1 series.

In 2.1.7, if peope on the first time to using drawpile, most of them don't know why that NSFW filter option can't be selected, not mention they don't know where to enable this option, and then they would though:
a. " maybe that NSFW filter option is unusable" then they will just leave it there and never find out all the nsfw sessions.
b."why that NSFW filter option can't be selected? what should i do ?" then they have to spend more time to figure out what is the problem is it and  how to solve it.
c. " who should i ask for help?"
(Also in this past two weeks, in drawpile's discord server, i notice there are at least three people ask for help about why this nsfw filter option can't be selected.)

Making the nsfw seesion choose "hide  from listings" by default only creates more explanation to the person experiencing drawpile for the first time and making people cost more time solve the problem out.

**Comment by callaa** [comment]
Done. This was an oversight. When I added the filtering option directly to the dialog, I had forgotten the default PC level was "hide NSFW sessions" and not unrestricted.
