### ISSUE TITLE
Feature idea: annotation borders

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#754]
In addition to background colors, annotations could have decorative borders too. There is a field reserved for a border type in the protocol already, but I haven't actually implemented any yet. Some basic border types might be ellipse and (rounded) rectangle:

![image](https://user-images.githubusercontent.com/464576/57157182-a9325880-6de8-11e9-96b4-d52834a0e2be.png)

Does anyone have more ideas? Without any other change, there are some limitations:

 * No way to adjust the border thickness
 * No way to adjust the border color separately from the text color

These are not hard limitations. I can always change the protocol to add a border color field, for example.

**Comment by notfood** [comment]
What're the benefits from just using elipse or rectangle tool? Just the aligment? Seems not so useful with many drawbacks compared to the other tools.

A client only ruler feature to align tools would achieve the alignment.

The rectangle tool could benefit a lot from a round corners size.

**Comment by callaa** [comment]
The advantage would be that you don't have to draw the borders manually and the borders are part of the annotation so they'll move with it if you move it.

As to how useful it is, that's what I'm interested in finding out. *Would* this feature be useful?

**Comment by notfood** [comment]
Such feature would be useful in situations where you need to draw a quick flow diagram where the pieces need to move all together. In that scenario, more shapes would be useful. Moveable vector lines/arcs would aid a lot there. Even "image objects" that point to a resource that you can move around but belong to the same type as text/vector.

It'd be useful for the technical crowd. The artistic crowd would prefer to beautify their squares themselves and leave them in place.

**Comment by Wade821** [comment]
I don't know that it is specifically just technical folk that would find it useful. Fair bit of people RP and for some, I imagine it's easier to type than to hand write out dialogue between characters. I think having the option is certainly useful anyway. 

If it's not too hard though, I would suggest making the color and thickness changeable. You know someone will want the ability to do so on the fly and ask for it as a feature. That's just my assumption though.
