### ISSUE TITLE
Can't find or connect to server

### ISSUE THREAD

**Issue by volpex** [drawpile/Drawpile#756]
I can't find my friend's password protected session on the list you see when you click join in Drawpile. My friends are very much online (and no they haven't blocked me - they are as puzzled as I am), I can see the server listed on the drawpile website, but when I try to join through _that_ it merely opens the drawpile program's join list, which again does _not_ show the session. Even though I know it should be there. 

The only way I can see the session listed is if I hit join drawpile.net, which pops up another list of sessions. There I can at least see the session listed but it's greyed out and has a question mark and a little x next to it and I can't join it. (Boy would it be nice if the website mentioned what this means)

I used to be able to join without a problem, without changing a thing, but I'm guessing something changed since I had to do a clean install of my OS. I have no idea what it could be. Open NAT did nothing, flushing DNS did nothing. Googling furiously did not turn up anything useful for me. So, I could use some help, please.

(Note: I am a network noob so it's best if you explain thoroughly rather than reply with some series of three letters and assume I know what it means)

**Comment by callaa** [comment]
Sounds like you're using a different version than your friend. (Either you're using 2.0.x and they're using 2.1.x or the other way around.)
The question mark means the session is not compatible with the client. If you hover the mouse over it for a while, there should be a tooltip.

**Comment by volpex** [comment]
Thank you so much callaa! I'll check it out and ask my friends about the version they're using.

**Comment by Wade821** [comment]
Any updates on this so we can close or proceed with addressing this issue?

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by notfood** [comment]
Stale, closing.
