### ISSUE TITLE
I can't make or see any servers

### ISSUE THREAD

**Issue by Yabafish** [drawpile/Drawpile#757]
Yesterday my friends were having trouble connecting to my new server because it was taking too long to catch up, and when it did they could talk but couldn't see the canvas and their username was something like "user 1". We could join other servers just fine. So another friend tried hosting but we all still had the same problem and decided to try again tomorrow.

I went on drawpile to test if it was fixed but when i went to join a session this popped up:
![image](https://user-images.githubusercontent.com/50483571/57518359-2f581d00-735c-11e9-9ffd-73938c3f5f98.png)
When I tried to host a session a message saying "could not connect to server connection refused" popped up. It was working fine 4 days ago. Any ideas?

**Comment by callaa** [comment]
This is now fixed. The server had run out of disk space and locked up.
