### ISSUE TITLE
Support copy from chat with platform's usual keyboard accellerators

### ISSUE THREAD

**Issue by GreenReaper** [drawpile/Drawpile#758]
I expected to be able to copy from other people's chat by highlighting their message and pressing Ctrl+C on Windows. While there *is* a context menu item for copying text, and it works, it does not have an accelerator; pressing the key combination does nothing (but it works as expected in the input box).

In the wider context: I was trying to translate some foreign-language text. So an inbuilt translation would be extra cool, but just making it easier to select and copy would be a good start. 😸

**Comment by callaa** [comment]
This is now fixed.
