### ISSUE TITLE
Long /pin messages break the window resolution.

### ISSUE THREAD

**Issue by toadlinerico** [drawpile/Drawpile#759]
![image](https://user-images.githubusercontent.com/50619481/57689153-27f78300-767e-11e9-9da7-b663c878a62a.png)

no clue how Github works but i thought i'd report this, i'll reupload the image if it doesnt work. making a huge /pin message can mess with the size of the window. the screenshot is of the whole window as it appears on my screen (my laptop is 1366x768) and i can move the window to see that it's been elongated. not really a huge problem but a little issue nonetheless.

**Comment by callaa** [comment]
Confirmed. Thanks for reporting!

**Comment by callaa** [comment]
This is now fixed. The fix will be part of the 2.1.9 release.
