### ISSUE TITLE
no  pressure sensitivity on my veikk tablet

### ISSUE THREAD

**Issue by jononathan** [drawpile/Drawpile#761]
i tried everything restarting , fiddling with the settings , restarting the tablet and it still wont work and i dont know why please help

**Comment by callaa** [comment]
This is under Windows, I assume? Can you try if your tablet works in Krita? Drawpile uses code from Krita for its tablet support, so if it works there, it should be possible to get it working in Drawpile too somehow.

**Comment by Wade821** [comment]
Any updates on this? Let us know if you've tried those things, you can get Krita for free here.
https://krita.org

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by jononathan** [comment]
Ive used kritia before and the pressure works and it works on all art
programs judt not drawpile which is really weird

**Comment by Wade821** [comment]
Fixed with user on Discord. User updated Drawpile, Enabled Windows Ink in Drawpile and within tablet to get pen pressure.
