### ISSUE TITLE
Smallest Chat Ever

### ISSUE THREAD

**Issue by RobotCat438** [drawpile/Drawpile#762]
Literally my chat is so small I cannot even read anything at all. I don't know how to fix it maybe I'm an idiot but I installed the newest update just before I got into a room.
Here is a pic of the smallest chat u've ever seen
![Screenshot (1)](https://user-images.githubusercontent.com/50889681/58132210-b6c04e80-7bee-11e9-8951-05f665c4450b.png)

**Comment by callaa** [comment]
Does the tiny font persist in new windows? If not, then most likely you accidentally zoomed it out. The chat scale can be adjusted by holding ctrl and scrolling with the mouse wheel.

**Comment by RobotCat438** [comment]
Oh my gosh thank u. It turns out I am actually just an idiot I didn't even think of that
