### ISSUE TITLE
Pen pressure not working

### ISSUE THREAD

**Issue by TigerMC** [drawpile/Drawpile#764]
Just updated to 2,1,9 and the pressure isn't working, not even recognized in the tester

![image](https://user-images.githubusercontent.com/47946599/58193318-65d25800-7ccb-11e9-9952-7231c678b40a.png)

**Comment by callaa** [comment]
Which version did you update from? Have you tried unchecking or checking the Windows Ink mode in the settings dialog?

**Comment by TigerMC** [comment]
Yes, sorry for the late reply and the bother, I did exactly that and it solved it. Thank you for your time and response tho <3
