### ISSUE TITLE
How to I make my remote server persistent?

### ISSUE THREAD

**Issue by gre1337** [drawpile/Drawpile#767]
Hi I'm trying to set up a drawpile sessions hosted by a remote server I own (on Digital Ocean). My goal is to have it running all the time, even when no users are hosting it.

So, I've gotten the server working. But obviously as soon as that last person leaves, the console mentions it's inpersistence, and shuts it down. 

I've read some stuff about config files & databases in the guide on the website, but I don't understand how to make use of those.

Anyone know how to do this?

**Comment by callaa** [comment]
Session persistence is disabled by default, you need a configuration file to enable it. Simplest is just:

    persistence = true

and then you launch the server like `drawpile-srv -c myconfigfile.cfg`

Another option is to use the configuration database like `drawpile-srv -d myconfig.db`
In that case, you must also enable the web admin feature and configure the server using the remote admin tool. (I'm currently working on the web-admin frontend that can be installed on the server and accessed with a browser.)

**Comment by Wade821** [comment]
Have you solved your issue? If not, can you provide more information on how your server is set up? Like if you're using Docker in Linux... or even basic info like the operating system your server is using.

**Comment by notfood** [comment]
Stale, support issue, no response from submitter, closing.
