### ISSUE TITLE
Crashed session, and after rejoining; Canvas is gone.

### ISSUE THREAD

**Issue by Merleawe** [drawpile/Drawpile#769]
I crashed when attempting to save a live session I was hosting. But when I rejoined, it seemingly loaded everything up... but the canvas wasn't there. No one else but me had this problem- Everyone else rejoined the session just fine.

I tried restarting my computer, but no avail. All I can do is chat with people on this session.
![Drawpileglitch](https://user-images.githubusercontent.com/17037623/58847416-49ce9f00-8659-11e9-9a4e-63d71c25748a.png)

**Comment by Topodic** [comment]
I've had this issue before. For me, I'm pretty sure it was occurring because I had Drawpile located in Program Files but wasn't running the server as administrator, so it couldn't cache the canvas.

**Comment by callaa** [comment]
Are you running the latest version?

**Comment by Merleawe** [comment]
> Are you running the latest version?

Yes I am. But I think my issue may be what Topodic mentioned... it was probably just the administrator permissions. I didn't run it as administrator; I didn't think to since the program didn't ask. So i'll try running it as administrator from now on.

**Comment by callaa** [comment]
Running as administrator shouldn't have any effect, though. The latest version (2.1.10) fixes one bug that can cause this effect, but it seems there is at least one more. When joining the session, try enabling recording. (The button next to the server text box in the join dialog.) If the problem happens again, the recording might offer a clue as to what's causing it.

**Comment by Merleawe** [comment]
> Running as administrator shouldn't have any effect, though. The latest version (2.1.10) fixes one bug that can cause this effect, but it seems there is at least one more. When joining the session, try enabling recording. (The button next to the server text box in the join dialog.) If the problem happens again, the recording might offer a clue as to what's causing it.

Alright! I'll keep a lookout and see if it occurs again for me.

**Comment by Merleawe** [comment]
> Running as administrator shouldn't have any effect, though. The latest version (2.1.10) fixes one bug that can cause this effect, but it seems there is at least one more. When joining the session, try enabling recording. (The button next to the server text box in the join dialog.) If the problem happens again, the recording might offer a clue as to what's causing it.



> Are you running the latest version?

I decided to double check to see if I was running the latest version; and apparently I might not be. I thought I updated it the second the update came out may 30th- but perhaps for whastever reason i'm still on the old version. I'll re-install and see if it ever happens to me again.

**Comment by callaa** [comment]
You can check your version from the About dialog, and also from the *Check for updates* action in the *Help* menu.

I'll close this issue for now, but let me know if the bug happens again.
