### ISSUE TITLE
weird pressure issue with newest version of drawpile

### ISSUE THREAD

**Issue by wandaboy** [drawpile/Drawpile#770]
![adadasdgsdfg](https://user-images.githubusercontent.com/50892723/58853280-8648cd80-864e-11e9-9166-0a55e33c4985.png) 
got a weird issue with drawpile, tryd unistalling and reinstalling. other programs work fine with my cintiq.

**Comment by callaa** [comment]
Since you didn't state which OS you're using, I assume you're using Windows.

First, check the pressure curve in the input dock. If that looks OK, try with windows ink enabled or disabled (settings dialog.)

**Comment by Wade821** [comment]
> ![adadasdgsdfg](https://user-images.githubusercontent.com/50892723/58853280-8648cd80-864e-11e9-9166-0a55e33c4985.png)
> got a weird issue with drawpile, tryd unistalling and reinstalling. other programs work fine with my cintiq.

Please provide an update if your issue was solved or not, so this can be closed or the issue addressed further as needed.

**Comment by Wade821** [comment]
**I haven't gotten a response within 7 days. I'm going to close out your issue.**

If this is still a problem, please comment so we can reopen this issue.
