### ISSUE TITLE
Pen Pressure Not Working

### ISSUE THREAD

**Issue by OoNekoPandaoO** [drawpile/Drawpile#771]
I use the Mac version of Drawpile and my tablet works fine for my other programs, but for some reason, I lose pen pressure in only Drawpile. It doesn't show in the tester either. ![Screen Shot 2019-06-05 at 12 01 54 AM](https://user-images.githubusercontent.com/28431224/58929470-283ae980-8725-11e9-8056-58def5ba58ef.png)

**Comment by notfood** [comment]
Still having this issue?

**Comment by OoNekoPandaoO** [comment]
Unfortunately yes. I've upgraded to the newest version, too, but still do not have pen pressure and I'm not sure why.

**Comment by notfood** [comment]
Can you show the pressure curve in the Input dock and also your brush settings?

**Comment by notfood** [comment]
Is tablet tester still saying that your tablet is a mouse? Can you set your tablet to absolute mode in the wacom tablet settings?

**Comment by ch98-1** [comment]
It might be permission problems with newer version of mac OS like Catalina. When running from command line by doing "/Applications/Drawpile.app/Contents/MacOS/Drawpile", it detects the pressure. This problem and the workaround seem to be common for various other open source media software like audacity and OBS as apple wants all software to be notarized now.

**Comment by OoNekoPandaoO** [comment]
Srry for the late reply, but my tablet's a huion and not a wacom so I'm unsure how to set it to absolute mode (if there's one for huion);; Tho I just did the tablet tester again as I haven't done it in a while, and it says 'Device(0)' now instead of mouse even w/o me doing the absolute mode thing. Idk if this helps tho;;
![Screen Shot 2020-01-20 at 1 57 33 AM](https://user-images.githubusercontent.com/28431224/72705140-9d2e2880-3b28-11ea-95c7-34378e2f9254.png)

**Comment by notfood** [comment]
Drawpile is detecting the pressure, as you can see from the P value. It's most likely that your pressure curve is messed up. Go to View > Docks > Input. And fix your curve.

**Comment by notfood** [comment]
Closing, no response from submitter
