### ISSUE TITLE
Color Erase not working for Eraser

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#772]
I'm not sure which update caused it to stop or if it's just happening to me, but when I try to use the "Color Erase" option for the eraser for any color it does nothing. Somehow it only works with the "Eraser mode" for the brush options (have to put opacity to 100% every time to erase the color completely) but not the eraser itself.

**Comment by callaa** [comment]
The color eraser should be working. Check that you don't have the "pick initial color from layer" button enabled. (It's next to the erase mode button.)

**Comment by vipperz** [comment]
Ah, that was the problem, thank you. It's hard to tell in the dark mode version.
