### ISSUE TITLE
I am not allowed to host a room

### ISSUE THREAD

**Issue by ReeceUlf** [drawpile/Drawpile#773]
I hosted for hours earlier today and now I'm getting the error that I "Can't join the room because it's full" when I am _making_ a room.

**Comment by callaa** [comment]
If you're trying to create a new session, the message you're seeing is "Server is full." This means that there is no more room for more sessions. The server has a limited capacity and when this limit is reached, no more sessions can be created. You can wait for space to free up or host a session on another server or set up your own server.
