### ISSUE TITLE
fullscreen stuck

### ISSUE THREAD

**Issue by ryokotedeschi** [drawpile/Drawpile#774]
Cannot get out of fullscreen without closing program. menu bar doesn't come up when leaving mouse at top of screen. f-key shortcuts do nothing. windows 7, latest version of drawpile.

**Comment by Wade821** [comment]
When you say the latest version of Drawpile, it would be preferable to get an actual version number. I've had people tell me that and then find they're out of date. In Drawpile, please go to Help, About Drawpile. Latest version is 2.1.10. And pressing F11 should do the trick to make it switch out of full screen mode. I have a machine I can test this on and will try to get back to you on this.

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings.

**Comment by Wade821** [comment]
> Cannot get out of fullscreen without closing program. menu bar doesn't come up when leaving mouse at top of screen. f-key shortcuts do nothing. windows 7, latest version of drawpile.

I tested this in Windows 7 64 bit with Drawpile 2.1.10, both offline and online. Tested with the "View", "Full Screen" option as well as F11. Both options work correctly. So I doubt this is a bug. Sometimes I've seen issues that were fixed simply by downloading and reinstalling the program. Please let me know if you've tried this and get back to me. :)

**Comment by notfood** [comment]
Stale, closing.
