### ISSUE TITLE
UI bug: can't rotate selection without hack

### ISSUE THREAD

**Issue by deliciouslytyped** [drawpile/Drawpile#776]
I'm on kde plasma if that matters,
I can only rotate selections by doing alt-shift, click+drag (this is skew mode), release-shift : after that sequence I will be able to rotate the selection till I release the mouse.

**Comment by callaa** [comment]
Do you happen to have the window action modifier key (system settings -> window management -> Window behavior -> Window actions) set to Alt? I always change this to Meta, because Alt+drag is used in many graphical applications, including Gimp and Blender.

**Comment by deliciouslytyped** [comment]
Sounds probable. Will check later.

**Comment by deliciouslytyped** [comment]
Ok this is a life changing fix. It works. ~~Who do I send hate mail to.~~

**Comment by deliciouslytyped** [comment]
It would be nice if there was a way to rebind everything, and on the side, some solution to this other than having to search github.

**Comment by deliciouslytyped** [comment]
It would be nice if there was a way to rebind everything, and on the side, some solution to this other than having to search github.

**Comment by callaa** [comment]
What would you rebind the keys to?

Also, what do you suggest could be done? As far as I know, this issue is peculiar to KDE, because for some reason it defaults to Alt as the window drag modifier, and the problem affects all applications equally.

**Comment by notfood** [comment]
You can rebind the modifier keys with the new **Canvas Shortcuts** feature.

**Comment by deliciouslytyped** [comment]
Thanks for working on this!
