### ISSUE TITLE
UX: Inconsistent undo behaviour

### ISSUE THREAD

**Issue by deliciouslytyped** [drawpile/Drawpile#779]
Sometimes you get more undo sometimes you get less.
Might have to do with server traffic. No idea.
I'm not even sure its an amount of undo's problem but its pretty annoying.
Do not have a reproducer.

**Comment by callaa** [comment]
What do you mean by sometimes getting more and sometimes less?

Do you mean the depth of the undo stack or the number of things undone by a single ctrl+z action?

**Comment by deliciouslytyped** [comment]
I think just the depth of the stack.

**Comment by callaa** [comment]
Undo stack depth is presently limited to 30 actions (by all users.) This number is largely arbitrary, a bigger one might be better, but I haven't done any testing to figure out. The depth of the undo stack is a tradeoff: the deeper the stack is, more actions must be reverted and replayed when something near the end is undone.

For example: One user draws a dab on the canvas, then does nothing while other users continue to paint. The user then presses ctrl-z. If the stack depth is not limited, this might mean several minutes worth of drawing would have to be replayed, leading to poor performance for everyone. So, to avoid this situation, the depth is capped.

**Comment by deliciouslytyped** [comment]
Ok that's kind of horrible. I guess I can think about this when I have more time. Maybe something can be done with a different data structure but I wouldn't know - and a deep redesign would be :(

**Comment by callaa** [comment]
Sorry, this was the best implementation I could manage.

I suppose a dependency graph could be used to separate concurrent editing actions to allow partial canvas updates instead of a complete replay, but this would be very complicated compared to the brute force "rollback and replay" way it works now. Also, as the undo stack grows deeper, the likelihood of later actions being causally dependent on some very much earlier, but still undoable, action increases, so the more clever scheme would just devolve back into "rollback and replay" anyway.

**Comment by deliciouslytyped** [comment]
I didn't mean anything directed at you with the "that's kind of horrible" comment. It is what it is and I didn't think about it too hard.

**Comment by deliciouslytyped** [comment]
I think different users should have different undo stacks, at least conceptually.

**Comment by callaa** [comment]
I would say that conceptually, each user has a different undo stack, it's just that it's implemented as a big global undo stack. I've written an explanation of how the undo system works [on the wiki](https://github.com/drawpile/Drawpile/wiki/How-Drawpile-works#undo)

**Comment by deliciouslytyped** [comment]
Cool, I'll check that out. Thanks.

**Comment by notfood** [comment]
This is a limitation of the implementation and known issue. Undo stack is reduced the more users are using it simultaneously.
