### ISSUE TITLE
UX: Chat continuing to capturing key strokes when trying to draw is annoying

### ISSUE THREAD

**Issue by deliciouslytyped** [drawpile/Drawpile#780]
Sometimes after writing some messages you want to go back to drawing, but then your hotkeys aren't working - oh you have to click on the canvas again (with mouse specifically, as far as I can tell).
This gets rather annoying.

The mouse behaviour is already "correct", just tablet usage doesn't trigger the context switch.

it's nice to be able to keep typing in the chat - but most of the time having your hotkeys is what you'd rather want, I think. It appears that there is already a hotkey for switching to the chat, namely "Alt-C", but that tells me there's some kind of conflict, even though I don't see anything else bound to it in my settings.

**Comment by callaa** [comment]
I believe this is a bug in Qt. Krita devs have a fix that's awaiting merge upstream: https://codereview.qt-project.org/c/qt/qtbase/+/255384

**Comment by deliciouslytyped** [comment]
Any rough idea how long those take / could we do a local patch temporarily?

**Comment by callaa** [comment]
No idea. You can try building Drawpile with `-DKIS_TABLET=ON` but I don't know if it helps with this particular problem.

**Comment by notfood** [comment]
This has been fixed already, I used to experience such under Linux. Feel free to re-open if it's still happening.
