### ISSUE TITLE
Cannot connect or host servers

### ISSUE THREAD

**Issue by 1sugar2spice** [drawpile/Drawpile#781]
Hi! I'm having an issue where it says I cannot connect to the drawpile server or host my own. I've checked my wifi and internet and everything is secure. I'm not sure what the problem is, I can see other people's servers and put in passwords to join, but it gives me an error message and says I don't have internet, when I do.

Thank you!

**Comment by callaa** [comment]
What does the error message say, exactly?

**Comment by 1sugar2spice** [comment]
It simply says: "cannot connect to server" when I try to join someones, and
"Cannot host server, contact drawpile's help website for more details"

**Comment by Wade821** [comment]
> It simply says: "cannot connect to server" when I try to join someones, and "Cannot host server, contact drawpile's help website for more details"

In regards to not being able to host, it sounds to me like this isn't really an issue with Drawpile, and more of an issue with the firewall. 

If you're not able to connect to sessions, and you're using the newest version (verifiable in Drawpile by going to Help, About Drawpile) which is 2.1.10... then it may be that there's an issue where your avatar is the correct size (64 by 64 pixels) but too big in terms of file size. You could try going to Edit, preferences, avatars and removing your avatar... or trying to connect to a session without an avatar. Haven't experienced the issue personally so I can't say off hand, but callaa just helped someone with this issue on the official Drawpile Discord group. He'll update the client I believe to address this possible issue with an appropriate error message. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings.

**Comment by notfood** [comment]
Is this still an issue?
