### ISSUE TITLE
Size issue 

### ISSUE THREAD

**Issue by Nargaia** [drawpile/Drawpile#785]
For some reason, whenever a file/canvas gets too big, I can't move selected images within the canvas or when I try to either view the file or relog into the session. All I can see is a grey screen and resizing the the canvas doesn't help either so I'm completely helpless

**Comment by Wade821** [comment]
Hello! Please provide more information so I can assist you. In Drawpile, go to Help, About Drawpile. Tell me which version you're using, which should be 2.1.11! If not, update first.

Secondly, I need to know if you're using the 32 bit Drawpile or the 64 bit. Doing this is a bit convoluted. We need to know two things to know for sure what you're using. First, we need to know if your operating system is 64 bit. If you're using Windows, use this image link below.
https://cdn.discordapp.com/attachments/546260997703467009/588883724758941706/unknown.png
Refer to this second image for how to tell if you're using the 32 bit Drawpile or 64 bit version. Large canvases would work better in 64 bit Drawpile.
https://cdn.discordapp.com/attachments/546260997703467009/588883861283405873/unknown.png

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by callaa** [comment]
By the canvas getting too big, do you mean big as in having very large dimensions, big as in having lots of layers, or a long history?

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
