### ISSUE TITLE
Feature request: Export with transparency

### ISSUE THREAD

**Issue by temporaryaccount11** [drawpile/Drawpile#786]
Exporting transparent images without white backgrounds

**Comment by Wade821** [comment]
This feature already exists. Go to Edit, Set Background, and set Alpha to 0.

![image](https://user-images.githubusercontent.com/18544575/60219421-357c5d00-9827-11e9-8ac3-c8f58be8dccb.png)

**Comment by callaa** [comment]
Another way is to copy the image to the clipboard using the "copy merged" option, which copies everything visible except the background. Also, when saving as an ORA file, the background is kept in a separate layer. (An ORA file is actually a ZIP file: the individual layers can be found inside as PNG images.)

**Comment by callaa** [comment]
Closing issue due to lack of further comment.
