### ISSUE TITLE
[Flatpak] No file browser and Drawpile locks up

### ISSUE THREAD

**Issue by mrjpaxton** [drawpile/Drawpile#789]
Hey, I have a problem with the Flatpak version of Drawpile. This has been happening since version 2.1.x, and still happens in 2.1.11.

What happens is that when I go to: Edit > Preferences > Avatars

And then I click on the "Add..." button, and there is no file selection menu. In fact, I use CWM (calm window manager) as my primary way to display windows, so I press Super+Tab to switch through my windows, and nothing pops up. Then the app "locks up". I can't press any other buttons, close the preferences pane, or quit the app. I have to send a kill signal like `pkill drawpile` in order to get out of it.

I don't know what is causing this.

Separate, but related issue that might help solve the problem, is that my mouse cursor forcibly moves and centers over to the preferences pane after every, about, two seconds.

I think some of the code there is just bad, I'd imagine.

Will this problem be fixed?

I can send any diagnostics upon request. I am using Debian Unstable (Sid).

My uname:
`Linux pc-main 5.0.0-trunk-amd64 #1 SMP Debian 5.0.2-1~exp1 (2019-03-18) x86_64 GNU/Linux`

**Comment by Wade821** [comment]
Hi, I'm on a limited internet connection right now, so I'm unable to download the unstable Debian to attempt anything special. And my knowledge of Linux is rather centered around Raspbian, as I've written a script to compile Drawpile from source so it works on an ARM processor. 

With those things in mind, I tried to do some testing on my own to see if I could replicate your issue. I attempted this on the systems listed below:

**Debian 9 in VMWare player(uname -a) - Drawpile installed using Flatpak, using QT 5.12.4 per help, about QT in Drawpile**
`Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux`

**Raspbian Stretch on Raspberry Pi 3 (uname -a) - Drawpile compiled from source using QT 5.7.1 with changes to source code per Callaa to make it work**
`Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

I was able to load up an icon, and Drawpile did not freeze on me in either case. I'm also able to do this in Windows 10, 1903 with no issues. 

Thus, I'm tempted to believe there might be something on your end, perhaps something with the unstable Debian distro or this CWM, but as I said before I could be completely incorrect here as well given my limited experience and ability to test it. As such, this is merely some food for thought until Callaa is able to review this issue. Sorry I can't offer more, being on the side of a mountain with limited cellular signal is pretty challenging.

**Comment by callaa** [comment]
Does a file picker appear when you use the file open / save actions? Do other flatpak packaged applications work correctly?

**Comment by mrjpaxton** [comment]
> Does a file picker appear when you use the file open / save actions? Do other flatpak packaged applications work correctly?

Hey,

So it also does not work for file opening and saving. Anything to do with it popping open a file browser window does not work. Strange how the preferences window works, however.

I use KeePassX as a Flatpak, which is also based on Qt I believe. I will test that when I get back home and see if it is working normally.

**Comment by Syberyn** [comment]
Did it ever work again?

**Comment by mrjpaxton** [comment]
> Did it ever work again?

No, not with version 1.4.3. Tried the newest with Flatpak version 1.5.0... same problem.

I still think this is a problem in regards to a combination of Flatpak, and my desktop configuration, because this happens with more Flatpak apps that I use. so I think I will close this, and consider filing a bug upstream.
