### ISSUE TITLE
Drawpile does not have pen preasure when I turn off waccoms "Windows ink"

### ISSUE THREAD

**Issue by DeadOnStudios** [drawpile/Drawpile#796]
I had to turn off "windows ink" in my waccom settings due to it messing up in other art programs,  after the most recent windows 10 update... My pen is registering as a mouse and the eraser end is not working as an eraser either. I do not want to have to turn on and off windows ink to use the program please help. I saw previous posts about there being tablet support and windows ink built into the program but I cant seem to locate that within the program. I have the latest version downloaded and installed about a month ago.

**Comment by Wade821** [comment]
Can you press the Windows key on your keyboard and the letter R at the same time and then release, type in *winver* and hit enter? Please tell me what the version number is for Windows 10. (... , 1803, 1809, 1903)

**Comment by DeadOnStudios** [comment]
1903, I have a wacom cintiq, Drawpile 2.1.11

**Comment by Wade821** [comment]
Heh, I misread something you said earlier. 

You can turn on Windows Ink by going to edit, preferences. Once you turn on Windows Ink in there, you must close all drawpile Windows and re open.

**Comment by DeadOnStudios** [comment]
Ok I just went in there and it is already enabled :(

**Comment by DeadOnStudios** [comment]
it is also reading as a mouse in test
Mouse move X=227 Y=209 B=1
Mouse move X=228 Y=210 B=1
Mouse move X=229 Y=210 B=1
Mouse move X=229 Y=211 B=1
Mouse move X=229 Y=212 B=1
Mouse release

**Comment by Wade821** [comment]
Try turning it off, sorry for mis typing. But if it's off on your tablet settings, it needs to be off in drawpile.

**Comment by DeadOnStudios** [comment]
yay, that worked! thank you so much :D
