### ISSUE TITLE
Scaling Transform Issue

### ISSUE THREAD

**Issue by VRArt1** [drawpile/Drawpile#799]
There's an issue I've discovered and think I've noted the cause of it. I noticed that sometimes when I would select something when I went to move it that it would suddenly scale and change size on it's own before moving.I believe the cause is when you select outside of the canvas so the selection tries to scale out so the bounds match up with that.

**Comment by Wade821** [comment]
Issue was already reported in #788.

**Comment by callaa** [comment]
Confirmed, this is the same bug as in the issue linked by Wade821.
