### ISSUE TITLE
Feature request: Brush Preset naming and preset stroke preview.

### ISSUE THREAD

**Issue by StickyFingazFo20** [drawpile/Drawpile#800]
drawpiles brush preset browser in its current state is somewhat useless when dealing with lots of saved brushes. since theres no way to tell the difference between certain brush configs. having the option to name presets will fix this issue. having a visual brush stroke preview in the browser would be a nice addition aswell.
![Captuggre](https://user-images.githubusercontent.com/55508996/65175771-d27c1a00-da53-11e9-90a7-1b702c030448.PNG)

**Comment by Wade821** [comment]
FYI, pretty sure something is already in the works for this. I don't know the details of how exactly this is going to be implemented, but Callaa has been talking for a while now about implementing MyPaint brushes in Drawpile. This will include the ability to export brushes and import them. :)

**Comment by callaa** [comment]
Yep, I will need to improve this once I add support for MyPaint brushes. I'll probably add an option to create brush preset folders too.

**Comment by Wade821** [comment]
Feature Request: Smoothing per brush? #915
[Feature request]Custom Brushes #617
