### ISSUE TITLE
master fails to build, complaining about QDeadlineTimer

### ISSUE THREAD

**Issue by vn971** [drawpile/Drawpile#801]
Hi. I'm trying to build Drawpile (master branch).
Cmake runs successfully:
```
cmake .. -DCLIENT=off -DSERVERGUI=off -DINITSYS=""
-- No build type selected, default to Release
-- Use -DCMAKE_BUILD_TYPE=debug to enable debugging
-- Build type: Release
CMake Warning at src/thinsrv/CMakeLists.txt:74 (message):
  Libmicrohttpd not found: web-admin not enabled


-- CXX flags (release): 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pavel/Drawpile/build
```

But when trying to run `make`, I get this error:
```
[ 48%] Building CXX object src/libserver/CMakeFiles/dpserver.dir/session.cpp.o
In file included from /home/pavel/Drawpile/src/libserver/session.cpp:25:0:
/home/pavel/Drawpile/src/libserver/announcements.h:26:26: fatal error: QDeadlineTimer: No such file or directory
 #include <QDeadlineTimer>
                          ^
compilation terminated.
src/libserver/CMakeFiles/dpserver.dir/build.make:110: recipe for target 'src/libserver/CMakeFiles/dpserver.dir/session.cpp.o' failed
make[2]: *** [src/libserver/CMakeFiles/dpserver.dir/session.cpp.o] Error 1
CMakeFiles/Makefile2:199: recipe for target 'src/libserver/CMakeFiles/dpserver.dir/all' failed
make[1]: *** [src/libserver/CMakeFiles/dpserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Might there be something wrong with how I compile Drawpile?
Thanks

**Comment by Wade821** [comment]
No, you simply have an outdated version of QT causing the build error. You can either update QT if there's a newer download available from your repo, compile QT from source, modify the source code accordingly in order to make it compile using your existing installation, or [try running my script ](https://github.com/Wade821/PiDrawpile) to compile the server from source and run the necessary code changes automatically. The script itself has sections that you can use for notes on required changes to the source code that you should be able to find if you decide to do it manually yourself. I'd help but I'm about to leave for work for the day. 

That being the case, these are the commands needed to get started if compiling Drawpile from Source on Linux. :smiley: The script will be there to walk you through the rest of the necessary steps. Improvements to come on the script implementation later, working on a major re-write. 

```
git clone https://github.com/Wade821/PiDrawpile.git
cd PiDrawpile
sudo chmod 755 drawpile-installer-official-build-from-sources
./drawpile-installer-official-build-from-sources
```

More information here in my Google Document.
https://docs.google.com/document/d/1QrHd6x-ShLK-bj2U0P8CxiZgecdnWwB5O2tdTeRxtTw

**Comment by vn971** [comment]
@Wade821 thanks for your response and your script! The 2.1.2 release is working for me so far, so I'll keep it for now. I'll use the script and the patches (https://github.com/Wade821/PiDrawpile/tree/master/scripts-for-other-scripts-only) when I'll need a newer version I guess, should upstream Drawpile not make something for backwards compatibility I guess..

I cannot unfortunately update my system as the server is run on OpenVZ, with a kernel that doesn't support a modern enough runc (installation of runc on this kernel breaks). So I cannot update the distro beyond Debian9 unfortunately, at least for now..

**Comment by Wade821** [comment]
There are three different things you need. First two are below (which you can download the files and save as the filename shown in the commands to type below). 

[Elapsed-Timer.patch](https://github.com/Wade821/PiDrawpile/blob/master/scripts-for-other-scripts-only/elapsed-timer.patch)
[elapsed-timer2.patch](https://github.com/Wade821/PiDrawpile/blob/master/scripts-for-other-scripts-only/elapsed-timer2.patch)

You can run these by typing the following once you have downloaded the files and saved them in the source files for Drawpile.

```
patch -p1 < elapsed-timer.patch
patch -p1 < elapsed-timer2.patch
```

This script below does the other changes. All you need to do is modify the variable I placed at the top called dpinstallloc to match where you have your source files for Drawpile located (not the build folder that you place inside the source). This should allow you to compile from source using the older QT. This was made on Raspbian Stretch using QT 5.7.1.

```
#!/bin/bash
dpinstallloc=/my/location/here
#---------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------
# These lines are to fix an issue with an older version of KArchive which cannot be easily upgraded.
# KArchive apparently doesn't supply a version number macro so this can't be detected at compile time as a problem.
# File is located under Drawpile/src/libclient/ora/orawriter.cpp and replaces the following text
# zip.errorLine() 
# zf.errorLine() 
#
# with this instead as per the creator of Drawpile
#
# QString("ZIP error")
#
# It is presumable that the current (09/18/2017)  stable release of KArchive at 5.28.0-2 has this issue fixed with 
# the testing version of KArchive which is 5.37.0-2. Once updated to or past that number, this section below should
# no longer be necessary to use.
#
# Page for newest KArchive download ---> https://api.kde.org/frameworks/karchive/html/index.html
# Also see https://tracker.debian.org/pkg/karchive
# Or see https://packages.qa.debian.org/k/karchive.html
#---------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------
echo
version=$(apt-cache policy libkf5archive-dev | grep "Installed:" | cut -c 14-40)
echo "K Archive is using version $version"
echo

if [[ "$version" > "5.29" ]]; then
	echo "Installed version of K Archive is greater than 5.29."
	echo "No modification of source files required."
elif [[ "$version" = "5.29" ]]; then
	echo "Installed version of K Archive is equal to 5.29."
	echo "No modification of source files required."
elif [[ "$version" < "5.29" ]]; then
	echo "Installed version of K Archive is less than 5.29."
	echo "Modification of source files required."
	echo
	echo 'Creating backup of file orawriter.cpp before modification.'
	sudo cp "$dpinstallloc/src/libclient/ora/orawriter.cpp" "$dpinstallloc/src/libclient/ora/orawriter.cpp.backup"
	echo
	echo 'Modifying file orawriter.cpp for use with older version of KArchive (5.28.0-2).'
	sudo sed -i -e 's/zip.errorString()/QString("ZIP error")/g' "$dpinstallloc/src/libclient/ora/orawriter.cpp"
	sudo sed -i -e 's/zf.errorString()/QString("ZIP error")/g' "$dpinstallloc/src/libclient/ora/orawriter.cpp"
else
	echo "Unable to make a determination of which version of K Archive is installed."
fi
echo
echo
#---------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------
# These lines are to fix an issue with an older version of QTBase5-dev.
# Q_FALLTHROUGH was introduced in Qt 5.8, this can be fixed by adding
# the following to the loginhandler.cpp file: #define Q_FALLTHROUGH (void)0
#---------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------
echo
versionQT=$(apt-cache policy qtbase5-dev | grep "Installed:" | cut -c 14-18)
echo "qtbase5-dev is using version $versionQT"
echo

if [[ "$versionQT" > "5.8" ]]; then
	echo "Installed version of qtbase5-dev is greater than 5.8."
	echo "No modification of source files required."
elif [[ "$versionQT" = "5.8" ]]; then
	echo "Installed version of qtbase5-dev is equal to 5.8."
	echo "No modification of source files required."
elif [[ "$versionQT" < "5.8" ]]; then
	echo "Installed version of qtbase5-dev is less than 5.8."
	echo "Modification of source files required."
	echo
	echo 'Creating backup of file loginhandler.cpp before modification.'	
	sudo cp "$dpinstallloc/src/libserver/loginhandler.cpp" "$dpinstallloc/src/libserver/loginhandler.cpp.backup"
	echo
	echo 'Modifying file loginhandler.cpp for use with older version of qtbase5-dev.'
	sudo sed -i -e 's/#include <QNetworkReply>/#include <QNetworkReply>\n#define Q_FALLTHROUGH() (void)0/g' "$dpinstallloc/src/libserver/loginhandler.cpp"
	echo
	echo
	echo 'Creating backup of file aclfilter.cpp before modification.'
	sudo cp "$dpinstallloc/src/libclient/canvas/aclfilter.cpp" "$dpinstallloc/src/libclient/canvas/aclfilter.cpp.backup"
	echo
	echo 'Modifying file aclfilter.cpp for use with older version of qtbase5-dev.'
	sudo sed -i -e 's/#include "..\/shared\/net\/undo.h"/#include "..\/shared\/net\/undo.h"\n#define Q_FALLTHROUGH() (void)0/g' "$dpinstallloc/src/libclient/canvas/aclfilter.cpp"
	sudo sed -i -e 's/#include "..\/libshared\/net\/undo.h"/#include "..\/libshared\/net\/undo.h"\n#define Q_FALLTHROUGH() (void)0/g' "$dpinstallloc/src/libclient/canvas/aclfilter.cpp"
	echo
	echo
	echo 'Creating backup of file navigator.cpp before modification.'
	sudo cp "$dpinstallloc/src/desktop/docks/navigator.cpp" "$dpinstallloc/src/desktop/docks/navigator.cpp.backup"
	echo
	echo 'Modifying file navigator.cpp for use with older version of qtbase5-dev.'
	sudo sed -i -e 's/right.center()/0.5 * right.p1() + 0.5 * right.p2()/g' "$dpinstallloc/src/desktop/docks/navigator.cpp"
	echo
	echo
	echo 'Creating backup of file joindialog.cpp before modification.'
	sudo cp "$dpinstallloc/src/desktop/dialogs/joindialog.cpp" "$dpinstallloc/src/desktop/dialogs/joindialog.cpp.backup"
	echo
	echo 'Modifying file joindialog.cpp for use with older version of qtbase5-dev.'
	sudo sed -i -e 's/currentSecsSinceEpoch()/currentMSecsSinceEpoch() \/ 1000/g' "$dpinstallloc/src/desktop/dialogs/joindialog.cpp"
	echo
```

**Comment by notfood** [comment]
Submitter seems to have fixed their issue.

**Comment by vn971** [comment]
@notfood I did not fixed the issue, I'm just unable to upgrade past 2.1.2, and thus keeping it there. I understand that drawpile might not want to support library versions from Debian 9 though. So if the decision to not support Debian9 is explicit, I don't mind.

**Comment by notfood** [comment]
I have a [fork with 2.1.11 support for Debian stretch](https://github.com/notfood/Drawpile/commit/b7cea59807f468e36954181f0de24bff554bc6bf), I tried to update it to 2.1.15 but the differences are getting bigger as Drawpile is using newer libraries.

I marked it as fixed since you got Drawpile running but it's unlikely Drawpile will be supporting Debian Stretch anymore.

**Comment by vn971** [comment]
@notfood did you try to merge it back to main Drawpile codebase? As far as I get from the diff, there's even no practical need to upgrade. Literally, all of the used components seem to have a direct analog.

Enforcing the a successful compilation in CI would then enforce that things aren't broken accidentally.

**Comment by notfood** [comment]
Not a call for me to make. Allow Callaa to respond.

**Comment by vn971** [comment]
I'll add a mention just in case, @callaa

**Comment by callaa** [comment]
I merged the patches. I think QDeadlineTimer is slightly neater in this case, but the difference is small enough that I don't feel strongly either way. Might revert the commit when upgrading to Qt 6.0.

@vn971 are there any other things blocking compilation?

**Comment by notfood** [comment]
I believe there is more than just QDeadlineTimer. Last time I couldn't build 2.1.15 on Debian Stretch.

**Comment by vn971** [comment]
Tested current master now. cmake runs successfully (`cmake .. -DCLIENT=off -DSERVERGUI=off -DINITSYS=""`)
But then `make` fails:
```
...
[ 63%] Building CXX object src/libserver/CMakeFiles/dpserver.dir/loginhandler.cpp.o
/home/pavel/Drawpile-master-2019-12-27/src/libserver/loginhandler.cpp: In member function 'void server::LoginHandler::handleIdentMessage(const protocol::ServerCommand&)':
/home/pavel/Drawpile-master-2019-12-27/src/libserver/loginhandler.cpp:308:17: error: 'Q_FALLTHROUGH' was not declared in this scope
   Q_FALLTHROUGH(); // fall through to badpass if guest logins are disabled
                 ^
src/libserver/CMakeFiles/dpserver.dir/build.make:278: recipe for target 'src/libserver/CMakeFiles/dpserver.dir/loginhandler.cpp.o' failed
```

Any ideas?

**Comment by vn971** [comment]
After I removed the line with `Q_FALLTHROUGH();`, the current master succeeded the build! It's awesome. Does anybody know how to fight hte `Q_FALLTHROUGH()` problem?

Having this line is desired as it is part of Qt coding style: https://wiki.qt.io/Qt_Coding_Style#Switch_statements

Maybe we can somehow artificially add this function on older Qt versions, or conditionally include the line on newer? Any ideas? I'd really love support for Debian-9 as we're literally 1 line of code away from making it happen.

**Comment by vn971** [comment]
I'd also be happy to try write a travis file for automatic compilation testing under ubuntu16.04, ubuntu18.04, macos, windows.

**Comment by vn971** [comment]
I've found a solution and made a PR here: https://github.com/drawpile/Drawpile/pull/851

If this gets merged, then I'd also be happy to work on CI, and then this issue can be closed I think.

**Comment by vn971** [comment]
Now that master branch of Drawpile successfully compiles on Debian9, should I attempt writing a CI job that tests compilation? I'm interested in that because it'd help me ensuring that the thing stays working on my system.:)

// I personally don't use Drawpile, but I help setting it up for a math/ML tutor I know (they don't have their own server).

**Comment by Wade821** [comment]
Personally, I don't see why not but I'm no programmer so probably best to wait for @callaa to answer this one. My interest in being able to have something maintained is because Raspbian doesn't have the latest version of QT, and updating it is a royal pain. 

Also, my script does have a thing to fix Q_FALLTHROUGH, but it may have not fixed it due to the way I wrote the elif statement, which is something I need to get around to fixing sometime.... ;C

**Comment by notfood** [comment]
Issue has been resolved. DP builds on Debian Stretch :tada: 

CI jobs for tests are always nice to have though don't Github actions demand payment above a threshold?

**Comment by vn971** [comment]
> CI jobs for tests are always nice to have though don't Github actions demand payment above a threshold?

I don't know any threshold for open-source apps. Maybe there is one that I've never hit. I'll try then doing the CI then!

**Comment by vn971** [comment]
I've created a pull request here: https://github.com/drawpile/Drawpile/pull/860

If anyone has time to look, would be great!
