### ISSUE TITLE
Theme Broken After Compiling

### ISSUE THREAD

**Issue by mrjpaxton** [drawpile/Drawpile#802]
Hey,

I'm not sure what's going on with this, but when I try to compile on my Debian Unstable system, the theme/icons are completely broken. I also cannot switch to night mode, as well. I get lots of messages like this:

`qt.svg: Cannot open file '/home/me/.local/src/Drawpile/theme:xyz.svg', because: No such file or directory`

Am I missing something here, like an extra thing to make? I have done `cmake ..` from the `build/` directory, and then ran `make`, but when I run the `drawpile` symlink after changing my current directory to the root Drawpile Git directory, and also from the build directory, it runs just fine, but without the icons.

**Comment by Wade821** [comment]
As far as compiling, I think there's nothing that you'd be missing simply because it usually relies on the local icons in the system. My own script on GitHub [for compiling from source ](https://github.com/Wade821/PiDrawpile/blob/master/drawpile-installer-official-build-from-sources) in Raspbian does some configuration of the server and source code modifications as necessary for older QT versions and karchive, but that shouldn't be your issue of course. Tired, so forgive me if I'm rambling here.

Anyway, I use this
```
sudo cmake .. -DINITSYS=systemd -DCLIENT=OFF
sudo make -j 4
sudo make install
```

I'm sorry I can't help more with this, as I haven't played around with Debian directly... mostly Raspbian on my end. However, I do recall a conversation on the [Official Drawpile Discord](https://discord.gg/M3yyMpC) (for which you can also find a link on Drawpile.net in the lower left corner) that might be of help to you. This is from the dev text channel. I don't know that I'll get any time soon to play with your specific situation, but perhaps this will help point you in the right direction. 

> NotFood: For some reason I get few icons, something missing?
> https://cdn.discordapp.com/attachments/543731850691215361/556551027352928257/unknown.png
> NotFood: Yeah...
> https://cdn.discordapp.com/attachments/543731850691215361/556551272744878105/unknown.png
> NotFood: Envy may have to install a theme
> 
> callaa: If you copy the theme directory (desktop/theme) to /usr/local/share/drawpile/drawpile/theme, Drawpile will load all icons not found in the system theme from there
> 
> NotFood: There is dark and light in there already
> NotFood: It's not using them
> NotFood: I'll try with moving everything under light to theme/
> 
> callaa: Perhaps the lookup path is different then. Try /usr/local/share/drawpile/theme
> 
> NotFood: same issue
> 
> callaa: are the any XDG environment variables set?
> 
> NotFood: https://cdn.discordapp.com/attachments/543731850691215361/556555537697865768/unknown.png
> NotFood: Apparently not
> NotFood: The path where the svg files is located is appdir/usr/share/drawpile/drawpile/theme
> 
> callaa: What's that appdir in the beginning?
> 
> NotFood: I put it as the DESTDIR
> 
> callaa: According to Qt docs, the search path, unless overridden by an environment variable, is "~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"
> 
> NotFood: The appimage sees it as root
> 
> callaa: Check out pkg/appimage/appimage-client.patch
> callaa: Looks like I've ran into the same problem
> 
> NotFood: Doesn't work
> NotFood: What makes the chat icon show and the others not?
> NotFood: https://cdn.discordapp.com/attachments/543731850691215361/556559674464403486/unknown.png
> 
> callaa: The chat icon is built-in
> 
> NotFood: Ah ok
> NotFood: Hmmm I think it's a theme issue, not an appimage issue
> NotFood: What does it show for you?
> NotFood: Are you on Linux?
> https://cdn.discordapp.com/attachments/490194198964862978/556560250363183104/Drawpile-2.1.3-x86_64.AppImage
> NotFood: In my arch desktop, the icons show just fine
> 
> callaa: Not at the moment. The way it works is that it first tries to load the icon from the system theme and if it's not found, falls back to the filesystem. The search paths are:
> qApp->applicationDirPath() and
> QStandardPaths::standardLocations(QStandardPaths::DataLocation);
> 
> callaa: The applicationDirPath should be the path where the executable is located.
> 
> NotFood: I'll test with strace
> NotFood: It just doesn't try anywhere else but where is running
> NotFood: https://cdn.discordapp.com/attachments/543731850691215361/556561921361444911/unknown.png
> NotFood: It does check for .theme files
> NotFood: This is compiled with your appimage diff
> 
> callaa: Yes, that part should work if you're seeing all the icons on your desktop. It's the fallback path that's wrong somehow.
> callaa: I checked the code and I think the diff is no longer needed. The same code is now included in the normal source code
> 
> NotFood: I think it's an issue with Fluxbox and QT apps
> NotFood: Seems a common search in google
> 
> callaa: I don't see how the WM could have any effect on the file search path
> callaa: Those error messages are a bit misleading. It's going through all the searchpaths and then finally trying the internal names.
> 
> NotFood: strace doesn't show it trying anywhere else
> NotFood: With a grep to a single file https://cdn.discordapp.com/attachments/543731850691215361/556565362888540182/unknown.png
> NotFood: I think it could be that theme: isn't being recognized by the QT engine because it's compiled with an older version
> NotFood: As a workaround I put all the theme files prefixed with theme: onto the zip file
> 
> It works...
> https://cdn.discordapp.com/attachments/543731850691215361/556568037948522522/unknown.png

**Comment by callaa** [comment]
Drawpile uses icons primarily from the system theme, then falls back to the bundled icon set if not found. Try copying the theme directory (`desktop/theme`) to `~/.local/share/drawpile/drawpile/`

**Comment by mrjpaxton** [comment]
Yeah. I've just been using the Flatpak version, even though I really did not want to for a couple of reasons. But now, Flatpak has gotten more stable for my desktop, and it's usable again. That version doesn't seem to have any issues related to this. It really only applies to when I compile it and run it from the build directory.

So unless anyone is really stressing out about it, it sounds like @callaa has the right solution. Good to know!
