### ISSUE TITLE
Eraser is broken in 2.1.12

### ISSUE THREAD

**Issue by phoe** [drawpile/Drawpile#807]
Me and my friend have opened a collaborative session on 2.1.12 clients only to find that the eraser tool no longer works. It worked in 2.1.11.

Tool settings:

![](https://cdn.discordapp.com/attachments/590177687512023100/636283878637830159/Przechwycenie_obrazu_ekranu_2019-10-22_21-24-50.png)

**Comment by phoe** [comment]
We have worked around this issue by selecting a color for the eraser (any color on the wheel).

The resulting toolbox:

![](https://cdn.discordapp.com/attachments/590177687512023100/636284667510915094/Przechwycenie_obrazu_ekranu_2019-10-22_21-27-57.png)

**Comment by callaa** [comment]
Confirmed.

**Comment by Kavukamari** [comment]
is this related to choosing a brush preset while having eraser tool chosen?

my friend and I had newest version and we accidentally chose a brush preset with Eraser enabled, this caused the eraser to paint as a normal brush, and we were unable to set "erase mode" back on, thus breaking the eraser. 

are the two issues the same? or is this an entirely different bug? I will make a new issue if it's a new bug.

**Comment by phoe** [comment]
This issue is about the eraser not erasing anything unless a color is selected for the eraser.

**Comment by callaa** [comment]
This should now be fixed in the master branch, and the fix will be part of the next release. (The underlying problem was that the brush color did not get initialized properly, or could be initialized to an invalid value.)
