### ISSUE TITLE
(2.1.12) Holding spacebar stops panning when you let go of the mouse button

### ISSUE THREAD

**Issue by Banderi** [drawpile/Drawpile#809]
When you let go of the mouse click to do a pan, spacebar stops registering the pan for some reason, requiring you to let go and re-press spacebar every time.

e.g.:

- Hold spacebar
- Hold left-click to pan/drag
- Let go of the mouse button
- You can not pan again until you let go and press the spacebar again

**Comment by MayorRev** [comment]
Can confirm; just updated DP and it's happening to me as well.
![drag-glitch](https://user-images.githubusercontent.com/31830867/67335483-c4596780-f4f1-11e9-96c6-7d91d56e28ff.gif)

**Comment by callaa** [comment]
Confirmed.

**Comment by callaa** [comment]
This is now fixed in the master branch and will be included in the 2.1.13 release.
