### ISSUE TITLE
2.1.12 Using spacebar occasionally creates line while panning

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#812]
This is different from the spacebar shortcut issue. First line is demonstrating what happens when trying to pan after the first pen move. The issue is the hard line that ignores any pressure input done while panning.
https://i.gyazo.com/915893ae5846f2ca3a174530d4596d6d.gif

**Comment by callaa** [comment]
This should now be fixed in the new version. Please comment if it still happens.
