### ISSUE TITLE
Record Playback window Opener 

### ISSUE THREAD

**Issue by DominoDoodles** [drawpile/Drawpile#817]
I've had consistent issues with the playback window not opening when I want to go over sessions in drawpile and the only option is the play button with no option to increase speed so I'm stuck at a snails pace.

Just an option to reopen in the "View" or "Tools" drop menu would be a good

**Comment by callaa** [comment]
The playback window should always be open when in playback mode. Could it be hidden off-screen? What operating system are you using?

**Comment by notfood** [comment]
Stale, no answer from submitter. Closing.
