### ISSUE TITLE
2.1.12 Moving the brushes preset cause error result

### ISSUE THREAD

**Issue by neiriod** [drawpile/Drawpile#820]
OS: Windows7
Drawpile Version : 2.1.12

Here is the preview of my brushes preset 
![1](https://user-images.githubusercontent.com/49644585/68078529-23807b80-fe12-11e9-8fc0-e6d174a6b4ae.PNG)

After moving each brushes preset
![2](https://user-images.githubusercontent.com/49644585/68078539-54f94700-fe12-11e9-8921-3064d950786e.PNG)

**Comment by callaa** [comment]
An actual fix won't make it to today's release, so as a temporary workaround I'm disabling drag&drop. I'll fix this properly in version 2.1.14.
