### ISSUE TITLE
Pressure not working on tablet mode

### ISSUE THREAD

**Issue by DyingStarArch** [drawpile/Drawpile#822]
I haven't been using drawpile in a while so I just updated it. For some reason when putting the drawpile window to my Cintiq 13HD the pressure sensitivity is gone but if I throw the window it to my normal desktop's screen the sensitivity is back when I draw on my tablet to my normal screen.

I have updated my drivers on tablet, tried putting windows ink off  and restarted my computer but nothing is working. I can't remember exactly how drawpile looked on my tablet but it seems huge as I can't see all the docks either like I normally did.

Is there anything I could do? :( 

Picture of drawpile on my tablet:
https://i.imgur.com/OB0Z62B.png

**Comment by Wade821** [comment]
Can you take a screen shot of your tablet settings in wacom, specifically what the pen mapping settings show.

**Comment by tincancrab** [comment]
Setting the Cintiq to be the user's primary monitor in windows is a confirmed work around. This used to be an issue that extended to Krita for me as well, but user says it doesn't happen in Krita. Possibly this was addressed in Krita's newer builds?

I cannot personally test to see if this is the same for me as my only monitor is my Cintiq right now.
