### ISSUE TITLE
Rotating selection changed / broken?

### ISSUE THREAD

**Issue by MayorRev** [drawpile/Drawpile#825]
I'm having trouble with rotating selections via the selection tool and lasso. Last I checked, it was Alt + dragging the mouse, but that doesn't seem to do so now, and the DP site still lists the command as such. Has this been changed? The current version I'm using is 2.1.13.

**Comment by Wade821** [comment]
Click inside the selection to change the mode. It was listed on the news page for 2.1.12. Guess Callaa needs to update the website. 

I'm at work so sorry for the short response.

**Comment by MayorRev** [comment]
Ah I see it now, thanks a lot.
