### ISSUE TITLE
Unable to connect to either syntheticdreams or drawpile.net

### ISSUE THREAD

**Issue by cubeheadhell** [drawpile/Drawpile#829]
Every board hosted outside of these two servers (including both syntheticdream and syntheticdreams) have worked, but for some reason, I'm unable to connect to either.

**Comment by Wade821** [comment]
What message do you get when you attempt to connect? Connection timed out?

**Comment by callaa** [comment]
Looks like the drawpile.net server had crashed. It should be up again now.
