### ISSUE TITLE
Eraser is locked as another draw layer. Is there a reset function?

### ISSUE THREAD

**Issue by engchristy** [drawpile/Drawpile#830]
While using your tool, the eraser function got locked as a brush tool and won't revert back.  Is there a way we can revert the toolset to the original eraser function?  We've been surviving off of other tool's eraser modes so far, but would like to get that eraser tool to work again.

**Comment by callaa** [comment]
This bug will be fixed in the next release. A workaround is to create a brush preset that is an eraser and select that.

**Comment by Wade821** [comment]
Drawpile issue resolved in 2.1.14. Closing issue, comment if you're still having problems.

https://drawpile.net/news/release-2.1.14/
