### ISSUE TITLE
Blending Brush

### ISSUE THREAD

**Issue by TheoSilvers** [drawpile/Drawpile#831]
Okay, so this isn't really an issue- error wise- but i cant find ANYTHING about a good blending brush for DP and I can't find anything like a forum on the official DP website. If anyone can, please tell me the exact settings if they got one that blends really well. Their default blending seems to be shitty and idk how to properly create brushes! Sorry if this doesnt belong here, i just don't know where to put it.

**Comment by callaa** [comment]
Drawpile's current brush engine is very basic, the controls you see are the ones you get. Are you perhaps looking for a blur type brush?
