### ISSUE TITLE
Selection transformation bug still occurring

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#832]
I know this has been addressed a few times, but it hasn't been fixed yet, at least not for me.

I don't know if the problem is going to be solved anytime soon since it hasn't been fixed like the other issues, but from a person who mostly draws on the side of a canvas often it's pretty inconvenient to have to be careful how far I select a drawing to have the same scale.

**Comment by Wade821** [comment]
Duplicate issue, #788. If you have a concern, please post on the existing issue. Making more issues like this just makes it harder for Callaa to keep up with the problems and make Drawpile awesome. I'd like it if it got fixed as well, but Drawpile is 10s of thousands of lines of code written by one person.
