### ISSUE TITLE
Flatpak: can't type file name into save dialog

### ISSUE THREAD

**Issue by yorgje** [drawpile/Drawpile#833]
not sure which version this started happening in, but it's been happening for several versions now (including 2.1.14, which I am currently on). If I click the filename entry field, it becomes highlighted and the cursor blinks there, but no keypresses are registered (and there doesnt seem to be anything logged in the terminal either). If I select a pre-existing file by clicking in the dialog, its filename will populate the filename field, but I still won't be able to type anything. I'm running Ubuntu 18.04 with mate 1.20.0 and XMonad, if that matters.

**Comment by callaa** [comment]
Are you using the flatpak version or a self built one? I seem to remember seeing something like this before, but I believe it affected all Qt based applications.

**Comment by yorgje** [comment]
this is with the flatpak version

**Comment by callaa** [comment]
Does the problem occur in any other Qt based flatpak packaged application, or does it only happen in Drawpile?

**Comment by notfood** [comment]
Is it still happening?

**Comment by yorgje** [comment]
yeah it's still happening and sorry I don't have any other flatpak applications to compare to.

**Comment by askmeaboutlo0m** [comment]
The Flatpak has been updated to a more recent runtime, which should resolve this issue.
