### ISSUE TITLE
BRUSH: The size is increasing by 2px when assigning a short-key

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#835]
Hi,

VERSION: Drawpile 2.1.14

When I assign the following shortcuts to the brush increase and decrease size:

![imagen](https://user-images.githubusercontent.com/3485891/69359636-95e4be80-0c4e-11ea-8dea-f3aacec19aaa.png)

PROBLEM:  I use those keys during a drawing session, it increase or decrease by 2px (even the first time you press the key, it doesn’t respond until the second time)

![imagen](https://user-images.githubusercontent.com/3485891/69359671-a006bd00-0c4e-11ea-8227-809543729e17.png)

![imagen](https://user-images.githubusercontent.com/3485891/69359680-a39a4400-0c4e-11ea-9e33-b641517d5c9e.png)

Regards

**Comment by callaa** [comment]
This is now fixed. The fix will be included in the next release.
