### ISSUE TITLE
Pen Stylus is being detected as mouse

### ISSUE THREAD

**Issue by Feral-Nebula** [drawpile/Drawpile#838]
I just downloaded Drawpile today and I can't get the pen pressure to work. I looked at a lot of old threads but none of them seem to be having the same issue as me. 
I'm on version 2.1.14 and I am using an XP-pen tablet with an up to date driver. I can't get the pressure sensitivity to work at all. I've turned off windows ink on both Drawpile and my tablet, I've turned it back on, I've messed with the actual brush settings themselves. Nothing works. It appears that the program is detecting my tablet as a mouse:
![a6f805a785fe42b21b22005abf4faa80](https://user-images.githubusercontent.com/58380429/69909277-3f9a1d00-13be-11ea-8ec9-77263d778fbc.png)

I'm not sure what the issue is.

**Comment by Wade821** [comment]
Do you have more than one monitor screen in use on your computer? There are some known issues with that if you do. You can right click the desktop, go to Display Settings, and try one of two different things (This is for Windows given you said you tried Windows Ink). 

1. Set your graphics tablet monitor as your main display. To do so, click identify, and click the corresponding monitor in the displays section at the top and scroll down until you find "Make this my main display". 
2. Try changing the scaling of your display in use to 100%. Some people have reported that this scaling has affected their ability to get pen pressure for some reason.

If you have a non-display graphics tablet, there may be some other things we can try. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by notfood** [comment]
Are you still having this issue?

**Comment by ArtOfCombat** [comment]
I am also having this problem. Changing desktop size and number did not help.

**Comment by notfood** [comment]
@ArtOfCombat My advice is to go to the Discord since you haven't provided any details.
