### ISSUE TITLE
Issue with Logging into my pre-exsisting account

### ISSUE THREAD

**Issue by jacetheasce** [drawpile/Drawpile#841]
Hi there drawpile! im having an issue with logging into my pre-exsisting account and get an issue message when i log in. I was using the account just fine last night but i updated and it kinda all fell apart! i had to create a new account to get into ANY of the boards! please help!
Oh yeah my username is Pummer by the way!

Below is the error im recieving
![image](https://user-images.githubusercontent.com/58659036/70390110-1f59f780-1996-11ea-96ae-ae7cffed982d.png)

**Comment by jacetheasce** [comment]
Update! I tried logging in with my alt Pum but its broken aswell..Please fix!

**Comment by callaa** [comment]
Should be fixed now.
