### ISSUE TITLE
Export/Import of bans and user flags

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#844]
When a room breaks and needs to be rehosted, all previous bans are forgotten and users need to be reflagged upon entry, or re-banned upon entry.

The main issue here is the bans-- as you cannot manually add a ban-- you have to wait for that user to reappear. Where oftentimes draw giant phalluses in a sfw room, ask for poopy diaper pics, or scribble/erase peoples' work. Again.

I have IP banned some these users in question, however, they are able to change IPs and reenter rooms where they were previously banned if the room was rehosted.

The other implementation of being able to import bans from a failed session is nsfw rooms and a banlist of known minors, and having to re-ban them once seen again.

This may be a privacy concern, but its also a major inconvenience to just say "ban them if they come back." If there's a way to approach this, that would be fantastic. (I know user flag imporation is not a privacy risk and should be pretty simple to export, its the banlist.)

**Comment by askmeaboutlo0m** [comment]
This is implemented now. Both server and client need updating for it.

What you called "user flags" is in the new "Roles" tab in the session settings. For operators, it shows a list of all users that the session is aware of, along with their roles. Non-operators get an empty list here and are told that it's for operators' eyes only.

You can change their operator and trusted status using the checkboxes at the bottom, even when they're not online. The list can be exported to a file and imported again. It will only export users that actually have any roles. Importing won't clobber existing roles, only add them, so merging multiple exports is possible this way.

![image](https://github.com/drawpile/Drawpile/assets/13625824/d37fa848-00a6-49d3-96ac-0c99a00bff1e)

Session bans can also be exported and imported now. Moderators can always export it in a "plain" format, non-moderators only get an encrypted file, which requires some server configuration to be available. Like with the roles above, importing bans doesn't overwrite existing entries, it's only additive.

For the encrypted format to work, the server has to be supplied with an encryption key on startup using the `--crypt-key` parameter. It can generate a random key using `drawpile-srv --generate-crypt-key`, which can then be pasted into your startup script.

Encrypted exports can only be imported on servers that use the same encryption key. Plain exports made by moderators can be imported on any server, no additional server configuration required.

![image](https://github.com/drawpile/Drawpile/assets/13625824/691961ed-8d14-40e8-b597-9d808af82092)

Thanks for suggesting!
