### ISSUE TITLE
Can't host session (connection refused)

### ISSUE THREAD

**Issue by ghost** [drawpile/Drawpile#845]
I had this issue a week ago, everytime i try to host a session this shows up:

![image](https://user-images.githubusercontent.com/58717734/70551235-e4062700-1b55-11ea-928c-9c999fda98f8.png)

I tried in the two versions i have (2.1.1) (2.0.11) and even download them again.
I did looked the most i could to find if there was a problem (nothing found), and it seems its only me cause i asked my friends about it and it works well for them.
Im worried that i cant host my sessions ever again, i hope theres a way to fix it.

**Comment by callaa** [comment]
Which server are you using?

**Comment by LazyWaff** [comment]
syntheticdream.net

**Comment by Wade821** [comment]
Try syntheticdreams.net instead

**Comment by LazyWaff** [comment]
Oh, well thanks!!

**Comment by Wade821** [comment]
Let me know if it works.

**Comment by LazyWaff** [comment]
Yes, it worked (im just confused of how that happened, i dont remember ever changing it) but thanks for helping!
