### ISSUE TITLE
Pressure sensitivity "faking" itself in 2.1.15 (not working), Windows Ink off

### ISSUE THREAD

**Issue by VoodieMcScoot** [drawpile/Drawpile#849]
As the title implies, after I enable pressure sensitivity, it seems to "fake" said sensitivity. No matter how hard or soft I press my pen, my lines start off at a certain thickness and end at a certain thickness. And always at the end of the line, it just rounds off. It even does the same thing with a **mouse**, of all things. It's frustrating as I cannot control this, and have every driver of mine updated and my sensitivity works in every single other program. Also as the title says, I have Ink disabled. I use a Huion GT-156 HD V2, if that helps

Here's what I mean:
![lines](https://user-images.githubusercontent.com/59189447/71393991-3b3bdb00-25dd-11ea-9533-7ac25975cec0.PNG)
All of my settings seem to be fine, as that's what my friends/other users use:
![settings](https://user-images.githubusercontent.com/59189447/71394004-57d81300-25dd-11ea-8d8c-12c74ba2fda7.PNG)
![tester](https://user-images.githubusercontent.com/59189447/71394005-57d81300-25dd-11ea-9a5e-ad4c8b8aaac2.PNG)
![ink](https://user-images.githubusercontent.com/59189447/71394006-57d81300-25dd-11ea-964c-ac8c3860e861.PNG)

Here's my log file, in case you guys see something that I dont:
![log](https://user-images.githubusercontent.com/59189447/71394017-69b9b600-25dd-11ea-8c17-7c62337a4f3d.PNG)

Thanks in advance!

**Comment by Wade821** [comment]
You probably have the input dock set to something other than stylus. Check your Input dock and make sure the "Pressure" drop down box is set to Stylus as well. At least, that is what it sounds like to me. I'm guessing it is the "distance" option rather than "velocity". Please check and let me know.

**Comment by VoodieMcScoot** [comment]
Thank you! That worked perfectly! I thought I had checked that, but apparently I didnt!
