### ISSUE TITLE
[MAC] Jagged and lagging lines (using Huion420 tablet)

### ISSUE THREAD

**Issue by Cherrypeep** [drawpile/Drawpile#856]
For a while now every time I open drawpile I am met with slow and jagged lines no matter how many times I restarted the driver, reopened program, reinstall program, install the latest version, reinstall driver, and unplugging the tablet I get the same results. 

![oough](https://user-images.githubusercontent.com/59669053/72019481-cb159200-3237-11ea-8608-8348f1bbdcb6.png)
It did work well before, then all of a sudden after a session it started to do this. I'm not sure why or what else to do at this point but any tips or help is appreciated.

**Comment by notfood** [comment]
Does it happen in other programs? Can you reduce the input smoothing slider to 0 and try again? How's your CPU usage? Have you rebooted?
