### ISSUE TITLE
Reconnect button issues

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#858]
Drawpile version: 610a83e47652d217d26c805f7d0a412e4ee6de82

To reproduce:
- Be kicked or cause network disruption.
- Try to reconnect.

For normal servers, avatar goes missing but reconnects successfully.
For ext-auth servers, an auth server error is returned.

![image](https://user-images.githubusercontent.com/5370107/72314431-f562b780-365c-11ea-86ce-50615906799e.png)

**Comment by callaa** [comment]
Thanks for reporting this early!

**Comment by callaa** [comment]
This should now be fixed.
