### ISSUE TITLE
Copy Paste Issue

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#859]
Using master c404fd73f39c67b39c7dd7e30db46ee9a2e50c68

A simple copy paste makes the selection become invisible if you try to move or modify it. Atempting to commit the change does nothing.

### Steps to Reproduce
1. Select anything
2. Copy
3. Paste
4. Move selection

### Video
[![Click to watch](https://i.imgur.com/azPjxYt.jpg)](https://i.imgur.com/azPjxYt.mp4)

According to `git bisect` bug was introduced in b3385b0bd15aa42ba6f5f5037e49fc8d0e696f55

**Comment by callaa** [comment]
Confirmed. Looks like there is a related bug in the 2.1.15 version too:

1. Make selection
2. Move selection
3. Copy
4. Paste <-- image is clipped to the selection's original geometry.

**Comment by callaa** [comment]
Both of these bugs should now be fixed. The regression turned out to be quite simple: the `intersected` function returns an explicitly closed polygon, while my code was expecting an implicitly closed one.
