### ISSUE TITLE
I can't host my server

### ISSUE THREAD

**Issue by Darkstur** [drawpile/Drawpile#862]
![god](https://user-images.githubusercontent.com/60514553/73550541-13922b00-4445-11ea-93d2-b0daab9e3a6b.png)
![why](https://user-images.githubusercontent.com/60514553/73550558-17be4880-4445-11ea-8181-7886bb4ac92c.png)

I go to host my server and that part is okay, but then the window for the avatar pops up and there's only this loading circle shown. it lasts a good minute or less and then says _I couldn't connect to it_.
I restarted my pc but it was the same, this happened yesterday so I hoped it would work today but no.
**So I think this is a bug or something, please help!**

**Comment by callaa** [comment]
The server at drawpile.net had crashed apparently. I restarted it.
