### ISSUE TITLE
Trying to host a session, says its full

### ISSUE THREAD

**Issue by apolloartbox** [drawpile/Drawpile#864]
I'm trying to host a session on Drawpile (nobody had joined in my previous session, it was only me.) but it keeps saying the session is full. Even though i'm the one that is trying to host it. I think it might be because I didn't leave it before closing my laptop, but I'm not sure. Is there a way to fix it? Do I just need to reinstall it maybe?

**Comment by notfood** [comment]
Are you hosting a server? Or merely a session on a remote server?

**Comment by apolloartbox** [comment]
A session on a remote server. I think it's working now, just had to redownload it a few times until it decided to cooperate, thank you though

**Comment by notfood** [comment]
You didn't have to redownload anything. The remote server was simply full.
