### ISSUE TITLE
session hosted via (pub.drawpile.net) won't list at (drawpile.net) in 2.1.16

### ISSUE THREAD

**Issue by neiriod** [drawpile/Drawpile#865]
![Snipaste_2020-02-10_02-27-32](https://user-images.githubusercontent.com/49644585/74107494-c849ec00-4bab-11ea-9258-634d614cdf75.png)

**ubanis.mydns.jp**
**syntheticdreams.net**
**dp.yong-gang.cn**

here are some free server in drawpile, and the session hosted via these server both can list at (drawpile.net)

looks like only session hosted via (pub.drawpile.net) won't list at (drawpile.net) in 2.1.16

**Comment by callaa** [comment]
Check the announcement: https://drawpile.net/news/release-2.1.16/

The drawpile.net list server is being replaced with pub.drawpile.net

**Comment by neiriod** [comment]
> Check the announcement: https://drawpile.net/news/release-2.1.16/
> 
> The drawpile.net list server is being replaced with pub.drawpile.net


if the session hosted via (pub.drawpile.net) won't list at (drawpile.net), then what is point having the option of (list at drawpile ) in the host page?

**Comment by callaa** [comment]
There is no point. You can remove it via the preferences dialog. The latest version will delete it automatically it once the old server has been removed entirely.

**Comment by neiriod** [comment]
> There is no point. You can remove it via the preferences dialog. The latest version will delete it automatically it once the old server has been removed entirely.


 the problem is ppl can find their session in the join page , unless they add pub.drawpile.net to the list server. but ppl won't know it when they just download drawpile. not mention lots of nonenglish speaker and some ppl who not good at computer.

it's ok change drawpile.net to pub.drawpile.net, but atleast you should let ppl easy to find their room , isn't it?

ppl just want to easy to make a session and esay to see the session.

**Comment by callaa** [comment]
They will, because if you've just downloaded Drawpile, there will be a notification directing you to the communities page where you can find servers.

**Comment by neiriod** [comment]
> They will, because if you've just downloaded Drawpile, there will be a notification directing you to the communities page where you can find servers.

do you mean ppl have to browse a web site to find session /server?
this is not a easy way.

all the session hosted via the other server both list at drawpile.net,  why only making pub.drawpile.net won't list at drawpile?

**Comment by callaa** [comment]
This has been discussed on the Discord server, but the short summary is: The purpose of this change is to make it clearer that there are multiple Drawpile servers, operated by different people, and that different servers will have different rules and different moderators.

**Comment by neiriod** [comment]
> This has been discussed on the Discord server, but the short summary is: The purpose of this change is to make it clearer that there are multiple Drawpile servers, operated by different people, and that different servers will have different rules and different moderators.

i don't know how this work, i just want you know the problem is ppl like me who can't find the seesion hosted via pub.drawpile.net in the join page. unless they come here or discord ask for help.
also they have to know some english.

ppl already get used to host a seesion list at drawpile.net ,and find the session in join page, this is the most directest and easiest.

since all the othe server both can list at drawpule.net,  is it possible you can make pub.drawpile.net list at drawpile.net?

**Comment by callaa** [comment]
Here's the problem. Some people host sessions with objectionable content in them and I get email from people reporting said stuff and asking to ban them. However, I can only do so if those sessions are on my server (pub.drawpile.net). The single list server for everyone approach creates confusion as to who is responsible for what. The purpose of the new "communities" section is to make clearer who is responsible for each server and make users opt-in to the sessions they want  to see.

**Comment by neiriod** [comment]
> Here's the problem. Some people host sessions with objectionable content in them and I get email from people reporting said stuff and asking to ban them. However, I can only do so if those sessions are on my server (pub.drawpile.net). The single list server for everyone approach creates confusion as to who is responsible for what. The purpose of the new "communities" section is to make clearer who is responsible for each server and make users opt-in to the sessions they want to see.

i get the problem you said. but i don't think this change will help. 
the huge reason is : for now, most of the session hosted via the other server both list at drawpile.net
. this means the confusion and reporting will still there.

also i don't think the problem you side is a big issues.
1. ip ban:  sure the room operator can do their job 
2. server ban: only server owner can do
if a guy wants a person get a server ban, that this guys must know "the server thing" , so he'll just come to ask the server owner. which no need for you to concern much.

the change of making pub.drawpile.net not list at drawpile.net , now this is only making drawpile unfriendly.

cuz ppl can't easy enough find all of the session in the same page!


drawpile should easy to let ppl draw together, not let ppl spend time to sovle technical problem.
ppl who use drawpile mostly are artist, not "computer" guy.

**Comment by callaa** [comment]
Regarding point two: yes, the problem is that it's not always clear who is the server owner, and many assume it's always me.

Also, the drawpile.net list will be removed (in a couple of days once I've finished the server migration.) In the future, as more servers start to use the new style system, there will be less need to even manually announce sessions, since sessions will be automatically listed on their servers.

I understand this change makes it slightly more difficult to get started, but once we see how the new way works out, I believe we can identify the difficulties and fix them.

**Comment by Wade821** [comment]
The point of this was to shift responsibility for server content to other servers by not listing them by default, because Drawpile cannot moderate other server content. Plus, this is actually a better system in the long run. When the listing server does down, no one can see other servers. This way the listings are pulled from the various servers directly and if one server does down, it only affects those listings for that server. 

Since people have to start by downloading the program, they should inevitably end up seeing the communities page. All the communities are listed here: https://drawpile.net/communities/

![image](https://user-images.githubusercontent.com/18544575/74109864-8e91ca80-4b44-11ea-899d-03d25004ecf3.png)

Further discussion when new issues like this arise are on the Official Discord server for Drawpile. Link is available on Drawpile.net in the bottom left corner as well as below this message:
https://discord.gg/M3yyMpC

**Comment by neiriod** [comment]
> Regarding point two: yes, the problem is that it's not always clear who is the server owner, and many assume it's always me.
> 
> Also, the drawpile.net list will be removed (in a couple of days once I've finished the server migration.) In the future, as more servers start to use the new style system, there will be less need to even manually announce sessions, since sessions will be automatically listed on their servers.
> 
> I understand this change makes it slightly more difficult to get started, but once we see how the new way works out, I believe we can identify the difficulties and fix them.

all my wish is: if i host a seesion no matter via what server,  ppl can see my session in the join page, no extra step. just like the way in the old version.

now i still has some confusion, here it is :

1. as you said, the drawpile.net list will be removed in a couple of days.
 
![Snipaste_2020-02-10_05-23-08](https://user-images.githubusercontent.com/49644585/74110077-5df17580-4bc4-11ea-90ed-1f693fd2954c.png)

will the option of listing at drawpile.net in host page will be removed?


2. when the drawpile.net be removed ,how will the join page looks like? 
can i still see my session in the join page?  or need to do some extra step to find it ?

**Comment by callaa** [comment]
You can replace the old list server with `pub.drawpile.net`. This can be done via the preferences dialog, or simply by pressing the add button in the join dialog (when the server address is typed into the box.) I think this might not be very clearly explained at the moment. I will have to improve the documentation and perhaps make it more obvious in the UI as well.

**Comment by Wade821** [comment]
1. In regards to Drawpile.net listing being removed automatically, I presume that will stay in the program and you'll receive some kind of error message if using that when trying to host. That option will probably be removed altogether when Drawpile updates to 2.2.

2. You should see a message directing you to the communities page on Drawpile.net's website provided you have not added any communites to Drawpile.net once the migration has been done.

**Comment by neiriod** [comment]
> You can replace the old list server with `pub.drawpile.net`. This can be done via the preferences dialog, or simply by pressing the add button in the join dialog (when the server address is typed into the box.) I think this might not be very clearly explained at the moment. I will have to improve the documentation and perhaps make it more obvious in the UI as well.

oh, no. that is what i mean the extra step. i don't think some of the ppl will know the way you said.

if the drawpile.net list will be removed . why not let all the other server both can list at pub.drawpile.net?  


the point is most ppl dont know the way you said. 
is it possible that you can making ppl see the session in the join page without that extra way?

maybe making pub.drawpile.net as a  default option in the  host page? 
(but not letting ppl do some extra step to manualy change it, back to the point, most ppl don't know how to do it.)

**Comment by notfood** [comment]
You can distribute a link to your session, if they're close friends they'll come.

The drawpile listining purpose has always been to invite guests to your session, the separation and removal of the default will help to find like minded groups and removing the burden of moderation from drawpile.net.

**Comment by Wade821** [comment]
Because allowing a listing server puts responsibility on Callaa for making sure all content is appropriately moderated, since it is included by default. By removing defaults and adding an extra step, it puts the responsibility of moderating content to the server owners, as it should be. That's why @neiriod ... and as @notfood said.

**Comment by neiriod** [comment]
> You can replace the old list server with `pub.drawpile.net`. This can be done via the preferences dialog, or simply by pressing the add button in the join dialog (when the server address is typed into the box.) I think this might not be very clearly explained at the moment. I will have to improve the documentation and perhaps make it more obvious in the UI as well.


i think i find a better way to solve this issues.
since you said you will remove the drawpile.net list server soon.

hear is the way :
**1.remove drawpile.net list server in the preferences dialog in 2.1.17.
2.add pub.drawpile.net list server in the preferences dialog in 2.1.17.**
(cuz 2.1.16 be released already)

by this way, ppl will see all the session in the join page when update to 2.1.17. no extra step.

will this way work ?

**Comment by Wade821** [comment]
They won't see all the sessions even if you do that, that will only show sessions hosted on the pub.drawpile.net server. Users will have to do the extra step to add servers to appear in the join dialogue, we are not reverting to that method that you keep asking about for the reasons that were previously mentioned.
