### ISSUE TITLE
fatal error: 'type_traits' file not found

### ISSUE THREAD

**Issue by AngryPenguinPL** [drawpile/Drawpile#866]
Hi.

When compile Drawpile on Clang (9/10) I see this error:
```
/usr/include/qt5/QtCore/qglobal.h:45:12: fatal error: 'type_traits' file not found
BUILDSTDERR: #  include <type_traits>
BUILDSTDERR:            ^~~~~~~~~~~~~
BUILDSTDERR: 1 error generated.
```
and

```
/builddir/build/BUILD/Drawpile-2.1.16/build/src/libshared/dpshared_autogen/XEGSBDYHWW/moc_announcementapi.cpp:9:10: fatal error: 'memory' file not found
DEBUG util.py:585:  BUILDSTDERR: #include <memory>
```

Full build log: http://file-store.openmandriva.org/api/v1/file_stores/72057c85d2d64537806b959ccc48ffec08f82f88.log?show=true

This problem not exist on GCC compiler, only on Clang.

OS: OpenMandriva

**Comment by callaa** [comment]
This looks like a problem with the standard library.
Check the root CMakeLists.txt file. On line 90, the clang specific CXX flags are set. Try removing the `-stdlib=libc++` part. This was required on macOS at some point, but is probably unnecessary now.

**Comment by AngryPenguinPL** [comment]
Yes, this fix issue. Clang now works fine. Thanks

**Comment by callaa** [comment]
Great! I updated the CMakeLists.txt file. It appears setting the stdlib parameter is no longer needed on macOS either.
