### ISSUE TITLE
(mac) can't join communities or sessions

### ISSUE THREAD

**Issue by peepobismol** [drawpile/Drawpile#867]
https://imgur.com/a/USxfvFs

I downloaded drawpile 2.16 on mac and tried to host a session (2nd pic), friends couldn't find it so I attempted to join a friends session only to not be able to find it. After that, I tried to join the drawpile community (3rd pic) and it opened up the join session screen and I had the same problem trying to enter the room code of friends session and the name. i restarted and reinstalled the app and same issue persists. Added pub.drawpile.net to list of servers, was able to see all sessions besides the one my friend was running. Tried to host my own session, first on my own computer then to drawpile.net (1st pic), no room code and friend still can't find it.

let me know if i can assist you with providing any additional information, i'm running catalina 10.15.3

feb 11th 2019

**Comment by peepobismol** [comment]
Fixed by adding pub.drawpile.net to list of servers

**Comment by peepobismol** [comment]
Ok genuinely no idea how this was able to be fixed but I can join my friends drawpile now, but not host one, and I didnt do any additional steps than the ones I listed.

**Comment by callaa** [comment]
First, you can add `pub.drawpile.net` to your list of servers by entering the server address in the join box, then clicking on the Add button. You should then see all the sessions hosted at that server.

Not sure why you can't host one. What kind of an error are you seeing?

**Comment by Wade821** [comment]
Well they noted they're trying to host remotely on drawpile.net and that server no longer exists. Please host remote sessions on pub.drawpile.net as well.
