### ISSUE TITLE
can't directly join the session via session url in client 2.1.16

### ISSUE THREAD

**Issue by neiriod** [drawpile/Drawpile#869]
![Snipaste_2020-02-16_07-58-02](https://user-images.githubusercontent.com/49644585/74596927-f1c5b480-5090-11ea-8bfd-f0c213c47bb8.png)

step: 
1.copy the session url and paste into chatbox
2.click the session url

result: 
can't directly join the session via session url , the address box is only showing the server address, not the session url

**Comment by callaa** [comment]
Confirmed. Fix will be included in the next release soon.

**Comment by callaa** [comment]
The new release that fixes this is now out.
