### ISSUE TITLE
 session hosted via the other server can't list at pub.drawpile.net 

### ISSUE THREAD

**Issue by neiriod** [drawpile/Drawpile#870]
1.all the session hosted via the other server both can't list at pub.drawpile.net 
![Snipaste_2020-02-22_12-49-40](https://user-images.githubusercontent.com/49644585/75086669-cd2a7a80-5571-11ea-9052-88c61fb23b0f.png)

the announcements is showing the session is list at pub.drawpile.net, but the session is not showing on the join page.

2.the address box won't able showing the session address by click the session title on join page, it only showing the server address
(except the session host via pub.drawpile.net)
example:
![Snipaste_2020-02-22_13-03-17](https://user-images.githubusercontent.com/49644585/75086749-a02a9780-5572-11ea-9927-d62c0f3039f3.png)
![Snipaste_2020-02-22_13-02-50](https://user-images.githubusercontent.com/49644585/75086839-98b7be00-5573-11ea-8119-f660f7bde757.png)

this two issues only happening today and everything was fine yesterday

**Comment by callaa** [comment]
This is most likely related to the listserver update I made yesterday. I'll investigate.

**Comment by callaa** [comment]
This is now fixed. There was a bug in the new listserver code: when querying the list of sessions, the ID was not being returned.
