### ISSUE TITLE
Glitched Gif Files

### ISSUE THREAD

**Issue by Arsynn** [drawpile/Drawpile#873]
I have watched multiple videos on making gifs using drawpile, and I had tried to make one as well. I finished drawing all the layers and when I previewed it, it was fine. Then I saved it and no matter what I set the settings as, it glitched the colors. As in, I made a pastel rainbow moving down, so multiple lines of different colors, but it glitched them by clumping them. As in the save file showed maybe three to four general colors but glitched. I tried looking up this problem, but I didn't get any results to similar problems, perhaps it is just mine, or perhaps not. I tried all of the settings, all the combinations, and maybe I am overlooking something, but I don't know what it could be.

**Comment by Arsynn** [comment]
> I believe it's a known issue if you aren't using ffmpeg, a work around is to export them as image sequence and use another program to convert them into a gif/webm/apng
> 
> I usually export as image sequence and use imagemagick to transform it into a gif.

Oh okay, thank you c:

**Comment by notfood** [comment]
It's a legitimate issue, allow Callaa to respond.

**Comment by callaa** [comment]
The current GIF exporter is indeed not very good. Currently, each frame is quantized to an 8 bit palette independently of the previous one, which can lead to weird color artifacts when new colors are introduced. Ideally, if there is some smart GIF encoder library out there, I could use that instead. (Haven't looked yet.)
