### ISSUE TITLE
error with make, /usr/bin/ld: can't find -lQt5::DBus - drawpile-2.1.17

### ISSUE THREAD

**Issue by edn9** [drawpile/Drawpile#874]
```
[ 49%] Linking CXX executable ../../bin/drawpile
/usr/bin/ld: não foi possível localizar -lQt5::DBus
collect2: error: ld returned 1 exit status
src/desktop/CMakeFiles/drawpile.dir/build.make:2612: recipe for target 'bin/drawpile-2.1.17' failed
make[2]: *** [bin/drawpile-2.1.17] Error 1
CMakeFiles/Makefile2:481: recipe for target 'src/desktop/CMakeFiles/drawpile.dir/all' failed
make[1]: *** [src/desktop/CMakeFiles/drawpile.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Trying to compile on:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Also QtColorWidgets could not be find even when I compiled and installed it.
```
-- Could NOT find QtColorWidgets (missing: LIBQTCOLORWIDGETS_LIBRARY)
CMake Warning at src/desktop/CMakeLists.txt:175 (message):
  QtColorWidgets not found: using bundled copy!
```
![QtColorWidgets-files](https://i.imgur.com/caFBlN6.png)

---

**Comment by callaa** [comment]
First, check if you have `libqt5dbus5` installed.
If you do, you can try adding `find_package(Qt5DBus)` to `src/desktop/CMakeLists.txt` and `Qt5::DBus` to the line with QTKEYCHAIN_LIBRARIES line like this:

    target_link_libraries(${CLIENTNAME} ${QTKEYCHAIN_LIBRARIES} Qt5::DBus)

**Comment by edn9** [comment]
![alt](https://i.imgur.com/L4nRkKr.png)

Looks like everything is working now, how about the QtColorWidgets? Also, the drawpile compiled but there was no /theme folder so I was without any icons in my program, so I just copy paste the folder theme in desktop to the build/bin one.

**Comment by callaa** [comment]
I'm not sure why it's not finding QtColorWidgets. However, it's not real a problem, since the bundled copy should be up to date.

If you run "make install" it will copy all the files in the right places. The default installation path should be /usr/local, so the icons, sounds, translations and default palettes get installed to /usr/local/drawpile/drawpile/

**Comment by notfood** [comment]
Issue appears resolved
