### ISSUE TITLE
odd windows ink issue

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#877]
When I run drawpile in windows ink mode, the pressure sensitivity works well, but when I try to move a slider, like the one for zoom or brush size, the cursor stops in its tracks for a few seconds, as if it's waiting for a press and hold right click that will never come. Am I missing something in the settings?

**Comment by Wade821** [comment]
Sounds like windows being windows... Might want to try method one here. I would detail the steps myself but I've been busy. Let me know how this goes for you. 

https://www.top-password.com/blog/turn-on-off-press-and-hold-for-right-clicking-in-windows-10/
