### ISSUE TITLE
unexpected pressure behavior

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#878]
Using a Wacom CTL-4100 with wintab, I'm getting uneven pressure sporadically, mainly in the form of lines that start off at maximum pressure when I'm putting the pen to the plastic gently. I'm attaching a screenshot to show what I mean. The real strange part is that the tablet tester doesn't show pressure at all. On one occasion it worked, but the blue pressure line broke off from the red position line at jagged angles before it went back to only showing the mouse again. Unfortunately I wasn't quick enough on the draw to screenshot it. 

![Screenshot 2020-03-12 01 59 26](https://user-images.githubusercontent.com/8505474/76491954-56143380-6405-11ea-8c07-cbae71cd55eb.png)

**Comment by ParisGreen** [comment]
On further investigation this was apparently being caused by my grip inadvertently holding down one of the pen's side buttons. I'm not sure if that's really something that can be fixed with software, but I'm thinking this is more of a "me" issue" than a "drawpile" issue.

**Comment by Wade821** [comment]
Been busy, and still busy so forgive me if I don't respond quickly. What version of drawpile are you using? I think a prior version had something similar going on that was fixed later... But I'm glad you figured it out (seemingly)!
