### ISSUE TITLE
trouble hosting drawpile session

### ISSUE THREAD

**Issue by afterclash** [drawpile/Drawpile#880]
every time i attempt to host a drawpile session, i get immediately disconnected. i tried to read the drawpile help page but i'm too stupid to understand it. my internet connection isn't from a wi-fi modem either, i just use my phone data so it makes all of this even more complicated.

**Comment by notfood** [comment]
It's very likely your phone internet doesn't allow UDP connections. For connectivity issues it's best to head to the Discord/Facebook for support as it's very specific to your case and not an issue in Drawpile.

https://discord.gg/M3yyMpC
https://www.facebook.com/groups/drawpile/
