### ISSUE TITLE
Multiple shortcuts for the same action

### ISSUE THREAD

**Issue by tobiasBora** [drawpile/Drawpile#882]
Hello,

First, thanks a lot for this tool. I have a feature request: would it be possible to add a way to map several shortcuts to the same action? For example, when I use the keyboard, I love using the usual "Ctrl-Z" shortcut. But on my tablet, I prefer to type on a key that generates a "F5" keystroke... So I would love to be able to say "Both Ctrl-Z and F5 maps to 'undo'".

Would it be possible to implement it? Sorry if I missed the function.

Thanks!

**Comment by callaa** [comment]
Yes, it should be possible. I think it's indeed a fairly common pattern in programs to have an optional customizable alternate shortcut.

**Comment by callaa** [comment]
This is now implemented. The feature will be included in the next release.

**Comment by tobiasBora** [comment]
Thanks a lot!
