### ISSUE TITLE
Stylus lost sensitivity

### ISSUE THREAD

**Issue by FennecPika** [drawpile/Drawpile#883]
Every time I try to draw by myself or on a server, the pressure sensitivity is completely gone. it just started after I updated it.
Anyway i could fix this?

**Comment by Wade821** [comment]
**Please provide the following information:**
- What brand is your tablet?
- What operating system are you using? (Windows, Mac, or Linux? And provide the specific version, such as Windows 7, Windows 8, Windows 8.1, Windows 10... etc etc). If you're using Windows, please provide a screenshot of tablet settings in the driver itself (usually where mapping is, for information about whether Windows Ink is enabled or not). 

**Share the following screenshots here:**
- Drawpile version found in Help > About Drawpile
- Tablet tester screenshot after you tested it found in Help > Tablet Tester
- Brush and Input docks (enable them in View > Docks if not already visible)
