### ISSUE TITLE
Cursor is too small

### ISSUE THREAD

**Issue by edn9** [drawpile/Drawpile#884]
When the canvas is too big (3000x3000), we cant see the cursor, there's any way to config that?
![cursor](http://i.imgur.com/ReWAUAj.png)

**Comment by Wade821** [comment]
Just change the cursor type via edit, preferences. I prefer the crosshair one myself.

Closing this issue since there's already a solution in place for it.

![image](https://user-images.githubusercontent.com/18544575/77307689-f3e5e900-6cb6-11ea-8557-18aae8708ac2.png)
