### ISSUE TITLE
Wobbly lines (linux)

### ISSUE THREAD

**Issue by stubbedto3** [drawpile/Drawpile#885]
![Screenshot from 2020-03-24 18-58-16](https://user-images.githubusercontent.com/62626747/77484893-19333e00-6e02-11ea-89b6-f23b5cc7363a.png)
![Screenshot from 2020-03-24 18-58-52](https://user-images.githubusercontent.com/62626747/77484898-1c2e2e80-6e02-11ea-9716-ff0534645c38.png)
 
my tablet is fine but when i draw in the program the lines are wobbly, i use a Wacom Intuos tablet

**Comment by notfood** [comment]
Can you share your docks > input settings? There is a slider for smoothing.

By default, the wacom instalation will use raw input and it's up to the programs to smooth it.

**Comment by stubbedto3** [comment]
![Screenshot from 2020-03-24 20-17-17](https://user-images.githubusercontent.com/62626747/77488761-821fb380-6e0c-11ea-9c00-e78b210aff60.png)

is this what your talking about?

**Comment by notfood** [comment]
`View > Docks > Input`

**Comment by stubbedto3** [comment]
oh here. thank you 
![Screenshot from 2020-03-25 10-47-28](https://user-images.githubusercontent.com/62626747/77549933-d798a680-6e86-11ea-9ecc-ecac80f1a5e8.png)

**Comment by notfood** [comment]
Please adjust smoothing slider and test again
