### ISSUE TITLE
"Persistance" doesn't work

### ISSUE THREAD

**Issue by whklhh** [drawpile/Drawpile#888]
Hello, thank you for great software.
I compiled from source with headless server, and write config file like:
```
[config]
persistence = true
idleTimeLimit = 60
```
The server still print "Closing non-persistent session.".

Then I think my config file is wrong, and test "persistence" option on Windows Client with Dedicated server.
Log showed `update QJsonObject({"extauth":false,"persistence":true})`, but still not worked. It print "Closing non-persistent session.".

I try to read source to fix but failed, so I can't post to help, sorry.

English isn't my first language, sorry for bad expression.

**Comment by notfood** [comment]
Hello, the persistance config option merely enables the persistance setting to be available. You have to go to the session settings and enable persistance, in a per-session basis, you only need to do it once after you created the session.

It's not a bug.
