### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Gabuzomeuh** [drawpile/Drawpile#890]
Hi.

Not an issue, just the french translation for those who need it.

Best regards and stay safe.

[drawpile_fr.ts.zip](https://github.com/drawpile/Drawpile/files/4548985/drawpile_fr.ts.zip)

**Comment by Wade821** [comment]
Thanks! I don't do any of the source code modification or anything, but I know enough about translations to help. I reviewed your file and made sure it had all the up to date phrases to be translated. You appeared to be missing just one! Secondly, there were a few I saw while browsing the file where the ampersand symbol seemed misplaced, so I removed the checkmark for you to review. Please double check that everything is alright!

[drawpile_fr.zip](https://github.com/drawpile/Drawpile/files/4550045/drawpile_fr.zip)

Thank you for contributing! Hopefully @callaa can get this into the next build. Stay safe.

**Comment by Gabuzomeuh** [comment]
The missing word is now translated (oops, my bad).

Qt accelerators are always tricky to place when translating. I try to place them logically, close to the original (ie : &Undo -> Ann&uler) while avoiding conflicts ; but I understand it may be confusing since there's no official guideline from Qt except "Use your own judgement"...

[drawpile_fr.ts.zip](https://github.com/drawpile/Drawpile/files/4550199/drawpile_fr.ts.zip)

**Comment by Wade821** [comment]
No worries. :) Honestly, doing translations is kind of tough. I tried to update the guide a bit to make it easier so you didn't have to do a big download/install of QT. It's not the best thing.

And yeah, I wasn't sure about that but I figured I'd flag it for your attention. Thank you. :)

**Comment by callaa** [comment]
Thank you! Sorry for not responding sooner. I've now added the translation.
