### ISSUE TITLE
Huion 610 Pro - Mac Mojave

### ISSUE THREAD

**Issue by pbezck** [drawpile/Drawpile#892]
Pressure sensitivity and stability will not work on Drawpile in any version. Sensitivity has never worked for me in Drawpile. The tablet is fine, it works well in other drawing programs (Clip Studio). I have no idea what the issue could be, I feel like I’ve tried everything. I’d like to be able to draw with my friends, any suggestions appreciated.

**Comment by Wade821** [comment]
Did you figure out the problem?
