### ISSUE TITLE
freehand

### ISSUE THREAD

**Issue by Darkstur** [drawpile/Drawpile#893]
hi, i just introduced a friend to drawpile and we're talking about brushes but there's a problem.
When they go to view and then docks, they don't have freehand, instead it says laser pointer.
they also mentioned that when go on a new screen it's there but then it's quickly gone.

I hope some one can help, thank you.

**Comment by Wade821** [comment]
Yeah, you just have the laser tool selected. Click the brush in the menu and you'll get the Freehand dock to show up. That dock's name changes depending on which tool is currently selected.
![image](https://user-images.githubusercontent.com/18544575/80897638-bc079380-8caf-11ea-8726-9cf6efe00928.png)

**Comment by Darkstur** [comment]
Alright, thank you!
