### ISSUE TITLE
Can't draw (at all) on canvas on Drawpile 2.1.7....

### ISSUE THREAD

**Issue by ghost** [drawpile/Drawpile#895]
As the title states, that's what I've been trying to figure out. Because I can't use _Draw_pile if I can't _draw_. No matter what I use--be it mouse or drawing tablet--it won't do anything. The only thing that I can do is select tools, change color, and add/delete layers (and open settings). But I literally cannot draw on the canvas. It literally won't do anything. It's shows the circle, but whenever I click down...._nothing_. 

I've tried going through forums, and tried tablet pressure/sensitivity and nope, that didn't work. I tried messing around with tablet settings, nope that didn't work. My tablet works perfectly in other systems, such as Clip Studio Paint; so, I don't think it's on my end. I just can't draw or anything...and it's extremely frustrating.

So did I download a bugged copy or is version 2.1.7 (for El Capitan/MacOS) no longer supported? All I want is to draw with my friends...but thanks for your time.

**Comment by Wade821** [comment]
Can you share a screenshot of your interface please?

**Comment by notfood** [comment]
The user is now ghost, they deleted the user or it got banned.

**Comment by Wade821** [comment]
Oh, didn't notice that. Gotcha.
