### ISSUE TITLE
laggy when drawing with people! 

### ISSUE THREAD

**Issue by floeflan** [drawpile/Drawpile#903]
I have a Wacom mobile studio pro 13’ and when I draw alone I draw fine..but then drawing with a heavy amount of people it gets laggy... but someone I see drawing with the same tablet I got too and they draw smoothly??? So I don’t get it

**Comment by notfood** [comment]
Try increasing your spacing, it's at 0 which uses more resources.

**Comment by Wade821** [comment]
Yeah. Share a screenshot of your interface and brush settings. Explain exactly what is laggy (drawing on canvas strokes are delayed, buttons on user interface, sending messages, etc). Most people don't have this problem, so this isn't really an issue for Github as this is for bugs with the program itself. Also, right click "Room" under the user list, and then select statistics. Check your latency there by keeping an eye on it for a bit, making note of the highest number you see, the lowest number, and what number it tends to stick around the most. 

![image](https://user-images.githubusercontent.com/18544575/82289302-5840c400-9959-11ea-8884-19ec1f199673.png)

However, you'll be glad to know there are things in the work that should help improve Drawpile performance. That may be a ways off though, so it may be your settings at fault or your internet speed. This could also be influenced by whether or not you're hosting or the session is hosted elsewhere. This sort of thing depends on a lot of factors.
