### ISSUE TITLE
Listing Issue When Hosting (From Computer) / Invalid URL

### ISSUE THREAD

**Issue by DoktorDoktorGimmeTheNews** [drawpile/Drawpile#904]
Hey! I've been having this problem for a bit now, and I'm not sure how or why it started, because everything was working just fine prior to ~1-2 weeks ago when it suddenly cropped up. Whenever I try to host from my computer now, the "List at" option is greyed out. I can't seem to make the drop down work no matter what, regardless of whether I set the "Type" category as either "Public" or "Private (room code only)." It seems to be keeping my friends from joining my session, because they all have updated versions of Drawpile and we really can't think of anything else they could be doing wrong as clients. (**NOTE**: When my friend updated their program, they noticed that their "List at" option had been greyed out, too. I read the most recent update notes for both 2.1.16 and .17 and didn't find any answers there. Am I just missing something?) Here's an image of the issue:

![image](https://user-images.githubusercontent.com/65744518/82619618-47779480-9b8b-11ea-8de8-2fb5dd2bdc0e.png)

Drawpile now lists my private, computer-hosted room addresses starting with "//", followed by my IP, and then a series of numbers/letters, so I'm assuming it's connecting directly from my IP instead of hosting on drawpile.net servers, but I've tried disabling all my firewalls and it still is telling my friends that the address is "Invalid." Would adding "drawpile:" in front of the address fix it?

I'm not really sure what to do. I recently installed Hamachi, so maybe that's the issue? Or maybe should I start connecting my friends through a Hamachi network? Any help would be appreciated, this is super frustrating lol. Thanks for reading!

**Comment by notfood** [comment]
You have to subscribe to any community server to be able to announce in their servers
https://drawpile.net/communities/

pub.drawpile.net is available there, just click the button "Add to Drawpile".

**Comment by DoktorDoktorGimmeTheNews** [comment]
> You have to subscribe to any community server to be able to announce in their servers
> https://drawpile.net/communities/
> 
> pub.drawpile.net is available there, just click the button "Add to Drawpile".

Oh, okay, thank you so much!

**Comment by DoktorDoktorGimmeTheNews** [comment]
> You have to subscribe to any community server to be able to announce in their servers
> https://drawpile.net/communities/
> 
> pub.drawpile.net is available there, just click the button "Add to Drawpile".

Hello! Thank you for your reply.

Unfortunately, whenever my friends try to connect, it still tells them my address is invalid. I added drawpile.net to my server list and listed it when hosting from my computer but we're still running into the same issue. I disabled all of my firewalls again, tried putting "drawpile:" in front of the // address, and we still encounter the problem. Thank you for helping me figure out the greyed out "Listing" issue, but is there a solution for this "Invalid" problem I'm having with my address? Thanks for your help!

**Comment by notfood** [comment]
It sounds like your router is not allowing outside connections. It could be that your ISP changed you to a NAT IP. Your issue is invalid because it's not an issue in Drawpile, it's not something fixable in this side.

Forget about listing. Does it connect to the IP address adverticed in the webpage ```ifconfig.me/ip```?  If it fails to connect, then it's a firewall/router/connectivity issue, we can merely guide you here.

**Comment by Wade821** [comment]
We can do that, or help you on the Drawpile discord, invite link on the bottom left of drawpile.net website. Github is intended for reporting bugs, and this isn't a bug. There's also a Facebook group as well, but I suggest discord since we can chat in real time.

**Comment by DoktorDoktorGimmeTheNews** [comment]
> It sounds like your router is not allowing outside connections. It could be that your ISP changed you to a NAT IP. Your issue is invalid because it's not an issue in Drawpile, it's not something fixable in this side.
> 
> Forget about listing. Does it connect to the IP address adverticed in the webpage `ifconfig.me/ip`? If it fails to connect, then it's a firewall/router/connectivity issue, we can merely guide you here.

Oh, it doesn't connect to the IP address on that webpage. I have put all my firewalls down, which means it must be one of those other issues.

**Comment by DoktorDoktorGimmeTheNews** [comment]
> We can do that, or help you on the Drawpile discord, invite link on the bottom left of drawpile.net website. Github is intended for reporting bugs, and this isn't a bug. There's also a Facebook group as well, but I suggest discord since we can chat in real time.

Ah, okay, thank you! I'll be sure to join there and bring up the issue. Sorry for posting in the incorrect location!

**Comment by DoktorDoktorGimmeTheNews** [comment]
Thank you everyone for your help! The issue has been solved. c:
