### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by TWINGSISTER** [drawpile/Drawpile#908]
I discovered this wonderful work and searched issues and found nothing about this so I dare to ask.
It is difficult for me to find a free server to install Sandstorm. I would be glad to propose my colleagues this environment but I would like to bring them to  a computer lab and ask them to follow a procedure so that at the end they have their own copy running for free and possibly with no credit card. So things like AWS are out.
Probably you can do that for an unlimited time onto Heroku free tier and onto IBM  Cloud. One year free tier from Pivotal and two months from Red Hat Open Shift. I couldn't find any other option. 
I think that deployment on Heroku could be the right way to go since I succeeded installing Huginn without installing Docker just pressing a button
https://elements.heroku.com/buttons/huginn/huginn
as in 
https://elements.heroku.com/buttons/huginn/huginn 
Can you help me in this?

**Comment by Wade821** [comment]
Let me start off by saying that Github is more intended for reporting bugs than it is for needing help with issues. And being that a Drawpile server setup may require more help, I'd suggest joining the Drawpile Discord Server ( https://discord.gg/M3yyMpC ) for which the invite link is also available on the bottom left corner of Drawpile.net website.

Secondly, if you need help setting up a server, [there are some instructions for doing so](https://drawpile.net/help/server-howto/). I've also [made a script up](https://github.com/Wade821/PiDrawpile) for it, though I need to do more testing as it really was originally intended for use with the Raspbian Operating System (Which is Debian based). 

I'm not familiar with some of those software/sources you linked, as I'm more of a Windows buff. Is this what you mean by Sandstorm? --> https://sandstorm.io/install

**Comment by ocdtrekkie** [comment]
@Wade821 I think the requestor copy/pasted the issue in a couple different repos, and didn't remember to edit which software they were asking after pasting, since they opened the issue with Sandstorm too. https://github.com/sandstorm-io/sandstorm/issues/3368

But I assume the issue is meant to ask about Drawpile here in this instance. ;)

**Comment by notfood** [comment]
This makes no sense. Please submit a proper issue or head to other channels like the Discord for assistance to unrelated software.
