### ISSUE TITLE
Feature Request: Smoothing per brush?

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#915]
Possible to maybe have the smoothing be applied per brush if possible? Sometimes smoothing works great for drawing, but then for details or writing, it tends to interfere.

**Comment by askmeaboutlo0m** [comment]
Implemented something that resolves this in #945.

It's also available in the fork of Drawpile I currently maintain: https://github.com/askmeaboutlo0m/Drawpile/releases/tag/2.1.17_UNOFFICIAL_FORK_V5
