### ISSUE TITLE
Drawpile Crashes when Resizing Canvas

### ISSUE THREAD

**Issue by dustiibunnii** [drawpile/Drawpile#917]
I have a MacOS Catalina, version 10.15.5 currently. The version of Drawpile I have downloaded is 2.1.17 for Mac.

Whenever I click to resize my canvas from the blank template, (the untitled one that shows up every time you load the program) drawpile shuts down on me. Should I include screenshots of the crash report?

**Comment by Wade821** [comment]
Sure, that'd be nice. I'm not a Mac buff though so I'm not sure how helpful I'll be on this issue.

**Comment by dustiibunnii** [comment]
<img width="993" alt="Screen Shot 2020-07-30 at 12 12 03 AM" src="https://user-images.githubusercontent.com/68013297/88879946-8106f480-d1f9-11ea-8e55-39604c2795be.png">

Here is the first part of it... The list of the crash report is very long, so I can copy and paste it if you wish. Everytime it crashes it sends it to Apple, though, so I don't know what that will do.

**Comment by Wade821** [comment]
Sorry for not replying, there's really nothing though that I can think of that might help here. Just have to wait till @callaa is around.

**Comment by dustiibunnii** [comment]
I  was  able  to  fix it  on my own  since then. I just pre-loaded a  saved canvas  and  eventually  the start-up drawpile  assumed that canvas' shape and size.

**Comment by Wade821** [comment]
Ah, I see. Good to know. Might just leave this open for @callaa to validate if this is something that can be fixed or not.
