### ISSUE TITLE
i2p support?

### ISSUE THREAD

**Issue by SoniEx2** [drawpile/Drawpile#920]
does drawpile support i2p? it'd be cool to see i2p support, and maybe even an embedded i2p router.

**Comment by notfood** [comment]
Drawpile uses the TCP protocol for comunication, i2p works with TCP through I2PTunnel. You merely need to set it from the I2PTunnel side to mask the Drawpile TCP port.

There is nothing on Drawpile side that needs to be done.

**Comment by SoniEx2** [comment]
if drawpile does something funky with IP addresses, it might need to be adapted. e.g. bittorrent also uses TCP (well, used, but anyway) but doesn't work as-is with i2p because it relies on IP addresses being sent around the network. IRC, on the other hand, mostly just works.

additionally, having an embedded i2p router would allow drawpile users to just seamlessly start a server and share a link and things would just work, ideally.

**Comment by notfood** [comment]
It doesn't do funky things. If you can reach it, it will comunicate. Why don't you try it?

**Comment by SoniEx2** [comment]
because my friend wants me to setup yggdrasil and I'd rather this was just a built-in feature in addition to "dedicated server" and "open to LAN". probably with a name like "share code".

**Comment by notfood** [comment]
If there were a bigger demand it'd be justified to develop but you're the only user with such requirements. Anyhow, Drawpile is open source, you're free to contribute such patch.

Either way, you can host your session on a public server and your experience will be the same.

**Comment by SoniEx2** [comment]
okay, thanks anyway
