### ISSUE TITLE
implement a code of conduct

### ISSUE THREAD

**Issue by SoniEx2** [drawpile/Drawpile#922]
It would be nice to have a code of conduct, similar to [FreeBSD's old one](http://web.archive.org/web/20200530031745/https://www.freebsd.org/internal/code-of-conduct.html).

**Comment by notfood** [comment]
We already have Drawpile's [Common Community Guidelines](https://drawpile.net/communities/drawpile.net/ccg/) and we are way too tiny for any commitees or implementing any control mechanisms that the bigger CoCs require.

**Comment by SoniEx2** [comment]
I mean in the context of the repo/etc.

**Comment by notfood** [comment]
Overkill, we are two or three.
