### ISSUE TITLE
Make didn't succeed

### ISSUE THREAD

**Issue by cuppajoeman** [drawpile/Drawpile#924]
When I tried to build this on arch I got errors like this: ```‘path’ has incomplete type ‘QPainterPath’``` so I added ```#include <QPainterPath>``` to the top of `src/desktop/CMakeFiles/drawpile.dir/widgets/popupmessage.cpp.o`, I tried compiling again and another one of these errors occured again, and so had to add another one of these imports, I think the file was like `color_wheel.cpp` or something like that.

Then I compiled again and got some new errors like this: https://i.imgur.com/NSssSoc.png. After talking in IRC and websearches I found this: https://github.com/xbmc/xbmc/pull/18131/commits/cb95e541be594f5716d0141ef6b4331afc7b6fba. 

And so for each of those functions I changed their signature to look like `MHD_Result` and that got most of the errors to stop, except for one final one, https://i.imgur.com/3Uf0NWT.png and merc'd that lad with `MHD_Result` casting like so https://i.imgur.com/oTMpPjM.png. 

Then I was able to make it fully and run the program.

I wrote this quite quickly, so if something doesn't make sense please ask me to clearify.

**Comment by notfood** [comment]
Known issue... It's been fixed twice in the PRs.
