### ISSUE TITLE
Export of recordings does not appear to include laser pointer trails

### ISSUE THREAD

**Issue by solehill** [drawpile/Drawpile#927]
I am not 100% sure if I am just missing something simple, but when recordings are played back, laser pointer trails are shown on screen as expected. However, exported image or video files do not seem to include them. Maybe this is intentional? An option to choose whether to include them or not would be useful.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Laser trails show up in recordings in Drawpile 2.2.
