### ISSUE TITLE
Pressure Sensitivity Issues - Huion Tablet

### ISSUE THREAD

**Issue by sammu1** [drawpile/Drawpile#928]
I have a Huion (H610Pro) tablet where sensitivity works fine on every drawing software that I have except Drawpile.

Tablet Tester does show I have pressure sensitivity.

The Pressure Setting is set to Stylus, but I've tried the other modes as well - just in case.

I've done a combination of ticking/unticking Windows Ink and the Wintab option as well.

Is there anything else I can try on my end?

I attached a log as well.
[drawpile-2.1.17-2020-09-11.log](https://github.com/drawpile/Drawpile/files/5211157/drawpile-2.1.17-2020-09-11.log)

Thank you!

**Comment by notfood** [comment]
Share screenshots of your brush dock and input dock.

**Comment by sammu1** [comment]
> 
> 
> Share screenshots of your brush dock and input dock.

Can do :) !

![brush and input](https://user-images.githubusercontent.com/15528229/92972332-fa8d3600-f479-11ea-8dbe-7357ae4b2c4b.png)

**Comment by notfood** [comment]
![image](https://user-images.githubusercontent.com/5370107/92977067-a3736b00-f451-11ea-97b9-24c087a6b4b0.png)
Click over here to fix your issue.

**Comment by sammu1** [comment]
ffs

Sorry about the confusion on my end, it's my first time using the software.

I have just toggled that and it sorted my pressure problem - thank you very much!
