### ISSUE TITLE
libsecret's absence not detected by cmake

### ISSUE THREAD

**Issue by fgaz** [drawpile/Drawpile#929]
If libsecret is not installed, it will not be detected until the linking failure at the end

Here's a log of this kind of failure: https://nix-cache.s3.amazonaws.com/log/pvx3aqxsbm1nyrjsg8h56169wkj4zr29-drawpile-2.1.17.drv

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Drawpile doesn't link to libsecret directly, so this is presumably a bug in some dependency. Maybe Qt or libsodium don't declare it properly.
