### ISSUE TITLE
Admin API is giving 404 errors

### ISSUE THREAD

**Issue by IamTheCarl** [drawpile/Drawpile#931]
Hello. I followed the instructions from here to setup a dedicated headless server running under a docker image.
https://drawpile.net/help/server/
I modified the settings to run slightly to better fit my use case.

```bash
#!/bin/bash

set -e

USER=drawpile
GROUP=drawpile

USER_ID=$(id -u $USER)
GROUP_ID=$(id -g $USER)
ADMIN_API_PORT=27780
FOLDER=/home/$USER

echo USER_ID: $USER_ID
echo GROUP_ID: $GROUP_ID
echo FOLDER: $FOLDER

docker run -dt --user $USER_ID:$GROUP_ID --name "drawpile-server" \
    -p 27750:27750 -p $ADMIN_API_PORT:$ADMIN_API_PORT \
    -v $FOLDER:/home/drawpile \
    --restart always \
    callaa/drawpile-srv:2.1 --sessions $FOLDER/sessions \
    --database $FOLDER/config.db \
    --web-admin-port $ADMIN_API_PORT --web-admin-access all
```
~~I am aware I should not give access to machines other than the local host to connect to the API. For now it is open as I am experimenting. I'll restrict it once I have this problem solved.~~

I can join sessions and host sessions from the DrawPile client without a problem, but the admin access API isn't working right.
I can establish a connection with it but web browsers give me an error 404.
I see the following messages coming from the docker image:
```
2020-09-20T22:01:15 HTTP(404) 192.168.1.43 "GET /"
```

If I try to use `drawpile-srv --gui --remote https://addressofmachine:27780/` I get similar issues.
I cannot input information into the fields without it immediately clearing out.
The docker container shows the following messages as I navigate between menus.
```
2020-09-20T21:55:52 HTTP(404) 192.168.1.43 "GET /server"
2020-09-20T21:55:57 HTTP(404) 192.168.1.43 "GET /sessions"
2020-09-20T21:56:16 HTTP(404) 192.168.1.43 "GET /banlist"
2020-09-20T21:56:17 HTTP(404) 192.168.1.43 "GET /accounts"
2020-09-20T21:56:17 HTTP(404) 192.168.1.43 "GET /log"
2020-09-20T21:56:18 HTTP(404) 192.168.1.43 "GET /users"
```

It sounds to me like the admin API may have somehow not been included into this docker image.
Is there more documentation on this api and how to get it working? Does it need to be installed into the image?

**Comment by notfood** [comment]
It's because it's
`drawpile-srv --gui --remote https://addressofmachine:27780/api/`

**Comment by IamTheCarl** [comment]
That seems to have done it.
Thank you.

Just wondering, where is that documented? There are some other things referencing that url on the setup page I mentioned, but nothing about using it with the drawpile-srv.

**Comment by notfood** [comment]
It was changed by this commit https://github.com/drawpile/Drawpile/commit/f480a5d826b246c00dd51f48e7f22a76aa88adc5

It hasn't been documented properly.
