### ISSUE TITLE
Remove cursors?

### ISSUE THREAD

**Issue by SmallestOfFries** [drawpile/Drawpile#936]
My friend and I draw together often and have to wait a while just to show each other if a single line works, is there any way to remove the big bulky cursors?

eg:
![image](https://user-images.githubusercontent.com/74099986/98440928-6cff5700-2147-11eb-83a1-4ab37ef28eea.png)

**Comment by notfood** [comment]
Disable show avatars or other things
![image](https://user-images.githubusercontent.com/5370107/98442185-41418a00-20d1-11eb-81f1-cc95ec8dd2f3.png)

**Comment by SmallestOfFries** [comment]
> Disable show avatars or other things
> ![image](https://user-images.githubusercontent.com/5370107/98442185-41418a00-20d1-11eb-81f1-cc95ec8dd2f3.png)

Huge thanks, that's been bugging me for ages
