### ISSUE TITLE
Drawpile isn't allowing me to connect or join

### ISSUE THREAD

**Issue by sdhifdjas** [drawpile/Drawpile#942]
Every time I try to make a server/join one it says "Could not connect to server. Auth server error: Connection closed" I have no idea what this means.

**Comment by Wade821** [comment]
It means that you're trying to log in with a username that is already registered. You should pick a different name. When you find one that works, you should register your username ( [https://drawpile.net/accounts/login/](https://drawpile.net/accounts/login/) ). 

If you have further issues, please feel free to comment back. Or you can join the Official Drawpile Discord server ( [https://discord.gg/M3yyMpC](https://discord.gg/M3yyMpC) ).
