### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by KingDanime** [drawpile/Drawpile#950]
I just opened drawpile for the first time in a few days/week(s) and every time I try to join or host a room it says 'ERROR: Banned' I was hoping to see what's wrong or what happened?

**Comment by doodlespoots** [comment]
Im having the same exact issue! i havent used mine in a couple of days and i know i have no reason to be banned since im only ever in one server consistently with my bf

**Comment by Wade821** [comment]
I had to ban racists so temporarily, users with IPv6 addresses will not be able to connect to pub.drawpile.net for the next 24 hours. I'm sorry for the trouble this will cause. I suggest using another server in the meantime. 

If you further have questions, please join the Drawpile Discord Server. Invite link on drawpile.net in the lower left corner or https://discord.gg/M3yyMpC
