### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by doodlespoots** [drawpile/Drawpile#951]
I'm only ever on one server with one other person consistently, but for some reason I can't create or join any servers. I saw that someone else was having this issue so i was just curious as to what could be done about this?

**Comment by Wade821** [comment]
I had to ban racists, so temporarily, users with IPv6 addresses will not be able to connect to pub.drawpile.net for the next 24 hours. I'm sorry for the trouble this will cause. I suggest using another server in the meantime. 

If you have further questions, please join the Drawpile Discord Server. Invite link on drawpile.net in the lower left corner or https://discord.gg/M3yyMpC

**Comment by doodlespoots** [comment]
Completely understandable!! Thank you for taking the time to not only kick those people from drawpile but to respond to me! Have a nice day!!

**Comment by Wade821** [comment]
Sorry. It's not the best solution, but this was a problem that was going to come up until a small configuration change is made on the server. Once that's done, it shouldn't be an issue in the future. Appreciate your understanding!
