### ISSUE TITLE
help! i'm banned and dont know why

### ISSUE THREAD

**Issue by cryptsouls** [drawpile/Drawpile#952]
hi! I went to host a session on drawpile and it said error, banned! I haven't been on drawpile in a bit and when I was last online I didn't do anything to get banned, and I haven't ever been kicked either. could I get some help? my username is imagrossrat

**Comment by Wade821** [comment]
I had to ban racists, so temporarily, users with IPv6 addresses will not be able to connect to pub.drawpile.net for the next 24 hours. I'm sorry for the trouble this will cause. I suggest using another server in the meantime. 

If you have further questions, please join the Drawpile Discord Server. Invite link on drawpile.net in the lower left corner or https://discord.gg/M3yyMpC
