### ISSUE TITLE
banned from pub.drawpile.net

### ISSUE THREAD

**Issue by ProwerMatt** [drawpile/Drawpile#953]
for some reason i'm banned from pub.drawpile.net, even though i didn't do anything wrong for some reason

could you unban me pls?

**Comment by Wade821** [comment]
I had to ban racists, so temporarily, users with IPv6 addresses will not be able to connect to pub.drawpile.net for the next 24 hours. I'm sorry for the trouble this will cause. I suggest using another server in the meantime. 

If you have further questions, please join the Drawpile Discord Server. Invite link on drawpile.net in the lower left corner or https://discord.gg/M3yyMpC
