### ISSUE TITLE
Freehand dock has dissapeared

### ISSUE THREAD

**Issue by Bennett-I-Guess** [drawpile/Drawpile#955]
When i had first opened the application i was fixing my setup as i'm usually on PC but have downloaded it on laptop, while i was doing this i was dragging the freehand dock to the side when it disappeared, later when i was trying to get it back i realised it had been removed from the ; View - Docks, at the top of the screen. i have closed and reopened the application and it hadn't returned.

![image](https://user-images.githubusercontent.com/78740124/107228767-f22f2c00-6a14-11eb-9193-e2e55345ec45.png)

**Comment by notfood** [comment]
I don't understand what you mean by FreeHand dock because I don't have it either. What was its function?
![image](https://user-images.githubusercontent.com/5370107/107247761-9f974500-69ff-11eb-9d43-1cfe749cc083.png)

**Comment by Bennett-I-Guess** [comment]
@notfood it let you changed the brush size and style. maybe its been removed if you also don't have it.

**Comment by Bennett-I-Guess** [comment]
> @notfood it let you changed the brush size and style. maybe its been removed if you also don't have it.

I've figured it out, i needed the pen selected then to go into docks.

![image](https://user-images.githubusercontent.com/78740124/107270413-d17dcb00-6a42-11eb-99ad-335fa8d99962.png)
