### ISSUE TITLE
Messages documentation appears to be wrong, and incomplete

### ISSUE THREAD

**Issue by weeryan17** [drawpile/Drawpile#961]
Hi there,

I am current in the process of working on bot in order to automate the hosting of drawpile sessions, however it appears that the [documentation](https://github.com/drawpile/Drawpile/blob/master/doc/messages.md) is wrong. Overall it looks like the message types have changed. for example ping is `02` in hex which translates to `2` in decimal where as the documentation says it's `15` in decimal or `0F` in hex.

Also the messages documentation now doesn't mention that there is a uint8 after message type that indicates the user id.

I'm currently in the process of looking through code and also just plain old reverse engineering the packets.
I'd be happy to pr an update to that documentation, but a little guidance on the structure of messages would be nice if you could point me in that direction. I already found updates message types in the [message.h](https://github.com/drawpile/Drawpile/blob/master/src/libshared/net/message.h#L32) file

**Comment by callaa** [comment]
Sorry about that, looks like I had forgotten to update that file. It still described the old 1.x series protocol. The most up to date documentation of the messages can be found in the headers next to the message.h file you already found. I removed the obsolete parts of the document and replaced them with a reference to those files. You can also take a look at the [rustpile protocol.yaml](https://github.com/callaa/rustpile/blob/master/dpcore/src/protocol/protocol.yaml) which I wrote for my experimental rust implementation. Not sure if that's easier or harder to read, though.
