### ISSUE TITLE
Not receiving verify emails

### ISSUE THREAD

**Issue by theArigoth** [drawpile/Drawpile#964]
Hello! 
I've been having issues trying to access an old account or to register new to be able to access some boards for drawing.
I had a registered account before, but nothing is popping up for the email that I used then, and now I've attempted to make a new account with the same email I had back then.
I tried a few months ago to register an account and never received any email, in focused, other or junk mail folders.
I've attempted again and still have yet to see an email, although the site says one has been sent out.
Anyone have any suggestions or how to fix this?

I've tried registering with a completely new email as well, with the same result.

**Comment by Wade821** [comment]
Providers outlook and hotmail will not receive anything due to their spam filters, even if you go out of your way to allow Drawpile to email you. Comcast/xfinity email will work, provided you change your spam filter settings. 

What email provider are you using?

Related issues: #746

**Comment by notfood** [comment]
It'll never arrive to hotmail or outlook. Try gmail.
