### ISSUE TITLE
No confirmation email

### ISSUE THREAD

**Issue by kiingblue** [drawpile/Drawpile#974]
When I signed up for an account, I wasn't sent a confirmation email. I checked for it on multiple devices, refreshing frequently, and still haven't gotten one. I just wanna drawpile with my friends lol, but there wasn't even an option on the original sign-up page to resend the confirmation email. Please help?

**Comment by notfood** [comment]
It won't arrive to Outlook or Hotmail. Try with gmail.

**Comment by kiingblue** [comment]
I used a gmail email.

**Comment by notfood** [comment]
Check spam
