### ISSUE TITLE
I think I was banned unfairly.

### ISSUE THREAD

**Issue by coobles** [drawpile/Drawpile#976]
On the 21st of this month I was banned for about a month (I think). I was in a server where someone was previously banned from another server for not marking it NSFW and having NSFW drawings on the canvas (none done by me). After that I left the server and got back on later and found a server with a similar name and joined saw that it was hosted by the people from the server I was in before. They were drawing crude NSFW doodles on the canvas. I had no idea that the server was not marked NSFW and decided to doodle one small one just for fun. Then a moderator came in and told the operators to mark the server NSFW, and as soon as the mod said that I stopped drawing and realized it wasn't marked NSFW. Then the two operators of the server started an argument with the mod and were banned for a month but I was also banned as well even though I never interacted with the mod and would have marked the server NSFW if I was operator. I understand if I stayed banned but I feel like I should be unbanned. (I don't know where else to put this issue so I put it here, im sorry if this is not where to put it.)

**Comment by notfood** [comment]
Github is not the place to discuss issues with servers.  Head to the Discord. You can find the link at the front page of [Drawpile](https://drawpile.net/).
