### ISSUE TITLE
ban

### ISSUE THREAD

**Issue by cardboardd-BOX** [drawpile/Drawpile#977]
all aggression in here is directed at bluestrings i apologize for any foul language used now lets discuss why im here your brilliant moderator bluestrings banned me even though i fixed the issues he had with my server i admit i was a bit aggressive but this is the second time he came into my server and started erasing stuff without giving me a chance to fix anything also he kicked people because they were away from the drawpile for a bit i dont know if that was what he was supposed to do but i dont think it should have happened its fine if i dont get unbanned but just check out that bluestring guy

**Comment by notfood** [comment]
Github is not the place to discuss issues with servers.  Head to the Discord. You can find the link at the front page of [Drawpile](https://drawpile.net/).
