### ISSUE TITLE
Pen pressure “dead zone” in middle of screen

### ISSUE THREAD

**Issue by Crystalgryphon** [drawpile/Drawpile#982]
I’m having a bizarre issue where pen pressure is not working on only part of the screen. 

![6CD3BAD8-587C-4110-B138-09CDE7D7E0C5](https://user-images.githubusercontent.com/88205687/127689677-3e176a0d-7390-4635-ad67-ea19bd9edc07.png)
There appears to be a certain spot where pen pressure does not work at all, but ONLY if the line started there. Starting a line outside the affected area and drawing the line through the dead zone will still have the correct pressure sensitivity. 

I did check to make sure it’s not a problem with my tablet (XP-pen artist pro), it is an issue only with drawpile.
it seems to only be affecting sessions, but I may have to test it further.

**Comment by notfood** [comment]
Make sure it's not lag. Lag causes pressure to not work.

**Comment by Crystalgryphon** [comment]
Nope, no lag to speak of. It’s otherwise functioning normally outside the very specific spot where the pressure doesn’t work.

**Comment by Wade821** [comment]
Do you have more than one display screen? From what I googled, it seems that way. Assuming you have Windows, is your tablet set to be your main display (right click, display settings)? 

I've had something similar myself, but my tablet was a Wacom operating in Mouse (Wintab) mode, in which case I simply had to configure the "main" display in Pen (Windows Ink) mode to the appropriate screen before switching back to Mouse mode.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Closing this for lack of response.
