### ISSUE TITLE
Banned from syntheticdreams for seemingly no reason?

### ISSUE THREAD

**Issue by Nilossy** [drawpile/Drawpile#987]

**Comment by Wade821** [comment]
Github is not the place for this kind of issue, as Github is intended primarily for bugs, feature requests, and help (to determine if it is a bug).

If you have a problem with a community server, I suggest you go to the main website ( https://drawpile.net/ ) and join the Drawpile Discord server ( https://discord.gg/M3yyMpC ), for which the invite link is available in the lower left corner of the website. Communities are run by other users and the main Drawpile server has no bearing over how they handle users.
