### ISSUE TITLE
Banned from syntheticdreams for seemingly no reason?

### ISSUE THREAD

**Issue by Nilossy** [drawpile/Drawpile#988]
Just started using Drawpile, username Niloss_. I was wondering if I could find out why I was banned from the syntheticdreams server - I have literally not drawn anything or put anything in chat, so I have no idea why I would be banned. Inactivity maybe? I am 18+ obviously, maybe I was misidentified as a minor? 

Sad to be banned from this community so quickly with no recourse.

**Comment by Wade821** [comment]
Github is not the place for this kind of issue, as Github is intended primarily for bugs, feature requests, and help (to determine if it is a bug).

If you have a problem with a community server, I suggest you go to the main website ( https://drawpile.net/ ) and join the Drawpile Discord server ( https://discord.gg/M3yyMpC ), for which the invite link is available in the lower left corner of the website. Communities are run by other users and the main Drawpile server has no bearing over how they handle users.
