### ISSUE TITLE
Feature Request : Hiding other users' mouse cursors

### ISSUE THREAD

**Issue by vtimofee** [drawpile/Drawpile#993]
Hi, not sure if this feature already exists, if so, I couldnt locate it!
But the ability to hide users' mouse cursors would be very handy - otherwise it is quite a chunky black square.
Thank you!

**Comment by notfood** [comment]
For anyone in the future coming from Google, the feature was already there under View.
![image](https://user-images.githubusercontent.com/5370107/131223156-b65cc3c0-e516-48b8-b79c-f511d5069c1f.png)
