### ISSUE TITLE
GPU canvas rendering?

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#996]
Does Drawpile renders the canvas using the CPU power or uses gpu power?
I ask because when I draw on a 4k display (Cintiq Pro user) the drawing lines go slow and result in jagged or choppy curves. Is there any way I can draw in pure 4k resolution without having to experience lag?
my graphics card is pretty decent also that's why I ask about GPU rendering, I have a 8GB Radeon RX480

**Comment by Wade821** [comment]
Drawpile currently renders using CPU power, there is no hardware based acceleration currently. I don't know that there is any plans for graphic card acceleration at this point.

Drawpile is currently undergoing a major re-work, writing the painting/drawing area in the Rust programming language. This will decouple Drawpile from the interface a bit, meaning that UI based lag (such as long chats that haven't been cleared in a while, right click chat to clear it or type /clear) should not affect your ability to draw smoothly. In addition, Rust is faster at rendering lines so it should be a lot better in general with drawing.
