### ISSUE TITLE
New 2.1.20 Themes Not Working

### ISSUE THREAD

**Issue by Shammiieee** [drawpile/Drawpile#999]
![Capture 1](https://user-images.githubusercontent.com/90091965/133251361-d17b7f58-331f-4a9e-ac1c-74da7b7914d6.PNG)
Not really an urgent help sort of thing but when I updated to the newest version, the theme display was light and when I selected either fusion or fusion dark nothing happened. I have tried restarting the app but it still displays itself as light mode.

**Comment by callaa** [comment]
From the screenshot, it looks like it's already using the fusion theme. I'll need to test this again. It's possible that it's not loading the windows theme for some reason and falling back to fusion, but switching between the light and dark versions should still work. (The app must be restarted for the change to take effect, though.)

**Comment by Wade821** [comment]
Yeah, the themes work for me in Windows. I imagine it's the lack of the "restart program" warning that is making the issue here, given the change between "System" and "Fusion" is not that noticeable on some systems besides the effect it makes on the slider bars.

**Comment by Shammiieee** [comment]
I did restart after switching though it was still on the light mode oddly enough

**Comment by Wade821** [comment]
Maybe try reinstalling it then? We've had odd reports about some features not working that were resolved after running the installation again. Or you could uninstall and then reinstall the program as well.

**Comment by Shammiieee** [comment]
I did another restart this time making sure that drawpile wasnt up on my task manager and it worked! Dark mode back on now I dont have to be flashbanged every second im on there hahah, thanks for the input too!

**Comment by Wade821** [comment]
Yeah, drawpile has to be *completely* closed. If any are open, the settings of the last opened Drawpile are written to the registry so it will appear that no changes took effect. Glad you figured it out. Should have probably asked if you had more than one open! :)
